/*
 * xns/test/test_xns_data.c - the XNS module data blocks (source-iq58)
 *
 * Generated by: Claude Opus 5.5
 *
 * xns/xns_data.c is #included, so the blocks under test are the real
 * definitions with the image's initial contents:
 *
 *   XNS_ERROR_$DATA  0x00E2B29C, map "D E2B29C XNS_ERROR size = 78"
 *   XNS_IDP_$DATA    0x00E2B314, map "D E2B314 XNS_IDP size = 53C"
 *
 * Facts under test:
 *   - the pointer-free head of XNS_IDP_$DATA (statistics, addr_port, addrs,
 *     the port table) sits at its A5 displacements on every build, with the
 *     strides the code uses (addr_port i*2, addrs i*6, ports p*0xC), and the
 *     port table is the map's XNS_IDP_$PORT_TABLE (0xE2B354);
 *   - XNS_IDP_$REGISTER_ADDR's append displacements (0x26/0x12,A5,count*n)
 *     are element count + 1 of addrs / addr_port;
 *   - XNS_IDP_$DATA is zero in the image;
 *   - XNS_ERROR_$DATA is 0x78 bytes with the image's four non-zero cells,
 *     CLIENT_REF_COUNT at 0xE2B310 and XNS_ERROR_$STD_IDP_CHANNEL at
 *     0xE2B312;
 *   - XNS_IDP_$PORT_MAC_CHANNEL(p) is &ports[p].mac_socket.
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "xns/xns_internal.h"

static int tests_passed = 0;
static int tests_failed = 0;
static int current_failed = 0;

#define RUN_TEST(name)                                                        \
    do {                                                                      \
        printf("  %-48s", #name);                                             \
        current_failed = 0;                                                   \
        test_##name();                                                        \
        if (current_failed) {                                                 \
            tests_failed++;                                                   \
        } else {                                                              \
            tests_passed++;                                                   \
            printf("PASSED\n");                                               \
        }                                                                     \
    } while (0)

#define CHECK_EQ(expected, actual)                                            \
    do {                                                                      \
        long _e = (long)(expected);                                           \
        long _a = (long)(actual);                                             \
        if (_e != _a) {                                                       \
            if (!current_failed) printf("FAILED\n");                          \
            current_failed = 1;                                               \
            printf("      %s:%d: %s: expected 0x%lx, got 0x%lx\n", __FILE__,  \
                   __LINE__, #actual, (unsigned long)_e, (unsigned long)_a);  \
        }                                                                     \
    } while (0)

#include "../xns_data.c"

#define I_OFF(p) ((long)((const uint8_t *)(p) - (const uint8_t *)&XNS_IDP_$DATA))
#define E_OFF(p) ((long)((const uint8_t *)(p) - (const uint8_t *)&XNS_ERROR_$DATA))

static long count_nonzero_bytes(const void *p, size_t n)
{
    const uint8_t *b = p;
    long c = 0;
    size_t i;

    for (i = 0; i < n; i++) {
        c += b[i] != 0;
    }
    return c;
}

static void test_idp_image_addresses(void)
{
    CHECK_EQ(0x00E2B314u, MODULE_DATA_ADDR(XNS_IDP_$DATA));
    /* map XNS_IDP_$PORT_TABLE */
    CHECK_EQ(0x00E2B354u, MODULE_DATA_ADDR(XNS_IDP_$DATA) + I_OFF(&XNS_IDP_$DATA.ports[0]));
    /* the next map segment, XNS_IDP_ASM, starts where the block ends */
    CHECK_EQ(0x00E2B850u, MODULE_DATA_ADDR(XNS_IDP_$DATA) + XNS_IDP_$DATA_SIZE);
}

static void test_idp_head_displacements(void)
{
    CHECK_EQ(0x000, I_OFF(&XNS_IDP_$DATA.packets_sent));
    CHECK_EQ(0x004, I_OFF(&XNS_IDP_$DATA.packets_received));
    CHECK_EQ(0x008, I_OFF(&XNS_IDP_$DATA.packets_dropped));
    CHECK_EQ(0x010, I_OFF(&XNS_IDP_$DATA.addr_port[0]));
    CHECK_EQ(0x012, I_OFF(&XNS_IDP_$DATA.addr_port[1]));
    CHECK_EQ(0x020, I_OFF(&XNS_IDP_$DATA.addrs[0][0]));
    CHECK_EQ(0x022, I_OFF(&XNS_IDP_$DATA.addrs[0][1]));
    CHECK_EQ(0x024, I_OFF(&XNS_IDP_$DATA.addrs[0][2]));
    CHECK_EQ(0x026, I_OFF(&XNS_IDP_$DATA.addrs[1][0]));
    CHECK_EQ(0x040, I_OFF(&XNS_IDP_$DATA.ports[0].mac_handle));
    CHECK_EQ(0x044, I_OFF(&XNS_IDP_$DATA.ports[0].net_addr_ptr));
    CHECK_EQ(0x048, I_OFF(&XNS_IDP_$DATA.ports[0].mac_socket));
    CHECK_EQ(0x04A, I_OFF(&XNS_IDP_$DATA.ports[0].refcount));
    CHECK_EQ(0x04C, I_OFF(&XNS_IDP_$DATA.ports[1]));
    CHECK_EQ(0x0A0, I_OFF(&XNS_IDP_$DATA.channels[0]));
}

/* 0x00E19064-0x00E1909E: (0x26,A5,count*6) and (0x12,A5,count*2) */
static void test_register_append_is_element_count_plus_one(void)
{
    int count;

    for (count = 0; count < XNS_MAX_ADDRS - 1; count++) {
        CHECK_EQ(0x26 + count * 6, I_OFF(&XNS_IDP_$DATA.addrs[count + 1][0]));
        CHECK_EQ(0x28 + count * 6, I_OFF(&XNS_IDP_$DATA.addrs[count + 1][1]));
        CHECK_EQ(0x2A + count * 6, I_OFF(&XNS_IDP_$DATA.addrs[count + 1][2]));
        CHECK_EQ(0x12 + count * 2, I_OFF(&XNS_IDP_$DATA.addr_port[count + 1]));
    }
}

static void test_idp_is_zero_in_the_image(void)
{
    CHECK_EQ(0, count_nonzero_bytes(&XNS_IDP_$DATA, sizeof(XNS_IDP_$DATA)));
}

static void test_port_mac_channel_is_the_port_table_word(void)
{
    int p;

    for (p = 0; p < XNS_MAX_PORTS; p++) {
        CHECK_EQ((long)(intptr_t)&XNS_IDP_$DATA.ports[p].mac_socket,
                 (long)(intptr_t)XNS_IDP_$PORT_MAC_CHANNEL(p));
    }
}

static void test_error_block(void)
{
    CHECK_EQ(0x00E2B29Cu, MODULE_DATA_ADDR(XNS_ERROR_$DATA));
    CHECK_EQ(0x78, sizeof(XNS_ERROR_$DATA));
    /* XNS_IDP_$DATA follows immediately in the map */
    CHECK_EQ(MODULE_DATA_ADDR(XNS_IDP_$DATA),
             MODULE_DATA_ADDR(XNS_ERROR_$DATA) + sizeof(XNS_ERROR_$DATA));
    CHECK_EQ(0x00, E_OFF(&XNS_ERROR_$DATA.send_rec));
    CHECK_EQ(0x6C, E_OFF(&XNS_ERROR_$DATA.buf_va_high));
    CHECK_EQ(0x70, E_OFF(&XNS_ERROR_$DATA.buf_va_low));
    /* map CLIENT_REF_COUNT / XNS_ERROR_$STD_IDP_CHANNEL */
    CHECK_EQ(0x00E2B310u, MODULE_DATA_ADDR(XNS_ERROR_$DATA) +
                          E_OFF(&XNS_ERROR_$DATA.client_ref_count));
    CHECK_EQ(0x00E2B312u, MODULE_DATA_ADDR(XNS_ERROR_$DATA) +
                          E_OFF(&XNS_ERROR_$DATA.std_idp_channel));
}

static void test_error_initial_contents(void)
{
    CHECK_EQ(0x00D94C00, XNS_ERROR_$DATA.buf_va_high);
    CHECK_EQ(0x00D64C00, XNS_ERROR_$DATA.buf_va_low);
    CHECK_EQ(0, XNS_ERROR_$DATA.client_ref_count);
    CHECK_EQ(-1, XNS_ERROR_$DATA.std_idp_channel);
    /* 00 D9 4C 00, 00 D6 4C 00 and FF FF: two non-zero bytes each */
    CHECK_EQ(6, count_nonzero_bytes(&XNS_ERROR_$DATA, sizeof(XNS_ERROR_$DATA)));
}

int main(void)
{
    printf("XNS module data (XNS_ERROR_$DATA 0x00E2B29C, XNS_IDP_$DATA 0x00E2B314)\n");

    RUN_TEST(idp_image_addresses);
    RUN_TEST(idp_head_displacements);
    RUN_TEST(register_append_is_element_count_plus_one);
    RUN_TEST(idp_is_zero_in_the_image);
    RUN_TEST(port_mac_channel_is_the_port_table_word);
    RUN_TEST(error_block);
    RUN_TEST(error_initial_contents);

    printf("\n%d passed, %d failed\n", tests_passed, tests_failed);
    return tests_failed ? 1 : 0;
}
