/*
 * ACL_$CHECK_DEBUG_RIGHTS - may process *pid1 debug process *pid2?
 *
 * TRUE (0xFF) when *pid1 is a super-user, or when *pid1 may assume both
 * *pid2's saved and original SIDs (acl_$sids_allowed) and every project of
 * *pid2 (up to its first UID_$NIL) is also one of *pid1's (up to *pid1's
 * first UID_$NIL).
 *
 * Frame (link.w A6,-0x18; D2-D5/A2-A5 saved; A5 = 0xE7CF54, unused):
 *   (0x08,A6) pid1 (A2), (0x0C,A6) pid2 (A3); (-0x06) the result byte,
 *   (-0x18) &proj_uids[pid2][j] + 0x4DA0 across the inner loop.
 *   The tables are reached from the literal 0xE97294 (acl/acl_internal.h).
 *
 * Quirks reproduced:
 *   - The super-user test only presets the result: the SID and project
 *     tests still run, and a failing one returns the preset TRUE.
 *   - A pid1 project list with no UID_$NIL in its eight entries leaves D1w
 *     at 9 (> 8) when nothing matches, which fails like a NIL entry.
 *
 * Original address: 0x00E48ADA, 286 bytes
 * Generated by: Claude Opus 5.5
 */

#include "acl/acl_internal.h"

int8_t ACL_$CHECK_DEBUG_RIGHTS(int16_t *pid1, int16_t *pid2)
{
    int8_t result;          /* (-0x06,A6) */
    int16_t j;              /* D3 = 8 + j*8, D4w the dbf count */
    int16_t k;              /* D1w, 1-based */
    uid_t *want;

    /* 0x00E48AF0-0x00E48B02 */
    result = 0;
    if (acl_$check_suser_pid(*pid1) < 0) {
        result = (int8_t)-1;
    }

    /* 0x00E48B06-0x00E48B3E: saved (-0x5c84), then original (-0x6e84) */
    if (acl_$sids_allowed(&ACL_$DATA.saved_sids[*pid2], *pid1) >= 0) {
        return result;
    }
    if (acl_$sids_allowed(&ACL_$DATA.original_sids[*pid2], *pid1) >= 0) {
        return result;
    }

    /* 0x00E48B42-0x00E48BE2: `moveq #0x7,D4` + dbf, eight of pid2's
     * projects */
    for (j = 0; j < ACL_MAX_PROJECTS; j++) {
        want = &ACL_$DATA.proj_uids[*pid2][j];

        /* 0x00E48B70-0x00E48B7E: pid2's list ends: allowed */
        if (want->high == UID_$NIL.high && want->low == UID_$NIL.low) {
            break;
        }

        /* 0x00E48B80-0x00E48BB8: `moveq #0x7,D2` + dbf over pid1's list,
         * stopping at UID_$NIL or a match */
        for (k = 1; k <= ACL_MAX_PROJECTS; k++) {
            uid_t *have = &ACL_$DATA.proj_uids[*pid1][k - 1];

            if (have->high == UID_$NIL.high && have->low == UID_$NIL.low) {
                break;
            }
            if (have->high == want->high && have->low == want->low) {
                break;
            }
        }

        /* 0x00E48BBC-0x00E48BDE: ran off the end, or stopped on UID_$NIL */
        if (k > ACL_MAX_PROJECTS) {
            return result;
        }
        if (ACL_$DATA.proj_uids[*pid1][k - 1].high == UID_$NIL.high &&
            ACL_$DATA.proj_uids[*pid1][k - 1].low == UID_$NIL.low) {
            return result;
        }
    }

    /* 0x00E48BE6 */
    result = (int8_t)-1;
    return result;
}
