/*
 * ACL_$GET_RE_ALL_SIDS - the current process's SIDs and project lists
 *
 * Original address: 0x00E48792
 * Size: 138 bytes (0x00E48792 .. 0x00E4881B)
 * Generated by: Claude Opus 5.5
 *
 * Frame (link.w A6,0x0; A2/A5 saved; A5 = 0xE7CF54, unused):
 *   (0x08,A6) orig_sids    36 bytes out    (0x0C,A6) cur_sids   36 bytes out
 *   (0x10,A6) saved_proj   12 bytes out    (0x14,A6) proj_list  12 bytes out
 *   (0x18,A6) status
 *
 * With pid = PROC1_$CURRENT and the ACL_$DATA base 0xE97294:
 *   0x00E487A0-0x00E487C4  nine longwords of original_sids[pid]
 *                          (-0x6E84 + pid*0x24, the index built as a word)
 *   0x00E487C8-0x00E487D4  nine longwords of current_sids[pid] (-0x6584)
 *   0x00E487D8-0x00E487FC  three longwords of saved_proj[pid]  (-0x536C,
 *                          pid*0xC)
 *   0x00E487FE-0x00E4880A  three longwords of proj_lists[pid]  (-0x506C)
 *   0x00E4880C-0x00E48810  *status = 0
 */

#include "acl/acl_internal.h"

void ACL_$GET_RE_ALL_SIDS(void *acl_data, void *re_sids,
                          void *prot_info, void *subsys_ids,
                          status_$t *status)
{
    int16_t pid = (int16_t)PROC1_$CURRENT;

    *(acl_sid_block_t *)acl_data = ACL_$DATA.original_sids[pid];    /* 0x00E487C2 */
    *(acl_sid_block_t *)re_sids = ACL_$DATA.current_sids[pid];      /* 0x00E487D2 */
    *(acl_proj_list_t *)prot_info = ACL_$DATA.saved_proj[pid];      /* 0x00E487F8 */
    *(acl_proj_list_t *)subsys_ids = ACL_$DATA.proj_lists[pid];     /* 0x00E48806 */
    *status = status_$ok;                                           /* 0x00E48810 */
}
