/*
 * ACL_$GET_PID_SID - a process's current SID block
 *
 * Original address: 0x00E489E2
 * Size: 70 bytes (0x00E489E2 .. 0x00E48A27)
 * Generated by: Claude Opus 5.5
 *
 * Frame (link.w A6,0x0; D2/A2/A5 saved; A5 = 0xE7CF54, unused):
 *   (0x08,A6) pid         word by value
 *   (0x0A,A6) sid_ret     36 bytes out (an acl_sid_block_t)
 *   (0x0E,A6) status_ret
 *
 *   0x00E489F0-0x00E48A14  nine longwords of current_sids[pid]
 *                          (0xE97294 - 0x6584 + pid*0x24, a word index)
 *   0x00E48A18-0x00E48A1C  *status_ret = 0
 *
 * No range check on pid.  Callers: PROC2's build_info_internal
 * (0x00E409A6, into a uid_t[4] + longword slot) and 0x00E70E12.
 */

#include "acl/acl_internal.h"

void ACL_$GET_PID_SID(int16_t pid, uid_t *sid_ret, status_$t *status_ret)
{
    *(acl_sid_block_t *)sid_ret = ACL_$DATA.current_sids[pid];     /* 0x00E48A12 */
    *status_ret = status_$ok;                                       /* 0x00E48A1C */
}
