/*
 * ACL_$GET_EXSID - the current process's extended SID
 *
 * Original address: 0x00E48972
 * Size: 110 bytes of code (0x00E48972 .. 0x00E489DF) and the word 8 it
 * passes by reference (0x00E489E0 .. 0x00E489E1).
 * Generated by: Claude Opus 5.5
 *
 * Frame (link.w A6,-0x48; A2/A5 saved; A5 = 0xE7CF54, unused):
 *   (0x08,A6)  exsid    acl_$exsid_t out (0x64 bytes)
 *   (0x0C,A6)  status
 *   (-0x46,A6) count    word, ACL_$GET_PROJ_LIST's count out (unused)
 *   (-0x40,A6) projs    uid_t[8]
 *
 *   0x00E48980-0x00E489A6  exsid->sids = current_sids[PROC1_$CURRENT]
 *   0x00E489AA-0x00E489BE  ACL_$GET_PROJ_LIST(projs, &8, &count, status)
 *                          (bsr.w 0x00e48034); its status is passed on
 *                          but not examined
 *   0x00E489C2-0x00E489D2  exsid->proj_uids = projs (sixteen longwords,
 *                          all of the local array whatever the count)
 */

#include "acl/acl_internal.h"

/* 0x00E489E0 (`pea (0x2c,PC)' at 0x00E489B2): `gsk read 0xE489E0 2` = 00 08. */
static const int16_t acl_get_exsid_max_projects = ACL_MAX_PROJECTS;

void ACL_$GET_EXSID(void *exsid, status_$t *status)
{
    acl_$exsid_t *out = (acl_$exsid_t *)exsid;
    int16_t count;                          /* (-0x46,A6) */
    uid_t projs[ACL_MAX_PROJECTS];          /* (-0x40,A6) */
    int i;

    /* 0x00E48980-0x00E489A6 */
    out->sids = ACL_$DATA.current_sids[(int16_t)PROC1_$CURRENT];

    /* 0x00E489AA-0x00E489BE */
    ACL_$GET_PROJ_LIST(projs, (int16_t *)&acl_get_exsid_max_projects, &count, status);

    /* 0x00E489C2-0x00E489D2: moveq #0xf / dbf = 16 longwords */
    for (i = 0; i < ACL_MAX_PROJECTS; i++) {
        out->proj_uids[i] = projs[i];
    }
}
