/*
 * ACL_$RIGHTS_CHECK - ACL_$RIGHTS for a caller-supplied SID context
 *
 * The same gate as ACL_$RIGHTS (0x00E46A00) in front of acl_$eval_rights
 * (0x00E464B8), except that the SID block and project list come from the
 * caller's record (a remote requester's, FILE_$PRIV_LOCK 0x00E5EE06)
 * instead of the current process's, `ignore_super` is always FALSE, and
 * the in-subsystem boolean is the caller's *check_flag.  As in ACL_$RIGHTS
 * there is no stack cleanup after the `bsr` (0x00E46B40): `unlk A6` drops
 * the arguments and acl_$eval_rights' D0 is the result.
 *
 * Frame (link.w A6,-0xC; A2-A3/A5 saved; A5 = 0xE7CF54 = ACL_$UNWIRED_DATA):
 *   (0x08,A6) acl_ctx  -> acl_sid_block_t at +0x00, proj_uids[8] at +0x24
 *   (0x0C) file_uid, (0x10) required_mask -> longword,
 *   (0x14) option_flags -> word, (0x18) check_flag -> byte,
 *   (0x1C) status; (-0x08) the UID copy.
 *
 *   0x00E46AFE-0x00E46B06  copy *file_uid
 *   0x00E46B0A-0x00E46B40  push status, *check_flag, super_count[PROC1_$
 *                          CURRENT] > 0 (sgt), *option_flags,
 *                          *required_mask, FALSE (clr.w), &uid,
 *                          acl_ctx + 0x24, acl_ctx; bsr acl_$eval_rights
 *
 * Original address: 0x00E46AEC, 98 bytes
 * Generated by: Claude Opus 5.5
 */

#include "acl/acl_internal.h"

/* acl_ctx + 0x24: `pea (0x24,A2)` 0x00E46B3A */
#define ACL_RIGHTS_CHECK_PROJ_OFF   0x24
_Static_assert(sizeof(acl_sid_block_t) == ACL_RIGHTS_CHECK_PROJ_OFF,
               "the project list follows the SID block");

uint32_t ACL_$RIGHTS_CHECK(void *acl_ctx, uid_t *file_uid,
                           void *required_mask, void *option_flags,
                           int8_t *check_flag, status_$t *status)
{
    uid_t local_uid;    /* (-0x08,A6) */

    /* 0x00E46AFE-0x00E46B06 */
    local_uid = *file_uid;

    /* 0x00E46B0A-0x00E46B40 */
    return acl_$eval_rights((acl_sid_block_t *)acl_ctx,
                            (uid_t *)((uint8_t *)acl_ctx + ACL_RIGHTS_CHECK_PROJ_OFF),
                            &local_uid,
                            false,                          /* clr.w 0x00E46B34 */
                            *(uint32_t *)required_mask,     /* 0x00E46B32 */
                            *(int16_t *)option_flags,       /* 0x00E46B2C */
                            /* 0x00E46B20 `tst.w (0xb76,A1)` + `sgt` */
                            ACL_$UNWIRED_DATA.super_count[PROC1_$CURRENT] > 0 ? true : false,
                            *check_flag,                    /* 0x00E46B12 */
                            status);
}
