/*
 * ACL_$SET_DEF_ACL_CHECK - may this ACL be installed as a directory's
 * default ACL?
 *
 * Original address: 0x00E48BF8 (SAU2 map: ACL_$SET_DEF_ACL_CHECK)
 * Size: 240 bytes (0x00E48BF8 .. 0x00E48CE7)
 * Generated by: Claude Opus 5.5 (reviewed by Claude Fable 5.1)
 *
 * Caller: dir_$write_def_prot (0x00E51F1A).  A nil ACL is always accepted;
 * otherwise the ACL is rendered (with the caller's privilege raised and both
 * ACL locks held, as ACL_$CONVERT_TO_10ACL does) and accepted only when the
 * image's manager UID is `acl_type`.  Returns a Domain boolean in D0b.
 *
 * Frame (link.w A6,-0x44; D2/A2-A5 saved; A5 = 0xE7CF54, ACL_$UNWIRED_DATA):
 *   (0x08,A6) dir_uid     copied to (-0x38,A6) and never used again
 *   (0x0C,A6) prot_data   never read
 *   (0x10,A6) acl_uid     (A3)
 *   (0x14,A6) unused_4    never read
 *   (0x18,A6) acl_type    compared with the image's manager UID
 *   (0x1C,A6) status_ret  (A2)
 *   (-0x40) acl_$image_internal's flag_out, (-0x3E) its len_out,
 *   (-0x30) its 44-byte data_out
 *
 * Blocks:
 *   0x00E48C06-0x00E48C16  dir_uid copied to the frame (dead)
 *   0x00E48C1A-0x00E48C30  acl_uid == UID_$NIL: result TRUE, nothing else
 *                          (not even *status_ret) is touched
 *   0x00E48C34-0x00E48C6A  super_count[PROC1_$CURRENT]++; exclusion on;
 *                          locksmith owner = us, override on; ML_$LOCK(0xA)
 *   0x00E48C6C-0x00E48C98  acl_$image_internal(acl_uid, 0x400, TRUE,
 *                          workspace, &len, &data, &flag, status_ret);
 *                          ML_$UNLOCK(0xA)
 *   0x00E48C9A-0x00E48CB6  status ok: the image's manager UID (workspace
 *                          +2) == *acl_type -> TRUE, else
 *                          status_$acl_wrong_type
 *   0x00E48CBC-0x00E48CD8  override off, exclusion off, super_count--
 *
 * Quirks reproduced:
 *   - The dir_uid copy at 0x00E48C0E is never read.
 *   - On the nil path *status_ret is left as the caller had it.
 */

#include "acl/acl_internal.h"
#include "uid/uid.h"

/* acl_$image_internal's buffer length and flag (`move.w #0x400` / `st`,
 * 0x00E48C7C-0x00E48C7E) */
#define ACL_SDAC_IMAGE_BUF_LEN  0x0400
#define ACL_SDAC_IMAGE_FLAG     ((int8_t)0xFF)

int8_t ACL_$SET_DEF_ACL_CHECK(uid_t *dir_uid, void *prot_data, uid_t *acl_uid,
                              const uint16_t *unused_4, uid_t *acl_type,
                              status_$t *status_ret)
{
    uid_t             dir_copy;         /* (-0x38,A6), dead */
    int8_t            image_flag;       /* (-0x40,A6) */
    int16_t           image_len;        /* (-0x3E,A6) */
    acl_$prot_data_t  data;             /* (-0x30,A6) */
    int8_t            result;           /* D2b */
    acl_$image_t     *image = (acl_$image_t *)ACL_$UNWIRED_DATA.workspace;

    (void)prot_data;
    (void)unused_4;

    /* 0x00E48C0E-0x00E48C16 */
    dir_copy = *dir_uid;
    (void)dir_copy;

    result = 0;                                         /* clr.b D2b */

    /* 0x00E48C1C-0x00E48C30 */
    if (acl_uid->high == UID_$NIL.high && acl_uid->low == UID_$NIL.low) {
        return (int8_t)0xFF;
    }

    /* 0x00E48C34-0x00E48C6A */
    ACL_$UNWIRED_DATA.super_count[PROC1_$CURRENT]++;
    ML_$EXCLUSION_START(&ACL_$WIRED_DATA.exclusion_lock);
    ACL_$UNWIRED_DATA.locksmith_owner_pid = (int16_t)PROC1_$CURRENT;
    ACL_$UNWIRED_DATA.locksmith_override = (int8_t)0xFF;      /* st (0xbf8,A5) */
    ML_$LOCK(ML_LOCK_ACL);

    /* 0x00E48C6C-0x00E48C98 */
    acl_$image_internal(acl_uid, ACL_SDAC_IMAGE_BUF_LEN, ACL_SDAC_IMAGE_FLAG,
                        ACL_$UNWIRED_DATA.workspace, &image_len, &data,
                        &image_flag, status_ret);
    ML_$UNLOCK(ML_LOCK_ACL);

    /* 0x00E48C9A-0x00E48CB6 */
    if (*status_ret == status_$ok) {
        if (image->acl_uid.high == acl_type->high &&
            image->acl_uid.low == acl_type->low) {
            result = (int8_t)0xFF;
        } else {
            *status_ret = status_$acl_wrong_type;
        }
    }

    /* 0x00E48CBC-0x00E48CD8 */
    ACL_$UNWIRED_DATA.locksmith_override = 0;
    ML_$EXCLUSION_STOP(&ACL_$WIRED_DATA.exclusion_lock);
    ACL_$UNWIRED_DATA.super_count[PROC1_$CURRENT]--;

    return result;
}
