/*
 * acl_$sids_allowed - May process `pid` assume these SIDs?
 *
 * Original address: 0x00E44CE8 (no map symbol; inside "I E44C3C ACL_")
 * Size: 214 bytes (0x00E44CE8 .. 0x00E44DBD); was FUN_00e44ce8
 * Generated by: Claude Opus 5.5
 *
 * Frame (link.w A6,-0x8; D2-D3/A2-A3 saved): (0x08,A6) sids (A0),
 * (0x0C,A6) pid word.  The per-process tables are reached from the literal
 * 0xE97294 with pid * 0x24 (ACL_$DATA, acl_internal.h):
 *   -0x6584 current_sids[pid], -0x5C84 saved_sids[pid],
 *   -0x6E6C original_sids[pid].login_sid (+0x18).
 *
 * Blocks (each a two-longword cmpm pair):
 *   0x00E44D04-0x00E44D2E  user SID: current or saved
 *   0x00E44D32-0x00E44D54  group SID: current or saved
 *   0x00E44D56-0x00E44D78  org SID: current or saved
 *   0x00E44D7A-0x00E44DB2  login SID: UID_$NIL, saved or original
 *   0x00E44DB2             st D0b; any mismatch leaves D0b = 0
 */

#include "acl/acl_internal.h"
#include "uid/uid.h"

int8_t acl_$sids_allowed(acl_sid_block_t *sids, int16_t pid)
{
    acl_sid_block_t *cur = &ACL_$DATA.current_sids[pid];
    acl_sid_block_t *saved = &ACL_$DATA.saved_sids[pid];
    acl_sid_block_t *orig = &ACL_$DATA.original_sids[pid];

    /* 0x00E44D04-0x00E44D2E */
    if (!acl_$uid_eq(&sids->user_sid, &cur->user_sid) &&
        !acl_$uid_eq(&sids->user_sid, &saved->user_sid)) {
        return 0;
    }
    /* 0x00E44D32-0x00E44D54 */
    if (!acl_$uid_eq(&sids->group_sid, &cur->group_sid) &&
        !acl_$uid_eq(&sids->group_sid, &saved->group_sid)) {
        return 0;
    }
    /* 0x00E44D56-0x00E44D78 */
    if (!acl_$uid_eq(&sids->org_sid, &cur->org_sid) &&
        !acl_$uid_eq(&sids->org_sid, &saved->org_sid)) {
        return 0;
    }
    /* 0x00E44D7A-0x00E44DB2 */
    if (acl_$uid_eq(&sids->login_sid, &UID_$NIL) ||
        acl_$uid_eq(&sids->login_sid, &saved->login_sid) ||
        acl_$uid_eq(&sids->login_sid, &orig->login_sid)) {
        return (int8_t)0xFF;
    }
    return 0;
}
