/*
 * SIO6509_$INIT - set up a 6509 console serial channel
 *
 * Original address: 0x00E3350C
 * Size: 100 bytes (0x00E3350C .. 0x00E3356F), the last routine of the
 * SAU2 map's SIO_IO code segment.
 * Generated by: Claude Opus 5.5
 *
 * Frame (link.w A6,-0x4; A2-A4 saved; A5 untouched):
 *   (0x08,A6) int_vec_ptr  (0x0C,A6) chip_num_ptr  (0x10,A6) chan_struct
 *   (0x14,A6) callback     (0x18,A6) config (A1)
 *
 *   0x00E33518-0x00E33526  SIO6509_$PTRS[vec-1] = chan_struct
 *                          (`move.l (0x10,A6),(-0x4,A2,D0w)', A2 =
 *                          0xE2DFD8, D0 = vec*4 as a word index)
 *   0x00E3352C-0x00E33532  the longword at 0x64 + vec*4 (A2 = 0x68, -4) =
 *                          0xE2DFE8, SIO6509_$INT1_RTE: exception vector
 *                          25 + vec (vec 1 is the level-2 autovector,
 *                          map KEYBD_VEC 0x68)
 *   0x00E3353A-0x00E33556  chan->regs = 0xFFB000 - 0x20 + chip*0x20;
 *                          chan->sio_desc = *callback
 *   0x00E3355A-0x00E33560  register +1 = config[0], then config[1],
 *                          through the regs just stored (`movea.l (A4),A0')
 *
 * The first index is `lsl.w #0x2' of the vector word and the second
 * `lsl.w #0x5' of the chip word, both used as signed word indices.
 *
 * Sole caller TERM_$INIT (0x00E3302C), with vec 1, chip 2 and config
 * {0x03, 0xD9}.
 */

#include "sio6509/sio6509_internal.h"

/* The SIO register page; a host test defines SAU2_SIO_BASE first. */
#define SIO6509_REGS_BASE   SAU2_SIO_BASE

/* 0x64 + vec*4 = the vector table longword of vector 25 + vec. */
#define SIO6509_VECTOR_BIAS 25

void SIO6509_$INIT(int16_t *int_vec_ptr, int16_t *chip_num_ptr,
                   void *chan_struct, m68k_ptr_t *callback, uint8_t *config)
{
    sio6509_chan_t *chan = (sio6509_chan_t *)chan_struct;
    int16_t vec;
    int16_t chip;
    volatile uint8_t *regs;

    /* 0x00E33518-0x00E33526 */
    vec = *int_vec_ptr;
    SIO6509_$PTRS[vec - 1] = ARCH_PTR_TO_VA(chan_struct);

    /* 0x00E3352C-0x00E33532 */
    ARCH_VECTOR(SIO6509_VECTOR_BIAS + vec) = (void *)SIO6509_$INT1_RTE;

    /* 0x00E3353A-0x00E33550 */
    chip = *chip_num_ptr;
    chan->regs = (m68k_ptr_t)(SIO6509_REGS_BASE - SIO6509_CHIP_STRIDE +
                              (int16_t)(uint16_t)(chip << 5));

    /* 0x00E33552-0x00E33556 */
    chan->sio_desc = *callback;

    /* 0x00E3355A-0x00E33560 */
    regs = (volatile uint8_t *)ARCH_VA_TO_PTR(chan->regs);
    regs[SIO6509_REG_CTRL] = config[0];
    regs[SIO6509_REG_CTRL] = config[1];
}
