/*
 * fim/sau2/com.s - FIM_COMMON_FAULT and FIM_$COM, the common fault entry
 * (m68k/SAU2)
 *
 * Generated by: Claude Opus 5.5
 *
 * Transcribed from the SAU2 image, 0x00E213A0..0x00E213F7 (88 bytes), the
 * head of the map segment `D E213A0 FIM_UNWIRED size = 4F0':
 *
 *   .text.FIM_UNWIRED  0x00E213A0..0x00E213A3   4 bytes  FIM_COMMON_FAULT
 *                      (the map names no symbol here: it is the segment's
 *                      first word, ordered (never pinned) by an ANCHORS key in
 *                      tools/gen_layout_ld.py)
 *   .text.FIM_$COM     0x00E213A4..0x00E213F7  84 bytes  map E213A4 FIM_$COM
 *                      (82 bytes of code and the word pad ahead of
 *                      FIM_$ADDR_ERR at 0x00E213F8)
 *
 * Image bytes (gsk read 0xE213A0 0x58):
 *   e213a0  486f 0004 48e7 ffff 514f 244f 266a 004c
 *   e213b0  4852 2f1b 3f1b 3f13 486a 0008 4e7a 0800
 *   e213c0  2f00 2f2a 0048 4eb9 00e0 a458 4a00 6600
 *   e213d0  0014 2012 4e7b 0800 4cea ffff 0008 4ef9
 *   e213e0  00e2 28bc 2012 4e7b 0800 2c40 2e6a 0004
 *   e213f0  4ef9 00e2 28bc 0000
 *
 * Every fault the kernel does not handle itself ends here.  Two ways in:
 *
 *   FIM_COMMON_FAULT  `bsr FIM_COMMON_FAULT' from an exception vector stub
 *                     (FIM_$ADDR_ERR .. FIM_$INV_STACK, FIM_$UII,
 *                     FIM_$COPROC, the FP stubs, FIM_$PRIV_VIOL,
 *                     FIM_$ILLEGAL_USP), followed inline by the 8-byte
 *                     fault descriptor (fim_fault_desc_t, fim/fim.h: status
 *                     longword, signal word, class word).  The bsr pushed
 *                     the descriptor's address; `pea (4,SP)' pushes the
 *                     address of the CPU exception frame above it.
 *   FIM_$COM          jumped to with that pair already on the stack:
 *                     (0,SP) = exception frame, (4,SP) = descriptor
 *                     (FIM_$BUS_ERR, FIM_$PARITY_TRAP, FIM_$FRESTORE,
 *                     FIM_$SOFT_FAULT, FIM_$COLD_BUS_ERR).
 *
 * FIM_$COM saves all sixteen registers and an 8-byte result pair below them
 * (A2 = SP: (0,A2) new USP, (4,A2) new SSP; (8,A2) D0..A7; (0x48,A2) the
 * frame pointer; (0x4C,A2) the descriptor pointer) and calls
 *
 *   FIM_$BUILD_DF(frame, usp, &regs, class, signal, status, &result)
 *
 * (pushed right to left; class and signal are word slots).  A result byte
 * of 0 means the fault is not delivered to a user handler: the USP is put
 * back and all registers, A7 included, are reloaded from the save area
 * before FIM_$EXIT.  Non-zero means BUILD_DF built a delivery frame on the
 * user stack: USP and A6 become the new user stack pointer, SP the new
 * supervisor stack pointer, and FIM_$EXIT returns into it.
 *
 * Calls: FIM_$BUILD_DF (map I E0A458, the first entry of the FIM_ code
 * segment) is NOT in our tree, so its operand stays an image literal
 * (TODO(source-h93c) below); FIM_$EXIT is fim/sau2/exit.s.
 *
 * Byte gate (tools/asm_compare.py): identical to the image modulo
 * relocations.  The `bne.w' (6600 0014) is written with an explicit .w so
 * gas keeps the image's word displacement.
 */

        .extern FIM_$EXIT               /* fim/sau2/exit.s, map 0xE228BC */

        /* TODO(source-h93c): FIM_$BUILD_DF (map I E0A458, 0x514 bytes, the
         * Pascal routine that builds the user delivery frame) is not in our
         * tree; until it is, the call goes to the 10.2 image address, which
         * in our relocated link is unrelated code. */
        .equ    FIM_BUILD_DF, 0x00E0A458

        .section ".text.FIM_UNWIRED","ax",@progbits
        .even

        .global FIM_COMMON_FAULT
FIM_COMMON_FAULT:
        pea     (4,%sp)                         /* e213a0  486f 0004: push &exception frame */
        /* falls into FIM_$COM (next section, linked adjacent) */

        .section ".text.FIM_$COM","ax",@progbits
        .even

        .global FIM_$COM
        .global FIM_COM
FIM_$COM:
FIM_COM:
        movem.l %d0-%d7/%a0-%a7,-(%sp)          /* e213a4  48e7 ffff */
        subq.w  #8,%sp                          /* e213a8  result pair: new USP, new SSP */
        movea.l %sp,%a2                         /* e213aa */
        movea.l (0x4c,%a2),%a3                  /* e213ac  A3 = &fault descriptor */
        pea     (%a2)                           /* e213b0  arg 7: &result */
        move.l  (%a3)+,-(%sp)                   /* e213b2  arg 6: status */
        move.w  (%a3)+,-(%sp)                   /* e213b4  arg 5: signal (word slot) */
        move.w  (%a3),-(%sp)                    /* e213b6  arg 4: class (word slot) */
        pea     (8,%a2)                         /* e213b8  arg 3: &saved D0..A7 */
        movec   %usp,%d0                        /* e213bc  4e7a 0800 */
        move.l  %d0,-(%sp)                      /* e213c0  arg 2: the USP */
        move.l  (0x48,%a2),-(%sp)               /* e213c2  arg 1: &exception frame */
        jsr     (FIM_BUILD_DF).l                /* e213c6  4eb9 00e0 a458 */
        tst.b   %d0                             /* e213cc */
        bne.w   .Lcom_deliver                   /* e213ce  6600 0014 */
        move.l  (%a2),%d0                       /* e213d2  not delivered: */
        movec   %d0,%usp                        /* e213d4  4e7b 0800 */
        movem.l (8,%a2),%d0-%d7/%a0-%a7         /* e213d8  4cea ffff 0008 */
        jmp     (FIM_$EXIT).l                   /* e213de  4ef9 00e2 28bc */
.Lcom_deliver:
        move.l  (%a2),%d0                       /* e213e4  delivered: new USP */
        movec   %d0,%usp                        /* e213e6  4e7b 0800 */
        movea.l %d0,%a6                         /* e213ea */
        movea.l (4,%a2),%sp                     /* e213ec  new SSP */
        jmp     (FIM_$EXIT).l                   /* e213f0  4ef9 00e2 28bc */
        .short  0x0000                          /* e213f6  pad; FIM_$ADDR_ERR is at 0xE213F8 */
