/*
 * fim/sau2/crash.s - FIM_$CRASH, the fatal-fault report (m68k/SAU2)
 *
 * Generated by: Claude Opus 5.5
 *
 * Transcribed from the SAU2 image, 0x00E1E864..0x00E1E97D (source-kt66):
 * 158 bytes of code and the 124-byte message template it fills in.  In the
 * image this is not FIM code at all but part of the CRASH_SYSTEM assembly
 * module (map `D E1E700 CRASH_SYSTEM size = 2F0': CRASH_SYSTEM,
 * CRASH_SHOW_STRING, REMAP_DISPLAY, FIM_$CRASH, then the crash report
 * block CRASH_REPORT at 0x00E1E97E), so the routine addresses its cells off
 * that module's base, A5 = CRASH_SYSTEM (0x00E1E700, `lea (-0x16c,PC),A5').
 * It is kept in its own section, .text.FIM_$CRASH, which
 * tools/gen_layout_ld.py links at its map position directly after
 * misc/sau2/crash_system.s (source-c573).
 *
 * Byte gate (tools/asm_compare.py, `make check'): identical to the image
 * modulo relocations, except the nine stores through A5, which are written
 * as absolute (xxx).l operands naming the cells (the (d16,An) -> (xxx).l
 * widening, A5 = 0x00E1E700 in REGISTER_BASES).  They cannot keep the
 * image's (d16,A5) form: A5 is our CRASH_SYSTEM, and in our link neither
 * this template (which the image has at CRASH_SYSTEM + 0x202) nor
 * CRASH_REPORT (a C object, misc/crash_system.c) is at the image distance
 * from it - misc/sau2/crash_system.s is itself widened and rebased.  The
 * `lea' that loads A5 is kept, since the image has it; nothing else here
 * reads A5 before the movem that reloads it.  Each widened store is marked
 * at its site.
 *
 * Calling convention (Pascal, called from FIM_$SPURIOUS_INT and the
 * unwired fault path):
 *   0x4(SP)  exception frame pointer        (0x6(SP) after the SR push)
 *   0x8(SP)  saved register block, D0..A7   (0xA(SP))
 *   0xC(SP)  status_$t * handed on to CRASH_SYSTEM (0xE(SP) after the
 *            extra longword pushed at 0x00E1E8EA)
 * The report is printed with crash_puts_string (A0 = template), whose
 * format is: bytes > 0 literal, '%' ends the line, 0x00 prefixes a word
 * printed as 4 hex digits, a negative byte prefixes a long printed as 8.
 */

        .section ".text.FIM_$CRASH","ax",@progbits
        .even

        /* CRASH_SYSTEM (misc/sau2/crash_system.s, map 0xE1E700), its
         * register-argument console routine crash_puts_string (0x00E1E7C8),
         * and the report block CRASH_REPORT (misc/crash_system.c, image
         * 0x00E1E97E); CRASH_REPORT + 0x68 is the map's CRASH_SP
         * (0x00E1E9E6, crash_report_t.reserved_0x68). */
        .extern CRASH_SYSTEM
        .extern crash_puts_string
        .extern CRASH_REPORT
        .set    CRASH_SP, CRASH_REPORT + 0x68           /* 0x00E1E9E6 */

/* ====================================================================
 * FIM_$CRASH - 0x00E1E864
 * ==================================================================== */
        .global FIM_$CRASH
FIM_$CRASH:
        move.w  %sr,-(%sp)                      /* e1e864  40e7 */
        ori.w   #0x0700,%sr                     /* e1e866  IPL 7 */
        lea     (CRASH_SYSTEM:w,%pc),%a5        /* e1e86a  4bfa fe94: A5 = CRASH_SYSTEM */
        movea.l (0x6,%sp),%a2                   /* e1e86e  A2 = exception frame */
        /* widened: image (0x21c,A5) = 0x00E1E91C */
        move.l  %a2,(fim_crash_frame).l         /* e1e872  2b4a 021c */
        /* widened: image (0x226,A5) = 0x00E1E926 */
        move.w  (%a2),(fim_crash_sr).l          /* e1e876  3b52 0226: frame SR */
        /* widened: image (0x22e,A5) = 0x00E1E92E */
        move.l  (0x2,%a2),(fim_crash_pc).l      /* e1e87a  2b6a 0002 022e: frame PC */
        move.w  (0x6,%a2),%d0                   /* e1e880  format/vector word */
        /* widened: image (0x238,A5) = 0x00E1E938 */
        move.w  %d0,(fim_crash_fmt).l           /* e1e884  3b40 0238 */
        lsr.w   #2,%d0                          /* e1e888  D0.b = vector number */
        lea     (fim_crash_trap,%pc),%a0        /* e1e88a  41fa 00e0 -> 0xE1E96C */
        cmpi.b  #0x20,%d0                       /* e1e88e  b03c 0020 (cmp <ea>=#imm) */
        blt.b   .Lcrash_scan_codes              /* e1e892 */
        cmpi.b  #0x30,%d0                       /* e1e894  b03c 0030: TRAP #0..#15 */
        blt.b   .Lcrash_have_char               /* e1e898  -> 'S' */
.Lcrash_scan_codes:
        lea     (fim_crash_codes,%pc),%a0       /* e1e89a  41fa 00b5 -> 0xE1E951 */
.Lcrash_scan:
        move.b  (%a0)+,%d1                      /* e1e89e  vector code of the pair */
        beq.b   .Lcrash_have_char               /* e1e8a0  end: A0 -> 'I' */
        cmp.b   %d0,%d1                         /* e1e8a2 */
        bne.b   .Lcrash_scan                    /* e1e8a4  (skips the char as a code) */
.Lcrash_have_char:
        /* widened: image (0x23c,A5) = 0x00E1E93C */
        move.b  (%a0),(fim_crash_type).l        /* e1e8a6  1b50 023c */
        moveq   #0x25,%d4                       /* e1e8aa  '%': end the report here */
        cmpi.b  #0x03,%d0                       /* e1e8ac  b03c 0003 */
        bgt.b   .Lcrash_set_more                /* e1e8b0  not a bus/address error */
        moveq   #0x20,%d4                       /* e1e8b2  ' ': print FA and SW too */
        move.w  (0x8,%a2),%d5                   /* e1e8b4  68010 format 8: SSW */
        move.l  (0xa,%a2),%d6                   /* e1e8b8  68010 format 8: fault address */
        cmpi.b  #0x80,(0x6,%a2)                 /* e1e8bc  format 8? */
        beq.b   .Lcrash_store_fault             /* e1e8c2 */
        move.w  (0xa,%a2),%d5                   /* e1e8c4  68020 format A/B: SSW */
        move.l  (0x10,%a2),%d6                  /* e1e8c8  data cycle fault address */
.Lcrash_store_fault:
        /* widened: image (0x24e,A5) = 0x00E1E94E */
        move.w  %d5,(fim_crash_sw).l            /* e1e8cc  3b45 024e */
        /* widened: image (0x244,A5) = 0x00E1E944 */
        move.l  %d6,(fim_crash_fa).l            /* e1e8d0  2b46 0244 */
.Lcrash_set_more:
        /* widened: image (0x23e,A5) = 0x00E1E93E */
        move.b  %d4,(fim_crash_more).l          /* e1e8d4  1b44 023e */
        lea     (fim_crash_msg,%pc),%a0         /* e1e8d8  41fa 0028 -> 0xE1E902 */
        bsr.w   crash_puts_string               /* e1e8dc  6100 feea -> 0xE1E7C8 */
        movea.l (0xa,%sp),%a0                   /* e1e8e0  A0 = saved registers */
        /* widened: image (0x2e6,A5) = 0x00E1E9E6, CRASH_SP inside
         * CRASH_REPORT (a C object in our tree) */
        move.l  (0x3c,%a0),(CRASH_SP).l         /* e1e8e4  2b68 003c 02e6: saved A7 */
        move.l  (0x20,%a0),-(%sp)               /* e1e8ea  saved A0 */
        movem.l (%a0)+,%d0-%d7/%a0-%a6          /* e1e8ee  reload D0..A6 */
        movea.l (%sp)+,%a0                      /* e1e8f2  then the saved A0 */
        move.l  (0xe,%sp),-(%sp)                /* e1e8f4  the status_$t pointer */
        jsr     (CRASH_SYSTEM:w,%pc)            /* e1e8f8  4eba fe06 */
        addq.w  #4,%sp                          /* e1e8fc */
        move.w  (%sp)+,%sr                      /* e1e8fe */
        rts                                     /* e1e900 */

/* --------------------------------------------------------------------
 * The report template, 0x00E1E902..0x00E1E97D (Ghidra
 * s_FAULT_IN_DOMAIN/OS:_00e1e902).  The fields the code above stores are
 * the value slots after each format byte; they ship as zero.
 * -------------------------------------------------------------------- */
fim_crash_msg:
        .ascii  "\r\n\r\nFAULT IN DOMAIN/OS:\r\n"   /* e1e902 */
        .byte   0xff                            /* e1e91b  long follows */
fim_crash_frame:
        .long   0                               /* e1e91c  (0x21c,A5) frame pointer */
        .ascii  ": SR:"                         /* e1e920 */
        .byte   0x00                            /* e1e925  word follows */
fim_crash_sr:
        .short  0                               /* e1e926  (0x226,A5) */
        .ascii  "  PC:"                         /* e1e928 */
        .byte   0xff                            /* e1e92d */
fim_crash_pc:
        .long   0                               /* e1e92e  (0x22e,A5) */
        .ascii  "  FF:"                         /* e1e932 */
        .byte   0x00                            /* e1e937 */
fim_crash_fmt:
        .short  0                               /* e1e938  (0x238,A5) format/vector */
        .ascii  " ("                            /* e1e93a */
fim_crash_type:
        .byte   0x20                            /* e1e93c  (0x23c,A5) fault class char */
        .ascii  ")"                             /* e1e93d */
fim_crash_more:
        .byte   0x25                            /* e1e93e  (0x23e,A5) '%' ends the */
                                                /* report, ' ' prints FA/SW too */
        .ascii  " FA:"                          /* e1e93f */
        .byte   0xff                            /* e1e943 */
fim_crash_fa:
        .long   0                               /* e1e944  (0x244,A5) fault address */
        .ascii  "  SW:"                         /* e1e948 */
        .byte   0x00                            /* e1e94d */
fim_crash_sw:
        .short  0                               /* e1e94e  (0x24e,A5) special status word */
        .ascii  "%"                             /* e1e950 */

/* (vector number, class char) pairs scanned from 0x00E1E951; a 0 code
 * ends the list and selects the char after it, 'I'.  Vectors 0x20..0x2F
 * (TRAP #n) take the 'S' at 0x00E1E96C directly. */
fim_crash_codes:
        .byte   0x02,0x42, 0x03,0x41, 0x04,0x55, 0x05,0x5a     /* e1e951  B A U Z */
        .byte   0x06,0x43, 0x07,0x54, 0x08,0x4d, 0x09,0x54     /* e1e959  C T M T */
        .byte   0x0a,0x55, 0x0b,0x55, 0x0e,0x46, 0x18,0x4a     /* e1e961  U U F J */
        .byte   0x1f,0x50, 0x20                                /* e1e969  P, TRAP */
fim_crash_trap:
        .byte   0x53                                           /* e1e96c  'S' */
        .byte   0x30,0x4f, 0x31,0x4f, 0x32,0x4f, 0x33,0x4f     /* e1e96d  O O O O */
        .byte   0x34,0x4f, 0x35,0x4f, 0x36,0x4f                /* e1e975  O O O */
        .byte   0x00, 0x49                                     /* e1e97b  end, 'I' */
        .byte   0x00                                           /* e1e97d  pad; */
                                                /* CRASH_REPORT follows at 0x00E1E97E */
