/*
 * fim/sau2/fp_put_state.s - FIM_$FP_PUT_STATE (m68k/SAU2)
 *
 * Generated by: Claude Opus 5.5
 *
 * Transcribed from the SAU2 image, 0x00E21E86..0x00E21F1F (map
 * FIM_$FP_PUT_STATE to FIM_$SPURIOUS_INT, 154 bytes: 152 of code and a
 * 2-byte longword pad), in its own section (source-kt66, source-c573).
 * Until source-kt66 this was an `rts' stub.
 *
 *   void FIM_$FP_PUT_STATE(void *regs, void *frame)
 *        0x18(SP), 0x1C(SP) after the 5-register save
 *
 * The inverse of FIM_$FP_GET_STATE, with an FPU configured.  Into the
 * current address space's save slot: if frame's first word is not 0x1234
 * the slot's frame pointer is cleared; otherwise the fsave frame is copied
 * from the words that follow (size byte + 4 bytes, as the image counts
 * them) to the end of the slot, and if regs is tagged 0x1234 too, its 27
 * longwords and the 0xFFFF "registers present" marker go below it and the
 * slot's frame pointer is set.  With no frame but tagged registers, the
 * registers are loaded straight into the FPU after making the current
 * address space the owner under FP_$EXCLUSION.
 *
 * Byte gate (tools/asm_compare.py): identical to the image modulo
 * relocations.
 */

        .section ".text.FIM_$FP_PUT_STATE","ax",@progbits
        .even

        .extern PROC1_$AS_ID            /* uint16_t, map 0xE2060A */
        .extern FP_$SAVEP               /* fp/sau2/savep.s, map 0xE218D0 */
        .extern FP_$EXCLUSION           /* fp/sau2/savep.s, image 0xE218D6 */
        .extern ML_$EXCLUSION_START     /* map 0xE20DF8 */
        .extern ML_$EXCLUSION_STOP      /* map 0xE20E7E */
        .extern fp_$switch_owner        /* fp/sau2/fp_context.s, image 0xE21B10 */

        .global FIM_$FP_PUT_STATE
FIM_$FP_PUT_STATE:
        movem.l %d2-%d3/%a2-%a4,-(%sp)          /* e21e86 */
        movea.l (0x18,%sp),%a3                  /* e21e8a  A3 = regs */
        movea.l (0x1c,%sp),%a4                  /* e21e8e  A4 = frame */
        addq.l  #4,%a3                          /* e21e92  past the count longword */
        addq.l  #4,%a4                          /* e21e94 */
        move.l  (FP_$SAVEP:w,%pc),%d0           /* e21e96 */
        beq.w   .Lps_done                       /* e21e9a  6700 007c: no FPU */
        movea.l (FP_$SAVEP:w,%pc),%a0           /* e21e9e */
        move.w  (PROC1_$AS_ID).l,%d0            /* e21ea2 */
        mulu.w  #0x14a,%d0                      /* e21ea8  FP_SAVE_AREA_SIZE */
        adda.l  %d0,%a0                         /* e21eac */
        subq.l  #4,%a0                          /* e21eae  A0 = &slot frame pointer */
        movea.l %a0,%a2                         /* e21eb0 */
        cmpi.w  #0x1234,(%a4)+                  /* e21eb2  frame tagged? */
        beq.b   .Lps_frame                      /* e21eb6 */
        clr.l   (%a0)                           /* e21eb8  no saved frame */
        bra.b   .Lps_live                       /* e21eba */
.Lps_frame:
        clr.w   %d0                             /* e21ebc */
        move.b  (1,%a4),%d0                     /* e21ebe  fsave frame size */
        addq.w  #4,%d0                          /* e21ec2 */
        adda.l  %d0,%a4                         /* e21ec4  d9c0 */
        lsr.w   #1,%d0                          /* e21ec6 */
        subq.l  #1,%d0                          /* e21ec8 */
.Lps_copy_frame:
        move.w  -(%a4),-(%a0)                   /* e21eca */
        dbf     %d0,.Lps_copy_frame             /* e21ecc */
        cmpi.w  #0x1234,(%a3)+                  /* e21ed0  registers tagged? */
        bne.b   .Lps_done                       /* e21ed4 */
        adda.l  #108,%a3                        /* e21ed6  d7fc 0000 006c: 27 longwords */
        move.w  #26,%d0                         /* e21edc */
.Lps_copy_regs:
        move.l  -(%a3),-(%a0)                   /* e21ee0 */
        dbf     %d0,.Lps_copy_regs              /* e21ee2 */
        move.w  #-1,-(%a0)                      /* e21ee6  0xFFFF: registers present */
        move.l  %a0,(%a2)                       /* e21eea  slot's frame pointer */
        bra.b   .Lps_done                       /* e21eec */
.Lps_live:
        cmpi.w  #0x1234,(%a3)+                  /* e21eee */
        bne.b   .Lps_done                       /* e21ef2 */
        pea     (FP_$EXCLUSION:w,%pc)           /* e21ef4 */
        jsr     (ML_$EXCLUSION_START).l         /* e21ef8 */
        addq.l  #4,%sp                          /* e21efe */
        bsr.w   fp_$switch_owner                /* e21f00  6100 fc0e */
        pea     (FP_$EXCLUSION:w,%pc)           /* e21f04 */
        jsr     (ML_$EXCLUSION_STOP).l          /* e21f08 */
        addq.l  #4,%sp                          /* e21f0e */
        fmovem.l (%a3)+,%fpcr/%fpsr/%fpiar      /* e21f10  f21b 9c00 */
        fmovem.x (%a3)+,%fp0-%fp7               /* e21f14  f21b d0ff */
.Lps_done:
        movem.l (%sp)+,%d2-%d3/%a2-%a4          /* e21f18 */
        rts                                     /* e21f1c */
        .short  0x0000                          /* e21f1e  pad; FIM_$SPURIOUS_INT is at 0xE21F20 */
