/*
 * fim/sau2/frestore.s - FIM_$FRESTORE, reload an FPU context saved by
 * FIM_$FSAVE (m68k/SAU2)
 *
 * Generated by: Claude Opus 5.5
 *
 * Transcribed from the SAU2 image, 0x00E21CD4..0x00E21D47 (map
 * FIM_$FRESTORE to FP_$GET_FP, 116 bytes), in its own section
 * (source-kt66, source-c573).  Until source-kt66 this was an `rts' stub.
 * Also SVC trap 3 entry 0x35 (svc/svc_tables.c).
 *
 *   void FIM_$FRESTORE(void **statep)     0x24(SP) after the 8-register save
 *
 * *statep points at a record written by fim_$copy_fp_frame (length, word
 * sum, then the flag word and fsave frame).  The words are copied onto the
 * stack, last first, while being summed.  If the sum does not match, the
 * registers are restored, the return address and argument dropped, and
 * the fault "coprocessor protocol violation" (0x0012002D, signal 0x13) is
 * raised by entering FIM_$COM with a descriptor, as FIM_$PARITY_TRAP does.
 * Otherwise, if the flag word is 1, the frame is `frestore'd under
 * FP_$EXCLUSION after making the current address space the FPU owner.
 *
 * Quirk reproduced: the descriptor's class word is pushed with
 * `move.w (0x2000).w,-(SP)' (3f38 2000) - the WORD AT ABSOLUTE ADDRESS
 * 0x2000 - where the sibling paths push an immediate (#0x3000 in
 * FIM_$PARITY_TRAP); the image has the absolute short form.
 *
 * Byte gate (tools/asm_compare.py): identical to the image modulo
 * relocations.  The absolute jmp to FIM_$COM (fim/sau2/com.s) is
 * relocated (source-k79b).
 */

        .section ".text.FIM_$FRESTORE","ax",@progbits
        .even

        .extern FP_$EXCLUSION           /* fp/sau2/savep.s, image 0xE218D6 */
        .extern ML_$EXCLUSION_START     /* map 0xE20DF8 */
        .extern ML_$EXCLUSION_STOP      /* map 0xE20E7E */
        .extern fp_$switch_owner        /* fp/sau2/fp_context.s, image 0xE21B10 */

        .extern FIM_COM                 /* fim/sau2/com.s: FIM_$COM, map 0xE213A4 */

        .global FIM_$FRESTORE
FIM_$FRESTORE:
        movem.l %d0-%d3/%a0-%a3,-(%sp)          /* e21cd4 */
        movea.l %sp,%a3                         /* e21cd8 */
        movea.l (0x24,%sp),%a0                  /* e21cda */
        movea.l (%a0),%a0                       /* e21cde  A0 = *statep */
        move.l  (%a0)+,%d1                      /* e21ce0  length */
        move.l  (%a0)+,%d0                      /* e21ce2  word sum */
        adda.l  %d1,%a0                         /* e21ce4 */
        lsr.l   #1,%d1                          /* e21ce6 */
        subq.l  #1,%d1                          /* e21ce8 */
        clr.l   %d3                             /* e21cea */
        clr.l   %d2                             /* e21cec */
.Lfr_copy:
        move.w  -(%a0),%d2                      /* e21cee */
        add.l   %d2,%d3                         /* e21cf0 */
        move.w  %d2,-(%sp)                      /* e21cf2 */
        dbf     %d1,.Lfr_copy                   /* e21cf4  51c9 fff8 */
        cmp.l   %d3,%d0                         /* e21cf8 */
        beq.b   .Lfr_restore                    /* e21cfa */
        movea.l %a3,%sp                         /* e21cfc */
        movem.l (%sp)+,%d0-%d3/%a0-%a3          /* e21cfe */
        addq.w  #8,%sp                          /* e21d02  return address, argument */
        move.w  (0x2000).w,-(%sp)               /* e21d04  3f38 2000: see the header */
        move.w  #0x13,-(%sp)                    /* e21d08  signal number */
        move.l  #0x0012002D,-(%sp)              /* e21d0c  "coprocessor protocol violation" */
        pea     (%sp)                           /* e21d12  &descriptor */
        pea     (0xc,%sp)                       /* e21d14  &exception frame */
        jmp     (FIM_COM).l                     /* e21d18  4ef9 00e2 13a4 */
.Lfr_restore:
        cmpi.w  #1,(%sp)+                       /* e21d1e  flag word */
        bne.b   .Lfr_done                       /* e21d22 */
        pea     (FP_$EXCLUSION:w,%pc)           /* e21d24 */
        jsr     (ML_$EXCLUSION_START).l         /* e21d28 */
        addq.l  #4,%sp                          /* e21d2e */
        bsr.w   fp_$switch_owner                /* e21d30  6100 fdde */
        frestore (%sp)+                         /* e21d34 */
        pea     (FP_$EXCLUSION:w,%pc)           /* e21d36 */
        jsr     (ML_$EXCLUSION_STOP).l          /* e21d3a */
        addq.l  #4,%sp                          /* e21d40 */
.Lfr_done:
        movem.l (%sp)+,%d0-%d3/%a0-%a3          /* e21d42 */
        rts                                     /* e21d46 */
