/*
 * fim/sau2/generate.s - FIM_$GENERATE, raise a fault from software (m68k/SAU2)
 *
 * Generated by: Claude Opus 5.5
 *
 * Transcribed from the SAU2 image, 0x00E214A8..0x00E214AF (map FIM_$GENERATE
 * to FIM_$FP_BSUN, 8 bytes: 6 of code and the segment's longword pad), in
 * its own section (source-kt66, source-c573).
 *
 *   void FIM_$GENERATE(status_$t status)    status at 0x4(SP)
 *
 * Drops its return address, pops the status into D0 and branches into
 * FIM_$SOFT_FAULT at 0x00E21458, which pushes the (status, signal 0x13,
 * class 0xA000) descriptor and enters FIM_$COM as a fault taken at the
 * caller's return point.
 *
 * Byte gate (tools/asm_compare.py): the image's `bra.s 0xE21458' (60aa) is
 * written `jmp (0x00E21458).l' (bra -> jmp widening): FIM_$SOFT_FAULT is
 * not in our tree.
 */

        .section ".text.FIM_$GENERATE","ax",@progbits
        .even

        /* TODO(source-k79b): FIM_$SOFT_FAULT (map 0xE2144C) is not in our
         * tree; 0xE21458 is its descriptor-building tail. */
        .equ    FIM_SOFT_FAULT_TAIL, 0x00E21458

        .global FIM_$GENERATE
FIM_$GENERATE:
        addq.w  #4,%sp                          /* e214a8  drop the return address */
        move.l  (%sp)+,%d0                      /* e214aa  D0 = status */
        jmp     (FIM_SOFT_FAULT_TAIL).l         /* e214ac  image bra.s 0xE21458 (60aa) */
        .short  0x0000                          /* e214ae  pad; FIM_$FP_BSUN is at 0xE214B0 */
