/*
 * fim/sau2/get_user_sr_ptr.s - FIM_$GET_USER_SR_PTR (m68k/SAU2)
 *
 * Generated by: Claude Opus 5.5
 *
 * Transcribed from the SAU2 image, 0x00E2277C..0x00E22865 (map
 * FIM_$GET_USER_SR_PTR to FIM_$DELIVER_TRACE_FAULT, 234 bytes: 118 of the
 * routine and its 116-byte frame checker at 0x00E227F2), in its own section
 * (source-kt66, source-c573).  Until source-kt66 the checker was an `rts'
 * stub.
 *
 *   void *FIM_$GET_USER_SR_PTR(uint16_t pid)     pid at 0x4(SP); result D0
 *
 * Finds the exception frame through which process pid entered the kernel
 * from user mode, at the top of its OS stack (OS_STACK_BASE[pid]): the
 * candidate frames end at the stack top, so each is tried at top - 8
 * (format 0), top - 8 - 0x32 (format 8, vector 2 or 3), - 0x54 (format B,
 * vector 2 or 3), - 0x18 (format A), - 0x4 (format 2) and - 0xC (format 9),
 * and the first that .Lcheck_frame accepts is returned; failing all, top -
 * 8 is.  proc1/sau2/misc.s calls it.
 *
 * Byte gate (tools/asm_compare.py): identical to the image modulo
 * relocations; the CMP/AND #imm,Dn instructions are the <ea>=#imm form in
 * the image (b07c, b0bc, c07c), CMPI/ANDI in ours (recognised by the gate).
 */

        .section ".text.FIM_$GET_USER_SR_PTR","ax",@progbits
        .even

        .extern FIM_$EXIT               /* fim/sau2/exit.s, map 0xE228BC */

        /* OS stack top per PROC1 process: PROC1_$DATA.os_stack_base[pid]
         * (proc1/proc1.h, block image 0x00E254E8, field +0x730 = map
         * OS_STACK_BASE 0x00E25C18). */
        .extern PROC1_$DATA
        .set    OS_STACK_BASE, PROC1_$DATA + 0x730

        /* Lowest PC accepted from user mode below the kernel: the SAU2
         * user/kernel VA limit (class 5 in tools/asm_abs_addrs.md). */
        .equ    USER_VA_LIMIT, 0x00CC0000

        .global FIM_$GET_USER_SR_PTR
FIM_$GET_USER_SR_PTR:
        move.w  (0x4,%sp),%d0                   /* e2277c  pid */
        lsl.w   #2,%d0                          /* e22780 */
        lea     (OS_STACK_BASE).l,%a0           /* e22782  41f9 00e2 5c18 */
        move.l  (0,%a0,%d0.w),%d0               /* e22788 */
        subq.l  #8,%d0                          /* e2278c */
        movea.l %d0,%a0                         /* e2278e  A0 = top - 8 */
        clr.w   %d1                             /* e22790  format 0 */
        bsr.b   .Lcheck_frame                   /* e22792 */
        beq.b   .Lgusp_found                    /* e22794 */
        movea.l %a0,%a1                         /* e22796  A1 = top - 8 */
        lea     (-0x32,%a1),%a0                 /* e22798 */
        move.w  #0x8008,%d1                     /* e2279c  format 8, vector 2 */
        bsr.b   .Lcheck_frame                   /* e227a0 */
        beq.b   .Lgusp_found                    /* e227a2 */
        move.w  #0x800c,%d1                     /* e227a4  format 8, vector 3 */
        bsr.b   .Lcheck_frame                   /* e227a8 */
        beq.b   .Lgusp_found                    /* e227aa */
        lea     (-0x54,%a1),%a0                 /* e227ac */
        move.w  #0xb008,%d1                     /* e227b0  format B */
        bsr.b   .Lcheck_frame                   /* e227b4 */
        beq.b   .Lgusp_found                    /* e227b6 */
        move.w  #0xb00c,%d1                     /* e227b8 */
        bsr.b   .Lcheck_frame                   /* e227bc */
        beq.b   .Lgusp_found                    /* e227be */
        lea     (-0x18,%a1),%a0                 /* e227c0 */
        move.w  #0xa008,%d1                     /* e227c4  format A */
        bsr.b   .Lcheck_frame                   /* e227c8 */
        beq.b   .Lgusp_found                    /* e227ca */
        move.w  #0xa00c,%d1                     /* e227cc */
        bsr.b   .Lcheck_frame                   /* e227d0 */
        beq.b   .Lgusp_found                    /* e227d2 */
        lea     (-0x4,%a1),%a0                  /* e227d4 */
        move.w  #0x2000,%d1                     /* e227d8  format 2, any vector */
        bsr.b   .Lcheck_frame                   /* e227dc */
        beq.b   .Lgusp_found                    /* e227de */
        lea     (-0xc,%a1),%a0                  /* e227e0 */
        move.w  #0x9000,%d1                     /* e227e4  format 9, any vector */
        bsr.b   .Lcheck_frame                   /* e227e8 */
        beq.b   .Lgusp_found                    /* e227ea */
        movea.l %a1,%a0                         /* e227ec  none: top - 8 */
.Lgusp_found:
        move.l  %a0,%d0                         /* e227ee */
        rts                                     /* e227f0 */

/* --------------------------------------------------------------------
 * .Lcheck_frame - 0x00E227F2 (module-local)
 *
 * A0 = candidate frame, D1 = expected format/vector word: 0 = format 0
 * with any valid vector offset; a word whose low 12 bits are zero =
 * that format with any valid vector offset (0x010..0x3FC, a multiple of
 * 4); otherwise an exact match.  The frame is accepted (Z set, via
 * `cmp.w D0,D0') if, in addition, its SR is a user-mode SR at IPL 0 with
 * nothing but T1, T0 and CCR bits (SR & 0x3FE0 == 0) and its PC is even,
 * above 0x8000, and either below USER_VA_LIMIT or FIM_$EXIT itself.
 * Rejection returns Z clear (`cmp.l A5,D0'; a supervisor-mode SR returns
 * with the Z of its `btst'), so the caller's beq tests the result.
 * Clobbers D0, D1.
 * -------------------------------------------------------------------- */
.Lcheck_frame:
        move.w  (0x6,%a0),%d0                   /* e227f2  format/vector word */
        tst.w   %d1                             /* e227f6 */
        beq.b   .Lcf_format0                    /* e227f8 */
        cmp.w   %d0,%d1                         /* e227fa  exact match? */
        beq.b   .Lcf_check_sr                   /* e227fc */
        lsl.l   #4,%d1                          /* e227fe */
        tst.w   %d1                             /* e22800  low 12 bits zero? */
        bne.b   .Lcf_reject                     /* e22802 */
        lsr.l   #4,%d1                          /* e22804 */
        and.w   %d1,%d0                         /* e22806 */
        cmp.w   %d1,%d0                         /* e22808  format matches? */
        bne.b   .Lcf_reject                     /* e2280a */
        bra.b   .Lcf_check_vector               /* e2280c */
.Lcf_format0:
        and.w   #0xf000,%d0                     /* e2280e  c07c f000 */
        bne.b   .Lcf_reject                     /* e22812 */
.Lcf_check_vector:
        move.w  (0x6,%a0),%d0                   /* e22814 */
        and.w   #0x0fff,%d0                     /* e22818  c07c 0fff */
        cmp.w   #0x03fc,%d0                     /* e2281c  b07c 03fc */
        bgt.b   .Lcf_reject                     /* e22820 */
        cmp.w   #0x0010,%d0                     /* e22822  b07c 0010 */
        blt.b   .Lcf_reject                     /* e22826 */
        and.w   #0x0003,%d0                     /* e22828  c07c 0003 */
        bne.b   .Lcf_reject                     /* e2282c */
.Lcf_check_sr:
        move.w  (%a0),%d0                       /* e2282e  SR */
        btst.l  #13,%d0                         /* e22830  supervisor mode? */
        bne.b   .Lcf_return                     /* e22834  Z clear: rejected */
        and.w   #0x3fe0,%d0                     /* e22836  c07c 3fe0 */
        bne.b   .Lcf_reject                     /* e2283a */
        move.l  (0x2,%a0),%d0                   /* e2283c  PC */
        btst.l  #0,%d0                          /* e22840 */
        bne.b   .Lcf_reject                     /* e22844  odd */
        cmp.l   #USER_VA_LIMIT,%d0              /* e22846  b0bc 00cc 0000 */
        bcs.b   .Lcf_check_low                  /* e2284c */
        cmp.l   #FIM_$EXIT,%d0                  /* e2284e  b0bc 00e2 28bc */
        bne.b   .Lcf_reject                     /* e22854 */
.Lcf_check_low:
        cmp.l   #0x00008000,%d0                 /* e22856  b0bc 0000 8000 */
        bls.b   .Lcf_reject                     /* e2285c */
        cmp.w   %d0,%d0                         /* e2285e  Z set: accepted */
.Lcf_return:
        rts                                     /* e22860 */
.Lcf_reject:
        cmp.l   %a5,%d0                         /* e22862  b08d: Z clear */
        rts                                     /* e22864 */
