/*
 * fim/sau2/uii.s - FIM_$UII, the unimplemented-instruction (line A) handler
 * (m68k/SAU2)
 *
 * Generated by: Claude Opus 5.5
 *
 * Transcribed from the SAU2 image, 0x00E2146C..0x00E2149B (map FIM_$UII to
 * FIM_$COPROC, 48 bytes), in its own section so tools/gen_layout_ld.py links
 * it at its map position (source-kt66, source-c573).
 *
 * A supervisor-mode line-A trap on an 0xA0xx / 0xA1xx opcode is a stopwatch
 * probe planted by STOP_$HOOK and goes to STOP_$WATCH_UII; everything else
 * is a fault.  Like every FIM_UNWIRED fault stub, the fault arm calls the
 * common fault entry at 0x00E213A0 (`pea (4,SP)' falling into FIM_$COM) and
 * never returns: the entry reads the three words that follow the call
 * through the pushed return address - the fault status, the signal number
 * and the fault class flags (fim_fault_desc_t, fim/fim.h).
 *
 * Byte gate (tools/asm_compare.py): identical to the image modulo
 * relocations, except the call to the common fault entry, which is not in
 * our tree: the image's `bsr.w 0xE213A0' is written `jsr (0x00E213A0).l'
 * (bsr -> jsr widening; the return address pushed is still the address of
 * the inline words).
 */

        .section ".text.FIM_$UII","ax",@progbits
        .even

        .extern STOP_$WATCH_UII         /* stop/sau2/watch.s, map 0xE81A56 */

        /* TODO(source-k79b): the FIM_UNWIRED common fault entry (0xE213A0,
         * `pea (4,SP)' then FIM_$COM) is not in our tree yet. */
        .equ    FIM_COMMON_FAULT, 0x00E213A0

        .global FIM_$UII
FIM_$UII:
        btst.b  #5,(%sp)                        /* e2146c  SR.S: trapped in supervisor mode? */
        beq.b   .Luii_fault                     /* e21470  user mode: a fault */
        move.l  %a0,-(%sp)                      /* e21472 */
        movea.l (0x6,%sp),%a0                   /* e21474  A0 = the trapping PC */
        cmpi.b  #0xa0,(%a0)                     /* e21478  0xA0xx: stopwatch probe? */
        beq.b   .Luii_stopwatch                 /* e2147c */
        cmpi.b  #0xa1,(%a0)                     /* e2147e  0xA1xx */
        bne.b   .Luii_restore                   /* e21482 */
.Luii_stopwatch:
        movea.l (%sp)+,%a0                      /* e21484 */
        jmp     (STOP_$WATCH_UII).l             /* e21486  4ef9 00e8 1a56 */
.Luii_restore:
        movea.l (%sp)+,%a0                      /* e2148c */
.Luii_fault:
        jsr     (FIM_COMMON_FAULT).l            /* e2148e  image bsr.w 0xE213A0 (6100 ff10) */
        .long   0x0012000A                      /* e21492  status "unimplemented instruction" */
        .short  0x0007                          /* e21496  signal number 7 */
        .short  0xA000                          /* e21498  fault class flags (FIM_FAULT_CLASS_OTHER) */
        .short  0x0000                          /* e2149a  pad; FIM_$COPROC is at 0xE2149C */
