/*
 * pmap/test/test_pmap_data.c - the PMAP module data blocks (source-iq58)
 *
 * Generated by: Claude Opus 5.5
 *
 * pmap/pmap_data.c is #included, so the blocks under test are the real
 * definitions with the image's initial contents:
 *
 *   PMAP_$DATA    0x00E24D44, map "D E24D44 PMAP_ size = 7A4"
 *   PMAP_$SEGMAP  0x00ED5000, map AST_PMAPS .. AST_PMAPS_END (0xEE4C00)
 *
 * Facts under test:
 *   - the timer elements and the exported scalars up to PMAP_$PAGES_EC sit
 *     at their A5 displacements on every build (the rest holds pointers and
 *     is asserted on the target in pmap/pmap.h);
 *   - the working-set timers are Pascal [1..64] with stride 0x1C, declared at
 *     their bias slot +0x24: ws_timer[i] is A5 + 0x24 + i*0x1C
 *     (PMAP_$INIT_WS_SCAN "lea (0x24,A5,D4w*1)", D4 = i*0x1C), element 1 at
 *     +0x40, element 64 ending at PMAP_$IDLE_INTERVAL, and the bias slot
 *     overlays the purifier timer element;
 *   - the block carries the image's initial values, with the three
 *     eventcounts and MOUNT_LOCK self-linked;
 *   - PMAP_$SEGMAP is 0xFC00 bytes of 0x80-byte rows and PMAP_SEGMAP_ROW
 *     takes the 1-based segment index ("lea (-0x80,A0,...)" off 0xED5000).
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "pmap/pmap_internal.h"

static int tests_passed = 0;
static int tests_failed = 0;
static int current_failed = 0;

#define RUN_TEST(name)                                                        \
    do {                                                                      \
        printf("  %-48s", #name);                                             \
        current_failed = 0;                                                   \
        test_##name();                                                        \
        if (current_failed) {                                                 \
            tests_failed++;                                                   \
        } else {                                                              \
            tests_passed++;                                                   \
            printf("PASSED\n");                                               \
        }                                                                     \
    } while (0)

#define CHECK_EQ(expected, actual)                                            \
    do {                                                                      \
        long _e = (long)(expected);                                           \
        long _a = (long)(actual);                                             \
        if (_e != _a) {                                                       \
            if (!current_failed) printf("FAILED\n");                          \
            current_failed = 1;                                               \
            printf("      %s:%d: %s: expected 0x%lx, got 0x%lx\n", __FILE__,  \
                   __LINE__, #actual, (unsigned long)_e, (unsigned long)_a);  \
        }                                                                     \
    } while (0)

#include "../pmap_data.c"

#define P_OFF(p) ((long)((const uint8_t *)(p) - (const uint8_t *)&PMAP_$DATA))

static void test_image_addresses(void)
{
    CHECK_EQ(0x00E24D44u, MODULE_DATA_ADDR(PMAP_$DATA));
    CHECK_EQ(0x00ED5000u, MODULE_DATA_ADDR(PMAP_$SEGMAP));
    /* PMAP_$IDLE_INTERVAL and PMAP_$PAGES_EC as the map has them */
    CHECK_EQ(0x00E25484u, MODULE_DATA_ADDR(PMAP_$DATA) + P_OFF(&PMAP_$DATA.idle_interval));
    CHECK_EQ(0x00E25494u, MODULE_DATA_ADDR(PMAP_$DATA) + P_OFF(&PMAP_$DATA.pages_ec));
    /* the next map segment, PROC1_, starts where the block ends */
    CHECK_EQ(0x00E254E8u, MODULE_DATA_ADDR(PMAP_$DATA) + PMAP_$DATA_SIZE);
}

static void test_pointer_free_displacements(void)
{
    CHECK_EQ(0x000, P_OFF(&PMAP_$DATA.update_timer));
    CHECK_EQ(0x020, P_OFF(&PMAP_$DATA.purifier_timer));
    CHECK_EQ(0x740, P_OFF(&PMAP_$DATA.idle_interval));
    CHECK_EQ(0x744, P_OFF(&PMAP_$DATA.t_pur_scans));
    CHECK_EQ(0x748, P_OFF(&PMAP_$DATA.pur_r_cnt));
    CHECK_EQ(0x74C, P_OFF(&PMAP_$DATA.pur_l_cnt));
    CHECK_EQ(0x750, P_OFF(&PMAP_$DATA.pages_ec));
}

/* "lea (0x24,A5,D4w*0x1)", D4 = index * 0x1C (0x00E14626-0x00E14632) */
static void test_ws_timers_are_one_based(void)
{
    int i;

    for (i = 0; i < PMAP_WS_TIMER_COUNT; i++) {
        CHECK_EQ(0x24 + i * 0x1C, P_OFF(&PMAP_$DATA.ws_timer[i].elem));
    }
    CHECK_EQ(0x40, P_OFF(&PMAP_$DATA.ws_timer[1]));
    CHECK_EQ(0x740, P_OFF(&PMAP_$DATA.ws_timer[PMAP_WS_TIMER_COUNT]));
    /* the expiry INIT_WS_SCAN writes at (0x30,A2) */
    CHECK_EQ(0x30 + 7 * 0x1C, P_OFF(&PMAP_$DATA.ws_timer[7].elem.expire_high));
    /* the bias slot starts inside the purifier timer element */
    CHECK_EQ(P_OFF(&PMAP_$DATA.purifier_timer) + 4, P_OFF(&PMAP_$DATA.ws_timer[0]));
}

static void test_initial_scalars(void)
{
    CHECK_EQ(0x063C, PMAP_$DATA.idle_interval);
    CHECK_EQ(0, PMAP_$DATA.t_pur_scans);
    CHECK_EQ(0, PMAP_$DATA.pur_r_cnt);
    CHECK_EQ(0, PMAP_$DATA.pur_l_cnt);
    CHECK_EQ(1, PMAP_$DATA.scan_fract);
    CHECK_EQ(0, PMAP_$DATA.mid_thresh);
    CHECK_EQ(0, PMAP_$DATA.low_thresh);
    CHECK_EQ(2, PMAP_$DATA.ws_scan_delta);
    CHECK_EQ(1, PMAP_$DATA.min_ws_interval);
    CHECK_EQ(8, PMAP_$DATA.max_ws_interval);
    CHECK_EQ(5, PMAP_$DATA.ws_interval);
    CHECK_EQ(0, PMAP_$DATA.shutting_down_flag);
    CHECK_EQ(0, PMAP_$DATA.short_wait_delay.high);
    CHECK_EQ(5, PMAP_$DATA.short_wait_delay.low);
    CHECK_EQ(0x4D, PMAP_$DATA.ws_random_seed);
    CHECK_EQ(5, PMAP_$DATA.current_slot);
}

static void test_eventcounts_and_lock_are_self_linked(void)
{
    const ec_$eventcount_t *ecs[3] = {
        &PMAP_$DATA.pages_ec, &PMAP_$DATA.r_purifier_ec, &PMAP_$DATA.l_purifier_ec,
    };
    int i;

    for (i = 0; i < 3; i++) {
        CHECK_EQ(0, ecs[i]->value);
        CHECK_EQ((long)(intptr_t)ecs[i], (long)(intptr_t)ecs[i]->waiter_list_head);
        CHECK_EQ((long)(intptr_t)ecs[i], (long)(intptr_t)ecs[i]->waiter_list_tail);
    }
    CHECK_EQ(0, PMAP_$DATA.mount_lock.f1);
    CHECK_EQ((long)(intptr_t)&PMAP_$DATA.mount_lock, (long)(intptr_t)PMAP_$DATA.mount_lock.f2);
    CHECK_EQ((long)(intptr_t)&PMAP_$DATA.mount_lock, (long)(intptr_t)PMAP_$DATA.mount_lock.f3);
    CHECK_EQ(0, PMAP_$DATA.mount_lock.f4);
    CHECK_EQ(-1, PMAP_$DATA.mount_lock.f5);
}

static void test_timers_are_zero_in_the_image(void)
{
    const uint8_t *b = (const uint8_t *)&PMAP_$DATA;
    long nonzero = 0;
    long i;

    for (i = 0; i < 0x740; i++) {
        nonzero += b[i] != 0;
    }
    CHECK_EQ(0, nonzero);
}

/* 0xED5000 + seg*0x80 - 0x80 + page*4 */
static void test_segmap_rows_are_one_based(void)
{
    const uint8_t *base = (const uint8_t *)&PMAP_$SEGMAP;

    CHECK_EQ(0xFC00, sizeof(PMAP_$SEGMAP));
    CHECK_EQ(0x1F8, PMAP_SEGMAP_ROWS);
    CHECK_EQ(0x000, (const uint8_t *)&PMAP_SEGMAP_ROW(1)[0] - base);
    CHECK_EQ(0x07C, (const uint8_t *)&PMAP_SEGMAP_ROW(1)[31] - base);
    CHECK_EQ(0x080, (const uint8_t *)&PMAP_SEGMAP_ROW(2)[0] - base);
    CHECK_EQ(0xFB80, (const uint8_t *)&PMAP_SEGMAP_ROW(PMAP_SEGMAP_ROWS)[0] - base);
    /* AST_PMAPS_END - AST_PMAPS */
    CHECK_EQ(0x00EE4C00u, MODULE_DATA_ADDR(PMAP_$SEGMAP) + sizeof(PMAP_$SEGMAP));
}

int main(void)
{
    printf("PMAP module data (PMAP_$DATA 0x00E24D44, PMAP_$SEGMAP 0x00ED5000)\n");

    RUN_TEST(image_addresses);
    RUN_TEST(pointer_free_displacements);
    RUN_TEST(ws_timers_are_one_based);
    RUN_TEST(initial_scalars);
    RUN_TEST(eventcounts_and_lock_are_self_linked);
    RUN_TEST(timers_are_zero_in_the_image);
    RUN_TEST(segmap_rows_are_one_based);

    printf("\n%d passed, %d failed\n", tests_passed, tests_failed);
    return tests_failed ? 1 : 0;
}
