/*
 * area_$alloc_resources - extend the area table by up to `count` entries
 *
 * Original address: 0x00E075CA (module-local; the SAU2 map has no symbol
 * here, Ghidra carries the tree name)
 * Size: 376 bytes (0x00E075CA .. 0x00E07741)
 * Generated by: Claude Opus 5.5
 *
 * Only caller: area_$internal_create (0x00E07828), with count 0x60 and the
 * area lock held when the create is local.  The routine does not load A5:
 * it runs on its caller's A5 = 0xE1E118, the AREA_ module block.
 *
 * Frame (link.w A6,-0x28; D2-D7/A2/A3 saved):
 *   (0x08,A6) count    word; clamped IN PLACE (0x00E07600)
 *   (-0x08)   ppn      from WP_$CALLOC
 *   (-0x0C)   status   MMU_$VTOP / WP_$CALLOC
 * Registers: D4w first new id (AREA_$N_AREAS + 1), D5w last new id, D2 the
 * running VA in the table at 0xD94C00 (entry k at 0xD94C00 + (k-1)*0x30),
 * A2 the first new entry, D6b the result.
 *
 * Blocks:
 *   0x00E075D2-0x00E075DE  n_areas >= AREA_$FORMAT.max_entries (unsigned
 *                          `bcs`): result FALSE, nothing else
 *   0x00E075E2-0x00E07600  result TRUE; count + n_areas (32-bit, both
 *                          zero-extended) above max_entries clamps count to
 *                          max_entries - n_areas
 *   0x00E07604-0x00E0765A  first entry's VA: if MMU_$VTOP fails, wire a page
 *                          there (WP_$CALLOC + MMU_$INSTALL flags 0x16)
 *   0x00E0765C-0x00E076B6  for each new entry: the same for the VA of its
 *                          LAST byte (+0x2F), then clear its 24 words
 *   0x00E076BA-0x00E07702  entries first..last-1: next = the following
 *                          entry, prev = NIL, area_id = own id
 *   0x00E07706-0x00E07732  last entry: next = AREA_$FREE_LIST, prev = NIL,
 *                          area_id = own id; AREA_$FREE_LIST = first;
 *                          AREA_$N_AREAS = last; AREA_$N_FREE += count
 * The MMU_$VTOP status of a page that is already mapped is not checked
 * further, and WP_$CALLOC's status is ignored.
 */

#include "area/area_internal.h"

/* `pea (0x16).w` 0x00E07648 / 0x00E07690 */
#define AREA_TABLE_MMU_FLAGS    0x16
/* `addi.l #0x2f,D2` 0x00E07666: the VA of an entry's last byte */
#define AREA_ENTRY_LAST_BYTE    0x2F
/* `moveq #0x17,D0` + dbf 0x00E076A4: 24 words = one 0x30-byte entry */
#define AREA_ENTRY_WORDS        (AREA_ENTRY_SIZE / 2)

/* VA of the 1-based area entry `id' (0xD94C00 + (id - 1) * 0x30) */
#define AREA_ENTRY_VA(id) \
    ((uint32_t)(AREA_TABLE_BASE + (uint32_t)((id) - 1) * AREA_ENTRY_SIZE))

/* 0x00E07624-0x00E07658 and 0x00E0766C-0x00E076A0: wire a page at `va'
 * unless MMU_$VTOP already translates it. */
static void area_$wire_table_page(uint32_t va)
{
    status_$t status;                   /* (-0xc,A6) */
    uint32_t ppn;                       /* (-0x8,A6) */

    MMU_$VTOP(va, &status);
    if (status != status_$ok) {
        WP_$CALLOC(&ppn, &status);
        MMU_$INSTALL(ppn, va, AREA_TABLE_MMU_FLAGS);
    }
}

boolean area_$alloc_resources(uint16_t count)
{
    boolean result;                     /* D6b */
    uint16_t first;                     /* D4w */
    uint16_t last;                      /* D5w */
    uint16_t id;                        /* D2w */
    uint16_t k;
    area_$entry_t *entry;               /* A3 / A0 */
    uint16_t *w;

    /* 0x00E075D2-0x00E075DE */
    first = (uint16_t)AREA_$N_AREAS;
    if (!(first < AREA_$FORMAT.max_entries)) {
        return false;
    }
    result = true;

    /* 0x00E075E4-0x00E07600 */
    if ((uint32_t)count + first > (uint32_t)AREA_$FORMAT.max_entries) {
        count = (uint16_t)(AREA_$FORMAT.max_entries - first);
    }

    /* 0x00E07604-0x00E0760A */
    last = (uint16_t)(count + first);
    first = (uint16_t)(first + 1);

    /* 0x00E0760C-0x00E0765A */
    area_$wire_table_page(AREA_ENTRY_VA(first));

    /* 0x00E0765C-0x00E076B6: D3w = last - first, dbf */
    if ((int16_t)(last - first) >= 0) {
        for (id = first; ; id++) {
            area_$wire_table_page(AREA_ENTRY_VA(id) + AREA_ENTRY_LAST_BYTE);
            w = (uint16_t *)AREA_ID_TO_ENTRY(id);
            for (k = 0; k < AREA_ENTRY_WORDS; k++) {
                w[k] = 0;
            }
            if (id == last) {
                break;
            }
        }
    }

    /* 0x00E076BA-0x00E07702: D1w = last - 1 - first, dbf */
    if ((int16_t)(last - 1 - first) >= 0) {
        for (id = first; id != last; id++) {
            entry = AREA_ID_TO_ENTRY(id);
            entry->next = AREA_ID_TO_ENTRY(id + 1);
            entry->prev = NULL;
            entry->area_id = (int16_t)id;
        }
    }

    /* 0x00E07706-0x00E07732 */
    entry = AREA_ID_TO_ENTRY(last);
    entry->next = AREA_$FREE_LIST;
    entry->prev = NULL;
    entry->area_id = (int16_t)last;
    AREA_$FREE_LIST = AREA_ID_TO_ENTRY(first);
    AREA_$N_AREAS = (int16_t)last;
    AREA_$N_FREE = (int16_t)(AREA_$N_FREE + count);

    return result;
}
