/*
 * area_$alloc_seg_table - hand out one overflow segment table
 *
 * Original address: 0x00E09D2E (Ghidra area_$alloc_seg_table; module-local,
 * no SAU2 map symbol)
 * Size: 282 bytes (0x00E09D2E .. 0x00E09E47)
 * Generated by: Claude Opus 5.5
 *
 * Caller: area_$resize (0x00E08A76), with A5 = the AREA_ block
 * (AREA_$GLOBALS); this routine does not load A5 itself.
 *
 * Frame (link.w A6,-0x24; D2-D7/A2 saved):
 *   (0x08,A6) asid       word (D4w)
 *   (0x0A,A6) area_id    word (D2w)
 *   (0x0C,A6) table_idx  word (D3w), stored as its low byte
 *   (-0x18) WP_$CALLOC's ppn, (-0x14) its status (never tested)
 * Result in A0 (A2): the record, or NIL when the pool is full.
 *
 * Blocks:
 *   0x00E09D42-0x00E09D50  A2 = NIL; ML_$LOCK(ML_LOCK_AST)
 *   0x00E09D52-0x00E09D66  64 records in use: ML_$UNLOCK, return NIL
 *   0x00E09D6A-0x00E09DA0  page = PIT_PAGES + next * 0x400; WP_$CALLOC;
 *                          MMU_$INSTALL(ppn, page, 0x16)
 *   0x00E09DA4-0x00E09DC2  count++; rec = &pool[next]; rec->allocated = TRUE
 *   0x00E09DC4-0x00E09E00  count < 64: next = the first unallocated record
 *                          above it (unchanged when there is none); else
 *                          next = 64
 *   0x00E09E06-0x00E09E1E  fill the record and push it on
 *                          seg_table_list[asid]
 *   0x00E09E22-0x00E09E38  ML_$UNLOCK; zero the page's 256 longwords
 *
 * Quirks reproduced:
 *   - WP_$CALLOC's status is never looked at.
 *   - The free-record scan only looks upward from next + 1 to 63; it does
 *     not wrap, and leaves the cursor alone when it finds nothing.
 *   - The page is zeroed after the lock is dropped, through the VA computed
 *     from the cursor before the allocation.
 */

#include "area/area_internal.h"
#include "wp/wp.h"
#include "mmu/mmu.h"

/* MMU_$INSTALL's flags for the slot page (`pea (0x16).w` 0x00E09D90) */
#define AREA_SEG_TABLE_PAGE_PROT    0x16

area_$seg_table_t *area_$alloc_seg_table(int16_t asid, int16_t area_id,
                                          int16_t table_idx)
{
    area_$seg_table_t *result = NULL;           /* A2 */
    area_$seg_table_t *rec;                     /* A0 */
    uint32_t           page;                    /* D5 */
    uint32_t           ppn;                     /* (-0x18,A6) */
    status_$t          st;                      /* (-0x14,A6) */
    int16_t            idx;                     /* D1w */
    int16_t            n;                       /* D0w */
    uint32_t          *p;
    int16_t            i;

    /* 0x00E09D42-0x00E09D50 */
    ML_$LOCK(ML_LOCK_AST);

    /* 0x00E09D52-0x00E09D66 */
    if ((int16_t)AREA_$GLOBALS.format.seg_table_count >= AREA_SEG_TABLE_POOL_COUNT) {
        ML_$UNLOCK(ML_LOCK_AST);
        return result;
    }

    /* 0x00E09D6A-0x00E09DA0 */
    page = AREA_PIT_PAGES_VA +
           (uint32_t)((int32_t)(int16_t)AREA_$GLOBALS.format.seg_table_next << 10);
    WP_$CALLOC(&ppn, &st);
    MMU_$INSTALL(ppn, page, 0, AREA_SEG_TABLE_PAGE_PROT);

    /* 0x00E09DA4-0x00E09DC2 */
    AREA_$GLOBALS.format.seg_table_count++;
    rec = &AREA_$GLOBALS.seg_table_pool[(int16_t)AREA_$GLOBALS.format.seg_table_next];
    rec->allocated = (int8_t)0xFF;
    result = rec;

    /* 0x00E09DC4-0x00E09E00 */
    if ((int16_t)AREA_$GLOBALS.format.seg_table_count < AREA_SEG_TABLE_POOL_COUNT) {
        idx = (int16_t)(AREA_$GLOBALS.format.seg_table_next + 1);
        n = (int16_t)(AREA_SEG_TABLE_POOL_COUNT - 1 - idx);
        if (n >= 0) {
            do {
                if (AREA_$GLOBALS.seg_table_pool[idx].allocated >= 0) {
                    AREA_$GLOBALS.format.seg_table_next = (uint16_t)idx;
                    break;
                }
                idx++;
            } while (--n != -1);                /* dbf */
        }
    } else {
        AREA_$GLOBALS.format.seg_table_next = AREA_SEG_TABLE_POOL_COUNT;
    }

    /* 0x00E09E06-0x00E09E1E */
    rec->bitmap_ptr = page;
    rec->area_id = area_id;
    rec->table_index = (uint8_t)table_idx;
    rec->next = ARCH_PTR_TO_VA(AREA_$GLOBALS.seg_table_list[asid]);
    AREA_$GLOBALS.seg_table_list[asid] = rec;

    /* 0x00E09E22-0x00E09E38 */
    ML_$UNLOCK(ML_LOCK_AST);
    p = (uint32_t *)ARCH_VA_TO_PTR(page);
    for (i = 0; i < 0x100; i++) {               /* move.w #0xff / dbf */
        *p++ = 0;
    }

    return result;
}
