/*
 * area_$free_seg_table - return an overflow segment table to the pool
 *
 * Original address: 0x00E09E48 (Ghidra area_$free_seg_table; module-local,
 * no SAU2 map symbol)
 * Size: 172 bytes (0x00E09E48 .. 0x00E09EF3)
 * Generated by: Claude Opus 5.5
 *
 * Callers: area_$free_slot_segments (0x00E08766) and area_$resize
 * (0x00E08AC0), with A5 = the AREA_ block (AREA_$GLOBALS); this routine
 * does not load A5 itself.
 *
 * Frame (link.w A6,-0x10; D2-D3/A2-A3 saved):
 *   (0x08,A6) entry   the record to free (A2)
 *   (0x0C,A6) prev    its predecessor on seg_table_list[asid], or NIL (A3)
 *   (0x10,A6) asid    word (D2w)
 *   (-0x08) MMU_$VTOP's status, (-0x0C) the ppn it returned
 *
 * Blocks:
 *   0x00E09E58-0x00E09E68  ML_$LOCK(ML_LOCK_AST)
 *   0x00E09E6A-0x00E09E76  D3 = the record's pool index, from its page VA:
 *                          (bitmap_ptr - PIT_PAGES) >> 10
 *   0x00E09E78-0x00E09EA6  ppn = MMU_$VTOP(page, &st); mapped: MMU_$REMOVE,
 *                          MMAP_$FREE
 *   0x00E09EA8-0x00E09ECC  count--; unlink (prev NIL: the list head);
 *                          entry->next = NIL, entry->allocated = FALSE
 *   0x00E09ED0-0x00E09EDA  next = min(next, D3)
 *   0x00E09EDE-0x00E09EE4  ML_$UNLOCK(ML_LOCK_AST)
 *
 * Quirks reproduced:
 *   - The pool index comes from the page VA, not from the record's address.
 *   - The cursor minimum is a signed word compare.
 */

#include "area/area_internal.h"
#include "mmu/mmu.h"
#include "mmap/mmap.h"

void area_$free_seg_table(area_$seg_table_t *entry,
                          area_$seg_table_t *prev, int16_t asid)
{
    int16_t   idx;                              /* D3w */
    uint32_t  ppn;                              /* (-0x0C,A6) */
    status_$t st;                               /* (-0x08,A6) */

    /* 0x00E09E58-0x00E09E68 */
    ML_$LOCK(ML_LOCK_AST);

    /* 0x00E09E6A-0x00E09E76: sub.l / lsr.l #8 / lsr.l #2 */
    idx = (int16_t)((entry->bitmap_ptr - AREA_PIT_PAGES_VA) >> 10);

    /* 0x00E09E78-0x00E09EA6 */
    ppn = MMU_$VTOP(entry->bitmap_ptr, &st);
    if (st == status_$ok) {
        MMU_$REMOVE(ppn);
        MMAP_$FREE(ppn);
    }

    /* 0x00E09EA8-0x00E09ECC */
    AREA_$GLOBALS.format.seg_table_count--;
    if (prev == NULL) {
        AREA_$GLOBALS.seg_table_list[asid] =
            (area_$seg_table_t *)ARCH_VA_TO_PTR(entry->next);
    } else {
        prev->next = entry->next;
    }
    entry->next = 0;
    entry->allocated = 0;

    /* 0x00E09ED0-0x00E09EDA */
    if (idx > (int16_t)AREA_$GLOBALS.format.seg_table_next) {
        idx = (int16_t)AREA_$GLOBALS.format.seg_table_next;
    }
    AREA_$GLOBALS.format.seg_table_next = (uint16_t)idx;

    /* 0x00E09EDE-0x00E09EE4 */
    ML_$UNLOCK(ML_LOCK_AST);
}
