/*
 * area_$resize - set an area's virtual and committed sizes
 *
 * Original address: 0x00E08816 (module-local; the SAU2 map has no symbol
 * here, Ghidra carries the tree name)
 * Size: 978 bytes (0x00E08816 .. 0x00E08BE7), plus its nested procedure
 * area_$remote_sync at 0x00E087BA (92 bytes)
 * Generated by: Claude Opus 5.5
 *
 * Callers: area_$internal_create (0x00E07982), area_$internal_delete
 * (0x00E07B84), AREA_$TRANSFER (0x00E08164, 0x00E081D6), AREA_$GROW
 * (0x00E08CA8), AREA_$GROW_TO (0x00E08D8E), AREA_$TOUCH (0x00E0963A); A5 =
 * 0xE1E118 (AREA_$GLOBALS) is the caller's.
 *
 * Frame (link.w A6,-0x58; D2-D7/A2 saved):
 *   (0x08,A6) area_id      word -> D4w
 *   (0x0A,A6) entry
 *   (0x0E,A6) virt_size    rounded up to 32K IN PLACE (0x00E0884C)
 *   (0x12,A6) commit_size  rounded up to 1K IN PLACE (0x00E0885E)
 *   (0x16,A6) is_grow      word (`tst.w`): sync a remote partner
 *   (0x18,A6) status_p
 *   (-0x2C)   old_pages = entry->virt_size >> 10; D5 new_pages
 *   (-0x3C)   old_virt; D6 old_commit; (-0x4C) first new overflow table
 *   (-0x12)/(-0x14) and (-0x18), (-0x30): see the blocks
 * The nested procedure reads (0x0A), (0x0E), (0x12) and (0x18) through its
 * static link; the C passes them.
 *
 * Blocks:
 *   0x00E08822-0x00E08838  AREA_FLAG_ACTIVE clear: status 0x00320006
 *   0x00E0883C-0x00E08872  round the sizes; commit > virt (unsigned):
 *                          status 0x0032000B
 *   0x00E08876-0x00E088AE  status 0; the old sizes
 *   shrink 0x00E088B2-0x00E089EE
 *     0x00E088B2-0x00E08928  the segment count changes and the area has a
 *                          BSTE: under ML lock 0x14 a loop computes the
 *                          first BSTE and each dropped segment's index into
 *                          two frame words nothing reads (kept)
 *     0x00E0892A-0x00E08954  area_$free_segments(area_id, new_pages,
 *                          old_pages - 1, TRUE); failure -> CRASH_SYSTEM
 *     0x00E08956-0x00E089C4  local: a commit above the new size gives the
 *                          surplus 1K blocks back with BAT_$CANCEL (a count
 *                          whose bytes exceed the old commit -> CRASH_SYSTEM
 *                          (Area_Internal_Error)) and commit := virt
 *     0x00E089C8-0x00E089EE  remote: is_grow -> area_$remote_sync (failure
 *                          returns at once); commit := virt if smaller
 *   grow 0x00E089F2-0x00E08B86
 *     0x00E089FA-0x00E08A14  is_grow and remote: area_$remote_sync
 *     0x00E08A18-0x00E08B38  new cells beyond the two inline ones need
 *                          overflow tables (old last cell .. new last cell):
 *                          area_$alloc_seg_table each; on NIL free every
 *                          table of this area from the first new one on,
 *                          tell a remote partner the size it had
 *                          (REM_FILE_$GROW_AREA, status ignored) and fail
 *                          with 0x00320005
 *     0x00E08B3E-0x00E08B86  new inline cells must be empty (else
 *                          CRASH_SYSTEM(Area_Internal_Error))
 *   0x00E08B8A-0x00E08BCE  commit grows: local BAT_$RESERVE of the extra 1K
 *                          blocks (failure returns), commit_size := commit
 *   0x00E08BD4  virt_size := virt
 */

#include "area/area_internal.h"
#include "bat/bat.h"
#include "misc/crash_system.h"

/* `addi.l #0x7fff` / `andi.l #-0x8000` 0x00E08840 */
#define AREA_RS_VIRT_ALIGN      0x8000
/* `addi.l #0x3ff` / `andi.w #-0x400` 0x00E08854 */
#define AREA_RS_COMMIT_ALIGN    0x400
/* `cmpi.w #0x2` 0x00E08A30 / 0x00E08B4A: cells 0 and 1 are in the entry */
#define AREA_RS_INLINE_CELLS    2
/* `cmpi.w #-0x1,(0x14,A0)` 0x00E088CA: no BSTE */
#define AREA_RS_NO_BSTE         (-1)

/*
 * The partner's size for an area of `virt' bytes: virt plus one 1K block
 * per started 256K.  Open-coded identically at 0x00E087C4-0x00E087DE (the
 * nested procedure) and 0x00E08AE6-0x00E08B00:
 *   x := virt - 1; if x < 0 then x := x + 0x3FFFF;   (bpl / addi.l)
 *   x := sign_extend(high word of x) asr 2;            (swap/ext.l/asr.l)
 *   result := (x + 1) * 0x400 + virt
 */
static uint32_t area_$partner_size(uint32_t virt)
{
    int32_t x = (int32_t)virt - 1;

    if (x < 0) {
        x += 0x3FFFF;
    }
    x = (int32_t)(int16_t)((uint32_t)x >> 16);
    x >>= 2;
    return (uint32_t)(x + 1) * 0x400 + virt;
}

/*
 * area_$remote_sync - nested procedure 0x00E087BA (92 bytes), static link
 * `movea.l (A6),A2'.  Tells the diskless partner the area's new size:
 * REM_FILE_$GROW_AREA(&AREA_$PARTNER, entry->remote_volx, size,
 * size - virt + commit, status) with size = area_$partner_size(virt).
 */
static void area_$remote_sync(area_$entry_t *entry, uint32_t virt_size,
                              uint32_t commit_size, status_$t *status_p)
{
    uint32_t size;          /* D2 */
    uint32_t commit;        /* D0 / (-0xc,A6) */

    /* 0x00E087C4-0x00E087EC */
    size = area_$partner_size(virt_size);
    commit = size - virt_size + commit_size;

    /* 0x00E087F0-0x00E08806 */
    REM_FILE_$GROW_AREA(&AREA_$PARTNER, (uint16_t)entry->remote_volx, size,
                        commit, status_p);
}

void area_$resize(int16_t area_id, area_$entry_t *entry,
                  uint32_t virt_size, uint32_t commit_size,
                  int16_t is_grow, status_$t *status_p)
{
    uint32_t old_pages;             /* (-0x2c,A6) */
    uint32_t new_pages;             /* D5 */
    uint32_t old_virt;              /* (-0x3c,A6) */
    uint32_t old_commit;            /* D6 */
    uint32_t blocks;                /* D2 */
    uint32_t partner;               /* D2 on the roll-back path */
    uint16_t old_segs, new_segs;    /* D3w, D2w */
    int16_t k;                      /* dbf counters */
    uint16_t s;                     /* D0w */
    int16_t bste_scratch;           /* (-0x14,A6): written, never read */
    int16_t seg_scratch;            /* (-0x12,A6): written, never read */
    int16_t old_cell;               /* D7w */
    int16_t new_cell;               /* D5w */
    int16_t first_tbl;              /* (-0x4c,A6) */
    int16_t last_tbl;               /* D0w */
    uint16_t t;                     /* D2w */
    area_$seg_table_t *tbl;         /* A2 */
    area_$seg_table_t *next;        /* D2 */
    area_$seg_table_t *prev;        /* (-0x18,A6) */
    int32_t n;

    /* 0x00E08822-0x00E08838: `lsr.b #0x1` / `bcs` on the flags' low byte */
    if ((entry->flags & AREA_FLAG_ACTIVE) == 0) {
        *status_p = status_$area_not_active;
        return;
    }

    /* 0x00E0883C-0x00E0885E */
    virt_size = (virt_size + (AREA_RS_VIRT_ALIGN - 1)) & ~(uint32_t)(AREA_RS_VIRT_ALIGN - 1);
    commit_size = (commit_size + (AREA_RS_COMMIT_ALIGN - 1)) & ~(uint32_t)(AREA_RS_COMMIT_ALIGN - 1);

    /* 0x00E08862-0x00E08872 */
    if (commit_size > virt_size) {
        *status_p = status_$area_bad_reserve;
        return;
    }

    /* 0x00E08876-0x00E088A2 */
    *status_p = status_$ok;
    old_pages = entry->virt_size >> 10;
    new_pages = virt_size >> 10;
    old_virt = entry->virt_size;
    old_commit = entry->commit_size;

    if (virt_size < old_virt) {
        /* ---- shrink ---- */

        /* 0x00E088B2-0x00E088D0 */
        old_segs = (uint16_t)((old_pages + 0x20 - 1) >> 5);
        new_segs = (uint16_t)((new_pages + 0x20 - 1) >> 5);
        if (old_segs != new_segs && entry->first_bste != AREA_RS_NO_BSTE) {
            /* 0x00E088D2-0x00E08928: the loop stores and nothing reads */
            ML_$LOCK(ML_LOCK_PMAP);
            k = (int16_t)(old_segs - 1 - new_segs);
            if (k >= 0) {
                s = new_segs;
                do {
                    bste_scratch = entry->first_bste;
                    if ((entry->flags & AREA_FLAG_REVERSED) != 0) {
                        seg_scratch = (int16_t)(entry->first_seg_index - s);
                    } else {
                        seg_scratch = (int16_t)(s + entry->first_seg_index);
                    }
                    s++;
                } while (--k != -1);
                (void)bste_scratch;
                (void)seg_scratch;
            }
            ML_$UNLOCK(ML_LOCK_PMAP);
        }

        /* 0x00E0892A-0x00E08954 */
        area_$free_segments(area_id, new_pages, old_pages - 1, (int8_t)-1,
                            status_p);
        if (*status_p != status_$ok) {
            CRASH_SYSTEM(status_p);
        }

        if (entry->remote_volx == 0) {
            /* 0x00E08960-0x00E089C4 */
            if (old_commit > virt_size) {
                n = (int32_t)(old_commit - virt_size);
                if (n < 0) {
                    n += 0x3FF;
                }
                blocks = (uint32_t)(n >> 10);
                if ((blocks << 10) > old_commit) {
                    CRASH_SYSTEM(&Area_Internal_Error);
                }
                BAT_$CANCEL(entry->volx, blocks, status_p);
                if (*status_p != status_$ok) {
                    CRASH_SYSTEM(status_p);
                }
                entry->commit_size = virt_size;
            }
        } else {
            /* 0x00E089C8-0x00E089EE */
            if (is_grow != 0) {
                area_$remote_sync(entry, virt_size, commit_size, status_p);
                if (*status_p != status_$ok) {
                    return;
                }
            }
            if (virt_size < old_commit) {
                entry->commit_size = virt_size;
            }
        }
        goto done;
    }

    if (virt_size > old_virt) {
        /* ---- grow ---- */

        /* 0x00E089FA-0x00E08A14 */
        if (is_grow != 0 && entry->remote_volx != 0) {
            area_$remote_sync(entry, virt_size, commit_size, status_p);
            if (*status_p != status_$ok) {
                return;
            }
        }

        /* 0x00E08A18-0x00E08A2E */
        n = (int32_t)old_pages - 1;
        if (n < 0) {
            n = 0;
        }
        old_cell = (int16_t)((uint32_t)n >> 8);
        n = (int32_t)new_pages - 1;
        if (n < 0) {
            n += 0xFF;
        }
        new_cell = (int16_t)(n >> 8);

        if (new_cell >= AREA_RS_INLINE_CELLS) {
            /* 0x00E08A38-0x00E08A5E */
            first_tbl = 0;
            if (old_cell >= AREA_RS_INLINE_CELLS) {
                first_tbl = (int16_t)((((uint32_t)(int32_t)old_cell - 2) >> 8) + 1);
            }
            last_tbl = (int16_t)(((uint32_t)(int32_t)new_cell - 2) >> 8);
            k = (int16_t)(last_tbl - first_tbl);
            if (k >= 0) {
                t = (uint16_t)first_tbl;
                do {
                    /* 0x00E08A68-0x00E08A80 */
                    if (area_$alloc_seg_table(entry->owner_asid, area_id,
                                              (int16_t)t) == NULL) {
                        /* 0x00E08A84-0x00E08AD4: free this area's tables
                         * from the first new one on */
                        tbl = AREA_$GLOBALS.seg_table_list[entry->owner_asid];
                        prev = NULL;
                        while (tbl != NULL) {
                            next = (area_$seg_table_t *)ARCH_VA_TO_PTR(tbl->next);
                            if (tbl->area_id == area_id &&
                                (int16_t)tbl->table_index >= first_tbl) {
                                area_$free_seg_table(tbl, prev,
                                                     entry->owner_asid);
                            } else {
                                prev = tbl;
                            }
                            tbl = next;
                        }

                        /* 0x00E08AD6-0x00E08B24 */
                        if (is_grow != 0 && entry->remote_volx != 0) {
                            partner = area_$partner_size(virt_size);
                            old_commit = old_commit + partner - old_virt;
                            REM_FILE_$GROW_AREA(&AREA_$PARTNER,
                                                (uint16_t)entry->remote_volx,
                                                partner, old_commit, status_p);
                        }

                        /* 0x00E08B2A-0x00E08B34 */
                        *status_p = status_$area_no_free_resources;
                        return;
                    }
                    t++;
                } while (--k != -1);
            }
        }

        /* 0x00E08B3E-0x00E08B4E */
        if (old_pages == 0) {
            old_cell = 0;
        } else {
            old_cell++;
        }
        if (old_cell < AREA_RS_INLINE_CELLS) {
            /* 0x00E08B50-0x00E08B86 */
            if (new_cell > 1) {
                new_cell = 1;
            }
            k = (int16_t)(new_cell - old_cell);
            if (k >= 0) {
                s = (uint16_t)old_cell;
                do {
                    if (entry->seg_bitmap[(int16_t)s] != 0) {
                        CRASH_SYSTEM(&Area_Internal_Error);
                    }
                    s++;
                } while (--k != -1);
            }
        }
    }

    /* 0x00E08B8A-0x00E08BCE */
    if (old_commit < commit_size) {
        if (entry->remote_volx == 0) {
            n = (int32_t)(commit_size - old_commit);
            if (n < 0) {
                n += 0x3FF;
            }
            BAT_$RESERVE(entry->volx, (uint32_t)(n >> 10), status_p);
            if (*status_p != status_$ok) {
                return;
            }
        }
        entry->commit_size = commit_size;
    }

done:
    /* 0x00E08BD4 */
    entry->virt_size = virt_size;
}
