/*
 * NETWORK_$GET_CHKSUM - Rotate-and-add checksum of a 1KB page
 *
 * Original address: 0x00E11EF0, 20 bytes, hand-written (NETWORK_ASM).
 * Generated by: Claude Opus 5.5
 *
 * The m68k build assembles network/sau2/get_chksum.s (byte-checked against
 * the image); this file is the host-side model of that routine, compiled
 * only for the host build so the unit tests can drive it.
 *
 * D0 = 0; 256 times: D0 = rol(D0, 1) + next longword (big-endian).
 */

#include "network/network_internal.h"

#if !defined(ARCH_M68K)

uint32_t NETWORK_$GET_CHKSUM(uint32_t va)
{
    const uint8_t *p = (const uint8_t *)ARCH_VA_TO_PTR(va);   /* A0 */
    uint32_t sum = 0;                                          /* D0 */
    int16_t n = 0xFF;                                          /* D1w */

    do {
        sum = (sum << 1) | (sum >> 31);                        /* rol.l #1 */
        sum += ((uint32_t)p[0] << 24) | ((uint32_t)p[1] << 16) |
               ((uint32_t)p[2] << 8) | (uint32_t)p[3];         /* add.l (A0)+ */
        p += 4;
    } while (--n != -1);                                       /* dbf */
    return sum;
}

#endif /* !ARCH_M68K */
