/*
 * NETWORK_$INIT - Initialise the network subsystem
 *
 * Original address: 0x00E2F684 (SAU2 map: NETWORK_$INIT)
 * Size: 358 bytes (0x00E2F684 .. 0x00E2F7E9); its four constant words
 * follow at 0x00E2F7EA.
 * Generated by: Claude Opus 5.5
 *
 * Called once by OS_$INIT.  Empties the network table, starts the packet,
 * buffer, message, I/O, routing, MAC and XNS layers, sets the allowed
 * services, takes a header page, finds the ring controller and starts one
 * page server, and primes the servers' next wait values.
 *
 * Frame (link.w A6,-0x10; nothing saved; A5 not loaded - the NETWORK
 * segment is addressed absolutely, `movea.l #0xe248fc`):
 *   (-0x08) the SET_SERVICE record (word flags, word pool size)
 *   (-0x04) ppn from WP_$CALLOC, (-0x0C) status
 *
 * Blocks:
 *   0x00E2F688-0x00E2F69E  NETWORK_$NET_TABLE[1..64] = 0 (moveq #0x3f/dbf)
 *   0x00E2F6A2-0x00E2F6F2  PKT_$INIT; SET_SERVICE(2, 0x17 if port 0's
 *                          routing bit is set, else 0); SET_SERVICE(3,
 *                          pool 0); NETBUF_$INIT, MSG_$INIT
 *   0x00E2F6F8-0x00E2F73E  a page for NETWORK_$HDR_PAGE (map failure
 *                          crashes)
 *   0x00E2F740-0x00E2F752  NET_IO_$INIT, RIP_$INIT, MAC_OS_$INIT,
 *                          XNS_IDP_$INIT
 *   0x00E2F758-0x00E2F780  the ring's DCTE (controller 2, unit 0), 0 if
 *                          there is none
 *   0x00E2F782-0x00E2F79E  page servers wait for EC values 1, 0,
 *                          NETLOG_$EC + 1 and TIME_$CLOCKH + 4
 *   0x00E2F7A2-0x00E2F7C0  NETWORK_$ADD_PAGE_SERVERS(1) (failure crashes)
 *   0x00E2F7C2-0x00E2F7E2  request server waits 1, 1, 1 and
 *                          TIME_$CLOCKH + 0x3C; NETWORK_$AGE_TICKS = 0
 *
 * Quirks reproduced:
 *   - WP_$CALLOC's status is not looked at; only NETBUF_$GETVA's is.
 *   - The first SET_SERVICE record's pool word (-0x06) is not written
 *     before the call; operation 2 reads only the flags word.  The C starts
 *     it at 0.
 *   - The constant word 2 at 0x00E2F7EA is both SET_SERVICE's operation and
 *     IO_$GET_DCTE's controller type.
 */

#include "network/network_internal.h"
#include "io/io.h"
#include "mac_os/mac_os.h"
#include "misc/misc.h"
#include "msg/msg.h"
#include "net_io/net_io.h"
#include "netbuf/netbuf.h"
#include "netlog/netlog.h"
#include "pkt/pkt.h"
#include "rip/rip.h"
#include "route/route.h"
#include "time/time.h"
#include "wp/wp.h"
#include "xns/xns.h"

/*
 * The four constant words after the code, `gsk read 0xE2F7EA 8` =
 * 00 02 00 01 00 00 00 03:
 *   0x00E2F7EA  2  `pea (0x124,PC)` 0x00E2F6C4 and `pea (0x88,PC)` 0x00E2F760
 *   0x00E2F7EC  1  `pea (0x44,PC)` 0x00E2F7A6
 *   0x00E2F7EE  0  `pea (0x90,PC)` 0x00E2F75C
 *   0x00E2F7F0  3  `pea (0x110,PC)` 0x00E2F6DE
 */
static const uint16_t network_$init_two = 2;
static const uint16_t network_$init_one = 1;
static const uint16_t network_$init_zero = 0;
static const uint16_t network_$init_three = 3;

/* Services allowed when port 0 routes (`move.w #0x17,(-0x8,A6)` 0x00E2F6B6) */
#define NETWORK_INIT_ROUTING_SERVICE    0x17

/* Wait deltas on the clock (`addq.l #0x4`, `moveq #0x3c`) */
#define NETWORK_INIT_PAGE_CLOCK_DELTA   4
#define NETWORK_INIT_RQST_CLOCK_DELTA   0x3C

void NETWORK_$INIT(void)
{
    uint32_t svc;                       /* (-0x08,A6): two words */
    uint32_t ppn;                       /* (-0x04,A6) */
    status_$t status;                   /* (-0x0C,A6) */
    uint32_t pa;
    int16_t i;

    /* 0x00E2F688-0x00E2F69E */
    for (i = 0x3F; i >= 0; i--) {
        NETWORK_$NET_TABLE[0x40 - i].refcount = 0;
        NETWORK_$NET_TABLE[0x40 - i].net_id = 0;
    }

    /* 0x00E2F6A2-0x00E2F6F2 */
    PKT_$INIT();
    if (ROUTE_$PORT_ARRAY[0].active == 0) {
        svc = 0;
    } else {
        svc = (uint32_t)NETWORK_INIT_ROUTING_SERVICE << 16;
    }
    NETWORK_$SET_SERVICE((int16_t *)&network_$init_two, &svc, &status);
    svc &= 0xFFFF0000u;                                 /* clr.w (-0x6,A6) */
    NETWORK_$SET_SERVICE((int16_t *)&network_$init_three, &svc, &status);
    NETBUF_$INIT();
    MSG_$INIT();

    /* 0x00E2F6F8-0x00E2F73E */
    WP_$CALLOC(&ppn, &status);
    pa = ppn << 10;
    NETWORK_$HDR_PAGE_PA = pa;
    NETBUF_$GETVA(pa, &NETWORK_$HDR_PAGE, &status);
    if (status != status_$ok) {
        CRASH_SYSTEM(&status);
    }

    /* 0x00E2F740-0x00E2F752 */
    NET_IO_$INIT();
    RIP_$INIT();
    MAC_OS_$INIT();
    XNS_IDP_$INIT();

    /* 0x00E2F758-0x00E2F780 */
    NETWORK_$RING_DCTE = ARCH_PTR_TO_VA(
        IO_$GET_DCTE((uint16_t *)&network_$init_two,
                     (uint16_t *)&network_$init_zero, &status));
    if (status != status_$ok) {
        NETWORK_$RING_DCTE = 0;
    }

    /* 0x00E2F782-0x00E2F79E */
    NETWORK_$PAGE_WAIT[0] = 1;
    NETWORK_$PAGE_WAIT[1] = 0;
    NETWORK_$PAGE_WAIT[2] = (uint32_t)NETLOG_$EC.value + 1;
    NETWORK_$PAGE_WAIT[3] = TIME_$CLOCKH + NETWORK_INIT_PAGE_CLOCK_DELTA;

    /* 0x00E2F7A2-0x00E2F7C0 */
    NETWORK_$ADD_PAGE_SERVERS((int16_t *)&network_$init_one, &status);
    if (status != status_$ok) {
        CRASH_SYSTEM(&status);
    }

    /* 0x00E2F7C2-0x00E2F7E2 */
    NETWORK_$RQST_WAIT[0] = 1;
    NETWORK_$RQST_WAIT[1] = 1;
    NETWORK_$RQST_WAIT[2] = 1;
    NETWORK_$RQST_WAIT[3] = TIME_$CLOCKH + NETWORK_INIT_RQST_CLOCK_DELTA;
    NETWORK_$AGE_TICKS = 0;
}
