/*
 * NETWORK_$LOAD - late network start-up (after PROC2_$INIT)
 *
 * Original address: 0x00E2F7F2
 * Size: 86 bytes (0x00E2F7F2 .. 0x00E2F847), then the 4-byte constant
 * record at 0x00E2F848
 * Generated by: Claude Opus 5.5
 *
 * Called by OS_$INIT (0x00E34738).  No arguments.
 *
 * Blocks:
 *   0x00E2F7FA-0x00E2F804  port = &ROUTE_$PORT_ARRAY[0] (`movea.l
 *                          #0xe2e0a0,A2', the array itself, not
 *                          ROUTE_$PORTP[0]); an inactive port (word +0x2C
 *                          zero) ends the routine
 *   0x00E2F806-0x00E2F80E  a driver without a +0x1C entry
 *                          (route_$driver_info_t.attach_service) ends it
 *   0x00E2F810-0x00E2F82A  call the entry with (&port->socket,
 *                          &network_$load_service_rec, 0, &(-0xa,A6),
 *                          &status) and a word result slot that is dropped
 *   0x00E2F82E-0x00E2F838  a non-zero status crashes the system
 */

#include "network/network_internal.h"
#include "route/route.h"        /* ROUTE_$PORT_ARRAY, route_$driver_info_t */
#include "misc/crash_system.h"  /* CRASH_SYSTEM */

/* `pea (0x2a,PC)' at 0x00E2F81C: the two words at 0x00E2F848
 * (`gsk read 0xE2F848 4` = 00 00 00 00), right after the rts. */
static const uint16_t network_$load_service_rec[2] = { 0x0000, 0x0000 };

void NETWORK_$LOAD(void)
{
    route_$port_t *port;                /* A2 */
    route_$driver_info_t *driver;       /* A3 */
    uint8_t out4[6];                    /* (-0xa,A6), never initialised */
    status_$t status;                   /* (-0x4,A6) */

    /* 0x00E2F7FA-0x00E2F804 */
    port = &ROUTE_$PORT_ARRAY[0];
    if (port->active != 0) {
        /* 0x00E2F806-0x00E2F80E */
        driver = (route_$driver_info_t *)ARCH_VA_TO_PTR(port->driver_info);
        if (driver->attach_service != 0) {
            /* 0x00E2F810-0x00E2F82A */
            ((route_$set_service_fn_t)ARCH_VA_TO_PTR(driver->attach_service))(
                &port->socket, network_$load_service_rec, 0, out4, &status);
            /* 0x00E2F82E-0x00E2F838 */
            if (status != status_$ok) {
                CRASH_SYSTEM(&status);
            }
        }
    }
}
