/*
 * NETWORK_$REPORT_FAILURE - Record a transmit failure and announce it
 *
 * Original address: 0x00E103FA (SAU2 map: NETWORK, NETWORK_$REPORT_FAILURE
 * at E103FA)
 * Size: 274 bytes (0x00E103FA .. 0x00E1050B); the zero longword that
 * follows at 0x00E1050C is this routine's constant (shared with
 * NETWORK_$REQUEST_SERVER).
 * Generated by: Claude Opus 5.5
 *
 * Fills NETWORK_$FAILURE_REC (A5+0x2F8) with the time, TRUE, this node and a
 * failure type - 1 when bit 5 of the caller's transmit-status word is set,
 * else 3 - and sends an 8-byte message { 0x0003000E, type } to socket 4 of
 * "node" <type> with packet flags 0x90.
 *
 * Frame (link.w A6,-0x54; D2/A2/A5 saved; A5 = 0xE248FC):
 *   (0x08,A6) xmit_status  -> word; `btst.b #5,(0x1,A0)` reads its low byte
 *   (-0x20,A6) pkt_info     NETWORK_$SERVER_PKT_INFO copy, flags = 0x90
 *   (-0x38,A6) msg          two longwords
 *   (-0x3C,A6) send_info    (-0x40,A6) hdr_pa     (-0x48,A6) hdr_va
 *   (-0x4C,A6) status       (-0x4E,A6) timeout    (-0x50,A6) retry
 *   (-0x52,A6) port         (-0x54,A6) hdr_len
 *
 * Quirks reproduced:
 *   - NETWORK_$GETHDR is handed &NETWORK_$FAILURE_REC.failure_type as its
 *     node argument (`pea (0x304,A5)` at 0x00E1045E), and the same value is
 *     the destination node of the internet header.
 *   - The send status is not looked at, and the header is returned whenever
 *     its address is non-zero.
 */

#include "network/network_internal.h"
#include "net_io/net_io.h"
#include "node/node.h"
#include "time/time.h"

/* The message type: `move.l #0x3000e,(-0x38,A6)` at 0x00E10432 */
#define NETWORK_FAILURE_MSG_TYPE    0x0003000E
#define NETWORK_FAILURE_MSG_LEN     0x18        /* 0x00E10488 #0x180000 */
#define NETWORK_FAILURE_DEST_SOCK   4
#define NETWORK_FAILURE_PKT_FLAGS   0x90        /* 0x00E10450 */
#define NETWORK_FAILURE_TYPE_BIT5   1           /* 0x00E10428 */
#define NETWORK_FAILURE_TYPE_OTHER  3           /* 0x00E1042C */

/*
 * 0x00E1050C: 00 00 00 00, reached PC-relative from 0x00E104D2 and from
 * NETWORK_$REQUEST_SERVER (0x00E11CBA, 0x00E11CEA, 0x00E11D36).
 */
const uint32_t network_$c_zero_long = 0;

void NETWORK_$REPORT_FAILURE(uint16_t *xmit_status)
{
    pkt_$info_t pkt_info;          /* (-0x20,A6) */
    uint32_t msg[2];               /* (-0x38,A6) */
    net_io_$send_info_t send_info; /* (-0x3C,A6) */
    uint32_t hdr_pa;               /* (-0x40,A6) */
    uint32_t hdr_va;               /* (-0x48,A6) */
    status_$t status;              /* (-0x4C,A6) */
    uint16_t timeout;              /* (-0x4E,A6) */
    uint16_t retry;                /* (-0x50,A6) */
    int16_t port;                  /* (-0x52,A6) */
    uint16_t hdr_len;              /* (-0x54,A6) */
    uint32_t hdr;                  /* A2 / D2 */
    const uint8_t *src;
    uint8_t *dst;
    int i;

    /* 0x00E10408-0x00E1042E */
    NETWORK_$FAILURE_REC.timestamp = TIME_$CLOCKH;
    NETWORK_$FAILURE_REC.flag = (int8_t)0xFF;
    NETWORK_$FAILURE_REC.node_id = NODE_$ME;
    if ((*xmit_status & 0x0020) != 0) {
        NETWORK_$FAILURE_REC.failure_type = NETWORK_FAILURE_TYPE_BIT5;
    } else {
        NETWORK_$FAILURE_REC.failure_type = NETWORK_FAILURE_TYPE_OTHER;
    }

    /* 0x00E10432-0x00E10450 */
    msg[0] = NETWORK_FAILURE_MSG_TYPE;
    msg[1] = NETWORK_$FAILURE_REC.failure_type;
    src = (const uint8_t *)&NETWORK_$SERVER_PKT_INFO;
    dst = (uint8_t *)&pkt_info;
    for (i = 0; i < NETWORK_SERVER_PKT_INFO_LEN; i++) {
        dst[i] = src[i];
    }
    pkt_info.flags = NETWORK_FAILURE_PKT_FLAGS;

    /* 0x00E10456-0x00E104B8 */
    NETWORK_$GETHDR(&NETWORK_$FAILURE_REC.failure_type, &hdr_va, &hdr_pa);
    hdr = hdr_va;
    PKT_$BLD_INTERNET_HDR(0, NETWORK_$FAILURE_REC.failure_type,
                          NETWORK_FAILURE_DEST_SOCK, -1, NODE_$ME, 0,
                          &pkt_info, 0, msg, NETWORK_FAILURE_MSG_LEN, 0,
                          &port, (pkt_$hdr_t *)ARCH_VA_TO_PTR(hdr), &hdr_len,
                          &retry, &timeout, &status);

    /* 0x00E104BA-0x00E104EE */
    if (status == status_$ok) {
        hdr_va = hdr;
        NET_IO_$SEND(port, &hdr_va, hdr_pa, hdr_len, 0,
                     (uint32_t *)&network_$c_zero_long, 0,
                     NETWORK_$REPORT_SEND_FLAGS, &send_info, &status);
    }

    /* 0x00E104F2-0x00E10500 */
    if (hdr != 0) {
        hdr_va = hdr;
        NETWORK_$RTNHDR(&hdr_va);
    }
}
