/*
 * route/test/test_route_data.c - the ROUTE module data blocks (source-ybch)
 *
 * Generated by: Claude Opus 5.5
 *
 * route/route_data.c is #included, so the objects under test are the real
 * blocks with the image's contents:
 *
 *   ROUTE_$WIRED_DATA    map "D E26EE4 ROUTE_WIRED size = 3C"
 *   ROUTE_$UNWIRED_DATA  map "D E825DC ROUTE_UNWIRED size = 8"
 *   ROUTE_$RTWIRED_DATA  map "D E87D80 ROUTE_RTWIRED size = 4A8"
 *
 * Checked: image addresses and sizes, the A5 offsets that hold on every
 * build (the ones behind a pointer-bearing cell are asserted at compile time
 * on the target only), the per-index tables' strides and end points, and the
 * initial contents.
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

/* ==========================================================================
 * Test framework
 * ========================================================================== */

static int tests_failed = 0;
static int tests_run = 0;

#define TEST(name) static void test_##name(void)
#define RUN_TEST(name)                                                        \
    do {                                                                      \
        printf("  Running %s... ", #name);                                    \
        tests_run++;                                                          \
        test_##name();                                                        \
        printf("done\n");                                                     \
    } while (0)

#define ASSERT_EQ(expected, actual)                                           \
    do {                                                                      \
        long long _e = (long long)(expected);                                 \
        long long _a = (long long)(actual);                                   \
        if (_e != _a) {                                                       \
            printf("FAILED\n    Expected: 0x%llx, Got: 0x%llx at line %d\n",  \
                   (unsigned long long)_e, (unsigned long long)_a, __LINE__); \
            tests_failed++;                                                   \
            return;                                                           \
        }                                                                     \
    } while (0)

#include "route/route_internal.h"
#include "../route_data.c"

#define OFF(block, field) \
    ((size_t)((const uint8_t *)&(field) - (const uint8_t *)&(block)))

/* ==========================================================================
 * Tests
 * ========================================================================== */

TEST(block_addresses_and_sizes)
{
    ASSERT_EQ(0x00E26EE4u, MODULE_DATA_ADDR(ROUTE_$WIRED_DATA));
    ASSERT_EQ(0x00E825DCu, MODULE_DATA_ADDR(ROUTE_$UNWIRED_DATA));
    ASSERT_EQ(0x00E87D80u, MODULE_DATA_ADDR(ROUTE_$RTWIRED_DATA));
    ASSERT_EQ(ROUTE_$UNWIRED_DATA_SIZE, sizeof(ROUTE_$UNWIRED_DATA));
    ASSERT_EQ(8, sizeof(route_$unwired_data_t));
    /* RTWIRED_DATA_END, the wired region's end (cell 0x00E69C00) */
    ASSERT_EQ(0x00E88228u,
              MODULE_DATA_ADDR(ROUTE_$RTWIRED_DATA) + ROUTE_$RTWIRED_DATA_SIZE);
}

TEST(wired_offsets)
{
    ASSERT_EQ(0x00, OFF(ROUTE_$WIRED_DATA, ROUTE_$WIRED_DATA.sock_ecval));
    ASSERT_EQ(ROUTE_$MAX_PORTS,
              sizeof(ROUTE_$WIRED_DATA.portp) / sizeof(ROUTE_$WIRED_DATA.portp[0]));
}

TEST(unwired_offsets)
{
    ASSERT_EQ(0x00, OFF(ROUTE_$UNWIRED_DATA, ROUTE_$UNWIRED_DATA.start_time));
    ASSERT_EQ(0x04, OFF(ROUTE_$UNWIRED_DATA, ROUTE_$UNWIRED_DATA.announce_template));
}

/* The map's symbols inside ROUTE_RTWIRED, as A5 = 0xE87D80 offsets. */
TEST(rtwired_offsets)
{
#define RT(field) OFF(ROUTE_$RTWIRED_DATA, ROUTE_$RTWIRED_DATA.field)
    ASSERT_EQ(0x00E87D80u - 0x00E87D80u, RT(wired_pages));
    ASSERT_EQ(0x00E87DA8u - 0x00E87D80u, RT(q_depth));
    ASSERT_EQ(0x00E87FACu - 0x00E87D80u, RT(std_dlen_err));
    ASSERT_EQ(0x00E87FB0u - 0x00E87D80u, RT(std_too_far));
    ASSERT_EQ(0x00E87FB4u - 0x00E87D80u, RT(std_misroute));
    ASSERT_EQ(0x00E87FB8u - 0x00E87D80u, RT(std_pkts_routed));
    ASSERT_EQ(0x00E87FBCu - 0x00E87D80u, RT(dlen_err));
    ASSERT_EQ(0x00E87FC0u - 0x00E87D80u, RT(too_far));
    ASSERT_EQ(0x00E87FC4u - 0x00E87D80u, RT(misroute));
    ASSERT_EQ(0x00E87FC8u - 0x00E87D80u, RT(pkts_routed));
    ASSERT_EQ(0x00E87FCCu - 0x00E87D80u, RT(q_oflo));
    ASSERT_EQ(0x00E87FD0u - 0x00E87D80u, RT(netbuf_alloc));
    ASSERT_EQ(0x00E87FD2u - 0x00E87D80u, RT(n_wired_pages));
    ASSERT_EQ(0x00E87FD4u - 0x00E87D80u, RT(n_user_ports));
    ASSERT_EQ(0x00E87FD6u - 0x00E87D80u, RT(user_stat));
    ASSERT_EQ(0x00E88216u - 0x00E87D80u, RT(pid));
    ASSERT_EQ(0x00E88218u - 0x00E87D80u, RT(user_checksum));
    ASSERT_EQ(0x49C, RT(service_id));
#undef RT
}

/* wired_pages[0..9], q_depth[0..0x80] and user_stat records 1..4. */
TEST(rtwired_tables)
{
    int i;

    for (i = 0; i < ROUTE_$MAX_WIRED_PAGES; i++) {
        ASSERT_EQ(i * 4, OFF(ROUTE_$RTWIRED_DATA, ROUTE_$RTWIRED_DATA.wired_pages[i]));
    }
    ASSERT_EQ(0x28, OFF(ROUTE_$RTWIRED_DATA,
                        ROUTE_$RTWIRED_DATA.wired_pages[ROUTE_$MAX_WIRED_PAGES - 1]) + 4);

    /* "addq.l #0x1,(0x28,A5,D1*0x1)", D1 = depth*4, depth capped at 0x80 */
    for (i = 0; i <= 0x80; i++) {
        ASSERT_EQ(0x28 + i * 4, OFF(ROUTE_$RTWIRED_DATA, ROUTE_$RTWIRED_DATA.q_depth[i]));
    }
    ASSERT_EQ(0x22C, OFF(ROUTE_$RTWIRED_DATA, ROUTE_$RTWIRED_DATA.q_depth[0x80]) + 4);

    /* Pascal [1..4]: record n at ROUTE_$USER_STAT + n*0x90 - 0x90
     * (0x00E5A664), reached through ROUTE_USER_STAT_ENTRY(n) */
    for (i = 1; i <= ROUTE_$MAX_USER_STATS; i++) {
        ASSERT_EQ(0x256 + i * 0x90 - 0x90,
                  OFF(ROUTE_$RTWIRED_DATA, ROUTE_USER_STAT_ENTRY(i)));
    }
    ASSERT_EQ(0x256, OFF(ROUTE_$RTWIRED_DATA, ROUTE_USER_STAT_ENTRY(1)));
    ASSERT_EQ(0x90, sizeof(ROUTE_USER_STAT_ENTRY(1)));
    ASSERT_EQ(0x496, OFF(ROUTE_$RTWIRED_DATA,
                         ROUTE_$RTWIRED_DATA.user_stat[ROUTE_$MAX_USER_STATS - 1]) + 0x90);
}

/* `gsk read 0xE26EE4 0x3C`, `gsk read 0xE825DC 8`, `gsk read 0xE87D80 1192` */
TEST(initial_contents_match_the_image)
{
    int i;

    ASSERT_EQ(0, ROUTE_$WIRED_DATA.sock_ecval);
    for (i = 0; i < ROUTE_$MAX_PORTS; i++) {
        /* image: 0xE2E0A0 + i*0x5C */
        ASSERT_EQ((uintptr_t)&ROUTE_$PORT_ARRAY[i], (uintptr_t)ROUTE_$WIRED_DATA.portp[i]);
    }
    ASSERT_EQ(0x5C, sizeof(route_$port_t));
    ASSERT_EQ(0, ROUTE_$WIRED_DATA.control_ecval);
    ASSERT_EQ(0, ROUTE_$WIRED_DATA.control_ec.value);
    ASSERT_EQ(0xFFFF, ROUTE_$WIRED_DATA.sock);
    ASSERT_EQ(0, ROUTE_$WIRED_DATA.std_n_routing_ports);
    ASSERT_EQ(0, ROUTE_$WIRED_DATA.n_routing_ports);
    ASSERT_EQ(0, ROUTE_$WIRED_DATA.routing);

    ASSERT_EQ(0, ROUTE_$UNWIRED_DATA.start_time);
    ASSERT_EQ(2, ROUTE_$UNWIRED_DATA.announce_template);

    for (i = 0; i < ROUTE_$MAX_WIRED_PAGES; i++) {
        ASSERT_EQ(0, ROUTE_$RTWIRED_DATA.wired_pages[i]);
    }
    for (i = 0; i <= 0x80; i++) {
        ASSERT_EQ(0, ROUTE_$RTWIRED_DATA.q_depth[i]);
    }
    ASSERT_EQ(0, ROUTE_$RTWIRED_DATA.q_oflo);
    ASSERT_EQ(0, ROUTE_$RTWIRED_DATA.netbuf_alloc);
    ASSERT_EQ(0, ROUTE_$RTWIRED_DATA.n_user_ports);
    ASSERT_EQ(0, ROUTE_$RTWIRED_DATA.pid);
    ASSERT_EQ(0, ROUTE_$RTWIRED_DATA.user_checksum);
    ASSERT_EQ(0, ROUTE_$RTWIRED_DATA.service_id);
    /* image 0x00E26F0C = &ROUTE_$WIRED_DATA.control_ec */
    ASSERT_EQ((uintptr_t)&ROUTE_$WIRED_DATA.control_ec,
              (uintptr_t)ROUTE_$RTWIRED_DATA.ptr_control_ec);
    ASSERT_EQ(1, ROUTE_$RTWIRED_DATA.fwd_timeout);
    ASSERT_EQ(0x8000, ROUTE_$RTWIRED_DATA.packet_seq);
}

int main(void)
{
    printf("ROUTE module data tests\n");

    RUN_TEST(block_addresses_and_sizes);
    RUN_TEST(wired_offsets);
    RUN_TEST(unwired_offsets);
    RUN_TEST(rtwired_offsets);
    RUN_TEST(rtwired_tables);
    RUN_TEST(initial_contents_match_the_image);

    printf("%d tests, %d failed\n", tests_run, tests_failed);
    return tests_failed != 0;
}
