/*
 * hint/hint_data.c - HINT module data
 *
 * Generated by: Claude Opus 5.5
 *
 * source-702z: the HINT cells were absolute-address macros on the target and
 * separate objects on the host; they are now one definition each, the same
 * on every build (docs/design-per-process-data.md).  Declarations and layout
 * asserts in hint/hint_internal.h.
 *
 *   0x00E7DB50  HINT_$DATA            map "D E7DB50 HINT_ size = 28"
 *   0x00E2459C  HINT_$HINTFILE_PTR    map NET_ASM, symbol at its start
 *   0x00E2C034  HINT_$EXCLUSION_LOCK  map "D E2C034 HINT_WIRED size = 14"
 */

#include "hint/hint_internal.h"

/*
 * HINT_$DATA, 0x00E7DB50..0x00E7DB77 (`gsk read 0xE7DB50 0x28`): zero except
 *
 *   0x00E7DB76  00 01        bucket_index: HINT_$add_internal's first
 *                            round-robin victim is slot 1
 */
MODULE_DATA_DEFINE_INIT(hint_globals_t, HINT_$DATA, 0x00E7DB50, {
    .bucket_index = 1,
});

/* Zero in the image (`gsk read 0xE2459C 4`). */
hint_file_t *HINT_$HINTFILE_PTR;

/* Zero in the image (`gsk read 0xE2C034 0x14`). */
ml_$exclusion_t HINT_$EXCLUSION_LOCK;
