/*
 * MST_$CHANGE_RIGHTS - remap a VA range with new access rights
 *
 * Original address: 0x00E42FB0 (SAU2 map: MST_$CHANGE_RIGHTS at E42FB0)
 * Size: 288 bytes (0x00E42FB0 .. 0x00E430CF)
 * Generated by: Claude Opus 5.5
 *
 * SVC slot 0x4B (svc/svc_tables.c; DATA xref 0x00E7BA12), every argument
 * by reference.  Frame (link.w A6,-0x20; D2-D4/A2-A3/A5 saved; A5 =
 * 0xE7CF0C, MST_UNWIRED, never used):
 *   (0x08,A6) va_ptr      (A3)
 *   (0x0C,A6) length_ptr  (D3)
 *   (0x10,A6) rights_ptr  -> a word, the new rights
 *   (0x14,A6) status      (A2)
 *   locals: (-0x08) uid, (-0x0C) map_info, (-0x10) entry, (-0x14) the
 *   restore status, (-0x1A) prot, (-0x1C) access; D2w the object offset,
 *   D4w the touch count.
 *
 * Blocks:
 *   0x00E42FCA-0x00E42FEE  the MSTE for *va_ptr; a nonzero low status word
 *                          returns
 *   0x00E42FF2-0x00E43024  UID, object offset, access (bit 15 of the word
 *                          at +0x0A) and touch count ((byte +0x0C & 0x7C)
 *                          >> 2, plus one) from the MSTE
 *   0x00E43028-0x00E43048  MST_$UNMAP_PRIVI mode 2 in the current ASID
 *   0x00E4304A-0x00E43082  if that worked, map the range again with the new
 *                          rights; if that worked too, return
 *   0x00E43084-0x00E430C0  otherwise map it again with the old rights (the
 *                          prot word) under ACL_$ENTER_SUPER, its status
 *                          into a local
 *
 * Quirks reproduced:
 *   - The object offset is word arithmetic: `lsl.w #8` + `lsl.w #7` of the
 *     MSTE segment keeps only its bit 0, so the offset is
 *     ((segment & 1) << 15) + (va & 0x7FFF), zero-extended.
 *   - The first status test is `tst.w (0x2,A2)`, the low word only.
 *   - After a failed unmap the restore mapping still runs.
 */

#include "mst/mst_internal.h"
#include "acl/acl.h"

/* `move.w #0x2,-(SP)` 0x00E4303A: MST_$UNMAP_PRIVI mode */
#define MST_CHANGE_RIGHTS_UNMAP_MODE    2

void MST_$CHANGE_RIGHTS(uint32_t *va_ptr, uint32_t *length_ptr,
                        uint16_t *rights_ptr, status_$t *status)
{
    uid_t uid;                  /* (-0x08,A6) */
    uint32_t map_info;          /* (-0x0C,A6) */
    void *entry;                /* (-0x10,A6) */
    status_$t restore_status;   /* (-0x14,A6) */
    uint16_t prot;              /* (-0x1A,A6) */
    int8_t access;              /* (-0x1C,A6) */
    uint16_t offset;            /* D2w */
    uint16_t touch_count;       /* D4w */
    mste_t *mste;

    /* 0x00E42FCA-0x00E42FEE */
    mst_$va_to_pte(PROC1_$AS_ID, *va_ptr, &prot, &entry, status);
    if ((uint16_t)*status != 0) {
        return;
    }

    /* 0x00E42FF2-0x00E43024 */
    mste = (mste_t *)entry;
    uid = mste->uid;
    offset = (uint16_t)((uint16_t)(mste->segment << 15) +
                        ((uint16_t)*va_ptr & 0x7FFFu));
    access = ((int16_t)mste->unknown_0a < 0) ? (int8_t)-1 : 0;
    touch_count = (uint16_t)((((mste->location >> 24) & 0x7Cu) >> 2) + 1);

    /* 0x00E43028-0x00E43048 */
    MST_$UNMAP_PRIVI(MST_CHANGE_RIGHTS_UNMAP_MODE, &uid, *va_ptr, *length_ptr,
                     PROC1_$AS_ID, status);
    if (*status == status_$ok) {
        /* 0x00E4304A-0x00E43082 */
        mst_$alloc_segs(*va_ptr, &uid, (uint32_t)offset, *length_ptr, 0,
                        (int16_t)PROC1_$AS_ID, *rights_ptr, touch_count,
                        (uint8_t)access, false, &map_info, status);
        if (*status == status_$ok) {
            return;
        }
    }

    /* 0x00E43084-0x00E430C0 */
    ACL_$ENTER_SUPER();
    mst_$alloc_segs(*va_ptr, &uid, (uint32_t)offset, *length_ptr, 0,
                    (int16_t)PROC1_$AS_ID, prot, touch_count, (uint8_t)access,
                    false, &map_info, &restore_status);
    ACL_$EXIT_SUPER();
}
