/*
 * MST_$FORK - Clone the current address space's MST into a child's
 *
 * Original address: 0x00E739F8 (SAU2 map: MST_$FORK)
 * Size: 448 bytes (0x00E739F8 .. 0x00E73BB7)
 * Generated by: Claude Opus 5.5
 *
 * Called once, by PROC2_$FORK (0x00E72F52).  Under the ASID lock (0xC):
 * give the child a table page for every MST page the current address space
 * has, copy every segment entry, and give each private anonymous area the
 * parent owns a copy (AREA_$COPY) that the child's entries then name.
 *
 * Frame (link.w A6,-0x2c; D2-D6/A2-A5 saved; A5 = 0xE85714 loaded, never
 * used):
 *   (0x08,A6) asid word (D3)   (0x0A,A6) pid word
 *   (0x0C,A6) flags long, copied to (-0x04)   (0x10,A6) status
 *   (-0x22) the parent's MST base, D6w the child's, D4w the parent asid
 *   (-0x08) the last area handle copied, (-0x10) its copy, (-0x0C) the
 *   entry's handle, (-0x1C) status, (-0x28) the page loop counter
 *
 * Blocks:
 *   0x00E73A12-0x00E73A3A  D4 = PROC1_$AS_ID; ML_$LOCK(0xC); both bases
 *   0x00E73A3E-0x00E73A86  for each of the MST_$SEG_TN/64 table pages the
 *                          parent has: MST_$ALLOC_TABLE_PAGE(asid, page*64,
 *                          &MST[child base + page]); a failure unlocks and
 *                          returns its status
 *   0x00E73A8A-0x00E73B98  for each such page, the 64 entries: copy the
 *                          16 bytes; an entry whose UID high is ANON_$UID's
 *                          and whose area (by the handle in uid.low) has
 *                          the handle's generation and is owned by the
 *                          parent gets the area's copy - AREA_$COPY once
 *                          per run of equal handles - and its flags' low 9
 *                          bits (cached ASTE) cleared.  A copy failure
 *                          unlocks and returns its status
 *   0x00E73B9C-0x00E73BAC  ML_$UNLOCK(0xC); status 0
 *
 * Quirks reproduced:
 *   - Only the handle of the previous copy is remembered: an entry whose
 *     handle equals it reuses that copy (0x00E73B34), so a handle of 0
 *     would reuse the not-yet-set (-0x10) - here 0, see below.
 *   - The page loop counts (-0x28) down with `subq.w #1 / bcc'.
 *   - The flags longword is forwarded to AREA_$COPY untouched.
 */

#include "mst/mst_internal.h"
#include "anon/anon.h"
#include "area/area.h"
#include "proc1/proc1.h"

/* ML_$LOCK / ML_$UNLOCK id, `move.w #0xc,-(SP)` 0x00E73A1A / 0x00E73B9E */
#define MST_FORK_LOCK           MST_LOCK_ASID

/* MSTE pages hold 64 16-byte entries (`moveq #0x3f` / dbf, `lsl.w #0x6`) */
#define MST_FORK_ENTRIES_M1     0x3F
#define MST_FORK_SEG_SHIFT      6

/* `andi.w #-0x200,(0xa,A3)`: the cached ASTE index in the flags word */
#define MST_FORK_FLAGS_KEEP     0xFE00

static mst_entry_t *mst_$fork_page(uint16_t table_page)
{
    /* MSTE_PAGES + page*0x400 - 0x400 (0x00E73AC0-0x00E73AD4) */
    return (mst_entry_t *)ARCH_VA_TO_PTR(MST_PAGE_TABLE_BASE +
                                         (uint32_t)table_page * 0x400u -
                                         0x400u);
}

void MST_$FORK(uint16_t asid, uint16_t pid, uint32_t flags, status_$t *status)
{
    uint32_t fork_flags;                /* (-0x04,A6) */
    uint32_t last_handle;               /* (-0x08,A6) */
    uint32_t handle;                    /* (-0x0C,A6) */
    uint32_t new_handle;                /* (-0x10,A6) */
    status_$t st;                       /* (-0x1C,A6) */
    uint16_t parent_base;               /* (-0x22,A6) */
    uint16_t pages_left;                /* (-0x28,A6) */
    uint16_t parent_asid;               /* D4w */
    uint16_t child_base;                /* D6w */
    uint16_t page;                      /* D5w */
    int16_t n;                          /* D0w / D2w */
    int16_t e;                          /* D2w */
    mst_entry_t *src;                   /* A2 */
    mst_entry_t *dst;                   /* A3 */
    area_$entry_t *area;

    /* 0x00E73A06-0x00E73A3A */
    fork_flags = flags;
    parent_asid = PROC1_$AS_ID;
    ML_$LOCK(MST_FORK_LOCK);
    parent_base = MST_ASID_BASE[parent_asid];
    child_base = MST_ASID_BASE[asid];

    /* 0x00E73A3E-0x00E73A86 */
    n = (int16_t)((MST_$SEG_TN >> MST_FORK_SEG_SHIFT) - 1);
    if (n >= 0) {
        page = 0;
        do {
            if (MST[(uint16_t)(parent_base + page)] != 0) {
                st = MST_$ALLOC_TABLE_PAGE(asid,
                                           (uint16_t)(page << MST_FORK_SEG_SHIFT),
                                           &MST[(uint16_t)(child_base + page)]);
                if (st != status_$ok) {
                    goto fail;
                }
            }
            page++;
        } while (--n != -1);
    }

    /* 0x00E73A8A-0x00E73B98 */
    last_handle = 0;
    /* (-0x10) is not written before the first AREA_$COPY; the C starts it
     * at 0 so a zero handle (which the image would pair with the stale
     * frame word) is at least deterministic */
    new_handle = 0;
    n = (int16_t)((MST_$SEG_TN >> MST_FORK_SEG_SHIFT) - 1);
    if (n < 0) {
        goto done;
    }
    pages_left = (uint16_t)n;
    page = 0;
    for (;;) {
        if (MST[(uint16_t)(parent_base + page)] != 0) {
            src = mst_$fork_page(MST[(uint16_t)(parent_base + page)]);
            dst = mst_$fork_page(MST[(uint16_t)(child_base + page)]);
            for (e = MST_FORK_ENTRIES_M1; e >= 0; e--) {
                *dst = *src;                                /* 4 x move.l */
                if (src->uid.high != 0) {
                    handle = src->uid.low;
                    if (src->uid.high == ANON_$UID.high) {
                        /* 0x00E73B12-0x00E73B2E: area id*0x30 - 0x30 */
                        area = (area_$entry_t *)ARCH_VA_TO_PTR(
                            AREA_TABLE_BASE +
                            (uint32_t)(uint16_t)handle * AREA_ENTRY_SIZE -
                            AREA_ENTRY_SIZE);
                        if ((uint16_t)area->generation == (uint16_t)(handle >> 16) &&
                            (uint16_t)area->owner_asid == parent_asid) {
                            if (handle != last_handle) {
                                /* 0x00E73B3A-0x00E73B74 */
                                new_handle = AREA_$COPY((int16_t)(handle >> 16),
                                                        (uint16_t)handle,
                                                        (int16_t)asid,
                                                        (int16_t)pid,
                                                        fork_flags, &st);
                                if (st != status_$ok) {
                                    goto fail;
                                }
                                last_handle = handle;
                            }
                            /* 0x00E73B7A-0x00E73B80 */
                            dst->uid.low = new_handle;
                            dst->flags &= MST_FORK_FLAGS_KEEP;
                        }
                    }
                }
                dst++;
                src++;
            }
        }
        page++;
        if (pages_left-- == 0) {                            /* subq / bcc */
            break;
        }
    }

done:
    /* 0x00E73B9C-0x00E73BAC */
    ML_$UNLOCK(MST_FORK_LOCK);
    *status = status_$ok;
    return;

fail:
    /* 0x00E73B5E-0x00E73B72 */
    ML_$UNLOCK(MST_FORK_LOCK);
    *status = st;
}
