/*
 * MST_$GROW_AREA - Change the virtual size of the VM area a VA lies in
 *
 * Original address: 0x00E4360C (SAU2 map: MST_$GROW_AREA at E4360C)
 * Size: 608 bytes (0x00E4360C .. 0x00E4386B)
 * Generated by: Claude Opus 5.5 (reviewed by Claude Fable 5.1)
 *
 * SVC slot 0x07 (svc/svc_tables.c; DATA xref 0x00E7B902), so every
 * argument is by reference.  Frame (link.w A6,-0x30; D2-D7/A2-A5 saved;
 * A5 = 0xE7CF0C, MST_UNWIRED, never used):
 *   (0x08,A6) va_ptr          -> a VA inside the area (D4)
 *   (0x0C,A6) virt_size_ptr   -> the new virtual size (D5)
 *   (0x10,A6) commit_size_ptr -> the new committed size (D6)
 *   (0x14,A6) status          (A3)
 *   (-0x04) unmap_st, (-0x08) handle (the MSTE's uid.low: generation in
 *   the high word, area id in the low word), (-0x0C) mste, (-0x10) start,
 *   (-0x14) map_info, (-0x1C) addr, (-0x1E) prot.
 *   D2w/D3w the area's segment count before/after (32 KB segments).
 *
 * Blocks:
 *   0x00E4362A-0x00E4364E  the MSTE for *va_ptr (mst_$va_to_pte)
 *   0x00E43652-0x00E436A0  the MSTE must name an ANON area handle (UID high
 *                          longword == ANON_$UID's) with area id 1..0x540
 *                          and the area's current generation
 *   0x00E436A4-0x00E436D4  segment counts; growing or shrinking?
 *   0x00E436D8-0x00E43794  growing into new segments: map them next to the
 *                          existing ones (below them for a reversed area)
 *   0x00E43798-0x00E437D4  AREA_$GROW; if it fails, unmap what was mapped
 *   0x00E437D8-0x00E43860  shrinking: AREA_$GROW, then unmap the segments
 *                          it no longer covers
 *
 * Quirks reproduced:
 *   - The segment counts are (size + 0x7FFF) >> 15 with a second 0x7FFF
 *     added when the first sum is negative.
 *   - The unmap after a failed AREA_$GROW reports into a local status; the
 *     caller sees AREA_$GROW's.
 *   - A5 is loaded but never used.
 */

#include "mst/mst_internal.h"
#include "anon/anon.h"

/* Area ids a VM area handle may carry: `cmpi.w #0x540` 0x00E4366A */
#define MST_GROW_MAX_AREA_ID    0x540

/* Segment size shift (32 KB): the `asr.l #0x8 / asr.l #0x7` pairs */
#define MST_GROW_SEG_SHIFT      15

/* mst_$alloc_segs arguments pushed at 0x00E43758-0x00E43770 */
#define MST_GROW_MAP_AREA_ID    7       /* high word of `move.l #0x70001` */
#define MST_GROW_MAP_TOUCH      1       /* its low word */

/* MST_$UNMAP_PRIVI mode: `clr.w -(SP)` 0x00E4385C */
#define MST_GROW_UNMAP_MODE     0

/* 0x00E436A4-0x00E436D0: Pascal (size + 0x7FFF) div 0x8000 */
static uint16_t mst_$grow_segs(uint32_t size)
{
    int32_t t = (int32_t)(size + 0x7FFF);

    if (t < 0) {
        t += 0x7FFF;
    }
    return (uint16_t)(t >> MST_GROW_SEG_SHIFT);
}

void MST_$GROW_AREA(uint32_t *va_ptr, uint32_t *virt_size_ptr,
                    uint32_t *commit_size_ptr, status_$t *status)
{
    status_$t unmap_st;                 /* (-0x04,A6) */
    uint32_t handle;                    /* (-0x08,A6) */
    void *entry;                        /* (-0x0C,A6) */
    uint32_t start;                     /* (-0x10,A6) */
    uint32_t map_info;                  /* (-0x14,A6) */
    uint32_t addr;                      /* (-0x1C,A6) */
    uint16_t prot;                      /* (-0x1E,A6) */
    mste_t *mste;                       /* A4 */
    area_$entry_t *area;                /* A2 */
    uint16_t area_id;                   /* D2w */
    uint16_t old_segs;                  /* D2w */
    uint16_t new_segs;                  /* D3w */
    uint32_t old_size;                  /* D1 */

    /* 0x00E4362A-0x00E4364E */
    mst_$va_to_pte(PROC1_$AS_ID, *va_ptr, &prot, &entry, status);
    if (*status != status_$ok) {
        return;
    }

    /* 0x00E43652-0x00E436A0 */
    mste = (mste_t *)entry;
    handle = mste->uid.low;
    area_id = (uint16_t)handle;
    if (mste->uid.high != ANON_$UID.high || area_id == 0 ||
        area_id > MST_GROW_MAX_AREA_ID) {
        *status = status_$mst_uid_not_vm_area;
        return;
    }
    area = AREA_ID_TO_ENTRY(area_id);
    if ((uint16_t)(handle >> 16) != (uint16_t)area->generation) {
        *status = status_$mst_object_not_found;
        return;
    }

    /* 0x00E436A4-0x00E436D4 */
    old_size = area->virt_size;
    old_segs = mst_$grow_segs(old_size);
    new_segs = mst_$grow_segs(*virt_size_ptr);

    if (old_size < *virt_size_ptr) {
        /* 0x00E436D8-0x00E43794: map the new segments */
        if (old_segs != new_segs) {
            if ((area->flags & AREA_FLAG_REVERSED) != 0) {
                addr = ((*va_ptr >> MST_GROW_SEG_SHIFT) +
                        (0xFFFFu - (uint32_t)mste->segment) -
                        (uint32_t)new_segs + 1) << MST_GROW_SEG_SHIFT;
                start = (0x10000u - (uint32_t)new_segs) << MST_GROW_SEG_SHIFT;
            } else {
                addr = ((*va_ptr >> MST_GROW_SEG_SHIFT) -
                        (uint32_t)mste->segment +
                        (uint32_t)old_segs) << MST_GROW_SEG_SHIFT;
                start = (uint32_t)old_segs << MST_GROW_SEG_SHIFT;
            }
            mst_$alloc_segs(addr, &mste->uid, start,
                            ((uint32_t)new_segs - (uint32_t)old_segs)
                                << MST_GROW_SEG_SHIFT,
                            0, (int16_t)PROC1_$AS_ID, MST_GROW_MAP_AREA_ID,
                            MST_GROW_MAP_TOUCH, 0xFF, 0, &map_info, status);
            if (*status != status_$ok) {
                return;
            }
        }

        /* 0x00E43798-0x00E437D4 */
        AREA_$GROW((int16_t)(handle >> 16), (uint16_t)handle, *virt_size_ptr,
                   *commit_size_ptr, status);
        if (*status == status_$ok) {
            return;
        }
        /* When no new segment was mapped (old_segs == new_segs) the image
         * still unmaps here with (-0x1C,A6) never written and a zero
         * length; `addr` is equally uninitialised on that path. */
        MST_$UNMAP_PRIVI(MST_GROW_UNMAP_MODE, &mste->uid, addr,
                         ((uint32_t)new_segs - (uint32_t)old_segs)
                             << MST_GROW_SEG_SHIFT,
                         PROC1_$AS_ID, &unmap_st);
        return;
    }

    /* 0x00E437D8-0x00E437F4: shrink */
    AREA_$GROW((int16_t)(handle >> 16), (uint16_t)handle, *virt_size_ptr,
               *commit_size_ptr, status);
    if (*status != status_$ok || old_segs == new_segs) {
        return;
    }

    /* 0x00E437F6-0x00E43860: unmap the segments beyond the new size */
    if ((area->flags & AREA_FLAG_REVERSED) != 0) {
        addr = (*va_ptr >> MST_GROW_SEG_SHIFT) +
               (0xFFFFu - (uint32_t)mste->segment) - (uint32_t)old_segs + 1;
    } else {
        addr = (*va_ptr >> MST_GROW_SEG_SHIFT) - (uint32_t)mste->segment +
               (uint32_t)new_segs;
    }
    addr <<= MST_GROW_SEG_SHIFT;
    MST_$UNMAP_PRIVI(MST_GROW_UNMAP_MODE, &mste->uid, addr,
                     ((uint32_t)old_segs - (uint32_t)new_segs)
                         << MST_GROW_SEG_SHIFT,
                     PROC1_$AS_ID, status);
}
