/*
 * MST_$INVALIDATE - Discard the pages behind a range of private address space
 *
 * Original address: 0x00E441CA (SAU2 map: MST_$INVALIDATE at E441CA)
 * Size: 842 bytes (0x00E441CA .. 0x00E44513)
 * Generated by: Claude Opus 5.5
 *
 * SVC 0x24 (the only reference is the SVC table entry at 0x00E7BB82).  The
 * range [*va_ptr, *va_ptr + *length_ptr - 1] must lie below the private B
 * region, in one ASID, and every segment it covers must be mapped with
 * protection 6 or 7, belong to *uid (unless *uid is UID_$NIL) and follow
 * its predecessor's object segment.  The whole pages of the range are then
 * invalidated through AREA_$INVALIDATE (anonymous objects) or
 * AST_$INVALIDATE, and when *zero_flag is TRUE the partial pages at either
 * end are cleared in place.
 *
 * Frame (link.w A6,-0x44; D2-D6/A2-A5 saved; A5 = 0xE7CF0C, unused):
 *   (0x08,A6) va_ptr, (0x0C,A6) length_ptr, (0x10,A6) uid,
 *   (0x14,A6) zero_flag, (0x18,A6) status_ret
 *   (-0x08,A6) uid_copy       the caller's UID (8 bytes)
 *   (-0x0C,A6) area_handle    MSTE uid.low of an anonymous segment
 *   (-0x14,A6) status         built under the ASID lock
 *   (-0x1C,A6) start_page     object page of the first byte (seg*32 + page)
 *   (-0x32,A6) seg_hi         (-0x34,A6) seg_lo   MST slots from VA_TO_SEGNO
 *   (-0x36,A6) is_area        (-0x38,A6) first    (-0x3A,A6) zero
 *   A2 the running VA, D3 the remaining length, D4w the object segment.
 *
 * Quirks reproduced:
 *   - A length of 1 fails with status_$mst_invalid_length: the test at
 *     0x00E4420E is end > start (`bhi`), not end >= start.
 *   - A zero length returns status_$ok without touching anything.
 *   - The object segment and start page come from the FIRST MST entry only;
 *     later entries are only checked (0x00E443C0-0x00E443C6).
 *   - For a reversed area (area flags bit 1) the start page counts down from
 *     segment 0xFFFF: (0xFFFF - seg) * 32 + page (0x00E44384-0x00E443A0).
 *   - The partial-page clears write `len mod 4` bytes first and then
 *     `len / 4` longwords at the head (0x00E4441A-0x00E4444C) but the
 *     longwords first and the bytes last at the tail (0x00E444D8-0x00E44506).
 */

#include "mst/mst_internal.h"
#include "math/math.h"
#include "anon/anon.h"

/* ML lock taken around the MST walk: `move.w #0xc,-(SP)` at 0x00E4428C */
#define MST_INVALIDATE_LOCK MST_LOCK_ASID

/* Highest ASID MST_$VA_TO_SEGNO may return: `cmpi.w #0x39,D2w` 0x00E4426A */
#define MST_INVALIDATE_MAX_ASID 0x39

/* Protections accepted at 0x00E44320 / 0x00E44326 */
#define MST_INVALIDATE_PROT_A 6
#define MST_INVALIDATE_PROT_B 7

/* Area flags bit 1: a reversed (downward-growing) area, 0x00E4437E */
#define MST_INVALIDATE_AREA_REVERSED 0x0002

/*
 * Clear `longs` longwords then advance; clr.l (A2)+ in a dbf loop.  Zero is
 * the same in either byte order, so the four byte stores are exact.
 */
static uint32_t mst_$invalidate_clear_longs(uint32_t va, int16_t longs)
{
    int16_t n = (int16_t)(longs - 1);   /* subq.w #1 / bmi */
    uint8_t *p;

    if (n < 0) {
        return va;
    }
    do {
        p = (uint8_t *)ARCH_VA_TO_PTR(va);
        p[0] = 0;
        p[1] = 0;
        p[2] = 0;
        p[3] = 0;
        va += 4;
    } while (--n != -1);                /* dbf */
    return va;
}

/* Clear `bytes` bytes then advance; clr.b (A2)+ in a dbf loop. */
static uint32_t mst_$invalidate_clear_bytes(uint32_t va, int16_t bytes)
{
    int16_t n = (int16_t)(bytes - 1);   /* subq.w #1 / bmi */

    if (n < 0) {
        return va;
    }
    do {
        *(uint8_t *)ARCH_VA_TO_PTR(va) = 0;
        va++;
    } while (--n != -1);                /* dbf */
    return va;
}

/* `move.l Dn,D1; bpl; addq.l #3,D1; asr.l #2,D1`: signed divide by 4 */
static int32_t mst_$invalidate_div4(int32_t v)
{
    if (v < 0) {
        v += 3;
    }
    return v >> 2;
}

void MST_$INVALIDATE(uint32_t *va_ptr, uint32_t *length_ptr, uid_t *uid,
                     int8_t *zero_flag, status_$t *status_ret)
{
    uid_t uid_copy;              /* (-0x8,A6) */
    uint32_t area_handle = 0;    /* (-0xc,A6) */
    status_$t status;            /* (-0x14,A6) */
    uint32_t start_page = 0;     /* (-0x1c,A6) */
    uint16_t seg_hi;             /* (-0x32,A6) */
    uint16_t seg_lo;             /* (-0x34,A6) */
    int8_t is_area;              /* (-0x36,A6) */
    int8_t first;                /* (-0x38,A6) */
    int8_t zero;                 /* (-0x3a,A6) */
    uint32_t va;                 /* A2 */
    uint32_t end;                /* D3 */
    uint32_t len;                /* D3 after 0x00E443FC */
    uint32_t chunk;              /* D2 */
    uint16_t asid;               /* D2w */
    uint16_t asid_hi;            /* D0w */
    uint16_t slot;               /* D5w */
    uint16_t last_slot;          /* D3w */
    uint16_t base;               /* D1w = MST_ASID_BASE[asid] */
    uint16_t obj_seg = 0;        /* D4w */
    uint16_t next_seg = 0;       /* D2w inside the loop */
    int16_t mst_byte_off;        /* D0w */
    uint16_t table_page;
    uint16_t prot;
    mst_entry_t *mste;           /* A0 - 0x400 */
    area_$entry_t *area;

    /* 0x00E441D8-0x00E441EC */
    uid_copy = *uid;
    zero = *zero_flag;
    is_area = 0;

    /* 0x00E441F0-0x00E441FE */
    if (*length_ptr == 0) {
        *status_ret = status_$ok;
        return;
    }

    /* 0x00E44202-0x00E4421C */
    va = *va_ptr;
    end = va + *length_ptr - 1;
    if (!(end > va)) {
        *status_ret = status_$mst_invalid_length;
        return;
    }

    /* 0x00E44220-0x00E4422E: must end below the private B region */
    if ((uint32_t)MST_$SEG_PRIVATE_B << 15 <= end) {
        goto illegal;
    }

    /* 0x00E44230-0x00E44276: both ends in one ASID, in order */
    asid = MST_$VA_TO_SEGNO(va, &seg_lo, PROC1_$AS_ID);
    slot = seg_lo;
    asid_hi = MST_$VA_TO_SEGNO(end, &seg_hi, PROC1_$AS_ID);
    last_slot = seg_hi;
    if (asid > MST_INVALIDATE_MAX_ASID || asid != asid_hi ||
        slot > last_slot) {
        goto illegal;
    }

    /* 0x00E44286-0x00E442AC */
    status = status_$ok;
    ML_$LOCK(MST_INVALIDATE_LOCK);
    first = (int8_t)0xFF;
    base = MST_ASID_BASE[asid];

    /* 0x00E442B0-0x00E443D6: check every MST entry of the range */
    do {
        mst_byte_off = (int16_t)((uint16_t)((slot >> 6) + base) * 2);
        table_page = MST[mst_byte_off / 2];
        if (table_page == 0) {
            status = status_$reference_to_illegal_address;   /* 0x00E442E2 */
            break;
        }
        mste = (mst_entry_t *)ARCH_VA_TO_PTR(MST_PAGE_TABLE_BASE +
                                             (uint32_t)table_page * 0x400u +
                                             (uint32_t)(int32_t)(int16_t)((slot & 0x3F) << 4) -
                                             0x400u);
        if (mste->uid.high == 0) {
            status = status_$reference_to_illegal_address;
            break;
        }

        /* 0x00E442EE-0x00E44314: UID_$NIL matches every object */
        if (uid_copy.high != UID_$NIL.high || uid_copy.low != UID_$NIL.low) {
            if (mste->uid.high != uid_copy.high ||
                mste->uid.low != uid_copy.low) {
                status = status_$mst_uid_mismatch;           /* 0x00E443C8 */
                break;
            }
        }

        /* 0x00E44318-0x00E44334 */
        prot = (uint16_t)((mste->flags & MSTE_FLAG_PROT_MASK) >> MSTE_FLAG_PROT_SHIFT);
        if (prot != MST_INVALIDATE_PROT_A && prot != MST_INVALIDATE_PROT_B) {
            status = status_$mst_insufficient_rights;
            break;
        }

        if (first < 0) {
            /* 0x00E44340-0x00E443BE: the first entry fixes the object */
            first = 0;
            if (mste->uid.high == ANON_$UID.high) {
                is_area = (int8_t)0xFF;
                area_handle = mste->uid.low;
            }
            obj_seg = mste->area_id;
            next_seg = obj_seg;
            /* 0x00E44360-0x00E44382: the area entry is 0xD94C00 +
             * id*0x30 - 0x30 (flags word read at -2 of 0xD94C00 + id*0x30) */
            area = NULL;
            if (is_area < 0) {
                area = (area_$entry_t *)ARCH_VA_TO_PTR(
                    AREA_TABLE_BASE + (uint32_t)(uint16_t)area_handle * AREA_ENTRY_SIZE -
                    AREA_ENTRY_SIZE);
            }
            if (area != NULL && (area->flags & MST_INVALIDATE_AREA_REVERSED) != 0) {
                start_page = ((0xFFFFu - (uint32_t)next_seg) << 5) +
                             ((va >> 10) & 0x1F);
            } else {
                start_page = ((uint32_t)next_seg << 5) + ((va >> 10) & 0x1F);
            }
        } else {
            /* 0x00E443C0-0x00E443D0: object segments must be consecutive */
            next_seg++;
            if (next_seg != mste->area_id) {
                status = status_$mst_uid_mismatch;
                break;
            }
        }

        slot++;                                             /* 0x00E443D2 */
    } while (slot <= last_slot);

    /* 0x00E443DA-0x00E443F2 */
    ML_$UNLOCK(MST_INVALIDATE_LOCK);
    *status_ret = status;
    if (status != status_$ok) {
        return;
    }

    /* 0x00E443F6-0x00E4445E: the partial first page */
    len = *length_ptr;
    chunk = va & 0x3FF;
    if (chunk != 0) {
        chunk = 0x400 - chunk;
        if ((int32_t)chunk > (int32_t)len) {                /* ble keeps it */
            chunk = len;
        }
        if (zero < 0) {
            va = mst_$invalidate_clear_bytes(va, (int16_t)M$OIS$WLW((long)chunk, 4));
            va = mst_$invalidate_clear_longs(va, (int16_t)mst_$invalidate_div4((int32_t)chunk));
        } else {
            va += chunk;                                    /* 0x00E4444E */
        }
        start_page++;                                       /* 0x00E44450 */
        if ((start_page & 0x1F) == 0) {
            obj_seg++;
        }
        len -= chunk;
    }

    /* 0x00E44460 */
    if (len == 0) {
        return;
    }

    /* 0x00E44466-0x00E444C0: the whole pages */
    chunk = len >> 10;
    if (chunk != 0) {
        if (is_area < 0) {
            AREA_$INVALIDATE((int16_t)(area_handle >> 16), (uint16_t)area_handle,
                             obj_seg, (uint16_t)(start_page & 0x1F), chunk,
                             zero, &status);
        } else {
            AST_$INVALIDATE(&uid_copy, start_page, chunk, zero, &status);
        }
        if (status != status_$ok) {
            *status_ret = status;
            return;
        }
    }

    /* 0x00E444C2-0x00E44508: the partial last page */
    if (zero >= 0) {
        return;
    }
    len &= 0x3FF;
    if (len == 0) {
        return;
    }
    va += chunk << 10;
    va = mst_$invalidate_clear_longs(va, (int16_t)mst_$invalidate_div4((int32_t)len));
    (void)mst_$invalidate_clear_bytes(va, (int16_t)M$OIS$WLW((long)len, 4));
    return;

illegal:
    /* 0x00E44278-0x00E44282 */
    *status_ret = status_$reference_to_illegal_address;
}
