/*
 * MST_$MAP_AREA_AT - create a VM area and map it at a given VA
 *
 * Original address: 0x00E43C04 (SAU2 map: MST_$MAP_AREA_AT at E43C04)
 * Size: 186 bytes (0x00E43C04 .. 0x00E43CBD)
 * Generated by: Claude Opus 5.5 (reviewed by Claude Fable 5.1)
 *
 * MST_$MAP_AREA with the address hint from the caller; a procedure (A0 is
 * not set).  SVC entry (DATA xref 0x00E7BC86) and called by PROC2_$INIT
 * (0x00E305F0, 0x00E30632), PROC2_$SET_VALID (0x00E734E4) and
 * proc2_$complete_vfork (0x00E7380C).  Every argument by reference.
 * Frame (link.w A6,-0x18; D2/A2-A5 saved; A5 = 0xE7CF0C, unused):
 *   (0x08,A6) addr_ptr -> the VA to map at
 *   (0x0C) virt_size_ptr (A3), (0x10) commit_size_ptr,
 *   (0x14) reversed_ptr -> Domain boolean (A4), (0x18) uid_out,
 *   (0x1C) status (A2)
 *   locals: (-0x08) the area UID, (-0x0C) the handle, (-0x10) the delete
 *   status, (-0x14) map_info, (-0x18) the object offset.
 *
 * Blocks:
 *   0x00E43C1E-0x00E43C3C  AREA_$CREATE; its handle comes back in D0
 *   0x00E43C3E-0x00E43C5E  UID = {ANON_$UID.high, handle}; a reversed area
 *                          is mapped from offset 0x7FFFFFFF - (size - 1)
 *   0x00E43C62-0x00E43C8E  mst_$alloc_segs at *addr_ptr, area id 7, touch
 *                          count 1 (the returned VA is dropped)
 *   0x00E43C92-0x00E43CB0  a failed map deletes the area; a good one hands
 *                          out the UID
 */

#include "mst/mst_internal.h"
#include "anon/anon.h"

/* `move.l #0x7fffffff,D2` 0x00E43C54; `move.l #0x70001` 0x00E43C6C */
#define MST_MAP_AREA_AT_TOP     0x7FFFFFFFu
#define MST_MAP_AREA_AT_AREA_ID 7
#define MST_MAP_AREA_AT_TOUCH   1

void MST_$MAP_AREA_AT(uint32_t *addr_ptr, uint32_t *virt_size_ptr,
                      uint32_t *commit_size_ptr, boolean *reversed_ptr,
                      uid_t *uid_out, status_$t *status)
{
    uid_t uid;                  /* (-0x08,A6) */
    area_$handle_t handle;      /* (-0x0C,A6) */
    status_$t del_status;       /* (-0x10,A6) */
    uint32_t map_info;          /* (-0x14,A6) */
    uint32_t start;             /* (-0x18,A6) */

    /* 0x00E43C1E-0x00E43C3C */
    handle = AREA_$CREATE(*virt_size_ptr, *commit_size_ptr, *reversed_ptr,
                          status);
    if (*status != status_$ok) {
        return;
    }

    /* 0x00E43C3E-0x00E43C5E */
    uid.high = ANON_$UID.high;
    uid.low = handle;
    start = 0;
    if (*reversed_ptr < 0) {
        start = MST_MAP_AREA_AT_TOP - (*virt_size_ptr - 1);
    }

    /* 0x00E43C62-0x00E43C8E */
    mst_$alloc_segs(*addr_ptr, &uid, start, *virt_size_ptr, 0,
                    (int16_t)PROC1_$AS_ID, MST_MAP_AREA_AT_AREA_ID,
                    MST_MAP_AREA_AT_TOUCH, 0, false, &map_info, status);

    /* 0x00E43C92-0x00E43CB0 */
    if (*status != status_$ok) {
        AREA_$DELETE(handle, &del_status);
    } else {
        *uid_out = uid;
    }
}
