/*
 * MST_$MAP_CANNED_AT - map part of a canned object at a fixed global VA
 *
 * Original address: 0x00E30FAA (SAU2 map: MST_$MAP_CANNED_AT at E30FAA)
 * Size: 242 bytes (0x00E30FAA .. 0x00E3109B)
 * Generated by: Claude Opus 5.5
 *
 * Frame (link.w A6,-0x18; D2-D7/A2 saved; no A5):
 *   (0x08,A6) va, (0x0C) uid, (0x10) offset, (0x14) size,
 *   (0x18) flags: high word the MSTE prot, low word the touch count,
 *   (0x1C) wire  - byte in the high half of its word slot,
 *   (0x1E) touch - byte in the high half of its word slot (D3b),
 *   (0x20) desc, (0x24) status; (-0x08) the in-ASID segment.
 *
 * Blocks:
 *   0x00E30FB2-0x00E30FD2  first object segment offset >> 15 (D5w); the
 *                          segment count (D4w) from the last byte
 *   0x00E30FD4-0x00E30FFE  MST_$VA_TO_SEGNO(va, &seg, 0x3A); a segment
 *                          table index above 0x39 fails with
 *                          status_$reference_to_illegal_address
 *   0x00E31002-0x00E31064  every MSTE of the range (in ASID 0's table) must
 *                          be free (UID high longword 0), or - when `touch`
 *                          is TRUE - carry a UID whose first byte is 0;
 *                          otherwise status_$no_space_available
 *   0x00E31068-0x00E31090  mst_$set_mstes in ASID 0, status 0
 */

#include "mst/mst_internal.h"

/* `move.w #0x3a,-(SP)` 0x00E30FD4 */
#define MST_CANNED_SEGNO_ASID   0x3A
/* `cmpi.w #0x39,D0w` 0x00E30FEE */
#define MST_CANNED_MAX_SEGNO    0x39
/* `lsr.l #0x8` + `lsr.l #0x7` */
#define MST_CANNED_SEG_SHIFT    15

void MST_$MAP_CANNED_AT(uint32_t va, uid_t *uid, uint32_t offset,
                        uint32_t size, uint32_t flags, boolean wire,
                        boolean touch, uint32_t desc, status_$t *status)
{
    uint16_t seg;           /* (-0x08,A6) -> D2w */
    uint16_t obj_seg;       /* D5w */
    uint16_t count;         /* D4w */
    uint16_t last;          /* D6w */
    uint16_t cur;           /* D1w */
    int16_t n;              /* D0w */
    uint16_t segno;
    mste_t *mste;

    /* 0x00E30FB2-0x00E30FD2 */
    obj_seg = (uint16_t)(offset >> MST_CANNED_SEG_SHIFT);
    count = (uint16_t)((uint16_t)((offset + size - 1) >> MST_CANNED_SEG_SHIFT) -
                       obj_seg + 1);

    /* 0x00E30FD4-0x00E30FFE */
    segno = MST_$VA_TO_SEGNO(va, &seg, MST_CANNED_SEGNO_ASID);
    if (segno > MST_CANNED_MAX_SEGNO) {
        *status = status_$reference_to_illegal_address;
        return;
    }

    /* 0x00E31002-0x00E31064: A2 = MST_ASID_BASE, read as (A2) = ASID 0 */
    last = (uint16_t)(count + seg - 1);
    cur = seg;
    for (n = (int16_t)(last - seg); n >= 0; n--, cur++) {
        mste = (mste_t *)ARCH_VA_TO_PTR(
            MST_PAGE_TABLE_BASE +
            (uint32_t)MST[(uint16_t)((cur >> 6) + MST_ASID_BASE[0])] * 0x400u +
            (uint32_t)(cur & 0x3F) * 0x10u - 0x400u);
        if (mste->uid.high != 0) {
            /* 0x00E31048-0x00E31054: seq of the UID's first byte AND touch */
            int8_t first_zero = ((mste->uid.high >> 24) == 0) ? (int8_t)-1 : 0;
            if ((int8_t)(first_zero & (int8_t)touch) >= 0) {
                *status = status_$no_space_available;
                return;
            }
        }
    }

    /* 0x00E31068-0x00E31090 */
    mst_$set_mstes(uid, obj_seg, desc, seg, last, (uint16_t)flags, 0,
                   (uint16_t)(flags >> 16), (int8_t)wire);
    *status = status_$ok;
}
