/*
 * MST_$REMAP_PRIVI - replace the mapping at a VA with another piece of the
 * same object
 *
 * Original address: 0x00E43A0C (SAU2 map: MST_$REMAP_PRIVI at E43A0C)
 * Size: 302 bytes (0x00E43A0C .. 0x00E43B39)
 * Generated by: Claude Opus 5.5
 *
 * Callers: MST_$REMAP (0x00E439FC, flags = the constant cell after its
 * body) and dir_$map_page (0x00E4B3F2).  Frame (link.w A6,-0x20;
 * D2-D5/A2-A5 saved; A5 = 0xE7CF0C, MST_UNWIRED, never used):
 *   (0x08,A6) flags        -> a word; bit 0 of its low byte = "privileged"
 *   (0x0C,A6) va_ptr       -> the VA to remap (A3)
 *   (0x10,A6) unmap_len    -> length unmapped at *va_ptr (A4)
 *   (0x14,A6) offset_ptr   -> offset in the object of the new mapping
 *   (0x18,A6) length_ptr   -> length of the new mapping
 *   (0x1C,A6) map_info     -> mst_$alloc_segs' map_info, cleared first (D3)
 *   (0x20,A6) status       (A2)
 *   locals: (-0x08) uid, (-0x0C) entry, (-0x10) result, (-0x12) asid,
 *   (-0x14) unmap mode, (-0x16) touch count, (-0x18) prot, (-0x1C) access.
 *
 * Blocks:
 *   0x00E43A1A-0x00E43A52  result = NULL, *map_info = 0; the MSTE for
 *                          *va_ptr in the current address space; a nonzero
 *                          low status word returns NULL
 *   0x00E43A56-0x00E43A76  copy the MSTE's UID; access = bit 15 of its word
 *                          at +0x0A (smi); touch count = ((byte +0x0C) &
 *                          0x7C) >> 2, plus one
 *   0x00E43A7A-0x00E43ABE  privileged (flags bit 0): unmap mode 3 in the
 *                          current ASID, or ASID 0 when *va_ptr lies at or
 *                          above segment MST_$SEG_GLOBAL_B; otherwise mode
 *                          2 in the current ASID
 *   0x00E43AC0-0x00E43AE2  MST_$UNMAP_PRIVI; a nonzero status returns NULL
 *   0x00E43AE4-0x00E43B2A  map the same UID under ACL_$ENTER_SUPER /
 *                          ACL_$EXIT_SUPER with mst_$alloc_segs
 *
 * Quirks reproduced:
 *   - The first status test is `tst.w (0x2,A2)`, the low word only.
 *   - The prot word mst_$va_to_pte returns becomes mst_$alloc_segs' area
 *     id argument and the "privileged" boolean (sne) its direction.
 */

#include "mst/mst_internal.h"
#include "acl/acl.h"

/* Unmap modes: `move.w #0x3` 0x00E43AAA, `move.w #0x2` 0x00E43ABA */
#define MST_REMAP_UNMAP_PRIV        3
#define MST_REMAP_UNMAP_USER        2

/* mst_$alloc_segs address hint: `move.l #0x7fffffff,-(SP)` 0x00E43B14 */
#define MST_REMAP_ADDR_HINT         0x7FFFFFFFu

/* Segment shift: `lsr.l #0x8` + `lsr.l #0x7` 0x00E43A8E-0x00E43A96 */
#define MST_REMAP_SEG_SHIFT         15

void *MST_$REMAP_PRIVI(uint16_t *flags, uint32_t *va_ptr, uint32_t *unmap_len,
                       uint32_t *offset_ptr, uint32_t *length_ptr,
                       uint32_t *map_info, status_$t *status)
{
    uid_t uid;              /* (-0x08,A6) */
    void *entry;            /* (-0x0C,A6) */
    void *result;           /* (-0x10,A6) */
    uint16_t asid;          /* (-0x12,A6) */
    int16_t mode;           /* (-0x14,A6) */
    uint16_t touch_count;   /* (-0x16,A6) */
    uint16_t prot;          /* (-0x18,A6) */
    int8_t access;          /* (-0x1C,A6) */
    int8_t privileged;      /* D2b */
    mste_t *mste;

    /* 0x00E43A26-0x00E43A2C */
    result = NULL;
    *map_info = 0;

    /* 0x00E43A2E-0x00E43A52 */
    mst_$va_to_pte(PROC1_$AS_ID, *va_ptr, &prot, &entry, status);
    if ((uint16_t)*status != 0) {
        return result;
    }

    /* 0x00E43A56-0x00E43A76 */
    mste = (mste_t *)entry;
    uid = mste->uid;
    access = ((int16_t)mste->unknown_0a < 0) ? (int8_t)-1 : 0;
    touch_count = (uint16_t)((((mste->location >> 24) & 0x7Cu) >> 2) + 1);

    /* 0x00E43A7A-0x00E43ABE */
    privileged = ((*flags & 0x0001u) != 0) ? (int8_t)-1 : 0;
    if (privileged < 0) {
        if ((*va_ptr >> MST_REMAP_SEG_SHIFT) < (uint32_t)MST_$SEG_GLOBAL_B) {
            asid = PROC1_$AS_ID;
        } else {
            asid = 0;
        }
        mode = MST_REMAP_UNMAP_PRIV;
    } else {
        asid = PROC1_$AS_ID;
        mode = MST_REMAP_UNMAP_USER;
    }

    /* 0x00E43AC0-0x00E43AE2 */
    MST_$UNMAP_PRIVI(mode, &uid, *va_ptr, *unmap_len, PROC1_$AS_ID, status);
    if (*status != status_$ok) {
        return result;
    }

    /* 0x00E43AE4-0x00E43B2A */
    ACL_$ENTER_SUPER();
    result = mst_$alloc_segs(MST_REMAP_ADDR_HINT, &uid, *offset_ptr,
                             *length_ptr, 0, (int16_t)asid, prot,
                             touch_count, (uint8_t)access, privileged,
                             map_info, status);
    ACL_$EXIT_SUPER();

    return result;
}
