/*
 * MST_$SET_TOUCH_AHEAD_CNT - MST_$PRIV_SET_TOUCH_AHEAD_CNT, unprivileged
 *
 * Original address: 0x00E446FC
 * Size: 48 bytes of code (0x00E446FC .. 0x00E4472B) and the flags word 0
 * it passes by reference (0x00E4472C); MST_$UNMAP follows at 0x00E4472E.
 * Generated by: Claude Opus 5.5
 *
 * Frame (link.w A6,0x0; A5 saved, A5 = 0xE7CF0C, unused):
 *   (0x08,A6) va_ptr  (0x0C,A6) length_ptr  (0x10,A6) count_ptr
 *   (0x14,A6) result_ptr  (0x18,A6) status - all passed on as-is
 *
 *   0x00E44708-0x00E44720  MST_$PRIV_SET_TOUCH_AHEAD_CNT(&0, the five
 *                          arguments); the unlk drops the 24 bytes
 *
 * Reached only through SVC_$TRAP5_TABLE (0x00E7BB96).
 */

#include "mst/mst_internal.h"

/* 0x00E4472C (`pea (0xe,PC)' at 0x00E4471C): `gsk read 0xE4472C 2` = 00 00. */
static const uint16_t mst_set_touch_ahead_flags = 0;

void MST_$SET_TOUCH_AHEAD_CNT(uint32_t *va_ptr, uint32_t *length_ptr,
                              int16_t *count_ptr, void *result_ptr,
                              status_$t *status)
{
    MST_$PRIV_SET_TOUCH_AHEAD_CNT((uint16_t *)&mst_set_touch_ahead_flags,
                                  va_ptr, length_ptr, count_ptr, result_ptr,
                                  status);                      /* 0x00E44720 */
}
