/*
 * MST_$UNMAPS_AND_FREE_AREA - MST_$UNMAP_PRIVI in the current address space, mode 0x10
 *
 * Original address: 0x00E44806
 * Size: 54 bytes (0x00E44806 .. 0x00E4483B)
 * Generated by: Claude Opus 5.5
 *
 * A forwarding wrapper like MST_$UNMAP (mst/unmap.c): A5 is saved and set
 * to 0xE7CF0C (MST_UNWIRED) but never used; no stack cleanup after the
 * call, the unlk drops the arguments.
 *
 * The "S" variants take no UID: UID_$NIL is passed (`move.l #0xe1737c',
 * 0x00E44828).  Frame (link.w A6,0x0):
 *   (0x08,A6) start_va_ptr  dereferenced (longword)  (0x00E44822)
 *   (0x0C,A6) length_ptr    dereferenced (longword)  (0x00E4481C)
 *   (0x10,A6) status_ret    pushed as-is             (0x00E44812)
 * Pushes PROC1_$AS_ID (0x00E44816) and mode `move.w #0x10' (0x00E4482E),
 * then bsr.b 0x00e448b0.  Reached only through SVC_$TRAP3_TABLE.
 */

#include "mst/mst_internal.h"

void MST_$UNMAPS_AND_FREE_AREA(uint32_t *start_va_ptr, uint32_t *length_ptr,
                               status_$t *status_ret)
{
    /* 0x00E44812 .. 0x00E44832 */
    MST_$UNMAP_PRIVI(0x10, &UID_$NIL, *start_va_ptr, *length_ptr,
                     PROC1_$AS_ID, status_ret);
}
