/*
 * mmu/test/test_mmu_data.c - the MMU module's data blocks
 *
 * Generated by: Claude Opus 5.5
 *
 * MMU_$GLOBALS (source-o56c): the data run at the head of the SAU2 map's
 * "D E23D2C MMU_ASM size = 5B8" segment, 0xE23D2C..0xE23D37 up to
 * MMU_$INIT - MMU_$PID_PRIV, M68020 and the three unnamed cells MMU_$INIT
 * writes through A5 = M68020 - with the image contents
 *   00e23d2c  00 00 00 00 00 0f fc 00  00 03 00 08
 * MMU_$PTTX (source-o56c): map MMU_$PTTX 0xEC2800 in OS_PMAPS, one word per
 * physical page 0..0xFFF, up to AUDIT_LIST 0xEC4800, zero-filled.
 */

#include <stdio.h>
#include <stdint.h>
#include <stddef.h>

static int tests_passed = 0;
static int tests_failed = 0;

#define RUN_TEST(name) do { \
    printf("  Running %s... ", #name); \
    test_##name(); \
    printf("PASSED\n"); \
    tests_passed++; \
} while (0)

#define ASSERT_EQ(expected, actual) do { \
    if ((unsigned long)(expected) != (unsigned long)(actual)) { \
        printf("FAILED\n    Expected: 0x%lx, Got: 0x%lx at line %d\n", \
               (unsigned long)(expected), (unsigned long)(actual), __LINE__); \
        tests_failed++; \
        return; \
    } \
} while (0)

#include "mmu/mmu_internal.h"
#include "../mmu_data.c"

/* The block's cells at their image offsets from 0xE23D2C. */
static void test_globals_layout(void)
{
    ASSERT_EQ(0x00E23D2Cu, MODULE_DATA_ADDR(MMU_$GLOBALS));
    ASSERT_EQ(0xC, sizeof(mmu_$globals_t));
    ASSERT_EQ(0xC, sizeof(MMU_$GLOBALS));
    ASSERT_EQ(0x0, offsetof(mmu_$globals_t, pid_priv));             /* 0xE23D2C */
    ASSERT_EQ(0x2, offsetof(mmu_$globals_t, m68020));               /* 0xE23D2E */
    ASSERT_EQ(0x4, offsetof(mmu_$globals_t, va_to_ptt_offset_mask));/* 0xE23D30 */
    ASSERT_EQ(0x8, offsetof(mmu_$globals_t, va_shift));             /* 0xE23D34 */
    ASSERT_EQ(0xA, offsetof(mmu_$globals_t, ptt_shift));            /* 0xE23D36 */
    /* the run ends where MMU_$INIT's code starts */
    ASSERT_EQ(0x00E23D38u, MODULE_DATA_ADDR(MMU_$GLOBALS) + MMU_$GLOBALS_SIZE);
}

/* MMU_$INIT's A5 is M68020 (`lea (-0xe,PC),A5' at 0xE23D3A = 0xE23D2E),
 * and it writes the mask at (0x2,A5) and the shifts at (0x6,A5) / (0x8,A5);
 * the mmu/sau2 aliases are MMU_$GLOBALS + 0x2 / 0x4 / 0x8 / 0xA. */
static void test_init_a5_displacements(void)
{
    const char *a5 = (const char *)&M68020;

    ASSERT_EQ(0x2, (const char *)&VA_TO_PTT_OFFSET_MASK - a5);
    ASSERT_EQ(0x6, (const char *)&MMU_$VA_SHIFT - a5);
    ASSERT_EQ(0x8, (const char *)&MMU_$PTT_SHIFT - a5);
    ASSERT_EQ(-0x2, (const char *)&MMU_$PID_PRIV - a5);
}

/* The image ships the 68010 parameters; MMU_$INIT rewrites them on a
 * 68020 (0x3FFC00, 1, 6). */
static void test_globals_image_values(void)
{
    ASSERT_EQ(0x0000, MMU_$PID_PRIV);
    ASSERT_EQ(0x0000, M68020);
    ASSERT_EQ(0x000FFC00u, VA_TO_PTT_OFFSET_MASK);
    ASSERT_EQ(3, MMU_$VA_SHIFT);
    ASSERT_EQ(8, MMU_$PTT_SHIFT);
}

/* One word per physical page 0..0xFFF, 0xEC2800..0xEC4800, no bias. */
static void test_pttx_layout(void)
{
    ASSERT_EQ(0x00EC2800u, MODULE_DATA_ADDR(MMU_$PTTX));
    ASSERT_EQ(0x2000, sizeof(mmu_$pttx_t));
    ASSERT_EQ(MMU_$PTTX_SIZE, sizeof(MMU_$PTTX));
    ASSERT_EQ(0x1000, MMU_PTTX_COUNT);
    ASSERT_EQ(2, (char *)&PTTX_FOR_PPN(1) - (char *)&PTTX_FOR_PPN(0));
    ASSERT_EQ((uintptr_t)&MMU_$PTTX, (uintptr_t)&PTTX_FOR_PPN(0));
    /* entry 0xFFF is the segment's last word, before AUDIT_LIST 0xEC4800 */
    ASSERT_EQ(0x00EC4800u - 2,
              MODULE_DATA_ADDR(MMU_$PTTX) +
              ((char *)&PTTX_FOR_PPN(0xFFF) - (char *)&MMU_$PTTX));
}

static void test_pttx_zero_filled(void)
{
    for (unsigned i = 0; i < MMU_PTTX_COUNT; i++) {
        ASSERT_EQ(0, MMU_$PTTX.entry[i]);
    }
}

int main(void)
{
    printf("test_mmu_data:\n");
    RUN_TEST(globals_layout);
    RUN_TEST(init_a5_displacements);
    RUN_TEST(globals_image_values);
    RUN_TEST(pttx_layout);
    RUN_TEST(pttx_zero_filled);
    printf("%d passed, %d failed\n", tests_passed, tests_failed);
    return tests_failed != 0;
}
