/*
 * dir_$do_op_add_entry - add an entry, accepting a repeat of the same add
 *
 * Original address: 0x00E4FEF2
 * Size: 454 bytes (0x00E4FEF2 .. 0x00E500B7)
 * Generated by: Claude Opus 5.5
 *
 * Module-local routine of the DIR segment (no map symbol).  Callers:
 * DIR_$DO_OP (0x00E4C332 hard link, 0x00E4C5E4 soft link), dir_$lookup_entry
 * (0x00E4CD3C), dir_$do_op_find_uid (0x00E4E6CE, 0x00E4E728) and
 * dir_$do_op_add_link (0x00E50488).
 *
 * Frame: (0x8,A6) uid (D5), (0xC,A6) rights word, (0xE,A6) name (A2),
 * (0x12,A6) name_len, (0x14,A6) entry_type (D2), (0x16,A6) extra (D3),
 * (0x1A,A6) target_uid (D6), (0x1E,A6) link_len (D4), (0x20,A6) link_data
 * (A3), (0x24,A6) volume_ret, (0x28,A6) status_ret (A4).  Locals: A6-0x1C
 * the handle, A6-0x18 the found entry, A6-0x20/-0x22 dir_$find_entry's
 * path and depth, A6-0x10 the hint pair.
 *
 * Blocks:
 *   0x00E4FF1A-0x00E4FF3A  ACL_$ENTER_SUPER; dir_$open_dir(uid, 2, rights,
 *                          &handle, status_ret); error -> release
 *   0x00E4FF3E-0x00E4FF5A  dir_$add_entry(handle, name, name_len,
 *                          entry_type, extra, target_uid, link_len,
 *                          link_data, status_ret)
 *   0x00E4FF5E-0x00E4FF7C  status_$name_already_exists from a type-9
 *                          process (PROC1_$DATA.type[PROC1_$CURRENT]):
 *   0x00E4FF80-0x00E4FFB0  dir_$find_entry(handle, name, name_len, 0,
 *                          &entry, ...); not found, or the entry's type
 *                          (byte 0 & 7) differs -> release, status kept
 *   0x00E4FFB4-0x00E5003E  same object?  type 2: the UID at +4; type 3:
 *                          the UID and the extra longword at +0xC; type 4:
 *                          the text length at +2 and the text bytes
 *                          (inline after the name at +0xC when the text
 *                          page at +4 is 0xFFFF, else
 *                          dir_$map_link_page(handle, page)); a difference
 *                          -> release, status kept
 *   0x00E50044-0x00E5004E  any other type: CRASH_SYSTEM(&Naming_bad_
 *                          request_header_ver_err) (`pea (-0x4e16,PC)' =
 *                          0x00E4B230)
 *   0x00E50050             a repeat of the same add: status_$ok
 *   0x00E50054-0x00E50056  other errors -> release
 *   0x00E50058-0x00E50090  a hard link (type 3) in NAME_$ROOT_UID:
 *                          HINT_$ADDI(target_uid, {extra,
 *                          target_uid->low & 0xFFFFF})
 *   0x00E50092-0x00E5009A  *volume_ret = handle->volume
 *   0x00E5009E-0x00E500A8  dir_$release_handle(&handle); ACL_$EXIT_SUPER
 *
 * Quirks reproduced:
 *   - dir_$add_entry gets a reserved Pascal result word it never fills.
 *   - The type-4 comparison runs link_len bytes whatever the text page
 *     holds; a zero link_len compares nothing and matches.
 *   - Callers whose link_len is 0 hand over any convenient address as
 *     link_data (DIR_$DO_OP pushes 0x00E4C9E4, dir_$find_entry's entry
 *     point); it is only turned into a pointer for type 4.
 */

#include "dir/dir_internal.h"

/* `move.w #0x2,-(SP)' 0x00E4FF2A: dir_$open_dir mode (write) */
#define DO_OP_ADD_OPEN_MODE     2
/* `cmpi.w #0x9,...' 0x00E4FF76: the process type allowed to repeat an add */
#define DO_OP_ADD_REPEAT_TYPE   9
/* `move.l #0xfffff,D0' 0x00E50076: the node-id bits of a UID's low half */
#define DO_OP_ADD_NODE_MASK     0x000FFFFFu

void dir_$do_op_add_entry(uid_t *uid, int16_t rights, void *name,
                          uint16_t name_len, uint16_t entry_type,
                          uint32_t extra, uid_t *target_uid,
                          uint16_t link_len, uint32_t link_data,
                          void *volume_ret, status_$t *status_ret)
{
    uint32_t handle;                    /* A6-0x1C */
    uint8_t *entry;                     /* A6-0x18, then A2 */
    uint8_t path[4];                    /* A6-0x20..-0x1D */
    int16_t depth;                      /* A6-0x22 */
    hint_addr_t hint;                   /* A6-0x10 */
    uint8_t *text;                      /* A0 */
    uint8_t *link = (uint8_t *)ARCH_VA_TO_PTR(link_data);   /* A3 */
    uid_t *entry_uid;
    int16_t n;
    int16_t i;

    /* 0x00E4FF1A-0x00E4FF3A */
    ACL_$ENTER_SUPER();
    dir_$open_dir(uid, DO_OP_ADD_OPEN_MODE, rights, &handle, status_ret);
    if (*status_ret != status_$ok) {
        goto release;
    }

    /* 0x00E4FF3E-0x00E4FF5A */
    dir_$add_entry(handle, name, name_len, entry_type, extra, target_uid,
                   link_len, link, status_ret);

    if (*status_ret == status_$name_already_exists &&
        PROC1_$DATA.type[PROC1_$CURRENT] == DO_OP_ADD_REPEAT_TYPE) {
        /* 0x00E4FF80-0x00E4FFB0 */
        if ((int8_t)dir_$find_entry(ARCH_VA_TO_PTR(handle), name,
                                    (int16_t)name_len, 0, (void **)&entry,
                                    path, &depth) >= 0) {
            goto release;
        }
        if ((uint16_t)(entry[0] & DIR_ENTRY_TYPE_MASK) != entry_type) {
            goto release;
        }

        /* 0x00E4FFB4-0x00E5004E */
        switch (entry_type) {
        case 2:
            entry_uid = (uid_t *)(entry + DIR_ENTRY_UID);
            if (entry_uid->high != target_uid->high ||
                entry_uid->low != target_uid->low) {
                goto release;
            }
            break;
        case 3:
            entry_uid = (uid_t *)(entry + DIR_ENTRY_UID);
            if (entry_uid->high != target_uid->high ||
                entry_uid->low != target_uid->low ||
                *(uint32_t *)(entry + DIR_ENTRY_EXTRA) != extra) {
                goto release;
            }
            break;
        case 4:
            if (*(uint16_t *)(entry + DIR_ENTRY_LINK_LEN) != link_len) {
                goto release;
            }
            if (*(int16_t *)(entry + DIR_ENTRY_LINK_PAGE) ==
                DIR_ENTRY_LINK_INLINE) {
                text = entry + DIR_ENTRY_LINK_NAME + entry[DIR_ENTRY_NAME_LEN];
            } else {
                text = (uint8_t *)dir_$map_link_page(
                    ARCH_VA_TO_PTR(handle),
                    *(uint16_t *)(entry + DIR_ENTRY_LINK_PAGE));
            }
            n = (int16_t)(link_len - 1);
            if (n >= 0) {
                i = 1;
                do {                            /* dbf D0w */
                    if (link[i - 1] != text[i - 1]) {
                        goto release;
                    }
                    i++;
                } while (n-- != 0);
            }
            break;
        default:
            CRASH_SYSTEM(&Naming_bad_request_header_ver_err);
            break;
        }

        /* 0x00E50050 */
        *status_ret = status_$ok;
    } else if (*status_ret != status_$ok) {
        /* 0x00E50054-0x00E50056 */
        goto release;
    }

    /* 0x00E50058-0x00E50090 */
    if (entry_type == 3 &&
        uid->high == NAME_$ROOT_UID.high && uid->low == NAME_$ROOT_UID.low) {
        hint.flags = extra;
        hint.node_id = target_uid->low & DO_OP_ADD_NODE_MASK;
        HINT_$ADDI(target_uid, (uint32_t *)&hint);
    }

    /* 0x00E50092-0x00E5009A */
    *(int16_t *)volume_ret =
        ((dir_$handle_t *)ARCH_VA_TO_PTR(handle))->volume;

release:
    /* 0x00E5009E-0x00E500A8 */
    dir_$release_handle(&handle);
    ACL_$EXIT_SUPER();
}
