/*
 * dir_$get_parent_uid - replace a directory UID by its parent's
 *
 * Original address: 0x00E4D060
 * Size: 130 bytes (0x00E4D060 .. 0x00E4D0E1)
 * Generated by: Claude Opus 5.5 (reviewed by Claude Fable 5.1)
 *
 * Module-local routine of the DIR segment (no map symbol); its one caller
 * is dir_$do_op_resolve (0x00E4D214), for a ".." component.
 *
 * Frame: (0x8,A6) uid (A2, in/out), (0xC,A6) status_ret (A3).  Locals:
 * A6-0x28 the object-location record (UID at A6-0x20, flags at A6-0xB),
 * A6-0x40 the common-attribute record.
 *
 * Blocks:
 *   0x00E4D070-0x00E4D07A  loc.uid = *uid; clear loc.flags bit 6
 *   0x00E4D080-0x00E4D096  AST_$GET_COMMON_ATTRIBUTES(&loc, 0x80, &cattr,
 *                          status_ret)  (result word reserved, unused)
 *   0x00E4D09A-0x00E4D0C2  ok: sub_type (A6-0x3F) 1 or 2 -> *uid = the UID
 *                          at cattr+0x08 (A6-0x38); otherwise
 *                          status_$naming_branch_is_not_a_directory
 *   0x00E4D0C4-0x00E4D0D2  error: file_$object_not_found, or any error
 *                          while loc.flags bit 7 (remote) is set, becomes
 *                          status_$naming_directory_object_not_found;
 *                          other errors pass through
 *
 * cattr+0x08 is ast_$common_attr_t.dirptr (aote+0x48, attribute 5), the
 * parent directory UID FILE_$SET_DIRPTR (0x00E5E1B2) stores; the field was
 * named mod_time until source-ysw9.
 */

#include "dir/dir_internal.h"

/* `move.w #0x80,-(SP)' at 0x00E4D088: the attribute selector */
#define DIR_CATTR_GET_PARENT    0x0080

void dir_$get_parent_uid(uid_t *uid, status_$t *status_ret)
{
    file_$obj_loc_t loc;                /* A6-0x28 */
    ast_$common_attr_t cattr;           /* A6-0x40 */

    /* 0x00E4D070-0x00E4D07A */
    loc.uid.high = uid->high;
    loc.uid.low = uid->low;
    loc.flags &= (int8_t)~FILE_OBJ_LOC_SCRATCH;

    /* 0x00E4D080-0x00E4D096 */
    AST_$GET_COMMON_ATTRIBUTES(&loc, DIR_CATTR_GET_PARENT, &cattr, status_ret);

    if (*status_ret == status_$ok) {
        /* 0x00E4D09E-0x00E4D0C2 */
        if (cattr.sub_type == 1 || cattr.sub_type == 2) {
            uid->high = cattr.dirptr.high;
            uid->low = cattr.dirptr.low;
        } else {
            *status_ret = status_$naming_branch_is_not_a_directory;
        }
    } else if (*status_ret == file_$object_not_found || loc.flags < 0) {
        /* 0x00E4D0C4-0x00E4D0D2 */
        *status_ret = status_$naming_directory_object_not_found;
    }
}
