/*
 * dir_$next_page - step a B-tree path to the next leaf page
 *
 * Original address: 0x00E4D7B0
 * Size: 250 bytes (0x00E4D7B0 .. 0x00E4D8A9)
 * Generated by: Claude Opus 5.5
 *
 * Module-local routine of the DIR segment (no map symbol).  Callers:
 * dir_$do_op_dir_readu (0x00E4DF88) and dir_$do_op_find_uid (0x00E4E584),
 * each passing the path dir_$find_entry left in its buffer.
 *
 * Frame: (0x8,A6) handle, (0xC,A6) depth word (D0 -> D4 = depth-1),
 * (0xE,A6) path (D6; level N is path[N-1], `(-0x4,A2)' / `(-0x2,A2)' with
 * A2 = path + 4*N), (0x12,A6) page_ret.
 *
 * Blocks:
 *   0x00E4D7C4             *page_ret = 0xFFFF (no next page)
 *   0x00E4D7C8-0x00E4D7D0  levels depth-1 down to 1 (dbf, D3 = level);
 *                          depth < 2 -> nothing to do
 *   0x00E4D7E8-0x00E4D826  map the level's page; its index table starts at
 *                          0x12, plus the root-area length (word +0x14) on
 *                          the root page (page_no == 0); the entry count is
 *                          (index_end - base) / 2, signed, rounded toward
 *                          zero; count <= the level's entry index -> go up
 *                          a level (0x00E4D896-0x00E4D89C)
 *   0x00E4D828-0x00E4D846  otherwise step the entry index and take the
 *                          child page number from that entry (+2 of the
 *                          entry the 1-based index word points at)
 *   0x00E4D84A-0x00E4D890  then for each deeper level up to depth-1 (dbf):
 *                          record {page, 1}, map the page and descend
 *                          through its first index entry (index table at
 *                          0x12: these are never the root page)
 */

#include "dir/dir_internal.h"

void dir_$next_page(void *handle, int16_t depth, dir_$page_path_t *path,
                    uint16_t *page_ret)
{
    int16_t last = (int16_t)(depth - 1);                /* D4 */
    int16_t level;                                      /* D3 */
    int16_t n;                                          /* D2 */
    int16_t j;                                          /* D0 */
    int16_t base;                                       /* D5 */
    int32_t count;                                      /* D0 */
    uint8_t *page;                                      /* A1 */
    dir_page_hdr_t *hdr;
    dir_$page_path_t *p;                                /* A2 - 4 */
    uint8_t *index;
    uint8_t *entry;

    /* 0x00E4D7C4 */
    *page_ret = 0xFFFF;

    /* 0x00E4D7C8-0x00E4D7D0 */
    n = (int16_t)(last - 1);
    if (n < 0) {
        return;
    }
    level = last;

    do {
        /* 0x00E4D7E8-0x00E4D7FC */
        p = &path[level - 1];
        page = (uint8_t *)dir_$map_page(handle, (int16_t)p->page_no);
        hdr = (dir_page_hdr_t *)page;

        /* 0x00E4D7FE-0x00E4D810 */
        if (hdr->page_no == 0) {
            base = (int16_t)(DIR_PAGE_HDR_SIZE +
                             *(int16_t *)(page + DIR_PAGE_ROOT_AREA_LEN));
        } else {
            base = DIR_PAGE_HDR_SIZE;
        }

        /* 0x00E4D812-0x00E4D826 */
        count = ((int32_t)(int16_t)hdr->index_end - (int32_t)base) / 2;
        if ((int16_t)count > (int16_t)p->entry_idx) {
            /* 0x00E4D828-0x00E4D846 */
            p->entry_idx++;
            index = page + base;
            entry = page + *(int16_t *)(index + 2 * (int16_t)p->entry_idx - 2);
            *page_ret = *(uint16_t *)(entry + 2);

            /* 0x00E4D84A-0x00E4D890 */
            j = (int16_t)(level + 1);
            n = (int16_t)(last - j);
            if (n < 0) {
                return;
            }
            do {
                p = &path[j - 1];
                p->page_no = *page_ret;
                p->entry_idx = 1;
                page = (uint8_t *)dir_$map_page(handle, (int16_t)*page_ret);
                entry = page + *(int16_t *)(page + DIR_PAGE_HDR_SIZE);
                *page_ret = *(uint16_t *)(entry + 2);
                j++;
            } while (n-- != 0);                         /* dbf D2w */
            return;
        }

        /* 0x00E4D896-0x00E4D89C */
        level--;
    } while (n-- != 0);                                 /* dbf D2w */
}
