/*
 * dir_$old_find_free_inline_slot - find an unused inline slot of an
 * old-format directory
 *
 * Original address: 0x00E54DCC
 * Size: 68 bytes (0x00E54DCC .. 0x00E54E0F)
 * Generated by: Claude Opus 5.5
 *
 * Module-local routine of the OLD_DIR segment (no map symbol); its one
 * caller is dir_$old_add_entry (`bsr' at 0x00E55294), which reserves a
 * Pascal result word (`subq.l #2,SP') and then tests D0b.
 *
 * Frame: (0x8,A6) handle (A1, the mapped directory), (0xC,A6) inline_count
 * word (D1), (0xE,A6) slot_out.
 *
 * Blocks:
 *   0x00E54DD8-0x00E54DDE  D0b = 0xFF (`st' leaves the flags of the
 *                          `move.w' alone); inline_count == 0 -> false
 *   0x00E54DE0-0x00E54E00  for i = 1..inline_count (dbf), A0 = dir + 0x30*i:
 *                          the slot's type byte (A0+0x11) is 0 ->
 *                          *slot_out = i, return true
 *   0x00E54E04             no free slot: false
 */

#include "dir/dir_internal.h"

int8_t dir_$old_find_free_inline_slot(uint32_t handle, uint16_t inline_count,
                                       uint16_t *slot_out)
{
    uint8_t *dir = (uint8_t *)ARCH_VA_TO_PTR(handle);  /* A1 */
    dir_$old_slot_t *slot;
    uint16_t i;                                        /* D2 */

    /* 0x00E54DE0-0x00E54E00 */
    for (i = 1; i <= inline_count; i++) {             /* dbf D1w */
        slot = (dir_$old_slot_t *)(dir + DIR_OLD_SLOT_STRIDE * (uint32_t)i -
                                   DIR_OLD_INLINE_SLOT_BIAS);
        if (slot->type == 0) {
            *slot_out = i;
            return (int8_t)0xFF;
        }
    }

    /* 0x00E54E04 */
    return 0;
}
