/*
 * DIR_$OLD_INIT - Legacy directory subsystem initialization
 *
 * Marks every process as holding no OLD_DIR directory lock by clearing the
 * high longword of NAME_$OLD_DIR_DATA.lock_uid[0..57].
 *
 * Original address: 0x00E314F4
 * Original size: 38 bytes
 *
 * Generated by: Claude Opus 5.5
 */

#include "dir/dir_internal.h"

/*
 * DIR_$OLD_INIT - Legacy directory initialization
 *
 * Assembly (A5 = 0x00E35040 here, the OLD_DIR block is reached through A0):
 *   0x00E31500  moveq #0x39,D0          ; dbf count: 58 iterations
 *   0x00E31502  movea.l #0xe7fd24,A0    ; A0 = NAME_$OLD_DIR_DATA
 *   0x00E31508  clr.l (0x2b8,A0)        ; lock_uid[i].high
 *   0x00E3150C  addq.l #0x8,A0          ; i += 1 (8-byte stride)
 *   0x00E3150E  dbf D0w,0x00e31508
 *
 * The first address cleared is 0x2B8 = lock_uid[0], the bias slot of the
 * Pascal [1..64] table (see name/name.h), and the last is lock_uid[57]; the
 * loop is reproduced as the image has it.  lock_uid[0].high is the same
 * longword as lock_handle[63], and lock_uid[58..64] are not cleared.
 */
void DIR_$OLD_INIT(void)
{
    int16_t i;

    for (i = 0; i < DIR_OLD_INIT_CLEAR_COUNT; i++) {
        NAME_$OLD_DIR_DATA.lock_uid[i].high = 0;
    }
}
