/*
 * dir_$old_alloc_block - hand out a block of an old-format directory
 *
 * Original address: 0x00E54E10
 * Size: 82 bytes (0x00E54E10 .. 0x00E54E61)
 * Generated by: Claude Opus 5.5
 *
 * Module-local routine of the OLD_DIR segment (no map symbol; Ghidra had it
 * as FUN_00e54e10).  Callers: dir_$old_reclaim_block (0x00E54F62),
 * dir_$old_find_overflow_slot (0x00E5505C) and dir_$old_add_link_entry
 * (0x00E5547A, 0x00E554E8).
 *
 * Frame: (0x8,A6) handle (A0, the mapped directory).  Result in D0w.
 *
 * Blocks:
 *   0x00E54E1A-0x00E54E32  free-list head (+0xC) non-zero: take it and make
 *                          its +0x36A link the new head
 *   0x00E54E34-0x00E54E4E  else blocks handed out (+0xA) below the limit
 *                          (+0x6, unsigned): take the next one
 *   0x00E54E52             either way clear the block's in-use count
 *   0x00E54E58             at the limit: 0
 */

#include "dir/dir_internal.h"

uint16_t dir_$old_alloc_block(uint32_t handle)
{
    uint8_t *dir = (uint8_t *)ARCH_VA_TO_PTR(handle);  /* A0 */
    uint16_t k;                                        /* D0 */
    uint8_t *block;                                    /* A1 */

    /* 0x00E54E1A-0x00E54E32 */
    k = DIR_OLD_W(dir, DIR_OLD_HDR_FREE_BLOCK);
    if (k != 0) {
        block = DIR_OLD_BLOCK(dir, k);
        DIR_OLD_W(dir, DIR_OLD_HDR_FREE_BLOCK) = DIR_OLD_W(block, DIR_OLD_BLOCK_NEXT);
    } else if (DIR_OLD_W(dir, DIR_OLD_HDR_BLOCKS) <
               DIR_OLD_W(dir, DIR_OLD_HDR_MAX_BLOCKS)) {
        /* 0x00E54E3E-0x00E54E4E */
        DIR_OLD_W(dir, DIR_OLD_HDR_BLOCKS)++;
        k = DIR_OLD_W(dir, DIR_OLD_HDR_BLOCKS);
        block = DIR_OLD_BLOCK(dir, k);
    } else {
        /* 0x00E54E58 */
        return 0;
    }

    /* 0x00E54E52 */
    block[DIR_OLD_BLOCK_USED] = 0;
    return k;
}
