/*
 * ring_$find_overlapping_pkt_type - Index of the entry overlapping a range
 *
 * Original address: 0x00E76422, 78 bytes (0x00E76422 .. 0x00E7646F); a
 * module-local routine with no map symbol (was FUN_00e76422).
 * Generated by: Claude Opus 5.5
 *
 * Frame (link.w A6,-0x10):
 *   (0x08,A6) low         longword (D1)
 *   (0x0C,A6) high        longword (D0)
 *   (0x10,A6) table       -> entry 1 of a 1-based ring_pkt_type_t table
 *   (0x14,A6) table_size  word
 *
 * The same test as ring_$pkt_type_overlaps, but returns the 1-based index
 * of the first overlapping entry (0x00E76456), or 0.
 * Callers: RING_$SVC_IOCTL (0x00E779D8, 0x00E77A98).
 */

#include "ring/ring_internal.h"

int16_t ring_$find_overlapping_pkt_type(uint32_t low, uint32_t high,
                                        ring_pkt_type_t *table,
                                        uint16_t table_size)
{
    int16_t n = (int16_t)(table_size - 1);   /* subq.w #1 / bmi */
    int16_t i = 1;                           /* D3 */

    if (n < 0) {
        return 0;
    }
    do {
        if (!(low > table[i - 1].high) && !(high < table[i - 1].low)) {
            return i;
        }
        i++;
    } while (--n != -1);                     /* dbf D2w */
    return 0;                                /* 0x00E76464 */
}
