/*
 * RING_$OPEN_OS - open a ring channel on the OS socket
 *
 * Original address: 0x00E77BA0 (SAU2 map)
 * Size: 132 bytes (0x00E77BA0 .. 0x00E77C23)
 * Generated by: Claude Opus 5.5
 *
 * Reached through RING_$CTL's driver block slot 0x3C.  A5 = 0xE86400.
 *
 * Frame (link.w A6,-0x98): (0x8,A6) unit word, (0xa,A6) args (D2),
 * (0xe,A6) status_ret (D3); (-0x88,A6) the ring_$open_args_t built for
 * ring_$open_internal, (-0x8c,A6) its status.
 *
 * Blocks:
 *   0x00E77BB6-0x00E77BC8  count > 0x10 (signed `ble`) -> invalid svc packet
 *                          type
 *   0x00E77BCA-0x00E77BD0  request = { version 1, count }
 *   0x00E77BD6-0x00E77BF4  count - 1 < 0 -> no copy; else dbf: count ranges
 *                          of 8 bytes from args + 0 to request + 4
 *   0x00E77BF8-0x00E77C08  ring_$open_internal(true, &unit, &request,
 *                          &status), word result slot reserved
 *   0x00E77C0C-0x00E77C14  *status_ret = status; args->channel = the word
 *                          at request + 4 (the channel on success, the high
 *                          word of the first range's low bound otherwise)
 */

#include "ring/ring_internal.h"

void RING_$OPEN_OS(uint16_t unit, ring_$open_os_args_t *args,
                   status_$t *status_ret)
{
    ring_$open_args_t request;      /* (-0x88,A6) */
    status_$t status;               /* (-0x8c,A6) */
    int16_t remaining;              /* D0w */
    int16_t i;

    /* 0x00E77BB6-0x00E77BC8 */
    if (args->u.in.count > 0x10) {
        *status_ret = status_$ring_invalid_svc_packet_type;
        return;
    }

    /* 0x00E77BCA-0x00E77BD0 */
    request.hdr.in.version = 1;
    request.hdr.in.count = (uint16_t)args->u.in.count;

    /* 0x00E77BD6-0x00E77BF4 */
    remaining = (int16_t)(args->u.in.count - 1);
    if (remaining >= 0) {
        i = 0;
        do {
            request.body.types[i] = args->u.types[i];
            i++;
        } while (--remaining != -1);
    }

    /* 0x00E77BF8-0x00E77C08: `st -(SP)`, `pea (0x8,A6)` */
    ring_$open_internal(true, &unit, &request, &status);

    /* 0x00E77C0C-0x00E77C14 */
    *status_ret = status;
    args->u.out.channel = request.body.channel;
}
