/*
 * RING_$SVC_CLOSE - close a ring channel (the driver's svc_close slot)
 *
 * Original address: 0x00E76E22
 * Size: 252 bytes (0x00E76E22 .. 0x00E76F1D)
 * Generated by: Claude Opus 5.5 (re-emitted from the disassembly because
 * RING_$CLOSE_OS showed the earlier three-argument C had the wrong frame)
 *
 * NET_$CLOSE's five-argument driver call (net/net.h net_$svc_ctl_fn_t) and
 * RING_$CLOSE_OS (0x00E77C4C) reach it.  Frame: (0x8,A6) unit_ptr,
 * (0xC,A6) channel_ptr, (0x10,A6) a word and (0x12,A6) a longword that are
 * never read, (0x16,A6) status_ret.  The callers reserve a word result slot
 * that this routine never writes.  A5 = RING_$CTL (0xE86400).
 *
 * Blocks:
 *   0x00E76E3C-0x00E76E4A  unit above 1: status_$ring_invalid_unit_num
 *   0x00E76E4E-0x00E76E62  u = &RING_$CTL.units[unit]; enter rx_exclusion
 *                          (+0x4C)
 *   0x00E76E64-0x00E76E8A  channel 0, above 10, or not open (flags byte at
 *                          +0x5A + 8*channel not negative): leave
 *                          rx_exclusion, status_$ring_channel_not_open
 *   0x00E76E8E             mark the channel closed
 *   0x00E76E92-0x00E76EA6  close its socket unless it is RING_OS_SOCKET_ID
 *   0x00E76EA8-0x00E76EE8  drop every packet-type entry the channel owns:
 *                          entry i (+0xA8 + 12*i, i = 1..pkt_type_cnt) whose
 *                          channel word equals *channel_ptr is overwritten
 *                          by the last entry and the count drops; i is then
 *                          tested again, else it advances
 *   0x00E76EEA-0x00E76F12  leave rx_exclusion; open_count-- under
 *                          tx_exclusion (+0x34); status_$ok
 *
 * Quirks reproduced:
 *   - Only 10 of the entry's 12 bytes move (`move.l'/`move.l'/`move.w',
 *     0x00E76ED2-0x00E76ED6): low, high and channel, not the pad word.
 *   - The channel word is re-read through channel_ptr on every comparison
 *     (`cmp.w (A3),D2w' 0x00E76EB6).
 */

#include "ring/ring_internal.h"

void RING_$SVC_CLOSE(uint16_t *unit_ptr, uint16_t *channel_ptr,
                     int16_t unused3, uint32_t unused4, status_$t *status_ret)
{
    ring_unit_t *u;                     /* A2 */
    uint16_t channel;                   /* D0 */
    uint16_t i;                         /* D0 */
    ring_pkt_type_t *dst;               /* A4 */
    ring_pkt_type_t *src;               /* A1 */

    (void)unused3;
    (void)unused4;

    /* 0x00E76E3C-0x00E76E4A */
    if (*unit_ptr > 1) {
        *status_ret = status_$ring_invalid_unit_num;
        return;
    }

    /* 0x00E76E4E-0x00E76E62 */
    u = &RING_$CTL.units[*unit_ptr];
    ML_$EXCLUSION_START(&u->rx_exclusion);

    /* 0x00E76E64-0x00E76E8A */
    channel = *channel_ptr;
    if (channel == 0 || channel > RING_MAX_CHANNELS ||
        RING_UNIT_CHANNEL(u, channel).flags >= 0) {
        ML_$EXCLUSION_STOP(&u->rx_exclusion);
        *status_ret = status_$ring_channel_not_open;
        return;
    }

    /* 0x00E76E8E */
    RING_UNIT_CHANNEL(u, channel).flags = 0;

    /* 0x00E76E92-0x00E76EA6 */
    if (RING_UNIT_CHANNEL(u, channel).socket_id != RING_OS_SOCKET_ID) {
        SOCK_$CLOSE((uint16_t)RING_UNIT_CHANNEL(u, channel).socket_id);
    }

    /* 0x00E76EA8-0x00E76EE8 */
    i = 1;
    while (i <= u->pkt_type_cnt) {
        if ((uint16_t)RING_UNIT_PKT_TYPE(u, i).channel == *channel_ptr) {
            dst = &RING_UNIT_PKT_TYPE(u, i);
            src = &RING_UNIT_PKT_TYPE(u, u->pkt_type_cnt);
            dst->low = src->low;
            dst->high = src->high;
            dst->channel = src->channel;
            u->pkt_type_cnt--;
        } else {
            i++;
        }
    }

    /* 0x00E76EEA-0x00E76F12 */
    ML_$EXCLUSION_STOP(&u->rx_exclusion);
    ML_$EXCLUSION_START(&u->tx_exclusion);
    u->open_count--;
    ML_$EXCLUSION_STOP(&u->tx_exclusion);
    *status_ret = status_$ok;
}
