/*
 * NET_IO_$CLEANUP_USER - per-address-space teardown of a USER-driver port
 *
 * Original address: 0x00E74F1E
 * Size: 92 bytes (0x00E74F1E .. 0x00E74F79)
 * Generated by: Claude Opus 5.5
 *
 * The proc2_cleanup slot of NET_IO_$USER_DRIVER, called like
 * NET_IO_$CLEANUP_NIL (net_io/net_io.h).  Frame: (0x8,A6) socket_ptr,
 * (0xC,A6) asid.
 *
 * Blocks:
 *   0x00E74F22-0x00E74F3A  if NET_IO_UNWIRED.port_asid[*socket_ptr] differs
 *                          from asid, nothing happens
 *   0x00E74F3C-0x00E74F50  port = ROUTE_$FIND_PORTP(2, socket) with the
 *                          socket word zero-extended (`clr.l D1' /
 *                          `move.w (A2),D1w')
 *   0x00E74F52-0x00E74F5E  ROUTE_$SHORT_PORT(port, &short_port)
 *   0x00E74F60-0x00E74F6C  ROUTE_$SERVICE(&net_io_$route_op_close (8),
 *                          &short_port, &status); the status is not looked at
 *
 * Quirks reproduced:
 *   - ROUTE_$FIND_PORTP's answer is handed to ROUTE_$SHORT_PORT without a
 *     nil test.
 *   - `pea (-0x4e,PC)' at 0x00E74F68 is the word at 0x00E74F1C, inside the
 *     preceding routine's code region, shared with NET_IO_$CLEANUP_NIL.
 */

#include "net_io/net_io_internal.h"

/* `move.w #0x2,-(SP)' 0x00E74F44: ROUTE_$FIND_PORTP's first argument */
#define CLEANUP_USER_PORT_TYPE  2

void NET_IO_$CLEANUP_USER(uint16_t *socket_ptr, uint16_t asid)
{
    route_$port_t *port;                /* A2 */
    route_$short_port_t short_port;     /* (-0x38,A6) */
    status_$t status;                   /* (-0x40,A6) */

    /* 0x00E74F22-0x00E74F3A */
    if (NET_IO_UNWIRED.port_asid[*socket_ptr] == asid) {
        /* 0x00E74F3C-0x00E74F50 */
        port = ROUTE_$FIND_PORTP(CLEANUP_USER_PORT_TYPE,
                                 (int32_t)(uint32_t)*socket_ptr);
        /* 0x00E74F52-0x00E74F5E */
        ROUTE_$SHORT_PORT(port, &short_port);
        /* 0x00E74F60-0x00E74F6C */
        ROUTE_$SERVICE(&net_io_$route_op_close, &short_port, &status);
    }
}
