/*
 * NET_IO_$CLEANUP_NIL - per-address-space teardown of a NIL-driver port
 *
 * Original address: 0x00E74EC8
 * Size: 84 bytes (0x00E74EC8 .. 0x00E74F1B; the word at 0x00E74F1C is the
 * shared constant net_io_$route_op_close)
 * Generated by: Claude Opus 5.5
 *
 * The proc2_cleanup slot of NET_IO_$NIL_DRIVER.  NET_IO_$FREE_ASID calls it
 * with the port's socket cell by address and the dying address space's id
 * by value (net_io/net_io.h).  Frame: (0x8,A6) socket_ptr, (0xC,A6) asid.
 *
 * Blocks:
 *   0x00E74ECC-0x00E74EE4  if NET_IO_UNWIRED.port_asid[*socket_ptr] differs
 *                          from asid, nothing happens
 *   0x00E74EE6-0x00E74F00  ROUTE_$SHORT_PORT(ROUTE_$PORTP[*socket_ptr],
 *                          &short_port)
 *   0x00E74F02-0x00E74F0E  ROUTE_$SERVICE(&net_io_$route_op_close (8),
 *                          &short_port, &status); the status is not looked at
 *
 * The socket word indexes both tables directly (`add.w D1w,D1w` for the
 * word table, `lsl.w #0x2,D1w` for ROUTE_$PORTP), with no range check.
 */

#include "net_io/net_io_internal.h"

void NET_IO_$CLEANUP_NIL(uint16_t *socket_ptr, uint16_t asid)
{
    route_$short_port_t short_port;     /* (-0x38,A6) */
    status_$t status;                   /* (-0x3C,A6) */

    /* 0x00E74ECC-0x00E74EE4 */
    if (NET_IO_UNWIRED.port_asid[*socket_ptr] == asid) {
        /* 0x00E74EE6-0x00E74F00 */
        ROUTE_$SHORT_PORT(ROUTE_$WIRED_DATA.portp[*socket_ptr], &short_port);
        /* 0x00E74F02-0x00E74F0E */
        ROUTE_$SERVICE(&net_io_$route_op_close, &short_port, &status);
    }
}
