/*
 * NET_IO_$COPY_PACKET - Copy a packet into fresh network buffers
 *
 * Original address: 0x00E0E514 (SAU2 map: NET_IO_$COPY_PACKET)
 * Size: 382 bytes (0x00E0E514 .. 0x00E0E691)
 * Generated by: Claude Opus 5.5
 *
 * NET_IO_$SEND's loopback paths use it to give the local receiver its own
 * copy.  The payload goes page by page into data pages from NETBUF_$GET_DAT
 * (each mapped with NETBUF_$GETVA for the copy), read either linearly from
 * src_data_va or from the pages src_pages names; the header goes into a
 * header buffer from NETBUF_$GET_HDR.
 *
 * Frame (link.w A6,-0x1c; D2-D7/A2-A4 saved; no A5):
 *   (0x08,A6) hdr_src_p  (0x0C,A6) hdr_len word (D5)  (0x0E,A6) src_data_va
 *   (0x12,A6) src_pages  (0x16,A6) data_len word  (0x18,A6) hdr_va_out
 *   (0x1C,A6) data_pages_out (A1)  (0x20,A6) status (A3)
 *   (-0x04) header physical address, (-0x08) destination page VA (D6),
 *   (-0x0C) source page VA (D7), (-0x1C) &data_pages_out[1];
 *   D2w the 1-based page number, D3w bytes left, D4w the dbf count
 *
 * Blocks:
 *   0x00E0E52C-0x00E0E534  *status = 0; no payload: data_pages_out[0] = 0
 *   0x00E0E538-0x00E0E566  pages = (data_len + 0x3FF) / 0x400
 *   0x00E0E568-0x00E0E5B8  per page: NETBUF_$GET_DAT, map it; map the
 *                          source page unless copying linearly
 *   0x00E0E5BC-0x00E0E600  a mapping failed: unmap what was mapped, return
 *                          every data page got so far, "transmit failed"
 *   0x00E0E604-0x00E0E65C  copy min(0x400, left) bytes, unmap both
 *   0x00E0E660-0x00E0E686  NETBUF_$GET_HDR; copy the header
 *
 * Quirks reproduced:
 *   - A failed destination mapping unmaps its VA only when GETVA left it
 *     non-zero; a failed source mapping unmaps the destination and then
 *     the source VA only when non-zero (0x00E0E590, 0x00E0E5C8).
 *   - On failure no header buffer is taken and *hdr_va_out is untouched.
 */

#include "net_io/net_io_internal.h"
#include "netbuf/netbuf.h"
#include "network/network.h"
#include "os/os.h"

/* The payload page size (`addi.l #0x3ff`, `move.w #0x400,D0w`) */
#define NET_IO_COPY_PAGE        0x400

void NET_IO_$COPY_PACKET(uint32_t *hdr_src_p, uint16_t hdr_len,
                         uint32_t src_data_va, uint32_t *src_pages,
                         uint16_t data_len, uint32_t *hdr_va_out,
                         uint32_t *data_pages_out, status_$t *status_ret)
{
    uint32_t hdr_pa;                    /* (-0x04,A6) */
    uint32_t dst_va;                    /* (-0x08,A6) */
    uint32_t src_va;                    /* (-0x0C,A6) */
    uint32_t dst;                       /* D6 */
    uint32_t src;                       /* D7 */
    uint16_t left;                      /* D3w */
    int16_t page;                       /* D2w, 1-based */
    int16_t count;                      /* D4w */
    int16_t k;
    uint16_t n;

    /* 0x00E0E52C-0x00E0E534 */
    *status_ret = status_$ok;
    left = data_len;
    if (data_len == 0) {
        data_pages_out[0] = 0;
    } else {
        /* 0x00E0E538-0x00E0E566 */
        count = (int16_t)(((uint32_t)data_len + (NET_IO_COPY_PAGE - 1)) /
                          NET_IO_COPY_PAGE - 1);
        if (count >= 0) {
            page = 1;
            do {
                /* 0x00E0E568-0x00E0E592 */
                NETBUF_$GET_DAT(&data_pages_out[page - 1]);
                NETBUF_$GETVA(data_pages_out[page - 1], &dst_va, status_ret);
                dst = dst_va;
                if (*status_ret != status_$ok) {
                    if (dst != 0) {
                        NETBUF_$RTNVA(&dst_va);
                    }
                    goto fail;
                }

                /* 0x00E0E59A-0x00E0E60E */
                if (src_data_va == 0) {
                    NETBUF_$GETVA(src_pages[page - 1], &src_va, status_ret);
                    src = src_va;
                    if (*status_ret != status_$ok) {
                        NETBUF_$RTNVA(&dst_va);
                        if (src != 0) {
                            src_va = src;
                            NETBUF_$RTNVA(&src_va);
                        }
                        goto fail;
                    }
                } else {
                    src = (uint32_t)((int32_t)page - 1) * NET_IO_COPY_PAGE +
                          src_data_va;
                }

                /* 0x00E0E612-0x00E0E65C */
                n = NET_IO_COPY_PAGE;
                if (n > left) {
                    n = left;
                }
                OS_$DATA_COPY(ARCH_VA_TO_PTR(src), ARCH_VA_TO_PTR(dst),
                              (uint32_t)n);
                left = (uint16_t)(left - NET_IO_COPY_PAGE);
                NETBUF_$RTNVA(&dst_va);
                if (src_data_va == 0) {
                    src_va = src;
                    NETBUF_$RTNVA(&src_va);
                }
                page++;
            } while (count-- != 0);
        }
    }

    /* 0x00E0E660-0x00E0E686 */
    NETBUF_$GET_HDR(&hdr_pa, hdr_va_out);
    OS_$DATA_COPY(ARCH_VA_TO_PTR(*hdr_src_p), ARCH_VA_TO_PTR(*hdr_va_out),
                  (uint32_t)hdr_len);
    return;

fail:
    /* 0x00E0E5DC-0x00E0E600: return data pages 1..page */
    for (k = (int16_t)(page - 1); k >= 0; k--) {
        NETBUF_$RTN_DAT(data_pages_out[(page - 1) - k]);
    }
    *status_ret = status_$network_transmit_failed;
}
