/*
 * NET_IO_$PUT_IN_SOCK - deliver a received packet to a local socket
 *
 * Original address: 0x00E0E4A0 (SAU2 map)
 * Size: 58 bytes (0x00E0E4A0 .. 0x00E0E4D9)
 * Generated by: Claude Opus 5.5
 *
 * The process-level entry to net_io_$put_in_sock_common (0x00E0E238);
 * NET_IO_$PUT_IN_SOCK_INT (0x00E0E4DA) is the interrupt-level twin.
 * Callers: ring_$receive_packet (0x00E76632), ROUTE_$INCOMING (0x00E87A3C).
 * A5 = 0xE244F0 (the NET_IO data segment), which the common routine uses.
 *
 * Frame (link.w A6,-0x4): (0x8,A6) net_type, (0xa,A6) socket, (0xc,A6)
 * hdr_va_p, (0x10,A6) data_pa_p, (0x14,A6) hdr_len, (0x16,A6) data_len;
 * (-0x4,A6) the eventcount cell the common routine fills.
 *
 *   0x00E0E4AC-0x00E0E4CE  net_io_$put_in_sock_common(nil port, net_type,
 *                          socket, false (`clr.w`), hdr_va_p, data_pa_p,
 *                          hdr_len, data_len, &ec) with a word result slot;
 *                          the result and the eventcount are dropped
 */

#include "net_io/net_io_internal.h"

void NET_IO_$PUT_IN_SOCK(uint16_t net_type, uint16_t socket, uint32_t *hdr_va_p,
                         uint32_t *data_pa_p, uint16_t hdr_len, uint16_t data_len)
{
    ec_$eventcount_t *ec;       /* (-0x4,A6) */

    /* 0x00E0E4AC-0x00E0E4CE */
    (void)net_io_$put_in_sock_common(NULL, net_type, socket, 0, hdr_va_p,
                                      data_pa_p, hdr_len, data_len, &ec);
}
