/*
 * TIME_$READ_CAL - Read calendar from OKI MSM5832 RTC
 *
 * Reads all 13 BCD registers from the OKI MSM5832 real-time clock/calendar
 * chip (memory-mapped at base address 0x00FFA800, short address 0x9C00)
 * and converts them to:
 *   - A 48-bit clock value (4-microsecond ticks since Apollo epoch)
 *   - A 32-bit timestamp (seconds since Apollo epoch, Jan 1 1980)
 *
 * MSM5832 Register Map (13 registers, 4-bit BCD each):
 *   Addr  Reg   Contents              Flags
 *   ----  ----  --------------------  -------------------------
 *   12    Y10   Year tens (0-9)       D0-D3
 *   11    Y1    Year ones (0-9)       D0-D3
 *   10    MO10  Month tens (0-1)      D0
 *    9    MO1   Month ones (0-9)      D0-D3
 *    8    D10   Day tens (0-3)        D0-D1, D2=leap year flag
 *    7    D1    Day ones (0-9)        D0-D3
 *    6    W     Weekday (0-6)         D0-D2
 *    5    H10   Hours tens (0-2)      D0-D1, D2=PM, D3=24-hour select
 *    4    H1    Hours ones (0-9)      D0-D3
 *    3    MI10  Minutes tens (0-5)    D0-D2
 *    2    MI1   Minutes ones (0-9)    D0-D3
 *    1    S10   Seconds tens (0-5)    D0-D2
 *    0    S1    Seconds ones (0-9)    D0-D3
 *
 * Apollo hardware interface (base 0x00FFA800):
 *   +0x20  CALENDAR CONTROL (write only)
 *          Bits 7-4: A3-A0 (MSM5832 register address, 0-12)
 *          Bit 2:    READ  (MSM5832 READ pin)
 *          Bit 1:    WRITE (MSM5832 WRITE pin)
 *          Bit 0:    HOLD  (MSM5832 HOLD pin - freezes counters)
 *          CS is generated by address decode hardware.
 *   +0x22  CALENDAR WRITE DATA (write only) - D0-D3 to MSM5832
 *   +0x24  CALENDAR READ DATA  (read only)  - D0-D3 from MSM5832
 *
 *   Data is inverted through the interface hardware (both read and
 *   write paths), so software must complement values (~digit).
 *
 * Read protocol:
 *   1. Assert HOLD (control = 0x01) to freeze MSM5832 counters
 *   2. For each register: set address + READ + HOLD (0xX5),
 *      delay, read inverted data from +0x24, complement & mask
 *   3. Deassert HOLD (control = 0x00)
 *
 * Write-back protocol (for leap year flag):
 *   1. Write inverted data to +0x22
 *   2. Set address + HOLD (0xX1)
 *   3. Assert WRITE: address + WRITE + HOLD (0xX3)
 *   4. Delay, then deassert WRITE: address + HOLD (0xX1)
 *
 * Uses a March-based calendar for the day count computation:
 *   March = month 0, February = month 11.
 * This simplifies leap year handling since the leap day (Feb 29)
 * falls at the end of the March-based "year".
 *
 * Called by TIME_$INIT during system boot to set the initial clock.
 *
 * Parameters:
 *   clock - Pointer to receive 48-bit clock value (ticks)
 *   time  - Pointer to receive 32-bit seconds since epoch
 *
 * Original address: 0x00e2af5e (gate entry), 0x00e2adfc (body)
 *
 * The gate is
 *     0x00E2AF5E  lea (-0x2,PC),A0     ; A0 = 0x00E2AF5E, the module base
 *     0x00E2AF62  jmp 0x00E2ADFC
 * and the body's first act is `movea.l A0,A5`.  A5 is then never used: the
 * body makes no (d,A5) reference at all, so the module-base setup is dead
 * here and has no C counterpart.
 *
 * Nested procedures (Pascal-style, now static helpers):
 *   time_$read_cal_delay      at 0x00e2af58 (generic delay loop)
 *   time_$read_cal_delay_20   at 0x00e2af54 (delay of 20 iterations)
 */

#include "time/time_internal.h"

/*
 * The MSM5832 register addresses, the Apollo control-byte bit assignments and
 * the three interface ports all live in cal/cal.h (CAL_$RTC_*, MSM5832_*),
 * shared with CAL_$WRITE_CALENDAR.
 *
 * The body loads the port base from the constant long at 0x00E2AF66
 * (0x00FFA800) into A0 and addresses the ports as (0x20,A0), (0x22,A0) and
 * (0x24,A0); CAL_$RTC_WRITE/CAL_$RTC_READ reproduce exactly that.
 */

/* First read control value: Y10 (addr 12) with READ + HOLD */
#define RTC_READ_START_CONTROL  CAL_$RTC_CTL_READ_HOLD(MSM5832_REG_Y10) /* 0xC5 */
#define RTC_CONTROL_STEP        CAL_$RTC_CTL_ADDR_STEP                  /* 0x10 */
#define RTC_INITIAL_DELAY       0xC8  /* 0x00E2AE10: move.w #0xC8,D1w   */
#define RTC_ACCESS_DELAY        0x14  /* 0x00E2AF54: move.w #0x14,D1w   */

/*
 * Digit array indices (order of reading: Y10 first, S1 last).
 * These map MSM5832 register addresses to array positions.
 */
#define DIGIT_YEAR_TENS     0   /* MSM5832 addr 12 (Y10) */
#define DIGIT_YEAR_ONES     1   /* MSM5832 addr 11 (Y1)  */
#define DIGIT_MONTH_TENS    2   /* MSM5832 addr 10 (MO10) */
#define DIGIT_MONTH_ONES    3   /* MSM5832 addr  9 (MO1) */
#define DIGIT_DAY_TENS      4   /* MSM5832 addr  8 (D10), D2=leap year */
#define DIGIT_DAY_ONES      5   /* MSM5832 addr  7 (D1)  */
#define DIGIT_WEEKDAY       6   /* MSM5832 addr  6 (W)   */
#define DIGIT_HOUR_TENS     7   /* MSM5832 addr  5 (H10), D2=PM/24H */
#define DIGIT_HOUR_ONES     8   /* MSM5832 addr  4 (H1)  */
#define DIGIT_MINUTE_TENS   9   /* MSM5832 addr  3 (MI10) */
#define DIGIT_MINUTE_ONES   10  /* MSM5832 addr  2 (MI1) */
#define DIGIT_SECOND_TENS   11  /* MSM5832 addr  1 (S10) */
#define DIGIT_SECOND_ONES   12  /* MSM5832 addr  0 (S1)  */

/*
 * Delay loop: counts down from 'count' to 0.
 * Provides timing margin for MSM5832 access (READ/WRITE setup/hold times).
 * Corresponds to time_$read_cal_delay at 0x00e2af58.
 */
static void time_$read_cal_delay(int16_t count)
{
    /*
     *   subq.w #0x1,D1w
     *   bne.b  time_$read_cal_delay
     * i.e. exactly `count` iterations (and 0x10000 for count == 0).
     * ARCH_SPIN_TICK() keeps the loop from being optimised away; the original
     * is pure CPU time used to meet the MSM5832 setup/hold times.
     */
    do {
        ARCH_SPIN_TICK();
        count = (int16_t)(count - 1);
    } while (count != 0);
}

/*
 * Standard delay of 0x14 (20) iterations for MSM5832 register access.
 * Corresponds to time_$read_cal_delay_20 at 0x00e2af54.
 * (Falls through to time_$read_cal_delay in the original assembly.)
 */
static void time_$read_cal_delay_20(void)
{
    time_$read_cal_delay(RTC_ACCESS_DELAY);
}

void TIME_$READ_CAL(clock_t *clock, uint32_t *time)
{
    int16_t digits[MSM5832_NUM_REGS];
    int16_t control;
    int i;
    short month;
    short march_month;     /* Month in March-based calendar (0=March, 11=February) */
    short march_flag;      /* 1 if original month >= 3, else 0 */
    short year_2digit;
    uint16_t year_from_epoch;
    uint16_t total_days;
    uint32_t total_seconds;
    uint32_t product_low;
    uint32_t product_high;
    uint16_t sec_low;
    uint16_t sec_high;

    /*
     * Assert HOLD to freeze the MSM5832 counters.
     * This prevents the clock from ticking while we read registers,
     * ensuring a consistent snapshot of the date/time.
     */
    CAL_$RTC_WRITE_CONTROL(CAL_$RTC_CTL_HOLD);

    /* Initial delay (0xC8 = 200 iterations) for HOLD setup time */
    control = RTC_READ_START_CONTROL;
    time_$read_cal_delay(RTC_INITIAL_DELAY);

    /*
     * Read all 13 MSM5832 registers (Y10 down to S1).
     *
     * For each register:
     *   1. Write control byte: address + READ + HOLD
     *   2. Delay for MSM5832 data output setup time
     *   3. Read data from read register, complement, mask to 4 bits
     *
     * Control values: 0xC5 (addr 12, Y10), 0xB5 (addr 11, Y1), 0xA5, 0x95,
     *   0x85, 0x75, 0x65, 0x55, 0x45, 0x35, 0x25, 0x15, 0x05 (addr 0, S1).
     *
     * Data is inverted through the Apollo interface hardware,
     * so we complement the read value to recover the true BCD digit.
     */
    i = 0;
    do {
        CAL_$RTC_WRITE_CONTROL((uint8_t)control);
        time_$read_cal_delay_20();
        /* 0x00E2AE20: move.b (0x24,A0),D1b / not.w D1w / and.w #0xF,D1w */
        digits[i] = (int16_t)((~(int16_t)CAL_$RTC_READ_DATA()) & 0xF);
        control -= RTC_CONTROL_STEP;
        i++;
    } while (control >= 0);

    /* Keep HOLD asserted (prepare for potential write-back) */
    CAL_$RTC_WRITE_CONTROL(CAL_$RTC_CTL_HOLD);

    /*
     * Reconstruct month value (1-12) from BCD digits.
     */
    month = digits[DIGIT_MONTH_TENS] * 10 + digits[DIGIT_MONTH_ONES];

    /*
     * Convert to March-based calendar.
     * In this system, March = month 0, February = month 11.
     * This simplifies leap year handling since the leap day
     * (Feb 29) falls at the end of the "year".
     */
    march_flag = 1;
    march_month = month - 3;
    if (march_month < 0) {
        march_flag = 0;
        march_month += 12;
    }

    /*
     * Reconstruct 2-digit year and adjust for March-based calendar.
     * If month >= March, the March-based year is year+1
     * (since we haven't finished the current March-based year yet).
     */
    year_2digit = digits[DIGIT_YEAR_TENS] * 10 + digits[DIGIT_YEAR_ONES];
    year_2digit += march_flag;

    /*
     * Normalize to years since March 1981.
     * (The Apollo epoch is Jan 1, 1980. In March-based terms,
     * the first complete year starts March 1980, which after
     * adding march_flag for month>=3 gives year 81.)
     *
     * 0x51 = 81 decimal.
     */
    year_from_epoch = (uint16_t)(year_2digit - 0x51);
    if ((int16_t)year_from_epoch < 0) {
        year_from_epoch += 100;
    }

    /*
     * Leap year check in March-based calendar.
     * (year_from_epoch + 1) divisible by 4 means this March-based
     * year contains a February 29.
     *
     * If leap year, write back the MSM5832 D10 register (addr 8)
     * with D2 set. The MSM5832 uses D10.D2 as the leap year
     * indicator for its internal day-counting logic.
     */
    if (((year_from_epoch + 1) & 3) == 0) {
        /*
         * 0x00E2AE74/0x00E2AE78: bset.l #2 -- D10 bit 2, which is where the
         * MSM5832 keeps the leap-year flag (D10 is {D0,D1 = date tens,
         * D2 = leap year, D3 = unused}).  This side is correct.
         *
         * CAL_$WRITE_CALENDAR deposits the same predicate in D10 bit 3 --
         * `add.w #0x50,D1w` at 0x00E816D6 -- which the chip ignores; that is
         * an original bug, resolved and documented in cal/cal.h and
         * cal/write_calendar.c (bead source-tcxm).  It is this write-back that
         * repairs the flag: TIME_$READ_CAL re-asserts D10 bit 2 on every read
         * taken during a leap year.
         */
        int16_t day_tens_with_flag =
            (int16_t)(digits[DIGIT_DAY_TENS] | MSM5832_D10_LEAP_FLAG);
        CAL_$RTC_WRITE_DATA((uint8_t)~(uint8_t)day_tens_with_flag);
        /* Write to D10 register (addr 8): set address + HOLD */
        CAL_$RTC_WRITE_CONTROL(CAL_$RTC_CTL_ADDR_HOLD(MSM5832_REG_D10));  /* 0x81 */
        /* Assert WRITE strobe */
        CAL_$RTC_WRITE_CONTROL(CAL_$RTC_CTL_WRITE_HOLD(MSM5832_REG_D10)); /* 0x83 */
        time_$read_cal_delay_20();
        /* Deassert WRITE, keep HOLD */
        CAL_$RTC_WRITE_CONTROL(CAL_$RTC_CTL_ADDR_HOLD(MSM5832_REG_D10));  /* 0x81 */
    }

    /* 0x00E2AE98: release HOLD - MSM5832 counters resume ticking */
    CAL_$RTC_WRITE_CONTROL(0);

    /*
     * ================================================================
     * Compute total days since epoch.
     *
     * Formula (March-based calendar):
     *   days = year_from_epoch * 365
     *        + year_from_epoch / 4        (leap days)
     *        + march_month * 30           (base days per month)
     *        + (march_month / 5) * 3      (correction for 31-day months)
     *        + ((march_month % 5) + 1) / 2  (fine correction)
     *        + day_of_month
     *        + 59                          (Jan + Feb = 31 + 28)
     *
     * The month formula approximates cumulative days from March:
     *   month 0 (Mar): 0     month 6 (Sep): 184
     *   month 1 (Apr): 31    month 7 (Oct): 214
     *   month 2 (May): 61    month 8 (Nov): 245
     *   month 3 (Jun): 92    month 9 (Dec): 275
     *   month 4 (Jul): 122   month 10 (Jan): 306
     *   month 5 (Aug): 153   month 11 (Feb): 337
     * ================================================================
     */
    total_days = (uint16_t)(year_from_epoch * 365) + (year_from_epoch >> 2);
    total_days += (uint16_t)((uint16_t)march_month * 30);
    total_days += (uint16_t)((uint16_t)(march_month / 5) * 3);
    total_days += (uint16_t)(((uint16_t)(march_month % 5) + 1) >> 1);

    /*
     * 0x00E2AEC8: and.w #3 -- only D0-D1 of D10 are date tens, so both the
     * leap-year flag (D2) and the unused bit CAL_$WRITE_CALENDAR sets (D3)
     * are discarded here.
     */
    total_days += (uint16_t)((digits[DIGIT_DAY_TENS] & MSM5832_TENS_MASK) * 10
                              + digits[DIGIT_DAY_ONES]);

    /* Add 59 for January (31) + February (28) to convert from March-based */
    total_days += 59;

    /*
     * ================================================================
     * Compute total seconds = day_seconds + time_of_day_seconds.
     *
     * Hours: mask off MSM5832 H10.D2 (24-hour/AM-PM flag).
     * ================================================================
     */

    /* Hours * 60 (mask H10 to D0-D1 only, ignoring D2 24H flag) */
    total_seconds = (uint32_t)(uint16_t)(
        ((digits[DIGIT_HOUR_TENS] & MSM5832_TENS_MASK) * 10
         + digits[DIGIT_HOUR_ONES]) * 60);

    /* Add minutes */
    total_seconds += (uint16_t)(digits[DIGIT_MINUTE_TENS] * 10
                                + digits[DIGIT_MINUTE_ONES]);

    /* Convert (hours*60 + minutes) to seconds */
    total_seconds = (uint32_t)(uint16_t)total_seconds * 60;

    /* Add seconds (32-bit add to handle full day range) */
    total_seconds += (uint32_t)(uint16_t)(digits[DIGIT_SECOND_TENS] * 10)
                     + (uint16_t)digits[DIGIT_SECOND_ONES];

    /*
     * Convert total_days to seconds and add.
     * total_days * 86400 = total_days * 2 * 43200.
     *
     * Note: The multiplication uses 16-bit intermediate (total_days * 2)
     * which can overflow for years past ~2069. This matches the original
     * m68k code which uses asl.w (16-bit shift) + mulu.w.
     */
    total_seconds += (uint32_t)(uint16_t)(total_days * 2) * 43200u;

    /* Store the seconds-since-epoch timestamp */
    *time = total_seconds;

    /*
     * ================================================================
     * Convert seconds to 48-bit clock ticks.
     *
     * ticks = seconds * 250,000 = seconds * 0x3D090
     * 0x3D090 = 3 * 0x10000 + 0xD090
     *
     * Uses partial products since the m68k 68010 only has
     * 16x16->32 multiply (mulu.w):
     *
     *   Let SL = seconds & 0xFFFF, SH = seconds >> 16
     *   clock->low  = (SL * 0xD090) & 0xFFFF
     *   clock->high = (SL * 0xD090) >> 16
     *               + SL * 3
     *               + SH * 0xD090
     *   Then add SH * 3 to the upper 16 bits of clock->high.
     * ================================================================
     */
    sec_low = (uint16_t)(total_seconds & 0xFFFF);
    sec_high = (uint16_t)(total_seconds >> 16);

    /* Low 16 bits of ticks */
    product_low = (uint32_t)sec_low * 0xD090u;
    clock->low = (uint16_t)product_low;

    /* Middle/high 32 bits of ticks */
    product_high = (product_low >> 16)
                 + (uint32_t)sec_low * 3u
                 + (uint32_t)sec_high * 0xD090u;
    clock->high = product_high;

    /* Add sec_high * 3 to upper 16 bits of clock->high (portably) */
    clock->high = ((uint32_t)((uint16_t)(clock->high >> 16) + sec_high * 3) << 16)
                | (clock->high & 0xFFFF);
}
