/*
 * disk_$grow_qblk_pool - grow the disk queue-block pool
 *
 * Original address: 0x00E3BC40 (Ghidra disk_$grow_qblk_pool; module-local,
 * no SAU2 map symbol)
 * Size: 586 bytes (0x00E3BC40 .. 0x00E3BE89)
 * Generated by: Claude Opus 5.5
 *
 * Caller: disk_$get_qblks_internal (0x00E3BEF0), with the module exclusion
 * lock (DISK_$DATA + 0x90) held and A5 = DISK_$DATA (0xE7A1CC); this routine
 * does not load A5 itself.
 *
 * Frame (link.w A6,-0x7c; D2-D6/A2-A4 saved):
 *   (0x08,A6) count   word: the number of free blocks wanted
 *   (-0x7C) want, (-0x78) the free count at entry, (-0x5C) pages to add,
 *   (-0x5A) first new page, (-0x58) last new page (both 1-based),
 *   (-0x50) WP_$CALLOC's ppn, (-0x4C) its status, (-0x48..-0x09) the new
 *   pages' ppns as a Pascal [1..16] array whose bias slot is that status
 *   (`(-0x4c,A4)` with A4 = A6 + page * 4, 0x00E3BD60), (-0x74)/(-0x70)
 *   the next page's VA cursors
 *
 * Blocks:
 *   0x00E3BC48-0x00E3BC58  want = count, at least 0x21 while there is no
 *                          reserve block (unsigned compare)
 *   0x00E3BC5A-0x00E3BC98  pages = ceil((want - avail) / 16): `asr.l #4`
 *                          after +15 for a negative, plus one when
 *                          M$OIS$WLW(want - avail, 16) is non-zero
 *   0x00E3BC9C-0x00E3BCC2  more than 16 pages in all: pages = 16 - allocated;
 *                          none left: growth disabled (0xAFA), done
 *   0x00E3BCC6-0x00E3BCE8  first = allocated + 1; allocated += pages;
 *                          last = allocated; exclusion lock released
 *   0x00E3BCEA-0x00E3BD6E  each new page: WP_$CALLOC (CRASH_SYSTEM on
 *                          error), MMU_$INSTALL(ppn, va, 0x16),
 *                          MMU_$CACHE_INHIBIT_VA(va), remember the ppn
 *   0x00E3BD72-0x00E3BD7C  exclusion lock retaken
 *   0x00E3BD7E-0x00E3BE20  each new page: its 16 blocks get free_next = the
 *                          following block and +0x10 = the physical address
 *                          of their own +0x20; the last block of a page
 *                          links to the next page, the last page's to the
 *                          old free list head
 *   0x00E3BE24-0x00E3BE44  free head = the first new page; avail +=
 *                          pages * 16
 *   0x00E3BE48-0x00E3BE70  no reserve block yet: take the head as the
 *                          reserve (its forward and free_next cleared),
 *                          reserve available, avail--
 *   0x00E3BE74-0x00E3BE7E  result: avail >= want
 *
 * Quirks reproduced:
 *   - The free head is set to the first new page even when no page was
 *     added (first > last skips both loops, 0x00E3BCF2 / 0x00E3BD80).
 *   - The last block of a non-final page is linked twice: by the block
 *     loop and again from (-0x74,A6) (0x00E3BE00).
 *   - The ceiling uses both the shifted quotient and M$OIS$WLW's remainder.
 */

#include "disk/disk_internal.h"
#include "math/math.h"
#include "wp/wp.h"
#include "mmu/mmu.h"
#include "misc/crash_system.h"

/* MMU_$INSTALL protection of a pool page (`pea (0x16).w` 0x00E3BD40) */
#define DISK_QBLK_PAGE_PROT     0x16

#define DMOD_U16(off)   (*(uint16_t *)(DISK_$DATA + (off)))
#define DMOD_I16(off)   (*(int16_t *)(DISK_$DATA + (off)))
#define DMOD_U32(off)   (*(uint32_t *)(DISK_$DATA + (off)))
#define QBLK_U32(va, off) (*(uint32_t *)((uint8_t *)ARCH_VA_TO_PTR(va) + (off)))

/* VA of pool page `page' (1-based) */
#define DISK_POOL_PAGE_VA(page) \
    (DISK_BLK_POOL_VA + (uint32_t)((int32_t)(int16_t)(page) << 10) - 0x400)

int8_t disk_$grow_qblk_pool(uint16_t count)
{
    uint16_t  want16;                   /* D1w */
    int32_t   want;                     /* (-0x7C,A6) */
    int32_t   diff;                     /* D2 */
    int16_t   pages;                    /* (-0x5C,A6) */
    int16_t   first;                    /* (-0x5A,A6) */
    int16_t   last;                     /* (-0x58,A6) */
    int16_t   n;                        /* D4w */
    int16_t   page;
    uint32_t  ppn;                      /* (-0x50,A6) */
    status_$t st;                       /* (-0x4C,A6) */
    uint32_t  ppns[DISK_QBLK_MAX_PAGES];/* (-0x48,A6): Pascal [1..16] */
    uint32_t  next_page_va;             /* (-0x74,A6) */
    uint32_t  page_end;                 /* (-0x70,A6) */
    uint32_t  phys;                     /* D3 */
    uint32_t  blk;
    int16_t   j;

    /* 0x00E3BC48-0x00E3BC58 */
    if (DMOD_U32(DMOD_RESERVE_BLOCK) != 0 || !(DISK_QBLK_MIN_GROW > count)) {
        want16 = count;
    } else {
        want16 = DISK_QBLK_MIN_GROW;
    }

    /* 0x00E3BC5A-0x00E3BC98 */
    want = (int32_t)(uint32_t)want16;
    diff = want - (int32_t)DMOD_I16(DMOD_AVAIL_COUNT);
    pages = (int16_t)(diff / 16);               /* +15 / asr.l #4 */
    if (M$OIS$WLW(diff, 16) != 0) {
        pages++;
    }

    /* 0x00E3BC9C-0x00E3BCC2 */
    if ((uint32_t)DMOD_U16(DMOD_PAGES_ALLOC) + (uint32_t)(uint16_t)pages >
        DISK_QBLK_MAX_PAGES) {
        pages = (int16_t)(DISK_QBLK_MAX_PAGES - DMOD_U16(DMOD_PAGES_ALLOC));
        if (pages == 0) {
            DISK_$DATA[DMOD_ALLOC_DISABLED] = 0xFF;
            goto done;
        }
    }

    /* 0x00E3BCC6-0x00E3BCE8 */
    first = (int16_t)(DMOD_U16(DMOD_PAGES_ALLOC) + 1);
    DMOD_U16(DMOD_PAGES_ALLOC) = (uint16_t)(DMOD_U16(DMOD_PAGES_ALLOC) + pages);
    last = (int16_t)DMOD_U16(DMOD_PAGES_ALLOC);
    ML_$EXCLUSION_STOP((ml_$exclusion_t *)(DISK_$DATA + DMOD_EXCLUSION));

    /* 0x00E3BCEA-0x00E3BD6E */
    n = (int16_t)(last - first);
    if (n >= 0) {
        for (page = first; page <= last; page++) {
            WP_$CALLOC(&ppn, &st);
            if (st != status_$ok) {
                CRASH_SYSTEM(&st);
            }
            MMU_$INSTALL(ppn, DISK_POOL_PAGE_VA(page), 0, DISK_QBLK_PAGE_PROT);
            MMU_$CACHE_INHIBIT_VA(DISK_POOL_PAGE_VA(page));
            ppns[page - 1] = ppn;
        }
    }

    /* 0x00E3BD72-0x00E3BD7C */
    ML_$EXCLUSION_START((ml_$exclusion_t *)(DISK_$DATA + DMOD_EXCLUSION));

    /* 0x00E3BD7E-0x00E3BE20 */
    if (n >= 0) {
        for (page = first; page <= last; page++) {
            page_end = DISK_BLK_POOL_VA + (uint32_t)((int32_t)page << 10);
            next_page_va = page_end;
            phys = ppns[page - 1] << 10;
            for (j = 0; j < DISK_QBLKS_PER_PAGE; j++) {   /* moveq #0xf / dbf */
                blk = page_end - 0x400 + (uint32_t)j * DISK_QBLK_SIZE;
                QBLK_U32(blk, DISK_QBLK_FREE_NEXT) = blk + DISK_QBLK_SIZE;
                QBLK_U32(blk, DISK_QBLK_PHYS) =
                    ((blk + 0x20) & 0x3FF) + phys;
            }
            blk = page_end - DISK_QBLK_SIZE;              /* (-0x38,A1) - 8 */
            if (page < last) {
                QBLK_U32(blk, DISK_QBLK_FREE_NEXT) = next_page_va;
            } else {
                QBLK_U32(blk, DISK_QBLK_FREE_NEXT) = DMOD_U32(DMOD_FREE_HEAD);
            }
        }
    }

    /* 0x00E3BE24-0x00E3BE44 */
    DMOD_U32(DMOD_FREE_HEAD) = DISK_POOL_PAGE_VA(first);
    DMOD_U16(DMOD_AVAIL_COUNT) =
        (uint16_t)(DMOD_U16(DMOD_AVAIL_COUNT) + (uint16_t)(pages << 4));

    /* 0x00E3BE48-0x00E3BE70 */
    if (DMOD_U32(DMOD_RESERVE_BLOCK) == 0) {
        DMOD_U32(DMOD_RESERVE_BLOCK) = DMOD_U32(DMOD_FREE_HEAD);
        DMOD_U32(DMOD_FREE_HEAD) =
            QBLK_U32(DMOD_U32(DMOD_FREE_HEAD), DISK_QBLK_FREE_NEXT);
        QBLK_U32(DMOD_U32(DMOD_RESERVE_BLOCK), DISK_QBLK_FREE_NEXT) = 0;
        QBLK_U32(DMOD_U32(DMOD_RESERVE_BLOCK), DISK_QBLK_FORWARD) = 0;
        DISK_$DATA[DMOD_RESERVE_AVAIL] = 0xFF;
        DMOD_U16(DMOD_AVAIL_COUNT)--;
    }

done:
    /* 0x00E3BE74-0x00E3BE7E */
    return ((int32_t)DMOD_I16(DMOD_AVAIL_COUNT) >= want) ? (int8_t)0xFF : 0;
}
