/*
 * DISK_$WRITE_MULTI - Write a chain of queue blocks, grouped by volume
 *
 * Original address: 0x00E3CCEE (SAU2 map: DISK_$WRITE_MULTI at E3CCEE)
 * Size: 622 bytes (0x00E3CCEE .. 0x00E3CF5B); its two status cells follow
 * at 0x00E3CF5C.  The helper before it, 0x00E3CCCE (32 bytes, no map
 * symbol, was FUN_00e3ccce), is disk_$set_chain_status below.
 * Generated by: Claude Opus 5.5
 *
 * Frame (link.w A6,-0x88; D2-D6/A2-A5 saved; A5 = DISK_$DATA 0x00E7A1CC):
 *   (0x08,A6) all_mounted  byte (D2b): TRUE writes only to volumes in
 *                          state 3; FALSE only to a volume in state 2 that
 *                          the calling process owns
 *   (0x0A,A6) req_list     the first queue block (linked through +0x00);
 *                          each block names its volume in its +0x1F byte
 *   (0x0E,A6) status       (D5 until the eventcount values reuse it)
 *   (-0x50) map[10]        disk_$map_request's per-volume chains; only the
 *                          heads are cleared (0x00E3CD08-0x00E3CD18)
 *   (-0x54) err_wait, (-0x58) io_wait   disk_$wait_io's values
 *   (-0x6A) issued         bit v: volume v was handed to DISK_$DO_IO
 *   (-0x70) queued         DISK_$DO_IO's result byte
 *   D6w     waited         bit v: volume v's request completes by interrupt
 *
 * Blocks:
 *   0x00E3CD08-0x00E3CD3A  clear the map heads, the masks and *status; mark
 *                          this process's I/O pending
 *   0x00E3CD3E-0x00E3CE26  walk the list a run of same-volume blocks at a
 *                          time: cut the run off, check the mount state,
 *                          then either DISK_IO each block synchronously
 *                          (NETLOG on, checksumming device, or a device
 *                          without queued writes), fail the run with
 *                          "write protected", or map it for queueing
 *   0x00E3CE2A-0x00E3CEBA  issue every mapped volume's chain with
 *                          DISK_$DO_IO and wait for the queued ones
 *   0x00E3CEBE-0x00E3CF4E  unless the I/O is still pending, post-process
 *                          the failed blocks of each issued volume
 *
 * Quirks reproduced:
 *   - The volume of the first block (+0x1F) is read before the list is
 *     tested for NULL (0x00E3CD44).
 *   - A mount-state failure of one run does not stop the others; a
 *     disk_$map_request failure returns at once, with the eventcounts
 *     untouched and the pending byte left set.
 *   - A queued block that failed with "write protected" only marks the
 *     volume write protected; the other failures go to disk_$io_error, and
 *     three of its outcomes (0x80031, 0x8002F, 0x80030) are cleared to 0.
 */

#include "disk/disk_internal.h"
#include "netlog/netlog.h"
#include "proc1/proc1.h"

/* DISK_IO operation: write (`move.w #0x1,-(SP)` 0x00E3CDC4) */
#define DISK_WRITE_OP               1
/* disk_$map_request's internal operation for a write (0x00E3CDFA) */
#define DISK_WRITE_MAP_OP           2

/* Bits of the device flag word at dev_info+8 (0x00E3CDA4) */
#define DEV_FLAG_CHECKSUM           0x4000  /* btst #14 */
#define DEV_FLAG_QUEUED_WRITES      0x0800  /* btst #11 */

/*
 * The status cells after the routine, reached PC-relative:
 * 0x00E3CF5C (00 08 00 0D) from 0x00E3CD92 and 0x00E3CF60 (00 08 00 07)
 * from 0x00E3CDE6.
 */
static const status_$t disk_$write_multi_not_mounted =
    status_$volume_not_properly_mounted;                  /* 0x00E3CF5C */
static const status_$t disk_$write_multi_protected =
    status_$disk_write_protected;                         /* 0x00E3CF60 */

/*
 * disk_$set_chain_status (0x00E3CCCE-0x00E3CCED) - store *status into every
 * block of the chain starting at req (linked through +0x00).
 */
static void disk_$set_chain_status(disk_io_req_t *req, const status_$t *status)
{
    disk_io_req_t *r;

    for (r = req; r != NULL; r = (disk_io_req_t *)ARCH_VA_TO_PTR(r->next)) {
        r->status = *status;
    }
}

void DISK_$WRITE_MULTI(int8_t all_mounted, void *req_list, status_$t *status)
{
    disk_$vol_map_entry_t map[DISK_VOLUME_MAP_ENTRIES];   /* (-0x50,A6) */
    int32_t io_wait;                                      /* (-0x58,A6) */
    int32_t err_wait;                                     /* (-0x54,A6) */
    uint16_t issued;                                      /* (-0x6A,A6) */
    int8_t queued;                                        /* (-0x70,A6) */
    uint16_t waited;                                      /* D6w */
    uint16_t vol_idx;                                     /* D3w */
    uint16_t bit;                                         /* D2w */
    uint32_t next;                                        /* D4 */
    disk_io_req_t *cur;                                   /* A1 */
    disk_io_req_t *run;                                   /* A2 */
    disk_io_req_t *r;                                     /* A4 */
    disk_$volume_t *vol;                                  /* A0 */
    disk_$per_proc_t *pp;
    int16_t v;
    int i;

    /* 0x00E3CD08-0x00E3CD3A */
    for (i = 0; i < DISK_VOLUME_MAP_ENTRIES; i++) {
        map[i].head = NULL;
    }
    waited = 0;
    issued = waited;
    *status = status_$ok;
    DISK_$PER_PROC[PROC1_$CURRENT].io_pending = (boolean)0xFF;

    /* 0x00E3CD3E-0x00E3CD48 */
    cur = (disk_io_req_t *)req_list;
    run = cur;
    vol_idx = cur->op_flags;

    while (cur != NULL) {
        /* 0x00E3CD4C-0x00E3CD5A: extend the run while the volume repeats */
        next = cur->next;
        if (next != 0 &&
            ((disk_io_req_t *)ARCH_VA_TO_PTR(next))->op_flags == vol_idx) {
            cur = (disk_io_req_t *)ARCH_VA_TO_PTR(next);
            continue;
        }

        /* 0x00E3CD5E-0x00E3CD90: cut the run off; may we write it? */
        vol = DISK_VOL(vol_idx);
        cur->next = 0;
        if ((vol->mount_state != DISK_MOUNT_BUSY && all_mounted < 0) ||
            (all_mounted >= 0 &&
             (vol->mount_state != DISK_MOUNT_ASSIGNED ||
              (uint16_t)vol->mount_proc != PROC1_$CURRENT))) {
            disk_$set_chain_status(run, &disk_$write_multi_not_mounted);
            goto next_run;                                /* 0x00E3CD92 */
        }

        /* 0x00E3CD98-0x00E3CDB4 */
        if (NETLOG_$OK_TO_LOG >= 0) {
            uint16_t dev_flags = *(const uint16_t *)((const uint8_t *)vol->dev_info + 8);

            if ((dev_flags & DEV_FLAG_CHECKSUM) == 0 &&
                (dev_flags & DEV_FLAG_QUEUED_WRITES) != 0) {
                /* 0x00E3CDDE-0x00E3CE0E: queue the run */
                if ((vol->as_options & DISK_VOL_FLAG_WRITE_PROTECT) != 0) {
                    disk_$set_chain_status(run, &disk_$write_multi_protected);
                } else {
                    disk_$map_request(run, (int16_t)vol_idx, DISK_WRITE_MAP_OP,
                                      map, status);
                    if (*status != status_$ok) {
                        return;                           /* 0x00E3CF52 */
                    }
                }
                goto next_run;
            }
        }

        /* 0x00E3CDB6-0x00E3CDDC: write the run a block at a time */
        while (run != NULL) {
            run->status = DISK_IO(DISK_WRITE_OP, vol_idx, run->ppn, run->daddr,
                                  run->header);
            run = (disk_io_req_t *)ARCH_VA_TO_PTR(run->next);
        }

    next_run:
        /* 0x00E3CE12-0x00E3CE20 */
        run = (disk_io_req_t *)ARCH_VA_TO_PTR(next);
        if (run != NULL) {
            vol_idx = run->op_flags;
        }
        cur = (disk_io_req_t *)ARCH_VA_TO_PTR(next);
    }

    /* 0x00E3CE2A-0x00E3CE9E: issue each mapped volume's chain */
    pp = &DISK_$PER_PROC[PROC1_$CURRENT];
    io_wait = (int32_t)pp->io_ec.value;                   /* D5 */
    err_wait = (int32_t)pp->err_ec.value + 1;
    for (v = 1; v <= DISK_VOLUME_MAP_ENTRIES; v++) {
        if (map[v - 1].head != NULL) {
            bit = 0;
            bit |= (uint16_t)(1u << v);
            issued |= bit;
            DISK_$DO_IO(DISK_VOL(v), map[v - 1].head, map[v - 1].tail, &queued);
            if (queued < 0) {
                io_wait++;
                waited |= bit;
            }
        }
    }

    /* 0x00E3CEA2-0x00E3CEBA */
    if (waited != 0) {
        disk_$wait_io(waited, &io_wait, &err_wait);
    }

    /* 0x00E3CEBE-0x00E3CF4E: the failed blocks */
    if (DISK_$PER_PROC[PROC1_$CURRENT].io_pending < 0) {
        return;
    }
    for (v = 1; v <= DISK_VOLUME_MAP_ENTRIES; v++) {
        if ((issued & (1u << v)) == 0) {
            continue;
        }
        for (r = map[v - 1].head; r != NULL;
             r = (disk_io_req_t *)ARCH_VA_TO_PTR(r->next)) {
            if (r->status == status_$ok) {
                continue;
            }
            if (r->status == status_$disk_write_protected) {
                DISK_VOL(v)->as_options |= DISK_VOL_FLAG_WRITE_PROTECT;
                continue;
            }
            disk_$io_error(v, r, r->header);
            if (r->status == status_$disk_ok_after_device_recovery ||
                r->status == status_$disk_ok_after_retry ||
                r->status == status_$disk_ok_after_crc_correction) {
                r->status = status_$ok;
            }
        }
    }
}
