/*
 * stop/stop_data.c - Stopwatch module data (A5 = 0x00E81814)
 *
 * Generated by: Claude Opus 5.5
 *
 * STOP_$DATA is the module's data block itself, 0x00E81BEC .. 0x00E82128
 * (A5+0x3D8 .. A5+0x914, the tail of the SAU2 map's STOP_WATCH segment,
 * size 0x914 from 0x00E81814).  MODULE_DATA_DEFINE_INIT gives it its own
 * section, which the generated build/sau2/layout.ld links right after the
 * module's code, where the map has it (0x00E81BEC is the ordering key, not
 * the link address); the layout and every A5 displacement are asserted in
 * stop/stop_internal.h.
 *
 * Everything except calib_patch, wire_start, wire_end and wire_count is zero
 * in the image; the stopwatch calibrates itself on the first call.
 */

#include "stop/stop_internal.h"

/* The address repeats the MODULE_DATA_DECLARE in stop/stop_internal.h; the
 * macro asserts the two agree. */
MODULE_DATA_DEFINE_INIT(stop_$data_t, STOP_$DATA, 0x00E81BEC, {
    /*
     * +0x128 (A5+0x500), 0x00E81D14: { 0x00E8193E, 0x00000000 }, the bare
     * `rts` at STOP_$NULL_PROC and no exit address.
     */
    .calib_patch = {
        /* .entry_addr = */ (uint16_t *)STOP_$NULL_PROC, /* 0x00E8193E */
        /* .exit_addr  = */ NULL,
    },
    /*
     * +0x130 (A5+0x508), 0x00E81D1C: 0x00E81814 in the image = STOP_$WATCH,
     * the start of the module.  A link-time value: wherever STOP_$WATCH is
     * linked (the image's value on the host).
     */
    .wire_start = ARCH_PTR_TO_VA_STATIC(STOP_$WATCH, 0x00E81814),
    /*
     * +0x134 (A5+0x50C), 0x00E81D20: 0x00E82128 = OS_DATA_SHUTWIRED, the
     * start of the FILE_ segment right after this block.  That object does
     * not exist in the tree yet, so the image's literal stays, although in
     * our link it no longer bounds the module.
     * TODO(source-h5ro): make it a link-time value once OS_DATA_SHUTWIRED /
     * the FILE_ block is linked after STOP_$DATA.
     */
    .wire_end = 0x00E82128,
    /* +0x13A (A5+0x512), 0x00E81D26 */
    .wire_count = 4,
});

/*
 * 0x00E21596.  Physically inside the FIM code region, not this block, but
 * written only by STOP_$WATCH_UII / STOP_$WATCH_TRACE (stop/sau2/watch.s)
 * and read by the FIM trace dispatcher at 0x00E215A6; its own `.text.'
 * section (stop/stop_internal.h) links it at its map position.
 */
boolean STOP_$WATCH_TRACE_FLAG STOP_WATCH_TRACE_FLAG_SECTION;
