#ifndef CAL_H
#define CAL_H

#include "base/base.h"
#include "math/math.h"
#include "time/time.h"

/* status_$t and status_$ok are defined in base/base.h */
#define status_$cal_refused 0x150007
#define status_$cal_date_or_time_invalid 0x150002

// Timezone record structure (12 bytes total at 0x00e7b030)
typedef struct {
  short utc_delta;  // offset from UTC in minutes (+0)
  char tz_name[4];  // timezone name, e.g. "EST" (+2)
  clock_t drift;    // drift correction (+6)
  ushort boot_volx; // boot volume index (+12)
} cal_$timezone_rec_t;

// Days per month lookup table
extern short CAL_$DAYS_PER_MONTH[12];

// Global timezone data at 0x00e7b030
extern cal_$timezone_rec_t CAL_$TIMEZONE;

// Boot volume index - separate variable that mirrors CAL_$TIMEZONE.boot_volx
// This exists as a separate variable because many files use it with extern declarations
extern int16_t CAL_$BOOT_VOLX;

// Last valid time (high word of clock) at 0x00e7b03c
extern uint CAL_$LAST_VALID_TIME;

/*
 * OKI MSM5832 RTC hardware registers (base address 0x00FFA800, short 0x9C00).
 *
 * The MSM5832 is a CMOS real-time clock/calendar with 13 BCD registers
 * (S1, S10, MI1, MI10, H1, H10, W, D1, D10, MO1, MO10, Y1, Y10)
 * accessed via 4-bit address (A3-A0) and 4-bit data (D3-D0) buses.
 *
 * Apollo interface registers:
 *   +0x20  CONTROL (W): bits 7-4 = A3-A0, bit 2 = READ, bit 1 = WRITE, bit 0 = HOLD
 *   +0x22  WRITE DATA (W): D3-D0 output to MSM5832 (inverted by hardware)
 *   +0x24  READ DATA (R): D3-D0 input from MSM5832 (inverted by hardware)
 *
 * CS is generated by the address decode hardware when accessing this range.
 */
extern volatile char CAL_$CONTROL_VIRTUAL_ADDR;    // 0x00ffa820 (base + 0x20)
extern volatile char CAL_$WRITE_DATA_VIRTUAL_ADDR; // 0x00ffa822 (base + 0x22)
extern volatile char CAL_$READ_DATA_VIRTUAL_ADDR;  // 0x00ffa824 (base + 0x24)

// 48-bit arithmetic
extern void ADD48(clock_t *dst, clock_t *src);
// Returns -1 if result is non-negative, 0 if result is negative
extern int8_t SUB48(clock_t *dst, clock_t *src);

// CAL functions
extern void CAL_$SEC_TO_CLOCK(uint *sec, clock_t *clock_ret);
extern ulong CAL_$CLOCK_TO_SEC(clock_t *clock);
extern void CAL_$APPLY_LOCAL_OFFSET(clock_t *clock);
extern void CAL_$REMOVE_LOCAL_OFFSET(clock_t *clock);
extern void CAL_$GET_LOCAL_TIME(clock_t *clock);
extern short CAL_$WEEKDAY(short *year, short *month, short *day);
extern void CAL_$DECODE_TIME(clock_t *clock, short *time_rec);
extern void CAL_$GET_INFO(cal_$timezone_rec_t *info);
extern void CAL_$SET_DRIFT(clock_t *drift);
extern void CAL_$READ_TIMEZONE(cal_$timezone_rec_t *tz, status_$t *status);
extern void CAL_$WRITE_TIMEZONE(cal_$timezone_rec_t *tz, status_$t *status);
extern void CAL_$SHUTDOWN(status_$t *status);
extern char CAL_$VERIFY(int *max_allowed_delta, void *param_2, char *param_3,
                        status_$t *status);
extern void CAL_$WRITE_CALENDAR(short *year, short *month, short *day,
                                short *weekday, short *hour, short *minute,
                                short *second);
extern void CAL_$SETUP_CALLBACK(void *callback_queue);

#endif /* CAL_H */
