/*
 * msg/test/test_msg_data.c - the MSG module data blocks (source-3llq)
 *
 * Generated by: Claude Opus 5.5
 *
 * Replaces test_data_layout.c (source-eq3o).  msg/msg_data.c is #included,
 * so the objects under test are the real blocks with the image's contents:
 *
 *   - MSG_$UNWIRED_DATA (map "D E80D84 MSG_UNWIRED size = 8E4"): offsets,
 *     the depth and ownership tables declared from their bias slots and
 *     indexed with the socket number (element k at +0x1E + k*2 and
 *     +0x1D8 + k*8), their strides and end points, and the template image;
 *   - MSG_$WIRED_DATA (map "D E242E4 MSG_WIRED size = 20"): the lock at +0,
 *     DPAGE_LOCK = -1 in the image (the page cell offsets are asserted at
 *     compile time on the target only: ml_$exclusion_t holds host pointers);
 *   - the ownership bit numbering the four writers share.
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

/* ==========================================================================
 * Test framework
 * ========================================================================== */

static int tests_failed = 0;
static int tests_run = 0;

#define TEST(name) static void test_##name(void)
#define RUN_TEST(name)                                                        \
    do {                                                                      \
        printf("  Running %s... ", #name);                                    \
        tests_run++;                                                          \
        test_##name();                                                        \
        printf("done\n");                                                     \
    } while (0)

#define ASSERT_EQ(expected, actual)                                           \
    do {                                                                      \
        long long _e = (long long)(expected);                                 \
        long long _a = (long long)(actual);                                   \
        if (_e != _a) {                                                       \
            printf("FAILED\n    Expected: 0x%llx, Got: 0x%llx at line %d\n",  \
                   (unsigned long long)_e, (unsigned long long)_a, __LINE__); \
            tests_failed++;                                                   \
            return;                                                           \
        }                                                                     \
    } while (0)

#include "msg/msg_internal.h"
#include "../msg_data.c"

#define OFF(field) ((size_t)((uint8_t *)&(field) - (uint8_t *)&MSG_$UNWIRED_DATA))

/* ==========================================================================
 * Tests
 * ========================================================================== */

/*
 * The image contents (`gsk read 0xE80D84 0x8E4`, `gsk read 0xE242E4 0x20`).
 * Runs first, before any test scribbles on the blocks.
 */
TEST(initial_contents_match_the_image)
{
    int sock;

    ASSERT_EQ(0x0000, MSG_$UNWIRED_DATA.send_template.flags);
    ASSERT_EQ(2, MSG_$UNWIRED_DATA.send_template.routing_type);
    ASSERT_EQ(2, MSG_$UNWIRED_DATA.send_template.addr_type);
    ASSERT_EQ(0x8031, MSG_$UNWIRED_DATA.send_template.protocol);
    ASSERT_EQ(0xFFFF, MSG_$UNWIRED_DATA.send_template.retry_limit);
    ASSERT_EQ(0, MSG_$UNWIRED_DATA.send_template.field_0a);
    ASSERT_EQ(0xFFFF, MSG_$UNWIRED_DATA.send_template.field_0c);
    for (sock = 1; sock <= MSG_MAX_SOCKET; sock++) {
        ASSERT_EQ(0, MSG_$UNWIRED_DATA.depth[sock]);
        ASSERT_EQ(0, MSG_$UNWIRED_DATA.ownership[sock][0]);
    }
    ASSERT_EQ(0, MSG_$UNWIRED_DATA.open_count);

    ASSERT_EQ(0, MSG_$WIRED_DATA.dpage_va);
    ASSERT_EQ(0, MSG_$WIRED_DATA.dpage_pa);
    ASSERT_EQ(-1, MSG_$WIRED_DATA.dpage_lock);
}

/* Image addresses and map sizes. */
TEST(block_addresses_and_sizes)
{
    ASSERT_EQ(0x00E80D84u, MODULE_DATA_ADDR(MSG_$UNWIRED_DATA));
    ASSERT_EQ(0x8E4, sizeof(MSG_$UNWIRED_DATA));
    ASSERT_EQ(MSG_$UNWIRED_DATA_SIZE, sizeof(msg_$unwired_data_t));
    ASSERT_EQ(0x00E242E4u, MODULE_DATA_ADDR(MSG_$WIRED_DATA));
    ASSERT_EQ(0, (size_t)((uint8_t *)&MSG_$WIRED_DATA.sock_lock -
                          (uint8_t *)&MSG_$WIRED_DATA));
}

/*
 * 0x00E59A40 "lea (A5),A2" (template), 0x00E59276
 * "move.w (A3),(0x1e,A5,D1w*0x1)" with D1 = socket*2, 0x00E5920A
 * "lea (0x1d8,A0),A1" with A0 = A5 + socket*8, 0x00E5927A
 * "addq.w #0x1,(0x8e0,A5)".
 */
TEST(recovered_offsets)
{
    ASSERT_EQ(0x000, OFF(MSG_$UNWIRED_DATA.send_template));
    ASSERT_EQ(0x01E, OFF(MSG_$UNWIRED_DATA.depth[0]));
    ASSERT_EQ(0x1D8, OFF(MSG_$UNWIRED_DATA.ownership[0][0]));
    ASSERT_EQ(0x8E0, OFF(MSG_$UNWIRED_DATA.open_count));
}

/* depth[k] at +0x1E + k*2 for every legal socket; depth[0xE0] ends where
 * socket 1's bitmap begins. */
TEST(depth_bias_stride_and_end)
{
    int sock;

    for (sock = 1; sock <= MSG_MAX_SOCKET; sock++) {
        ASSERT_EQ(0x1E + sock * 2, OFF(MSG_$UNWIRED_DATA.depth[sock]));
    }
    ASSERT_EQ(0x1E0, OFF(MSG_$UNWIRED_DATA.depth[MSG_MAX_SOCKET]) + 2);
    ASSERT_EQ(OFF(MSG_$UNWIRED_DATA.ownership[1][0]),
              OFF(MSG_$UNWIRED_DATA.depth[MSG_MAX_SOCKET]) + 2);
}

/* ownership[k] at +0x1D8 + k*8; ownership[0xE0] ends at open_count. */
TEST(ownership_bias_stride_and_end)
{
    int sock;

    for (sock = 1; sock <= MSG_MAX_SOCKET; sock++) {
        ASSERT_EQ(0x1D8 + sock * 8, OFF(MSG_$UNWIRED_DATA.ownership[sock][0]));
    }
    ASSERT_EQ(0x8E0, OFF(MSG_$UNWIRED_DATA.ownership[MSG_MAX_SOCKET][0]) + 8);
}

/* Neighbouring sockets' cells stay apart. */
TEST(writes_do_not_alias_neighbours)
{
    memset(&MSG_$UNWIRED_DATA, 0, sizeof(MSG_$UNWIRED_DATA));

    MSG_$UNWIRED_DATA.depth[5] = 0x1234;
    MSG_$UNWIRED_DATA.depth[MSG_MAX_SOCKET] = 0x5678;
    MSG_$UNWIRED_DATA.ownership[5][7] = 0x08;

    ASSERT_EQ(0x08, MSG_$UNWIRED_DATA.ownership[5][7]);
    ASSERT_EQ(0x1234, MSG_$UNWIRED_DATA.depth[5]);
    ASSERT_EQ(0x5678, MSG_$UNWIRED_DATA.depth[MSG_MAX_SOCKET]);
    ASSERT_EQ(0, MSG_$UNWIRED_DATA.ownership[4][7]);
    ASSERT_EQ(0, MSG_$UNWIRED_DATA.ownership[6][7]);
    ASSERT_EQ(0, MSG_$UNWIRED_DATA.open_count);

    /* socket 1's bitmap is not the last depth word */
    memset(&MSG_$UNWIRED_DATA, 0, sizeof(MSG_$UNWIRED_DATA));
    memset(MSG_$UNWIRED_DATA.ownership[1], 0xFF, 8);
    ASSERT_EQ(0, MSG_$UNWIRED_DATA.depth[MSG_MAX_SOCKET]);
}

/*
 * The bit numbering the four writers share: byte (0x3F - asid) >> 3 computed
 * in word arithmetic with a logical shift, bit asid & 7
 * (0x00E5925C-0x00E59260, 0x00E5942E-0x00E59436).
 */
TEST(ownership_bit_numbering)
{
    uint16_t asid;

    memset(&MSG_$UNWIRED_DATA, 0, sizeof(MSG_$UNWIRED_DATA));

    for (asid = 0; asid < 64; asid++) {
        int byte_index = (int)((uint16_t)(0x3F - asid) >> 3);
        MSG_$UNWIRED_DATA.ownership[9][byte_index] |= (uint8_t)(1 << (asid & 7));
    }

    ASSERT_EQ(0xFF, MSG_$UNWIRED_DATA.ownership[9][0]);
    ASSERT_EQ(0xFF, MSG_$UNWIRED_DATA.ownership[9][7]);
    ASSERT_EQ(0, MSG_$UNWIRED_DATA.ownership[8][7]);
    ASSERT_EQ(0, MSG_$UNWIRED_DATA.ownership[10][0]);

    ASSERT_EQ(7, (int)((uint16_t)(0x3F - 0) >> 3));
    ASSERT_EQ(0, (int)((uint16_t)(0x3F - 63) >> 3));
}

int main(void)
{
    printf("MSG module data tests\n");

    RUN_TEST(initial_contents_match_the_image);
    RUN_TEST(block_addresses_and_sizes);
    RUN_TEST(recovered_offsets);
    RUN_TEST(depth_bias_stride_and_end);
    RUN_TEST(ownership_bias_stride_and_end);
    RUN_TEST(writes_do_not_alias_neighbours);
    RUN_TEST(ownership_bit_numbering);

    printf("%d tests, %d failed\n", tests_run, tests_failed);
    return tests_failed != 0;
}
