/*
 * pmap_$write_page - write one dirty page to its backing store
 *
 * Original address: 0x00E12E5E (module-local; the SAU2 map has no symbol
 * here, Ghidra carries the tree name)
 * Size: 1044 bytes (0x00E12E5E .. 0x00E13271; the three status cells it
 * hands CRASH_SYSTEM follow at 0x00E13272..0x00E1327D)
 * Generated by: Claude Opus 5.5 (reviewed by Claude Fable 5.1)
 *
 * Callers: PMAP_$FLUSH (0x00E1390E), PMAP_$PURIFIER_L (0x00E140E6) and
 * PMAP_$PURIFIER_R (0x00E1430E), all holding ML lock 0x14.  The routine
 * drops the lock around the I/O and holds it again on every return.
 *
 * Frame (link.w A6,-0x78; D2-D7/A2-A4 saved):
 *   (0x08,A6) vpn        longword physical page number -> D6
 *   (0x0C,A6) status                                    -> A3
 *   (0x10,A6) sync_flag  byte (`tst.b (0x10,A6)`)
 *   (-0x64)   segment    mmape.segment                  (word)
 *   D3b       seg_offset mmape.seg_offset
 *   A4        0xEC5400 + segment*0x14: one past the segment's ASTE, so
 *             (-0x10,A4) is aste->aote, (-0x8,A4) aste->segment and
 *             (-0x2,A4) aste->flags
 *   (-0x70)   the segment-map entry + 0x80 (fields at (-0x80,..))
 *   (-0x74)   the mmape + 0x2000 (fields at (-0x2000+n,..))
 *   D5b       `smi` of mmape.flags2: the page belongs to an anonymous area
 *   D4        first a Domain boolean "remote", then the packet count
 *   (-0x30)   network_$page_request_t req: uid (-0x30), page_num (-0x28),
 *             +0x0C (-0x24), bytes +0x10 (-0x20) and +0x11 (-0x1f)
 *   (-0x10)   8-byte node address of the backing node
 *   (-0x3c)   clock_t NETWORK_$WRITE returns; (-0x60) its word result
 *   (-0x5c)   packet size; (-0x5e) the local volume index
 *
 * Blocks:
 *   0x00E12E66-0x00E12EC6  locate mmape, ASTE and segment-map entry
 *   0x00E12EC6-0x00E12F3A  area page (flags2 bit 7): the ASTE must be
 *                          remote (ASTE_FLAG_REMOTE, else CRASH_SYSTEM with
 *                          0x0032000A); req.uid = {ANON_$UID.high, the area
 *                          entry's remote_volx}, page_num = segment*32 +
 *                          seg_offset plus (that + 0x100) >> 8, byte +0x11 0
 *   0x00E12F3C-0x00E12F7E  object page: remote = ASTE_FLAG_REMOTE; volume
 *                          = aote->vol_index; req.uid = aote->uid,
 *                          page_num = segment*32 + seg_offset, byte +0x11
 *                          = aote->sub_type
 *   0x00E12F84-0x00E12F8C  byte +0x10 := 0; mark the entry "writing"
 *   0x00E12F92-0x00E12FB6  local page, DISK_$DO_CHKSUM on and the entry
 *                          installed: uninstall it and MMU_$REMOVE(vpn)
 *   0x00E12FB8-0x00E12FE0  NETLOG_$LOG_IT(3, &req, page_num >> 5,
 *                          seg_offset, vpn, 0, 0, 0)
 *   0x00E12FE4-0x00E12FF0  ML_$UNLOCK(0x14)
 *   remote 0x00E12FF8-0x00E130BC  count := 1; area page: node AREA_$PARTNER,
 *                          packet AREA_$PARTNER_PKT_SIZE, req +0x0C := 0;
 *                          object page: req +0x0C := aote->dtv_high, node
 *                          aote+0xAC, packet 1 << ((obj_uid byte 1 & 15) +
 *                          9); a short last page (max 1 << ((remote_flag &
 *                          15) + 9) below 0x400 and the page straddling the
 *                          object's end) is sent as `count` packets of
 *                          0x400 (count 0 -> CRASH_SYSTEM 0x00050006)
 *     0x00E130C2-0x00E130F6  NETWORK_$WRITE, then ML_$LOCK(0x14)
 *     0x00E130F8-0x00E13158  success: object page - write the DTV/DTM/DTA
 *                          back into the AOTE, and a synchronous write that
 *                          took more than one packet becomes status
 *                          0x0003000C; area page - disk_addr := 1 and the
 *                          ASTE dirty.  PROC1 stat[3] of the current
 *                          process += 1
 *     0x00E1315C-0x00E13182  0x110016 on an object page: ML_$UNLOCK,
 *                          AST_$SAVE_CLOBBERED_UID(&aote->uid), relock
 *     0x00E13186-0x00E131EC  0x30005 (NETWORK_$WRITE_VIOL_CNT += 1), 0xF0001
 *                          and 0x30001: clear "writing", advance
 *                          AST_$PMAP_IN_TRANS_EC; an area page crashes with
 *                          the status, an object page is invalidated with
 *                          AST_$INVALIDATE_PAGE; return
 *   local 0x00E131EE-0x00E1324C  disk address (low 22 bits, 0 -> CRASH_SYSTEM
 *                          0x00050009); DISK_$WRITE; write-protected is
 *                          success; PROC1 stat[2] += 1; ML_$LOCK(0x14)
 *   0x00E1324E-0x00E13262  pmap_$write_complete(vpn, status); success ->
 *                          EC_$ADVANCE(&AST_$PMAP_IN_TRANS_EC)
 */

#include "pmap/pmap_internal.h"
#include "area/area.h"
#include "ast/ast.h"
#include "ec/ec.h"
#include "file/file.h"
#include "misc/crash_system.h"

/*
 * The three cells after the body, each reached by one `pea (d,PC)`:
 *   0x00E13272  00 32 00 0a  (0x00E12EE2) an area page whose ASTE is not
 *                            remote - the AREA_ internal-error code
 *   0x00E13276  00 05 00 09  (0x00E131FE) "bad disk address" (stcodes 50009)
 *   0x00E1327A  00 05 00 06  (0x00E130B0) "bad assoc" (stcodes 50006)
 */
static const status_$t pmap_$area_internal_error_00e13272 = 0x0032000A;
static const status_$t pmap_$bad_disk_address_00e13276    = 0x00050009;
static const status_$t pmap_$bad_assoc_00e1327a           = status_$pmap_bad_assoc;

/* `move.w #0x3,-(SP)` 0x00E12FD6: the NETLOG record kind of a page write */
#define PMAP_WP_NETLOG_KIND     3
/* `addi.l #0x9,D0` 0x00E13036/0x00E13048: packet sizes are 1 << (n + 9) */
#define PMAP_WP_PKT_SHIFT_BASE  9
#define PMAP_WP_PAGE_SIZE       0x400

/* A word `lsl.w Dn` of 1: counts of 16 and up shift every bit out. */
static uint16_t pmap_$wp_word_shl1(uint32_t count)
{
    return (uint16_t)(count < 16 ? (1u << count) : 0);
}

void pmap_$write_page(uint32_t vpn, status_$t *status, int8_t sync_flag)
{
    mmape_t *page;                  /* (-0x74,A6) - 0x2000 */
    uint16_t segment;               /* (-0x64,A6) */
    uint8_t seg_offset;             /* D3b */
    aste_t *aste;                   /* A4 - 0x14 */
    aote_t *aote;                   /* A2 */
    uint32_t *entry;                /* (-0x70,A6) - 0x80 */
    int8_t is_area;                 /* D5b */
    int8_t remote;                  /* D4b */
    uint16_t count;                 /* D4w on the remote path */
    uint16_t area_id;               /* D2w on the area path */
    uint16_t volx;                  /* (-0x5e,A6) */
    uint16_t pkt_size;              /* (-0x5c,A6) */
    uint16_t max_size;              /* D0w */
    uint16_t dtv_low;               /* (-0x60,A6) -> D2w */
    uint32_t pn;                    /* D1 */
    uint32_t off;                   /* D1 */
    uint32_t daddr;                 /* D2 */
    int32_t n;                      /* D4 */
    uid_t node;                     /* (-0x10,A6) */
    clock_t dtm;                    /* (-0x3c,A6) */
    network_$page_request_t req;    /* (-0x30,A6) */

    /* 0x00E12E66-0x00E12EC2 */
    page = MMAPE_FOR_VPN(vpn);
    segment = page->segment;
    seg_offset = page->seg_offset;
    aste = AST_ASTE_ENTRY(segment);
    entry = (uint32_t *)&PMAP_SEGMAP_ROW(segment)[seg_offset];

    /* 0x00E12EC6 tst.b (-0x1ff7,A1) / smi D5b */
    is_area = ((int8_t)page->flags2 < 0) ? -1 : 0;

    if (is_area < 0) {
        /* 0x00E12ED0-0x00E12EEC: an area segment's ASTE names a record
         * whose word at +0x2A is the area id (the low half of dtm_high,
         * as ast/deactivate_segment.c reads it) */
        aote = aste->aote;
        area_id = (uint16_t)(aote->dtm_high & 0xFFFF);
        if ((aste->flags & ASTE_FLAG_REMOTE) == 0) {
            CRASH_SYSTEM(&pmap_$area_internal_error_00e13272);
        }

        /* 0x00E12EEE-0x00E12F18 */
        remote = -1;
        req.reserved[1] &= 0xFF00FFFFu;                 /* clr.b (-0x1f) */
        req.uid.high = ANON_$UID.high;
        req.uid.low = (uint32_t)(uint16_t)AREA_ID_TO_ENTRY(area_id)->remote_volx;

        /* 0x00E12F1C-0x00E12F36 */
        pn = (uint32_t)seg_offset + ((uint32_t)aste->segment << 5);
        req.page_num = pn;
        req.page_num += (pn + 0x100) >> 8;
    } else {
        /* 0x00E12F3C-0x00E12F7E */
        aote = aste->aote;
        remote = ((aste->flags & ASTE_FLAG_REMOTE) != 0) ? -1 : 0;
        volx = aote->vol_index;
        req.uid = aote->uid;
        req.page_num = ((uint32_t)aste->segment << 5) + seg_offset;
        req.reserved[1] = (req.reserved[1] & 0xFF00FFFFu) |
                          ((uint32_t)aote->sub_type << 16);
    }

    /* 0x00E12F84-0x00E12F8C: byte +0x10 := 0; mark the entry being written */
    req.reserved[1] &= 0x00FFFFFFu;
    *entry |= PMAP_SEGMAP_L_WRITING;

    /* 0x00E12F92-0x00E12FB6 */
    if (remote >= 0 && DISK_$DO_CHKSUM < 0 &&
        (*entry & PMAP_SEGMAP_L_INSTALLED) != 0) {
        *entry &= ~PMAP_SEGMAP_L_INSTALLED;
        MMU_$REMOVE(vpn);
    }

    /* 0x00E12FB8-0x00E12FE0 */
    if (NETLOG_$OK_TO_LOG < 0) {
        NETLOG_$LOG_IT(PMAP_WP_NETLOG_KIND, (uint32_t *)&req,
                       (uint16_t)(req.page_num >> 5), seg_offset,
                       (uint16_t)vpn, 0, 0, 0);
    }

    /* 0x00E12FE4-0x00E12FF0 */
    ML_$UNLOCK(PMAP_LOCK_ID);

    if (remote < 0) {
        /* 0x00E12FF8 moveq #0x1,D4 */
        count = 1;

        if (is_area < 0) {
            /* 0x00E12FFE-0x00E13018 */
            req.reserved[0] = 0;
            node = AREA_$PARTNER;
            pkt_size = (uint16_t)AREA_$PARTNER_PKT_SIZE;
        } else {
            /* 0x00E1301C-0x00E1303E */
            req.reserved[0] = aote->dtv_high;
            node.high = aote->obj_loc_net;
            node.low = aote->obj_loc_node;
            pkt_size = pmap_$wp_word_shl1(
                ((aote->obj_uid.high >> 16) & 0x0F) + PMAP_WP_PKT_SHIFT_BASE);

            /* 0x00E13042-0x00E1305E */
            max_size = pmap_$wp_word_shl1(
                ((uint8_t)aote->remote_flag & 0x0F) + PMAP_WP_PKT_SHIFT_BASE);
            if (max_size < PMAP_WP_PAGE_SIZE) {
                /* 0x00E13060-0x00E1307E: byte offset of the page */
                off = ((((uint32_t)aste->segment << 5) + seg_offset) << 10);
                if (!(off > aote->length)) {
                    /* 0x00E13080-0x00E13092 */
                    if (!((int32_t)(off + PMAP_WP_PAGE_SIZE - max_size) <
                          (int32_t)aote->length)) {
                        /* 0x00E13094-0x00E130AA: Pascal div by 0x400 */
                        n = (int32_t)(aote->length - off + 0x3FF);
                        if (n < 0) {
                            n += 0x3FF;
                        }
                        n >>= 10;
                        count = (uint16_t)n;
                        /* 0x00E130AC-0x00E130BA */
                        if (count == 0) {
                            CRASH_SYSTEM(&pmap_$bad_assoc_00e1327a);
                        }
                        /* 0x00E130BC */
                        pkt_size = PMAP_WP_PAGE_SIZE;
                    }
                }
            }
        }

        /* 0x00E130C2-0x00E130E6 */
        NETWORK_$WRITE(&node, &req, vpn, pkt_size, count, &dtv_low, &dtm,
                       status);

        /* 0x00E130EA-0x00E130F6 */
        ML_$LOCK(PMAP_LOCK_ID);

        if (*status == status_$ok) {
            if (is_area >= 0) {
                /* 0x00E13100-0x00E1311C */
                aote->dtv_high = req.reserved[0];
                aote->dtv_low = dtv_low;
                aote->dtm_high = dtm.high;
                aote->dtm_low = dtm.low;
                aote->dta_high = dtm.high;
                aote->dta_low = dtm.low;
                /* 0x00E13122-0x00E1312E */
                if (sync_flag < 0 && count != 1) {
                    *status = status_$ast_last_page_partially_written;
                }
            } else {
                /* 0x00E13136-0x00E13140 */
                page->disk_addr = 1;
                aste->flags |= ASTE_FLAG_DIRTY;
            }
            /* 0x00E13146-0x00E13154 */
            PROC1_$DATA.stats[PROC1_$CURRENT].stat[3]++;
        } else if (*status == status_$network_memory_parity_error_during_transmit &&
                   is_area >= 0) {
            /* 0x00E13168-0x00E13180 */
            ML_$UNLOCK(PMAP_LOCK_ID);
            AST_$SAVE_CLOBBERED_UID(&aote->uid);
            /* 0x00E13240-0x00E1324C */
            ML_$LOCK(PMAP_LOCK_ID);
        } else {
            /* 0x00E13186-0x00E131A6 */
            if (*status == status_$ast_write_concurrency_violation) {
                NETWORK_$WRITE_VIOL_CNT++;
            } else if (*status != status_$file_object_not_found &&
                       *status != status_$ast_eof) {
                goto complete;
            }

            /* 0x00E131AA-0x00E131C0 */
            *entry &= ~PMAP_SEGMAP_L_WRITING;
            EC_$ADVANCE(&AST_$PMAP_IN_TRANS_EC);

            if (is_area < 0) {
                /* 0x00E131C6-0x00E131CE */
                CRASH_SYSTEM(status);
            } else {
                /* 0x00E131D2-0x00E131EC */
                AST_$INVALIDATE_PAGE(aste, entry, vpn);
            }
            return;
        }
    } else {
        /* 0x00E131EE-0x00E13208 */
        daddr = page->disk_addr & PMAP_DADDR_MASK;
        if (daddr == 0) {
            CRASH_SYSTEM(&pmap_$bad_disk_address_00e13276);
        }

        /* 0x00E1320A-0x00E1322C */
        DISK_$WRITE((int16_t)volx, daddr, vpn, (uint32_t *)&req, status);
        if (*status == status_$disk_write_protected) {
            *status = status_$ok;
        }

        /* 0x00E1322E-0x00E1323C */
        PROC1_$DATA.stats[PROC1_$CURRENT].stat[2]++;

        /* 0x00E13240-0x00E1324C */
        ML_$LOCK(PMAP_LOCK_ID);
    }

complete:
    /* 0x00E1324E-0x00E13262 */
    pmap_$write_complete((int32_t)vpn, status);
    if (*status == status_$ok) {
        EC_$ADVANCE(&AST_$PMAP_IN_TRANS_EC);
    }
}
