/*
 * vtoc/test/test_truncate.c - unit tests for VTOCE_$TRUNCATE (0x00E39E42)
 * and its nested vtoc_$free_indirect (0x00E39BC2)
 *
 * Generated by: Claude Opus 5.5
 *
 * Drives the real routine over a small in-memory "disk" of 1K blocks
 * through mocked DBUF_$GET_BLOCK / DBUF_$SET_BUFF, BAT_$FREE,
 * BAT_$ADD_PART_VTOCE, vtoc_$hash_uid, vtoc_$uid_cache_lookup and the
 * two Pascal math helpers.
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

static int tests_passed = 0;
static int tests_failed = 0;

#define RUN_TEST(name) do { \
    printf("  Running %s... ", #name); \
    reset_state(); \
    test_##name(); \
    if (!test_failed_flag) { printf("PASSED\n"); tests_passed++; } \
    test_failed_flag = 0; \
} while (0)

static int test_failed_flag = 0;

#define ASSERT_EQ(expected, actual) do { \
    if ((unsigned long)(expected) != (unsigned long)(actual)) { \
        printf("FAILED\n    Expected: 0x%lx, Got: 0x%lx at line %d\n", \
               (unsigned long)(expected), (unsigned long)(actual), __LINE__); \
        tests_failed++; \
        test_failed_flag = 1; \
        return; \
    } \
} while (0)

#include "vtoc/vtoc_internal.h"
#include "math/math.h"

vtoc_$data_t vtoc_$data;
uid_t VTOC_$UID = { 0x00000202u, 0 };
uid_t VTOC_BKT_$UID = { 0x00000204u, 0 };

#define NBLOCKS 16
static union { uint32_t l[0x100]; uint8_t b[0x400]; } disk[NBLOCKS];

static int       mock_lock_depth;
static int       mock_get_calls;
static uint32_t  mock_get_block[16];
static uid_t    *mock_get_uid[16];
static uint32_t  mock_get_hint[16];
static uint16_t  mock_get_type[16];
static int       mock_set_calls;
static void     *mock_set_buf[32];
static uint16_t  mock_set_op[32];
static int       mock_free_calls;
static int16_t   mock_free_count[16];
static uint32_t  mock_freed[1024];
static int       mock_freed_n;
static int       mock_part_calls;
static uint32_t  mock_hash_block;
static uint16_t  mock_hash_idx;
static int       mock_cache_calls;
static char      mock_cache_remove;

void ML_$LOCK(int16_t id)   { (void)id; mock_lock_depth++; }
void ML_$UNLOCK(int16_t id) { (void)id; mock_lock_depth--; }

void *DBUF_$GET_BLOCK(uint16_t vol_idx, int32_t block, uid_t *uid,
                      uint32_t hint, uint16_t type, uint16_t flags, status_$t *status)
{
    (void)vol_idx; (void)flags;
    mock_get_block[mock_get_calls] = (uint32_t)block;
    mock_get_uid[mock_get_calls] = uid;
    mock_get_hint[mock_get_calls] = hint;
    mock_get_type[mock_get_calls] = type;
    mock_get_calls++;
    *status = status_$ok;
    return disk[block & 0x7FFFFFFF].b;
}

void DBUF_$SET_BUFF(void *buf, uint16_t op, status_$t *status)
{
    mock_set_buf[mock_set_calls] = buf;
    mock_set_op[mock_set_calls] = op;
    mock_set_calls++;
    *status = status_$ok;
}

void BAT_$FREE(uint32_t *blocks, int16_t count, int16_t vol_idx,
               int16_t reserved, status_$t *status)
{
    int16_t k;
    (void)vol_idx; (void)reserved;
    mock_free_count[mock_free_calls++] = count;
    for (k = 0; k < count; k++) {
        mock_freed[mock_freed_n++] = blocks[k];
    }
    *status = status_$ok;
}

uint32_t BAT_$ADD_PART_VTOCE(int16_t vol_idx, uint32_t block, status_$t *status)
{
    (void)vol_idx; (void)block;
    mock_part_calls++;
    *status = status_$ok;
    return 0x1234;
}

void vtoc_$hash_uid(uid_t *uid, short vol_idx, uint16_t *bucket_idx,
                    uint32_t *block, status_$t *status)
{
    (void)uid; (void)vol_idx;
    *bucket_idx = mock_hash_idx;
    *block = mock_hash_block;
    *status = status_$ok;
}

uint8_t vtoc_$uid_cache_lookup(uid_t *uid, uint16_t *flags, uint32_t *block_info, char remove)
{
    (void)uid; (void)flags; (void)block_info;
    mock_cache_calls++;
    mock_cache_remove = remove;
    return 0;
}

long M$DIS$LLL(long dividend, long divisor) { return dividend / divisor; }
long M$MIS$LLW(long multiplicand, short multiplier) { return multiplicand * multiplier; }

#include "vtoc/truncate.c"

#define VOL      2
#define VTOCBLK  1
#define ENTRY    1

static vtoc_$lookup_req_t req;

static void reset_state(void)
{
    memset(&vtoc_$data, 0, sizeof(vtoc_$data));
    memset(disk, 0, sizeof(disk));
    mock_lock_depth = 0;
    mock_get_calls = 0;
    mock_set_calls = 0;
    mock_free_calls = 0;
    mock_freed_n = 0;
    mock_part_calls = 0;
    mock_cache_calls = 0;
    mock_cache_remove = 0;
    mock_hash_block = 0;
    mock_hash_idx = 0;

    vtoc_$data.mounted[VOL] = (int8_t)0xFF;
    memset(&req, 0, sizeof(req));
    req.vol_idx = VOL;
    req.block_hint = (VTOCBLK << 4) | ENTRY;
    req.uid.high = 0x11112222u;
    req.uid.low = 0x33334444u;
}

static vtoce_$old_fm_t *old_entry(void)
{
    return (vtoce_$old_fm_t *)(disk[VTOCBLK].b + 4 + ENTRY * VTOCE_OLD_SIZE);
}

static vtoce_$new_fm_t *new_entry(void)
{
    return (vtoce_$new_fm_t *)(disk[VTOCBLK].b + 8 + ENTRY * VTOCE_NEW_SIZE);
}

static void make_new_entry(void)
{
    vtoce_$hdr_t *h = (vtoce_$hdr_t *)new_entry();
    vtoc_$data.format[VOL] = (int8_t)0xFF;
    h->status = VTOCE_STATUS_IN_USE;
    h->uid = req.uid;
}

/* not mounted: 0x20001, nothing fetched, lock balanced */
static void test_not_mounted(void)
{
    uint32_t freed = 77; status_$t st = 0;
    vtoc_$data.mounted[VOL] = 0;
    VTOCE_$TRUNCATE(&req, 0, 0, 0, &freed, &st);
    ASSERT_EQ(status_$VTOC_not_mounted, st);
    ASSERT_EQ(0, freed);
    ASSERT_EQ(0, mock_get_calls);
    ASSERT_EQ(0, mock_lock_depth);
}

/* old format, 2049 bytes -> 3 blocks: direct 3..4 go, bit 31 masked */
static void test_old_direct_truncate(void)
{
    uint32_t freed = 0; status_$t st = 1;
    vtoce_$old_fm_t *e = old_entry();
    e->direct[0] = 100; e->direct[1] = 101; e->direct[2] = 102;
    e->direct[3] = 0x80000067u; e->direct[4] = 104;

    VTOCE_$TRUNCATE(&req, 0, 2049, 0, &freed, &st);

    ASSERT_EQ(status_$ok, st);
    ASSERT_EQ(2, freed);
    ASSERT_EQ(102, e->direct[2]);
    ASSERT_EQ(0, e->direct[3]);
    ASSERT_EQ(0, e->direct[4]);
    ASSERT_EQ(1, mock_free_calls);
    ASSERT_EQ(2, mock_free_count[0]);
    ASSERT_EQ(0x67, mock_freed[0]);
    ASSERT_EQ(104, mock_freed[1]);
    ASSERT_EQ(1, mock_set_calls);
    ASSERT_EQ(BAT_BUF_WRITEBACK, mock_set_op[0]);
    ASSERT_EQ(VTOCBLK, mock_get_block[0]);
    ASSERT_EQ((uintptr_t)&VTOC_$UID, (uintptr_t)mock_get_uid[0]);
    ASSERT_EQ(0, mock_lock_depth);
}

/* nothing beyond the end: released with 9, no BAT_$FREE, count 0 */
static void test_unchanged_released_dirty(void)
{
    uint32_t freed = 55; status_$t st = 1;
    old_entry()->direct[0] = 100;

    VTOCE_$TRUNCATE(&req, 0, 1024, 0, &freed, &st);

    ASSERT_EQ(status_$ok, st);
    ASSERT_EQ(0, freed);
    ASSERT_EQ(0, mock_free_calls);
    ASSERT_EQ(1, mock_set_calls);
    ASSERT_EQ(BAT_BUF_DIRTY, mock_set_op[0]);
    ASSERT_EQ(100, old_entry()->direct[0]);
}

/* new format entry not in use: 0x80020002, VTOCE block never released */
static void test_new_format_not_in_use(void)
{
    uint32_t freed = 0; status_$t st = 0;
    make_new_entry();
    ((vtoce_$hdr_t *)new_entry())->status = 0;

    VTOCE_$TRUNCATE(&req, 0, 0, 0, &freed, &st);

    ASSERT_EQ(status_$VTOC_uid_mismatch, (uint32_t)st);
    ASSERT_EQ(1, mock_get_calls);
    ASSERT_EQ(0, mock_set_calls);
    ASSERT_EQ(0, mock_lock_depth);
}

/* new format delete: bucket slot found, in-use cleared, count 3 -> 2
 * relinks, cache entry dropped, slot emptied, direct blocks freed */
static void test_new_format_delete(void)
{
    uint32_t freed = 0; status_$t st = 1;
    vtoc_$bucket_entry_t *bkt = (vtoc_$bucket_entry_t *)(disk[3].b + 2 * VTOC_BUCKET_ENTRY_SIZE);
    vtoc_$vtoce_block_t *vb = (vtoc_$vtoce_block_t *)disk[VTOCBLK].b;

    make_new_entry();
    vb->entry_count = 3;
    new_entry()->direct[0] = 200; new_entry()->direct[31] = 231;
    mock_hash_block = 3; mock_hash_idx = 2;
    bkt->slots[5].uid = req.uid; bkt->slots[5].block_info = 0x17;

    VTOCE_$TRUNCATE(&req, 0, 0, (boolean)-1, &freed, &st);

    ASSERT_EQ(status_$ok, st);
    ASSERT_EQ(2, freed);
    ASSERT_EQ(0, (uint16_t)((vtoce_$hdr_t *)new_entry())->status);
    ASSERT_EQ(2, vb->entry_count);
    ASSERT_EQ(1, mock_part_calls);
    ASSERT_EQ(0x1234, vb->next_block);
    ASSERT_EQ(1, mock_cache_calls);
    ASSERT_EQ((char)0xFF, mock_cache_remove);
    ASSERT_EQ(0, bkt->slots[5].block_info);
    ASSERT_EQ(2, mock_set_calls);
    ASSERT_EQ(BAT_BUF_WRITEBACK, mock_set_op[0]);
    ASSERT_EQ((uintptr_t)disk[3].b, (uintptr_t)mock_set_buf[1]);
    ASSERT_EQ(BAT_BUF_DIRTY, mock_set_op[1]);
    ASSERT_EQ(200, mock_freed[0]);
    ASSERT_EQ(231, mock_freed[1]);
    ASSERT_EQ((uintptr_t)&VTOC_BKT_$UID, (uintptr_t)mock_get_uid[0]);
    ASSERT_EQ(0, mock_lock_depth);
}

/* delete with the UID in no bucket: chain walked, 0x20006 */
static void test_new_format_delete_not_found(void)
{
    uint32_t freed = 0; status_$t st = 0;
    vtoc_$bucket_entry_t *b0 = (vtoc_$bucket_entry_t *)disk[3].b;

    make_new_entry();
    mock_hash_block = 3; mock_hash_idx = 0;
    b0->next_bucket = 4; b0->next_bkt_idx = 1;

    VTOCE_$TRUNCATE(&req, 0, 0, (boolean)-1, &freed, &st);

    ASSERT_EQ(status_$VTOC_invalid_vtoce, st);
    ASSERT_EQ(2, mock_get_calls);
    ASSERT_EQ(4, mock_get_block[1]);
    ASSERT_EQ(2, mock_set_calls);
    ASSERT_EQ(BAT_BUF_CLEAN, mock_set_op[1]);
    ASSERT_EQ(0, mock_lock_depth);
}

/* level 1 partial: 0x22 blocks keeps indirect entries 0,1; 2,3 go */
static void test_level1_partial(void)
{
    uint32_t freed = 0; status_$t st = 1;
    vtoce_$old_fm_t *e = old_entry();
    e->indirect[0] = 5;
    disk[5].l[0] = 50; disk[5].l[1] = 51; disk[5].l[2] = 52; disk[5].l[3] = 0x80000035u;

    VTOCE_$TRUNCATE(&req, 0, 0x22 * 1024, 0, &freed, &st);

    ASSERT_EQ(status_$ok, st);
    ASSERT_EQ(5, e->indirect[0]);
    ASSERT_EQ(51, disk[5].l[1]);
    ASSERT_EQ(0, disk[5].l[2]);
    ASSERT_EQ(0, disk[5].l[3]);
    ASSERT_EQ(2, freed);
    ASSERT_EQ(52, mock_freed[0]);
    ASSERT_EQ(0x35, mock_freed[1]);
    /* GET_BLOCK(5, object uid, hint 0x20, type 1) */
    ASSERT_EQ(5, mock_get_block[1]);
    ASSERT_EQ((uintptr_t)&req.uid, (uintptr_t)mock_get_uid[1]);
    ASSERT_EQ(0x20, mock_get_hint[1]);
    ASSERT_EQ(1, mock_get_type[1]);
    /* VTOCE released 9, indirect written 3, released 8 */
    ASSERT_EQ(3, mock_set_calls);
    ASSERT_EQ(BAT_BUF_DIRTY, mock_set_op[0]);
    ASSERT_EQ(3, mock_set_op[1]);
    ASSERT_EQ(BAT_BUF_CLEAN, mock_set_op[2]);
}

/* truncate to 0 with a level-2 tree: root zeroed, child freed whole,
 * then the root block itself; each whole block is released with 0xC */
static void test_level2_whole(void)
{
    uint32_t freed = 0; status_$t st = 1;
    vtoce_$old_fm_t *e = old_entry();
    e->direct[0] = 100;
    e->indirect[1] = 6;
    disk[6].l[1] = 7;                       /* entry 1 -> child block 7 */
    disk[7].l[0] = 70; disk[7].l[255] = 0x800000FFu;

    VTOCE_$TRUNCATE(&req, 0, 0, 0, &freed, &st);

    ASSERT_EQ(status_$ok, st);
    ASSERT_EQ(0, e->indirect[1]);
    ASSERT_EQ(0, e->direct[0]);
    /* 1 direct + 2 data + child 7 + root 6 */
    ASSERT_EQ(5, freed);
    ASSERT_EQ(100, mock_freed[0]);
    ASSERT_EQ(70, mock_freed[1]);
    ASSERT_EQ(0xFF, mock_freed[2]);
    ASSERT_EQ(7, mock_freed[3]);
    ASSERT_EQ(6, mock_freed[4]);
    /* child: base 0x120 + 1*0x100, type 1 */
    ASSERT_EQ(7, mock_get_block[2]);
    ASSERT_EQ(0x220, mock_get_hint[2]);
    ASSERT_EQ(1, mock_get_type[2]);
    ASSERT_EQ(0x120, mock_get_hint[1]);
    ASSERT_EQ(2, mock_get_type[1]);
    /* entries of a whole block are not cleared */
    ASSERT_EQ(70, disk[7].l[0]);
    ASSERT_EQ(3, mock_set_calls);
    ASSERT_EQ(BAT_BUF_WRITEBACK, mock_set_op[0]);
    ASSERT_EQ(0xC, mock_set_op[1]);
    ASSERT_EQ(0xC, mock_set_op[2]);
    ASSERT_EQ(0, mock_lock_depth);
}

int main(void)
{
    printf("VTOCE_$TRUNCATE tests:\n");
    RUN_TEST(not_mounted);
    RUN_TEST(old_direct_truncate);
    RUN_TEST(unchanged_released_dirty);
    RUN_TEST(new_format_not_in_use);
    RUN_TEST(new_format_delete);
    RUN_TEST(new_format_delete_not_found);
    RUN_TEST(level1_partial);
    RUN_TEST(level2_whole);
    printf("\n%d passed, %d failed\n", tests_passed, tests_failed);
    return tests_failed != 0;
}
