/*
 * DMA_$CHECK - read and clear a DMAC channel's completion state
 *
 * Original address: 0x00E0A3A6
 * Size: 134 bytes of code (0x00E0A3A6 .. 0x00E0A44B), with the two status
 * cells it hands CRASH_SYSTEM at 0x00E0A44C / 0x00E0A450 (to 0x00E0A453).
 * Generated by: Claude Opus 5.5 (reviewed by Claude Fable 5.1)
 *
 * Frame (link.w A6,-0x10, nothing saved, no module base):
 *   (0x8,A6)  channel  word by value
 * A0 = SAU2_DMAC_BASE + (int16_t)(channel << 6) (`lsl.w #0x6,D1w' then a
 * word index, 0x00E0A3B4-0x00E0A3B8).  The result is a status_$t in D0.
 *
 *   0x00E0A3BC-0x00E0A3C6  csr = CSR byte, cer = CER byte, CSR = 0xFF
 *                          (writing ones clears the status bits)
 *   0x00E0A3CA  CSR bit 4 (ERR) set: switch on cer - 1 through the word
 *               table at 0x00E0A3E4 (16 entries, `cmpi.w #0x10' / bcc for
 *               the rest, so cer 0 lands in the default arm too):
 *                 cer 1-7, 13-15   CRASH_SYSTEM(&0x00080005)  (0x00E0A404)
 *                 cer 8, 12, other CRASH_SYSTEM(&0x00080019)  (0x00E0A41A)
 *                 cer 9-11         return 0x00080017           (0x00E0A40A)
 *                 cer 16           return 0x00080006           (0x00E0A412)
 *   0x00E0A426  else CSR bit 3 (ACT) set: CCR = 0x10 (SAB, software
 *               abort), CSR = 0xFF, return 0x0008001D
 *   0x00E0A438  else the MTC word (+0x0A) non-zero: return 0x0008001D
 *   0x00E0A446  else return 0
 *
 * Quirks reproduced:
 *   - After CRASH_SYSTEM the code branches to the exit with D0 as the
 *     crash routine left it (CRASH_SYSTEM does not return); the C returns
 *     the crash status there, which is not a value the image defines.
 *   - 0x00080006 is "floppy is not 2-sided" in the SR10.2 status database
 *     although it answers M68450 error code 16 here; the image's value is
 *     kept.  0x00080017 is "bus error occurred during disk DMA transfer",
 *     0x0008001D "dma not at end of range", 0x00080005 "disk equipment
 *     check", 0x00080019 "unknown status returned by hardware".
 *
 * Callers: WIN_$INT (0x00E19C6C) and FLP_$EXCS (0x00E3E30E), both with
 * channel 3.
 */

#include "dma/dma_internal.h"
#include "misc/misc.h"                  /* CRASH_SYSTEM */
#include "disk/disk.h"                  /* status_$disk_equipment_check, status_$bus_error_... */
#include "flp/flp.h"                    /* status_$floppy_is_not_2_sided, ..._unknown_status..., ..._dma_not_at_end_of_range */

/*
 * The DMAC base: arch/m68k/sau2/hw.h through arch/arch.h; a host test
 * defines SAU2_DMAC_BASE before including this file.
 */
#define DMA_CHECK_REGS      ((volatile uint8_t *)(uintptr_t)SAU2_DMAC_BASE)

#define M68450_CSR_ERR      0x10        /* btst.l #0x4,D0  0x00E0A3CA */
#define M68450_CSR_ACT      0x08        /* btst.l #0x3,D0  0x00E0A426 */

/* 0x00E0A44C / 0x00E0A450: the cells `pea (0x46,PC)' / `pea (0x34,PC)'. */
static const status_$t dma_check_equipment_check = status_$disk_equipment_check;          /* 00 08 00 05 */
static const status_$t dma_check_unknown_status  = status_$unknown_status_returned_by_hardware; /* 00 08 00 19 */

status_$t DMA_$CHECK(uint16_t channel)
{
    volatile uint8_t *regs;
    uint16_t csr;
    uint16_t cer;

    /* 0x00E0A3AA-0x00E0A3B8 */
    regs = DMA_CHECK_REGS + (int16_t)(uint16_t)(channel << 6);

    /* 0x00E0A3BC-0x00E0A3C6 */
    csr = regs[M68450_REG_CSR];
    cer = regs[M68450_REG_CER];
    regs[M68450_REG_CSR] = 0xFF;

    if ((csr & M68450_CSR_ERR) != 0) {
        /* 0x00E0A3D0-0x00E0A3E0: jump table on (uint16_t)(cer - 1) */
        switch ((uint16_t)(cer - 1)) {
        case 0: case 1: case 2: case 3: case 4: case 5: case 6:
        case 12: case 13: case 14:
            CRASH_SYSTEM(&dma_check_equipment_check);   /* 0x00E0A404 */
            return dma_check_equipment_check;
        case 8: case 9: case 10:
            return status_$bus_error_occurred_during_disk_dma_transfer;                         /* 0x00E0A40A */
        case 15:
            return status_$floppy_is_not_2_sided;                        /* 0x00E0A412 */
        default:        /* 7, 11 and everything >= 16 */
            CRASH_SYSTEM(&dma_check_unknown_status);    /* 0x00E0A41A */
            return dma_check_unknown_status;
        }
    }

    if ((csr & M68450_CSR_ACT) != 0) {
        regs[M68450_REG_CCR] = M68450_CCR_SAB;          /* 0x00E0A42C */
        regs[M68450_REG_CSR] = 0xFF;                    /* 0x00E0A432 */
        return status_$dma_not_at_end_of_range;          /* 0x00E0A43E */
    }

    /* 0x00E0A438: the memory transfer counter word at +0x0A */
    if (*(volatile uint16_t *)(regs + M68450_REG_MTCH) != 0) {
        return status_$dma_not_at_end_of_range;
    }
    return 0;                                           /* 0x00E0A446 */
}
