/*
 * name/name_data.c - NAME module data: the OLD_DIR data block, the UID_LIST
 * entry and the literal cells NAME owns
 *
 * Generated by: Claude Opus 5.5 (OLD_DIR block, source-vj9w)
 */

#include "name/name_internal.h"

/*
 * ============================================================================
 * NAME_$OLD_DIR_DATA - the OLD_DIR data block, 0x00E7FD24..0x00E801E4
 * ============================================================================
 *
 * SAU2 map: "D E7FD24 OLD_DIR size = 4C0"; layout, biases and asserts in
 * name/name.h.  MODULE_DATA_DEFINE_INIT gives the block its own section,
 * which build/sau2/layout.ld links between the DIR block (D E7DBF8) and
 * DIR_SERVER (D E801E4), where the map has it; 0x00E7FD24 is the ordering
 * key, not the link address.  The address repeats the MODULE_DATA_DECLARE
 * in name/name.h; the macro asserts the two agree.
 *
 * Image contents (`gsk read 0xE7FD24 0x4C0`): the two leaf sets, all other
 * bytes (the four lock tables) zero.
 */
MODULE_DATA_DEFINE_INIT(name_$old_dir_data_t, NAME_$OLD_DIR_DATA, 0x00E7FD24, {{{
    /* +0x000, 0x00E7FD24 */
    .leaf_char_set = {
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x7f, 0xff, 0xff, 0xff, 0xef, 0xff, 0xff, 0xff,
        0xff, 0xff, 0x7f, 0xfe, 0x00, 0x00, 0x00, 0x00
    },
    /* +0x020, 0x00E7FD44; bytes 28..31 (0x00E7FD60) are also lock_slot[0] */
    .leaf_first_char_set = {
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x3f, 0xff, 0xff, 0xfe, 0xff, 0xff, 0xff, 0xff,
        0xff, 0xff, 0x3f, 0xfe, 0x00, 0x00, 0x00, 0x00
    },
}}});

/*
 * ============================================================================
 * UID_LIST entry owned by NAME
 * ============================================================================
 *
 * NAME_$CANNED_REP_ROOT_UID lives in the shared read-only UID table the map
 * calls "I E1737C UID_LIST size = 210"; its slot is 0x00E173FC, between
 * DISKLESS_$UID (0x00E173F4) and DISPLAY3_$UID (0x00E17404), so the object is
 * 8 bytes.  Image bytes: 00 00 04 04 00 00 00 00.  (NAME_$CANNED_ROOT_UID,
 * the neighbouring 0x00E173E4 slot, is defined in name/init.c.)
 */
uid_t NAME_$CANNED_REP_ROOT_UID = UID_CONST(0x00000404, 0);

/*
 * ============================================================================
 * Literal cells in the NAME / OLD_DIR code regions
 * ============================================================================
 *
 * Domain Pascal passes VAR and const parameters by address, so each literal
 * argument becomes a cell in the code region whose address is pushed.  All
 * three below sit in "I E53EF8 OLD_DIR size = 4308" or "I E58488 NAME
 * size = 5B0"; the map exports no symbol for them, so the Ghidra labels are
 * kept.
 */

/* 0x00E5472E: the word 0, immediately after an `rts` at 0x00E5472C.
 * Image bytes: 00 00. */
int16_t NAME_$CONST_ZERO_W = 0;

/* 0x00E54730: the longword 0, immediately after NAME_$CONST_ZERO_W and
 * immediately before NAME_$UNLOCK_DIR (0x00E54734).  Image bytes:
 * 00 00 00 00. */
uint32_t NAME_$CONST_ZERO_L = 0;


/*
 * Naming_Internal_Err - 0x00E5855C, the status cell NAME_$MAP_DIR pea's to
 * CRASH_SYSTEM at 0x00E5852A.  Image bytes: 00 0E 00 25.
 */
status_$t Naming_Internal_Err = 0x000E0025;

