/*
 * name_$old_get_entry_nonroot - look a name up in an old-format directory,
 * wherever its hints say it lives
 *
 * Original address: 0x00E57CE0
 * Size: 656 bytes (0x00E57CE0 .. 0x00E57F6F), then the status cell
 * 0x00E57F70
 * Generated by: Claude Opus 5.5
 *
 * Module-local routine of the OLD_DIR segment (no map symbol).  Callers:
 * name_$old_get_root_entry (0x00E57F9A), DIR_$OLD_GET_ENTRYU (0x00E580B6)
 * and DIR_$OLD_VALIDATE_ROOT_ENTRY (0x00E580F0).
 *
 * Frame: (0x8,A6) dir_uid, (0xC,A6) name, (0x10,A6) name_len word,
 * (0x12,A6) entry_ret (A4), (0x16,A6) status_ret (A3).  Locals: A6-0x60
 * the directory UID, A6-0x58 the parsed name and A6-0x7A its length,
 * A6-0x38 the hint array (entry k, 1-based, at A6-0x40+8k), A6-0x10 the
 * found UID, A6-0x70 the handle, A6-0x6C the slot, A6-0x68 the unlock
 * status.  D3 = hint number.
 *
 * Blocks:
 *   0x00E57CF0-0x00E57D20  copy dir_uid; name_$validate_leaf(name, len,
 *                          parsed, &plen) false -> status_$naming_invalid_leaf
 *   0x00E57D24-0x00E57D38  n = HINT_$GET_HINTS(&uid, hints); none -> crash
 *   0x00E57D4E-0x00E57D56  each hint: its node is NODE_$ME -> local lookup
 *   0x00E57D5A-0x00E57DB4  REM_FILE_$NAME_GET_ENTRYU(&hints[k-1], &uid,
 *                          parsed, plen, entry_ret, status_ret);
 *                          status_$naming_directory_locked -> local lookup;
 *                          other errors: not found, not a directory, no
 *                          rights and insufficient rights end the call, the
 *                          rest try the next hint (0x00E57F54)
 *   0x00E57DB8-0x00E57E3C  remote success: a hint other than the first is
 *                          promoted (HINT_$ADDI(&uid, &hints[k-1])); a type
 *                          1 entry on another node (UID low 20 bits differ)
 *                          gets a hint too - in the root directory
 *                          {extra, node} when extra != 0, elsewhere
 *                          hints[k-1]
 *   0x00E57E40-0x00E57E5C  local: NAME_$LOCK_DIR(&uid, &handle, 1, 1,
 *                          status_ret); low word non-zero -> ACL_$EXIT_SUPER
 *   0x00E57E60-0x00E57F32  dir_$old_find_entry(handle, parsed, plen, &slot,
 *                          ...); found: entry_ret = {type, UID, extra in the
 *                          root directory else 0}; a type 1 entry on another
 *                          node: root -> HINT_$ADDI(&found, {extra, node})
 *                          when extra != 0, else HINT_$ADDU(&found, &uid)
 *   0x00E57F34             not found: status_$naming_name_not_found
 *   0x00E57F3A-0x00E57F4C  NAME_$UNLOCK_DIR(&unlock); ok status takes the
 *                          unlock status; ACL_$EXIT_SUPER
 *   0x00E57F5C-0x00E57F60  hints exhausted: CRASH_SYSTEM(&0x000E0007)
 *
 * Quirks reproduced:
 *   - Success is judged on the status's low word (`tst.w (0x2,A3)'), both
 *     after the remote call and after NAME_$LOCK_DIR.
 *   - The root-directory hint pair is built in hints[0]'s cells (A6-0x38),
 *     overwriting the first hint.
 *   - Running out of hints crashes the system rather than failing.
 */

#include "name/name_internal.h"
#include "dir/dir.h"
#include "hint/hint.h"
#include "node/node.h"
#include "rem_file/rem_file.h"

/* 0x00E57F70, the longword after the `rts': status_$naming_name_not_found,
 * CRASH_SYSTEM's argument at 0x00E57F5C.  Image bytes 00 0E 00 07. */
static const status_$t name_$old_nonroot_crash_status = 0x000E0007;

/* `move.l #0x10001,-(SP)' 0x00E57E42: NAME_$LOCK_DIR mode 1, rights 1 */
#define NONROOT_LOCK_MODE       1
#define NONROOT_LOCK_RIGHTS     1
/* `move.l #0xfffff,D1' 0x00E57DE0: the node bits of a UID's low half */
#define NONROOT_NODE_MASK       0x000FFFFFu
#define NONROOT_MAX_HINTS       5       /* A6-0x38 .. A6-0x11 */

void name_$old_get_entry_nonroot(uid_t *dir_uid, char *name, uint16_t name_len,
                                 dir_$old_entry_t *entry_ret,
                                 status_$t *status_ret)
{
    uid_t uid;                          /* A6-0x60 */
    uint8_t parsed[0x20];               /* A6-0x58 */
    uint16_t parsed_len;                /* A6-0x7A */
    hint_addr_t hints[NONROOT_MAX_HINTS];   /* A6-0x38 */
    uid_t found;                        /* A6-0x10 */
    uint32_t handle;                    /* A6-0x70 */
    int32_t slot_va;                    /* A6-0x6C */
    uint16_t slot_idx;                  /* A6-0x76 */
    uint16_t chain_level;               /* A6-0x78 */
    status_$t unlock_status;            /* A6-0x68 */
    dir_$old_slot_t *slot;              /* A0 */
    uint32_t node;                      /* D0 */
    int16_t n;                          /* D2 */
    int16_t k;                          /* D3 */
    status_$t st;

    /* 0x00E57CF0-0x00E57D20 */
    uid.high = dir_uid->high;
    uid.low = dir_uid->low;
    if (name_$validate_leaf(name, name_len, parsed, &parsed_len) >= 0) {
        *status_ret = status_$naming_invalid_leaf;
        return;
    }

    /* 0x00E57D24-0x00E57D38 */
    n = (int16_t)(HINT_$GET_HINTS(&uid, (uint32_t *)hints) - 1);
    if (n >= 0) {
        k = 1;
        do {
            /* 0x00E57D4E-0x00E57D56 */
            if (hints[k - 1].node_id == NODE_$ME) {
                goto local;
            }

            /* 0x00E57D5A-0x00E57DB4 */
            REM_FILE_$NAME_GET_ENTRYU(&hints[k - 1], &uid, (char *)parsed,
                                      parsed_len, entry_ret, status_ret);
            if (*status_ret == status_$naming_directory_locked) {
                goto local;
            }
            if ((*status_ret & 0xFFFF) == 0) {
                /* 0x00E57DB8-0x00E57DD2 */
                if (k != 1) {
                    HINT_$ADDI(&uid, (uint32_t *)&hints[k - 1]);
                }
                /* 0x00E57DD4-0x00E57DFA */
                found.high = entry_ret->uid.high;
                found.low = entry_ret->uid.low;
                node = found.low & NONROOT_NODE_MASK;
                if ((uid.low & NONROOT_NODE_MASK) == node ||
                    entry_ret->type != 1) {
                    return;
                }
                /* 0x00E57DFE-0x00E57E3C */
                if (uid.high == NAME_$ROOT_UID.high &&
                    uid.low == NAME_$ROOT_UID.low) {
                    if (entry_ret->extra == 0) {
                        return;
                    }
                    hints[0].flags = entry_ret->extra;
                    hints[0].node_id = node;
                    HINT_$ADDI(&found, (uint32_t *)&hints[0]);
                } else {
                    HINT_$ADDI(&found, (uint32_t *)&hints[k - 1]);
                }
                return;
            }
            st = *status_ret;
            if (st == status_$naming_name_not_found ||
                st == status_$naming_branch_is_not_a_directory ||
                st == status_$naming_no_rights ||
                st == status_$naming_insufficient_rights) {
                return;
            }
            /* 0x00E57F54-0x00E57F58 */
            k++;
        } while (n-- != 0);
    }

    /* 0x00E57F5C-0x00E57F60 */
    CRASH_SYSTEM(&name_$old_nonroot_crash_status);
    return;

local:
    /* 0x00E57E40-0x00E57E5C */
    NAME_$LOCK_DIR(&uid, &handle, NONROOT_LOCK_MODE, NONROOT_LOCK_RIGHTS,
                   status_ret);
    if ((*status_ret & 0xFFFF) != 0) {
        goto exit_super;
    }

    /* 0x00E57E60-0x00E57E88 */
    if (dir_$old_find_entry(handle, parsed, parsed_len, &slot_va, &slot_idx,
                            &chain_level) < 0) {
        /* 0x00E57E8C-0x00E57ECA */
        slot = (dir_$old_slot_t *)ARCH_VA_TO_PTR((uint32_t)slot_va);
        entry_ret->type = slot->type;
        entry_ret->uid.high = slot->uid.high;
        entry_ret->uid.low = slot->uid.low;
        found.high = slot->uid.high;
        found.low = slot->uid.low;
        if (uid.high == NAME_$ROOT_UID.high && uid.low == NAME_$ROOT_UID.low) {
            entry_ret->extra = slot->extra;
        } else {
            entry_ret->extra = 0;
        }

        /* 0x00E57ECC-0x00E57F32 */
        node = found.low & NONROOT_NODE_MASK;
        if (node != (uid.low & NONROOT_NODE_MASK) && slot->type == 1) {
            if (uid.high == NAME_$ROOT_UID.high &&
                uid.low == NAME_$ROOT_UID.low) {
                if (entry_ret->extra != 0) {
                    hints[0].flags = entry_ret->extra;
                    hints[0].node_id = node;
                    HINT_$ADDI(&found, (uint32_t *)&hints[0]);
                }
            } else {
                HINT_$ADDU(&found, &uid);
            }
        }
    } else {
        /* 0x00E57F34 */
        *status_ret = status_$naming_name_not_found;
    }

    /* 0x00E57F3A-0x00E57F48 */
    NAME_$UNLOCK_DIR(&unlock_status);
    if (*status_ret == status_$ok) {
        *status_ret = unlock_status;
    }

exit_super:
    /* 0x00E57F4C */
    ACL_$EXIT_SUPER();
}
