/*
 * smd_$cursor_op - draw or erase a cursor on the caller's display unit
 *
 * Original address: 0x00E6DFFA (module-local; the SAU2 map has no symbol
 * here; was Ghidra smd_$cursor_op)
 * Size: 134 bytes (0x00E6DFFA .. 0x00E6E07F)
 * Generated by: Claude Opus 5.5
 *
 * The body of SMD_$DISPLAY_CURSOR (clear_flag false, `clr.w -(SP)`
 * 0x00E6E090) and SMD_$CLEAR_CURSOR (`st -(SP)` 0x00E6E0BA); both load
 * A5 = 0xE82B8C (SMD_GLOBALS) and push the cursor number word, the 4-byte
 * position record by value (`move.l (A0),-(SP)`), the flag byte and the
 * status pointer.
 *
 * Frame (link.w A6,-0x10): (0x8,A6) cursor number (D2w), (0xa,A6) the
 * position, (0xe,A6) the flag byte, (0x10,A6) status (A3).  The first three
 * are passed on to SMD_$XOR_CURSOR by address (pea (0x8/0xa/0xe,A6)).
 *
 * Blocks:
 *   0x00E6E006-0x00E6E01E  unit = asid_to_unit[PROC1_$AS_ID]; 0 ->
 *                          status_$display_invalid_use_of_driver_procedure
 *   0x00E6E020-0x00E6E02C  cursor number > 3 (unsigned, bls) ->
 *                          status_$display_invalid_cursor_number
 *   0x00E6E02E-0x00E6E03E  A4 = 0xE2E3FC + unit * 0x10C (mulu.w, unsigned);
 *                          A2 = the unit record's hw pointer at (-0xf4,A4)
 *   0x00E6E042-0x00E6E04A  SMD_$ACQ_DISPLAY(&SMD_SYNC_LOCK_DATA) (pea
 *                          (-0x4c,PC) = 0x00E6DFF8, the word 1); result ignored
 *   0x00E6E04C-0x00E6E06C  SMD_$XOR_CURSOR(&cursor_num, &pos, &hw->min_x, hw,
 *                          &clear_flag, rec->display_base (0x14,A4 = +0x108),
 *                          rec->ctrl_regs (0x8,A4 = +0xFC)); result ignored
 *   0x00E6E070-0x00E6E074  SMD_$REL_DISPLAY(); status = ok
 */

#include "smd/smd_internal.h"

void smd_$cursor_op(int16_t cursor_num, smd_cursor_pos_t pos,
                    boolean clear_flag, status_$t *status_ret)
{
    uint16_t unit;                  /* D0w */
    smd_display_unit_t *rec;        /* A4 - 0xF4 */
    smd_display_hw_t *hw;           /* A2 */

    /* 0x00E6E006-0x00E6E016 */
    unit = SMD_GLOBALS.asid_to_unit[PROC1_$AS_ID];
    if (unit == 0) {
        /* 0x00E6E018 */
        *status_ret = status_$display_invalid_use_of_driver_procedure;
        return;
    }

    /* 0x00E6E020-0x00E6E024: cmpi.w #3 / bls, an unsigned compare */
    if ((uint16_t)cursor_num > 3) {
        /* 0x00E6E026 */
        *status_ret = status_$display_invalid_cursor_number;
        return;
    }

    /* 0x00E6E02E-0x00E6E03E: mulu.w; the only unit is 1 */
    rec = smd_$unit_rec((int16_t)unit);
    hw = rec->hw;

    /* 0x00E6E042-0x00E6E04A */
    SMD_$ACQ_DISPLAY(&SMD_SYNC_LOCK_DATA);

    /* 0x00E6E04C-0x00E6E06C */
    SMD_$XOR_CURSOR(&cursor_num, &pos, &hw->min_x, hw, &clear_flag,
                    rec->display_base, rec->ctrl_regs);

    /* 0x00E6E070-0x00E6E074 */
    SMD_$REL_DISPLAY();
    *status_ret = status_$ok;
}
