/*
 * smd_$reschedule_blink_timer - queue the cursor blink callback `interval`
 * ticks from now
 *
 * Original address: 0x00E72690 (module-local; the SAU2 map has no symbol
 * here; was Ghidra smd_$reschedule_blink_timer)
 * Size: 88 bytes (0x00E72690 .. 0x00E726E7), then a 4-byte constant
 * Generated by: Claude Opus 5.5
 *
 * Callers: SMD_$INIT_BLINK path (0x00E34EF0) and SMD_$BLINK_CURSOR_CALLBACK
 * (0x00E6FFA4), both pushing the interval longword by value.
 *
 * Frame (link.w A6,-0x18): (0x8,A6) interval; (-0x18) now, (-0x10) status,
 * (-0xc) when.  A5 = 0xE2E060 (SMD_$BLINK_TIMER_DATA, `lea` 0x00E72696).
 *
 * Blocks:
 *   0x00E7269C-0x00E726A4  when = { high = 0:interval>>16, low = interval }:
 *                          `clr.w (-0xc)` / `move.l D0,(-0xa)`, i.e. the
 *                          interval as a 48-bit clock
 *   0x00E726A8-0x00E726B2  TIME_$ABS_CLOCK(&now)
 *   0x00E726B4-0x00E726DA  TIME_$Q_ADD_CALLBACK(&TIME_$RTEQ, &when, 0 (relative),
 *                          &now, SMD_$BLINK_CURSOR_CALLBACK, 0, 4,
 *                          &interval cell (pea (0x2c,PC) = 0x00E726E8),
 *                          &SMD_$BLINK_TIMER_DATA.qelem, &status); the
 *                          status is dropped
 */

#include "smd/smd_internal.h"

/*
 * pea (0x2c,PC) at 0x00E726BA = 0x00E726E8, the 4-byte Pascal constant 0
 * that follows the routine's `rts`.  TIME_$Q_ADD_CALLBACK copies six bytes
 * from it (interval_high, interval_low), so it also reads the first word
 * of the next routine, `link.w A6` (0x4E56) at 0x00E726EC:
 *   gsk read 0xE726E8 8 -> 00 00 00 00 4e 56 ff a4
 * The six bytes are reproduced here.
 */
static const clock_t smd_$c_blink_interval = { 0x00000000, 0x4E56 };

void smd_$reschedule_blink_timer(uint32_t interval)
{
    clock_t now;            /* (-0x18,A6) */
    status_$t status;       /* (-0x10,A6) */
    clock_t when;           /* (-0xc,A6) */

    /* 0x00E7269C-0x00E726A4 */
    when.high = interval >> 16;
    when.low = (uint16_t)(interval & 0xFFFF);

    /* 0x00E726A8-0x00E726B2 */
    TIME_$ABS_CLOCK(&now);

    /* 0x00E726B4-0x00E726DA */
    TIME_$Q_ADD_CALLBACK(&TIME_$RTEQ, &when, 0, &now,
                         (void *)SMD_$BLINK_CURSOR_CALLBACK, NULL, 4,
                         (clock_t *)&smd_$c_blink_interval,
                         &SMD_$BLINK_TIMER_DATA.qelem, &status);
}
