/*
 * misc/chk.c - CHK
 *
 * Original address: 0x00E1A404
 * Size: 68 bytes (0x00E1A404 .. 0x00E1A447)
 * Generated by: Claude Opus 5.5
 *
 * The first routine of the IO_ code segment (map "I E1A404 IO_ size =
 * 5D0", symbol CHK with no `$', so module-local and filed under misc/ per
 * the tree's rule).  A Pascal function returning a Domain boolean: is a
 * controller of type *ctype configured with a zero controller status?
 *
 * Frame (link.w A6,-0x10; A5 saved, A5 = 0xE2C368 = the IO_ data segment):
 *   (0x8,A6)   ctype_p   pointer to the controller type word
 *   (-0x4,A6)  st        the last matching DCTE's cstatus, preset to
 *                        0x00100001 so that no match answers false
 *
 *   00e1a410  movea.l (0x8,A6),A0 / move.w (A0),D0w
 *   00e1a416  move.l #0x100001,(-0x4,A6)
 *   00e1a41e  move.l (0x54c,A5),D1 / beq.b 0x00e1a43a    IO_$DCTE_LIST
 *   00e1a424  movea.l D1,A0
 *   00e1a426  cmp.w (0x4,A0),D0w / bne.b 0x00e1a434     dcte->ctype
 *   00e1a42c  move.l (0x10,A0),(-0x4,A6) / beq.b 0x00e1a43e   cstatus == 0
 *   00e1a434  move.l (0x8,A0),D1 / bne.b 0x00e1a424     dcte->nextp
 *   00e1a43a  tst.l (-0x4,A6)
 *   00e1a43e  seq D0b
 *
 * The walk stops at the first matching DCTE whose cstatus is zero; a
 * matching DCTE with a non-zero status only overwrites `st' and the walk
 * goes on, so the answer is true exactly when some DCTE of the type has a
 * zero status.  0x00100001 has no entry in the SR10.2 status database; it
 * is only a non-zero preset and never leaves the routine.
 */

#include "misc/misc_internal.h"
#include "io/io.h"

int8_t CHK(const uint16_t *ctype)
{
    uint16_t want;
    status_$t st;               /* (-0x4,A6) */
    dcte_t *dcte;

    want = *ctype;                                      /* 0x00E1A414 */
    st = 0x00100001;                                    /* 0x00E1A416 */

    for (dcte = IO_$DCTE_LIST; dcte != NULL; dcte = dcte->nextp) {  /* 0x00E1A41E / 0x00E1A434 */
        if (want == dcte->ctype) {                      /* 0x00E1A426 */
            st = dcte->cstatus;                         /* 0x00E1A42C */
            if (st == 0) {
                break;                                  /* beq.b 0x00e1a43e */
            }
        }
    }

    return (st == 0) ? (int8_t)0xFF : 0;                /* 0x00E1A43A-0x00E1A43E seq */
}
