/*
 * misc/name_convert_acl_status.c - NAME_CONVERT_ACL_STATUS
 *
 * Original address: 0x00E5861C
 * Size: 58 bytes (0x00E5861C .. 0x00E58655)
 * Generated by: Claude Opus 5.5
 *
 * A module-local NAME routine (no `$' in its map name, so it lives in misc/
 * per CLAUDE.md; its prototype stays in name/name.h, which every caller
 * already includes).  Frame: (0x8,A6) status_ret.  Thirteen callers in DIR
 * and NAME.
 *
 * Rewrites three ACL statuses as naming statuses, in place:
 *   0x00E58624-0x00E5862C  0x230001 no right to perform operation
 *                          -> 0xE0013 no rights
 *   0x00E58634-0x00E5863C  0x230002 insufficient rights to perform operation
 *                          -> 0xE0014 insufficient rights
 *   0x00E58644-0x00E5864C  0x230004 wrong type - operation illegal on system
 *                          objects -> 0xE000E branch is not a directory
 * Any other status is left alone.
 */

#include "name/name.h"
#include "acl/acl.h"

void NAME_CONVERT_ACL_STATUS(status_$t *status_ret)
{
    if (*status_ret == status_$no_right_to_perform_operation) {
        *status_ret = status_$naming_no_rights;
    } else if (*status_ret == status_$insufficient_rights_to_perform_operation) {
        *status_ret = status_$naming_insufficient_rights;
    } else if (*status_ret == status_$acl_wrong_type) {
        *status_ret = status_$naming_branch_is_not_a_directory;
    }
}
