/*
 * win/reinit_drive.c - win_$reinit_drive
 *
 * Original address: 0x00E194B4 (was FUN_00e194b4; no map symbol)
 * Size: 194 bytes (0x00E194B4 .. 0x00E19575)
 * Generated by: Claude Opus 5.5
 *
 * A module-internal routine of the WIN driver: it runs on its caller's A5
 * (the WIN_ block, 0xE2B89C), is reached with `bsr' (SEEK 0x00E1968A,
 * WIN_$DO_IO 0x00E1985C and 0x00E19922) and returns its status in D0 with
 * no Pascal result slot.  Frame: (0x8,A6) unit, (0xA,A6) dev_unit.
 *
 * Blocks:
 *   0x00E194BC-0x00E194C4  save the current-request cell (+0x60) and clear
 *                          it for the duration
 *   0x00E194C8-0x00E194EA  status = DISK_INIT(unit, dev_unit, &WIN+0x68,
 *                          &w, &w, &geometry, &w) (the same frame word three
 *                          times); failure skips to the epilogue
 *   0x00E194EC-0x00E19526  mode register = 0x0A; wait value = the unit's
 *                          eventcount + 1; WIN_$ANSI_COMMAND(unit, REZERO
 *                          (4), &WIN_ANSI_IN_PARAM, &out)
 *   0x00E19528-0x00E1954C  EC_$WAIT(ecs = {&unit ec, TIME_$CLOCKH, nil},
 *                          vals = {that value, TIME_$CLOCKH + 0x28, 0});
 *                          which one fired is not looked at
 *   0x00E19550-0x00E19554  status = WIN_$CHECK_DISK_STATUS(unit)
 *   0x00E19558-0x00E19568  both paths: the longword at +0x64 counts one
 *                          more reinit; current cylinder and head (+0x74,
 *                          +0x72) become -1; the request cell is restored
 *
 * Quirks reproduced:
 *   - The ANSI command's own status is discarded (0x00E19524).
 */

#include "win/win_internal.h"

/* +0x64: the reinit counter (`addq.l #0x1,(0x64,A5)' 0x00E19558) */
#define WIN_REINIT_CNT_OFFSET   0x64
/* +0x68: DISK_INIT's total_blocks cell (`pea (0x68,A5)' 0x00E194D6) */
#define WIN_TOTAL_BLOCKS_OFFSET 0x68
/* `move.b #0xa,(0xc,A1)' 0x00E19502 */
#define WIN_MODE_COMMAND        0x0A
/* `move.w #0x4,-(SP)' 0x00E1951A: ANSI REZERO */
#define WIN_ANSI_REZERO         0x04
/* `moveq #0x28,D0' 0x00E1952A */
#define WIN_REZERO_TICKS        0x28

status_$t win_$reinit_drive(uint16_t unit, uint16_t dev_unit)
{
    uint32_t saved_req;                 /* D3 */
    uint16_t w;                         /* (-0x2A,A6) */
    uint16_t geometry[2];               /* (-0x18,A6) */
    char out;                           /* (-0x2C,A6) */
    volatile uint8_t *regs;             /* A1 */
    uint32_t wait_val;                  /* D5, (-0x20,A6) */
    status_$t status;                   /* D0 */

    /* 0x00E194BC-0x00E194C4 */
    saved_req = WIN_CUR_REQ_VA;
    WIN_CUR_REQ_VA = 0;

    /* 0x00E194C8-0x00E194EA */
    status = DISK_INIT(unit, dev_unit,
                       (int32_t *)(WIN_DATA_BASE + WIN_TOTAL_BLOCKS_OFFSET),
                       &w, &w, geometry, &w);
    if (status == status_$ok) {
        /* 0x00E194EC-0x00E19526 */
        regs = WIN_UNIT_REGS(unit);
        regs[WIN_REG_MODE] = WIN_MODE_COMMAND;
        wait_val = WIN_UNIT_EC(unit)->value + 1;
        WIN_$ANSI_COMMAND(unit, WIN_ANSI_REZERO, (char *)&WIN_ANSI_IN_PARAM,
                          &out);

        /* 0x00E19528-0x00E1954C */
        EC_$WAIT((ec_$wait_ecs_t){{ WIN_UNIT_EC(unit),
                                    (ec_$eventcount_t *)&TIME_$CLOCKH,
                                    NULL }},
                 (ec_$wait_vals_t){{ (int32_t)wait_val,
                                     (int32_t)(TIME_$CLOCKH + WIN_REZERO_TICKS),
                                     0 }});

        /* 0x00E19550-0x00E19554 */
        status = WIN_$CHECK_DISK_STATUS(unit);
    }

    /* 0x00E19558-0x00E19568 */
    *(uint32_t *)(WIN_DATA_BASE + WIN_REINIT_CNT_OFFSET) += 1;
    WIN_$DATA.image.cur_cyl = -1;
    WIN_$DATA.image.cur_head = -1;
    WIN_CUR_REQ_VA = saved_req;
    return status;
}
