/*
 * proc2/proc2_internal.h - Internal PROC2 Definitions
 *
 * Contains internal functions, data, and types used only within
 * the PROC2 subsystem. External consumers should use proc2/proc2.h.
 */

#ifndef PROC2_INTERNAL_H
#define PROC2_INTERNAL_H

#include "proc2/proc2.h"
#include "proc1/proc1.h"
#include "as/as.h"
#include "ec/ec.h"
#include "fim/fim.h"
#include "uid/uid.h"
#include "acl/acl.h"
#include "mst/mst.h"
#include "dtty/dtty.h"
#include "name/name.h"
#include "audit/audit.h"
#include "os/os.h"
#include "tape/tape.h"
#include "flop/flop.h"
#include "mmu/mmu.h"
#include "xpd/xpd.h"
#include "file/file.h"
#include "time/time.h"    /* TIME_$CLOCKH */
#include "pchist/pchist.h"
#include "msg/msg.h"
#include "misc/crash_system.h"

/*
 * ============================================================================
 * Internal Data Declarations
 * ============================================================================
 */

/*
 * Boot flags word, initialized by PROC2_$INIT and returned by
 * PROC2_$GET_BOOT_FLAGS.
 * Original address: 0xE7C068 (DAT_00e7c068, = 0xE7BE84 + 0x1E4)
 */
extern int16_t proc2_boot_flags;

/*
 * System process UID, generated by PROC2_$INIT and copied into the
 * PROC2_$UID table and into each new process entry.
 * Original address: 0xE7BE8C (DAT_00e7be8c)
 */
extern uid_t proc2_system_uid;

/*
 * UID of /node_data/proc_dir, resolved by PROC2_$INIT (UID_$NIL on failure).
 * Original address: 0xE7BE84 (DAT_00e7be84)
 */
extern uid_t proc2_proc_dir_uid;

/*
 * Per-process eventcount pairs (0x18 bytes per process, indexed by
 * process table index - 1).  The fork completion eventcount is at
 * offset 0x00 and the creation record eventcount at offset 0x0C.
 *
 * Original address: 0xE2B978 (Ghidra label PROC2_$EC).
 *
 * NOTE: an earlier note here claimed this was the same storage as
 * ec/ec.h's EC1_ARRAY_BASE.  It is not: that pool is EC2_$WAIT_ECS at
 * 0xE20F6C (`D E20F6C EC2_ASM size = 300` in the SAU2 map), which
 * EC2_$INIT_S initialises at 0x00E30978.
 */
typedef struct proc2_ec_entry_t {
    ec_$eventcount_t fork_ec;    /* 0x00: Fork completion EC */
    ec_$eventcount_t cr_rec_ec;  /* 0x0C: Creation record EC */
} proc2_ec_entry_t;

/* Remaining documented offsets (bead source-pewa).  Guarded: ec_$eventcount_t
 * holds two native pointers, so the pair is 0x18 bytes only on the target. */
#if defined(ARCH_M68K)
_Static_assert(__builtin_offsetof(proc2_ec_entry_t, fork_ec) == 0x00, "proc2_ec_entry_t.fork_ec");
_Static_assert(__builtin_offsetof(proc2_ec_entry_t, cr_rec_ec) == 0x0C, "proc2_ec_entry_t.cr_rec_ec");
_Static_assert(sizeof(proc2_ec_entry_t) == 0x18, "proc2_ec_entry_t must be 0x18 bytes");
#endif

/*
 * One pair per process table slot, indices 1..P2_INFO_TABLE_SIZE.  The pair
 * for index 1 is at 0xE2B978 (0x00E305A4 `movea.l #0xe2b978,A3` with
 * 0x00E305B2 `pea (-0x18,A3,D2w*0x1)`, D2 = idx*0x18), and the next labelled
 * object is UID_$GENERATOR_STATE at 0xE2C008 -- (0xE2C008 - 0xE2B978) / 0x18
 * is exactly 70, so the array holds one pair for every slot the info table
 * has (bead source-nm9e).
 */
#define PROC2_EC_ENTRIES P2_INFO_TABLE_SIZE
extern proc2_ec_entry_t PROC2_$EC[PROC2_EC_ENTRIES];

/* Fork / creation record ECs for a 1-based process table index */
#define PROC_FORK_EC(idx)    (&PROC2_$EC[(idx) - 1].fork_ec)
#define PROC_CR_REC_EC(idx)  (&PROC2_$EC[(idx) - 1].cr_rec_ec)

/* AS_$STACK_FILE_LOW, AS_$INIT_STACK_FILE_SIZE, AS_$CR_REC,
 * AS_$CR_REC_FILE_SIZE, AS_$STACK_HIGH - as/as.h (fields of AS_$INFO)
 * FIM_$INITIAL_STACK_SIZE - fim/fim.h */

extern status_$t PROC2_Internal_Error;

/*
 * ============================================================================
 * Internal PROC2 Functions
 * ============================================================================
 */

/*
 * Rolling UPID allocator used by PROC2_$INIT_ENTRY_INTERNAL.  The word is
 * initialised data in the image (0x0041 at 0xE7C06A), read at 0x00E73330
 * and bumped at 0x00E7333C / 0x00E73344.
 *
 * Original address: 0xE7C06A (= 0xE7BE84 + 0x1E6)
 */
extern uint16_t PROC2_$NEXT_UPID;

/* Wrap bounds of the UPID allocator (0x00E73334 / 0x00E7333C). */
#define P2_UPID_WRAP_AT    30000
#define P2_UPID_WRAP_TO    0x41

/* Process entry initialization */
void PROC2_$INIT_ENTRY_INTERNAL(proc2_info_t *entry);

/* Cleanup handlers */
void PROC2_$CLEANUP_HANDLERS_INTERNAL(proc2_info_t *entry);

/*
 * Signal delivery.  A Pascal procedure: every caller pushes 2+2+4+4 bytes
 * and no result slot (e.g. PROC2_$AWAKEN_GUARDIAN 0x00E3E99E..0x00E3E9B0).
 */
void PROC2_$DELIVER_SIGNAL_INTERNAL(int16_t proc_index, int16_t signal,
                                    int32_t param, status_$t *status_ret);

/* Build process info structure */
void PROC2_$BUILD_INFO_INTERNAL(int16_t proc2_index, int16_t proc1_pid,
                                 void *info, status_$t *status_ret);

/* Signal event logging */
void PROC2_$LOG_SIGNAL_EVENT(uint16_t event_type, int16_t target_idx,
                              uint16_t signal, uint32_t param, int32_t success);

/* Debug setup and teardown */
void DEBUG_UNLINK_FROM_LIST(int16_t proc_idx);
void DEBUG_SETUP_INTERNAL(int16_t target_idx, int16_t debugger_idx, int8_t flag);
void DEBUG_CLEAR_INTERNAL(int16_t proc_idx, int8_t flag);

/*
 * ============================================================================
 * Process Group Internal Functions
 * ============================================================================
 */

/* Find pgroup by UPGID - returns index (1-69) or 0 if not found */
int16_t PGROUP_FIND_BY_UPGID(uint16_t upgid);

/* Process group cleanup - mode: 0=leader only, 1=refcount only, 2=both */
void PGROUP_CLEANUP_INTERNAL(proc2_info_t *entry, int16_t mode);

/* Set process's process group */
void PGROUP_SET_INTERNAL(proc2_info_t *entry, uint16_t new_upgid, status_$t *status_ret);

/*
 * PROC2_$PGROUP_INHERIT_INTERNAL - Copy one entry's process group to another
 *
 * Bumps the source group's reference count (if any) and copies the pgroup
 * table index across.  Only caller: PROC2_$INIT_ENTRY_INTERNAL (0x00E733EC).
 * Original address: 0x00e4216e
 */
void PROC2_$PGROUP_INHERIT_INTERNAL(proc2_info_t *from, proc2_info_t *to);

/* Decrement pgroup leader count - signals orphaned group if count reaches 0 */
void PGROUP_DECR_LEADER_COUNT(int16_t pgroup_idx);

/* Signal process group internal implementation */
void PROC2_$SIGNAL_PGROUP_INTERNAL(int16_t pgroup_idx, int16_t signal,
                                    uint32_t param, int8_t check_perms,
                                    status_$t *status_ret);

/*
 * ============================================================================
 * PROC2_$WAIT result record (0x68 bytes)
 * ============================================================================
 *
 * Built at A6-0x68 by PROC2_$WAIT (0x00E3FDD0) through its two helpers and
 * copied to the caller with `moveq #0x19` / dbf = 26 longwords (0x00E3FF30).
 * Offsets are the (d,A2)/(d,A3) displacements the helpers use:
 *   0x00  14 longwords copied from the child entry +0x60..+0x97 (REAP 0x00E3FC22)
 *   0x38  child +0x08 parent_uid (REAP 0x00E3FC16), or UID_$NIL (TRY_ZOMBIE 0x00E3FD64)
 *   0x40  child +0x00 uid (TRY_ZOMBIE stop arm 0x00E3FDB2)
 *   0x48  exit status: the longword at child +0x98 (REAP/TRY_ZOMBIE) or
 *         (stop signal << 8) | 0x7F (the two stop arms)
 *   0x4C  the longword at child +0x9C (REAP/TRY_ZOMBIE zombie arm) or the
 *         fault param at child +0xC2 with bit 23 cleared (TRY_ZOMBIE stop arm)
 *   0x50  five longwords from child +0xA4 (REAP 0x00E3FC04)
 *   0x64  boolean: fault param bit 23 was set (TRY_ZOMBIE 0x00E3FDAE); cleared
 *         by PROC2_$WAIT at 0x00E3FDF6 on the CALLER's record
 *   0x65  boolean: bit 15 of the word at child +0xA0 (REAP 0x00E3FC36, smi)
 *   0x66  boolean: bit 14 of that word (REAP 0x00E3FC44, sne)
 */
typedef struct proc2_wait_result_t {
    uint8_t     entry_60[0x38];     /* 0x00 */
    uid_t       parent_uid;         /* 0x38 */
    uid_t       child_uid;          /* 0x40 */
    uint32_t    exit_status;        /* 0x48 */
    uint32_t    exit_info;          /* 0x4C */
    uint8_t     usage[20];          /* 0x50: five big-endian longwords */
    int8_t      flag_64;            /* 0x64 */
    int8_t      flag_65;            /* 0x65 */
    int8_t      flag_66;            /* 0x66 */
    uint8_t     pad_67;             /* 0x67 */
} proc2_wait_result_t;

_Static_assert(__builtin_offsetof(proc2_wait_result_t, parent_uid) == 0x38, "proc2_wait_result_t.parent_uid");
_Static_assert(__builtin_offsetof(proc2_wait_result_t, child_uid) == 0x40, "proc2_wait_result_t.child_uid");
_Static_assert(__builtin_offsetof(proc2_wait_result_t, exit_status) == 0x48, "proc2_wait_result_t.exit_status");
_Static_assert(__builtin_offsetof(proc2_wait_result_t, exit_info) == 0x4C, "proc2_wait_result_t.exit_info");
_Static_assert(__builtin_offsetof(proc2_wait_result_t, usage) == 0x50, "proc2_wait_result_t.usage");
_Static_assert(__builtin_offsetof(proc2_wait_result_t, flag_64) == 0x64, "proc2_wait_result_t.flag_64");
_Static_assert(sizeof(proc2_wait_result_t) == 0x68, "proc2_wait_result_t is 0x68 bytes");

/*
 * The longwords a zombie leaves at entry +0x98 and +0x9C (over asid_alt /
 * level1_pid and cleanup_flags / name[0..1]), read as the big-endian
 * memory they are.
 */
#define PROC2_ZOMBIE_EXIT_98(entry) \
    (((uint32_t)(entry)->asid_alt << 16) | (uint32_t)(entry)->level1_pid)
#define PROC2_ZOMBIE_EXIT_9C(entry) \
    (((uint32_t)(entry)->cleanup_flags << 16) | \
     ((uint32_t)(uint8_t)(entry)->name[0] << 8) | (uint32_t)(uint8_t)(entry)->name[1])

/*
 * ============================================================================
 * Wait Subsystem Internal Functions
 * ============================================================================
 */

/*
 * PROC2_$WAIT_REAP_CHILD - Reap child and collect exit status
 *
 * Called when a child process has exited. Collects exit status,
 * resource usage, cleans up process group, and frees the process entry.
 * Original address: 0x00e3fb34
 */
void PROC2_$WAIT_REAP_CHILD(int16_t child_idx, int16_t parent_idx,
                            int16_t prev_sibling, proc2_wait_result_t *result,
                            int16_t *pid_ret);

/*
 * PROC2_$WAIT_TRY_LIVE_CHILD - Try to collect status from live child
 *
 * Checks if a live child has stopped or exited and can be waited on.
 * Original address: 0x00e3fc5c
 */
void PROC2_$WAIT_TRY_LIVE_CHILD(int16_t child_idx, uint16_t options,
                                 int16_t parent_idx, int16_t prev_idx,
                                 int8_t *found, proc2_wait_result_t *result,
                                 int16_t *pid_ret);

/*
 * PROC2_$WAIT_TRY_ZOMBIE - Try to collect status from zombie child
 *
 * Checks if a zombie can be reaped and collects its status.
 * Original address: 0x00e3fd06
 */
void PROC2_$WAIT_TRY_ZOMBIE(int16_t zombie_idx, uint16_t options,
                             int8_t *found, proc2_wait_result_t *result,
                             int16_t *pid_ret);

/*
 * ============================================================================
 * Process Hierarchy Internal Functions
 * ============================================================================
 */

/*
 * PROC2_$DETACH_FROM_PARENT - Detach process from parent's child list
 *
 * Unlinks a process from its parent's child list. For zombies,
 * also cleans up pgroup and adds to free list.
 * Original address: 0x00e40df4
 */
void PROC2_$DETACH_FROM_PARENT(int16_t child_idx, int16_t prev_sibling_idx);

/*
 * ============================================================================
 * Signal Subsystem Internal Functions
 * ============================================================================
 */

/*
 * PROC2_$GET_NEXT_PENDING_SIGNAL - Get next pending signal
 *
 * Scans the pending signal mask to find the next unblocked signal.
 * Original address: 0x00e3ef38
 */
int16_t PROC2_$GET_NEXT_PENDING_SIGNAL(proc2_info_t *info);  /* proc2/deliver_pending_internal.c */


/*
 * ============================================================================
 * Creation record (moved here from proc2/set_valid.c; also used by
 * proc2/complete_vfork.c, which fills 0x94/0xA8/0xB0/0xB4 at
 * 0x00E737E4..0x00E73822)
 * ============================================================================
 */

/*
 * Creation record structure (partial - offsets determined from the
 * disassembly).  It is reached through proc2_info_t.cr_rec_2 (entry+0x6C)
 * and holds process creation and accounting information.
 */
typedef struct cr_rec_t {
    uint32_t    fields_0x00[0x1d];  /* 0x00-0x73: cleared by the two dbf loops */
    uint32_t    field_74;           /* 0x74: CPU time related */
    uint16_t    field_78;           /* 0x78: CPU time related */
    uint16_t    pad_7a;             /* 0x7A: alignment hole */
    uint32_t    field_7c;           /* 0x7C: Timing */
    uint32_t    field_80;           /* 0x80: Timing */
    uint32_t    field_84;           /* 0x84: Timing */
    uint8_t     field_88;           /* 0x88: Flag byte */
    uint8_t     field_89;           /* 0x89: Flag byte */
    uint8_t     field_8a[4];        /* 0x8A: CPU usage.  Declared as bytes so
                                     * that the 0x8A offset survives on a
                                     * host where uint32_t wants 4-byte
                                     * alignment; m68k needs only 2. */
    uint8_t     field_8e[2];        /* 0x8E: CPU usage */
    uint8_t     field_90;           /* 0x90: TRUE when entry->debugger_idx != 0 */
    uint8_t     pad_91[3];          /* 0x91: Padding */
    status_$t   status;             /* 0x94: Status */
    uid_t       proc_uid;           /* 0x98: Process UID */
    uid_t       parent_uid;         /* 0xA0: Parent UID */
    uid_t       stack_uid;          /* 0xA8: Stack file UID */
    uint32_t    addr_lo;            /* 0xB0: Stack file low address */
    uint32_t    size;               /* 0xB4: Stack file size */
    int32_t     field_b8;           /* 0xB8: entry->upid, sign-extended */
    uid_t       debugger_uid;       /* 0xBC: PROC2_$UID[entry->parent_pgroup_idx] */
    uint8_t     pad_c4;             /* 0xC4: Padding */
    uint8_t     flags_c5;           /* 0xC5: Flags byte (bit 3 gates 0xBC) */
    uint16_t    count_c6;           /* 0xC6: Counter (set to 1) */
    uint8_t     field_c8;           /* 0xC8: Field */
} cr_rec_t;

_Static_assert(__builtin_offsetof(cr_rec_t, field_74) == 0x74, "cr_rec_t.field_74");   /* 0x00E73578 */
_Static_assert(__builtin_offsetof(cr_rec_t, field_78) == 0x78, "cr_rec_t.field_78");   /* 0x00E7357C */
_Static_assert(__builtin_offsetof(cr_rec_t, field_7c) == 0x7C, "cr_rec_t.field_7c");   /* 0x00E73580 */
_Static_assert(__builtin_offsetof(cr_rec_t, field_80) == 0x80, "cr_rec_t.field_80");   /* 0x00E73584 */
_Static_assert(__builtin_offsetof(cr_rec_t, field_84) == 0x84, "cr_rec_t.field_84");   /* 0x00E73586 */
_Static_assert(__builtin_offsetof(cr_rec_t, field_8a) == 0x8A, "cr_rec_t.field_8a");
_Static_assert(__builtin_offsetof(cr_rec_t, field_90) == 0x90, "cr_rec_t.field_90");   /* 0x00E7358A */
_Static_assert(__builtin_offsetof(cr_rec_t, status) == 0x94, "cr_rec_t.status");       /* 0x00E734CC */
_Static_assert(__builtin_offsetof(cr_rec_t, proc_uid) == 0x98, "cr_rec_t.proc_uid");   /* 0x00E7354E */
_Static_assert(__builtin_offsetof(cr_rec_t, parent_uid) == 0xA0, "cr_rec_t.parent_uid"); /* 0x00E73564 */
_Static_assert(__builtin_offsetof(cr_rec_t, stack_uid) == 0xA8, "cr_rec_t.stack_uid"); /* 0x00E734FE */
_Static_assert(__builtin_offsetof(cr_rec_t, addr_lo) == 0xB0, "cr_rec_t.addr_lo");     /* 0x00E734BC */
_Static_assert(__builtin_offsetof(cr_rec_t, size) == 0xB4, "cr_rec_t.size");           /* 0x00E734C4 */
_Static_assert(__builtin_offsetof(cr_rec_t, field_b8) == 0xB8, "cr_rec_t.field_b8");   /* 0x00E7355C */
_Static_assert(__builtin_offsetof(cr_rec_t, debugger_uid) == 0xBC, "cr_rec_t.debugger_uid"); /* 0x00E735AA */
_Static_assert(__builtin_offsetof(cr_rec_t, flags_c5) == 0xC5, "cr_rec_t.flags_c5");   /* 0x00E73598 */
_Static_assert(__builtin_offsetof(cr_rec_t, count_c6) == 0xC6, "cr_rec_t.count_c6");   /* 0x00E73592 */
_Static_assert(__builtin_offsetof(cr_rec_t, field_c8) == 0xC8, "cr_rec_t.field_c8");   /* 0x00E7358E */


/*
 * ============================================================================
 * Startup context (shared by PROC2_$FORK 0x00E72D2C and PROC2_$CREATE
 * 0x00E7286A..0x00E7288C; moved here from proc2/fork.c)
 * ============================================================================
 */

/*
 * Startup context planted below the new process's stack.
 *
 * Built at 0x00E72D2C-0x00E72D42:
 *   ctx+0x00 = ctx + 4          (self pointer)
 *   ctx+0x04 = *arg2
 *   ctx+0x08 = *arg1
 *   ctx+0x0C = new_entry->asid  (a WORD -- the record is 14 bytes)
 *
 * The record is placed 0x10 (not sizeof) bytes below
 * stack_ptr - FIM_$INITIAL_STACK_SIZE (0x00E72D1C-0x00E72D2A).
 */
typedef struct startup_context_t {
    void       *self_ptr;       /* 0x00 */
    int32_t     user_data;      /* 0x04 */
    int32_t     entry_point;    /* 0x08 */
    uint16_t    asid;           /* 0x0C */
} startup_context_t;

#if defined(ARCH_M68K)
_Static_assert(__builtin_offsetof(startup_context_t, self_ptr) == 0x00,
               "startup_context_t.self_ptr must be at 0x00");
_Static_assert(__builtin_offsetof(startup_context_t, user_data) == 0x04,
               "startup_context_t.user_data must be at 0x04");
_Static_assert(__builtin_offsetof(startup_context_t, entry_point) == 0x08,
               "startup_context_t.entry_point must be at 0x08");
_Static_assert(__builtin_offsetof(startup_context_t, asid) == 0x0C,
               "startup_context_t.asid must be at 0x0C");
_Static_assert(sizeof(startup_context_t) == 14,
               "startup_context_t must be 14 bytes");
#endif

/*
 * The original reserves 0x10 bytes for the record even though it is only
 * 14 bytes long (0x00E72D1C: moveq #0x10,D1).
 */
#define STARTUP_CONTEXT_RESERVE 0x10

/*
 * PROC1_$SET_PRIORITY's second parameter is a Pascal boolean.  The
 * original pushes it with `st -(SP)` (0x00E7309E), which -- because byte
 * operations on A7 adjust the stack by two and address the even byte --
 * puts 0xFF in the HIGH half of the word slot; PROC1_$SET_PRIORITY reads
 * it back with `move.b (0xa,A6),D3b` at 0x00E15248 and branches on
 * `tst.b`/`bpl`.  Modelled as an int16_t, that value is 0xFF00, which is
 * what makes proc1/set_priority.c's `mode < 0` test fire.  The other call
 * sites push `clr.w -(SP)` == 0.
 */
/* proc1/proc1.h now types the parameter as the int8_t the callee reads
 * (`move.b (0xa,A6),D3b`), so the values are the byte itself. */
#define PROC1_SET_PRIORITY_SET  ((int8_t)0xFF)
#define PROC1_SET_PRIORITY_GET  ((int8_t)0)

#endif /* PROC2_INTERNAL_H */

/*
 * The byte-count longword (value 1) at 0x00E41A20 that both
 * DEBUG_SETUP_INTERNAL (`pea (0x36,PC)` at 0x00E419E8) and
 * DEBUG_CLEAR_INTERNAL (`pea (-0x62,PC)` at 0x00E41A80) hand to XPD_$WRITE.
 * Defined in proc2/debug_setup_internal.c.
 */
extern const int32_t PROC2_$DEBUG_XPD_WRITE_LEN;

/*
 * The longword 0x00004000 at 0x00E735F4 that PROC2_$SET_VALID
 * (`pea (0x11a,PC)` at 0x00E734D8) and PROC2_$COMPLETE_VFORK
 * (`pea (-0x20e,PC)` at 0x00E73800) hand to MST_$MAP_AREA_AT as its
 * third argument.  Defined in proc2/set_valid.c.
 */
extern const uint32_t proc2_$map_area_size_00e735f4;
