/*
 * proc2/proc2_internal.h - Internal PROC2 Definitions
 *
 * Contains internal functions, data, and types used only within
 * the PROC2 subsystem. External consumers should use proc2/proc2.h.
 */

#ifndef PROC2_INTERNAL_H
#define PROC2_INTERNAL_H

#include "proc2/proc2.h"
#include "proc1/proc1.h"
#include "as/as.h"
#include "ec/ec.h"
#include "fim/fim.h"
#include "uid/uid.h"
#include "acl/acl.h"
#include "mst/mst.h"
#include "dtty/dtty.h"
#include "name/name.h"
#include "audit/audit.h"
#include "os/os.h"
#include "tape/tape.h"
#include "flop/flop.h"
#include "mmu/mmu.h"
#include "xpd/xpd.h"
#include "file/file_internal.h"
#include "pchist/pchist.h"
#include "msg/msg.h"
#include "misc/crash_system.h"

/*
 * ============================================================================
 * Internal Data Declarations
 * ============================================================================
 */

/*
 * Boot flags word, initialized by PROC2_$INIT and returned by
 * PROC2_$GET_BOOT_FLAGS.
 * Original address: 0xE7C068 (DAT_00e7c068, = 0xE7BE84 + 0x1E4)
 */
extern int16_t proc2_boot_flags;

/*
 * System process UID, generated by PROC2_$INIT and copied into the
 * PROC2_UID table and into each new process entry.
 * Original address: 0xE7BE8C (DAT_00e7be8c)
 */
extern uid_t proc2_system_uid;

/*
 * UID of /node_data/proc_dir, resolved by PROC2_$INIT (UID_$NIL on failure).
 * Original address: 0xE7BE84 (DAT_00e7be84)
 */
extern uid_t proc2_proc_dir_uid;

/*
 * Per-process eventcount pairs (0x18 bytes per process, indexed by
 * process table index - 1).  The fork completion eventcount is at
 * offset 0x00 and the creation record eventcount at offset 0x0C.
 *
 * Original address: 0xE2B978 (Ghidra label PROC2_$EC; the same storage is
 * EC1_ARRAY_BASE in ec/ec.h)
 */
typedef struct proc2_ec_entry_t {
    ec_$eventcount_t fork_ec;    /* 0x00: Fork completion EC */
    ec_$eventcount_t cr_rec_ec;  /* 0x0C: Creation record EC */
} proc2_ec_entry_t;

/* Remaining documented offsets (bead source-pewa).  Guarded: ec_$eventcount_t
 * holds two native pointers, so the pair is 0x18 bytes only on the target. */
#if defined(ARCH_M68K)
_Static_assert(__builtin_offsetof(proc2_ec_entry_t, fork_ec) == 0x00, "proc2_ec_entry_t.fork_ec");
_Static_assert(__builtin_offsetof(proc2_ec_entry_t, cr_rec_ec) == 0x0C, "proc2_ec_entry_t.cr_rec_ec");
_Static_assert(sizeof(proc2_ec_entry_t) == 0x18, "proc2_ec_entry_t must be 0x18 bytes");
#endif

/*
 * One pair per process table slot, indices 1..P2_INFO_TABLE_SIZE.  The pair
 * for index 1 is at 0xE2B978 (0x00E305A4 `movea.l #0xe2b978,A3` with
 * 0x00E305B2 `pea (-0x18,A3,D2w*0x1)`, D2 = idx*0x18), and the next labelled
 * object is UID_$GENERATOR_STATE at 0xE2C008 -- (0xE2C008 - 0xE2B978) / 0x18
 * is exactly 70, so the array holds one pair for every slot the info table
 * has (bead source-nm9e).
 */
#define PROC2_EC_ENTRIES P2_INFO_TABLE_SIZE
extern proc2_ec_entry_t PROC2_$EC[PROC2_EC_ENTRIES];

/* Fork / creation record ECs for a 1-based process table index */
#define PROC_FORK_EC(idx)    (&PROC2_$EC[(idx) - 1].fork_ec)
#define PROC_CR_REC_EC(idx)  (&PROC2_$EC[(idx) - 1].cr_rec_ec)

/* AS_$STACK_FILE_LOW, AS_$INIT_STACK_FILE_SIZE, AS_$CR_REC,
 * AS_$CR_REC_FILE_SIZE, AS_$STACK_HIGH - as/as.h (fields of AS_$INFO)
 * FIM_$INITIAL_STACK_SIZE - fim/fim.h */

extern status_$t PROC2_Internal_Error;

/*
 * ============================================================================
 * Internal PROC2 Functions
 * ============================================================================
 */

/*
 * Rolling UPID allocator used by PROC2_$INIT_ENTRY_INTERNAL.  The word is
 * initialised data in the image (0x0041 at 0xE7C06A), read at 0x00E73330
 * and bumped at 0x00E7333C / 0x00E73344.
 *
 * Original address: 0xE7C06A (= 0xE7BE84 + 0x1E6)
 */
extern uint16_t PROC2_$NEXT_UPID;

/* Wrap bounds of the UPID allocator (0x00E73334 / 0x00E7333C). */
#define P2_UPID_WRAP_AT    30000
#define P2_UPID_WRAP_TO    0x41

/* Process entry initialization */
void PROC2_$INIT_ENTRY_INTERNAL(proc2_info_t *entry);

/* Cleanup handlers */
void PROC2_$CLEANUP_HANDLERS_INTERNAL(proc2_info_t *entry);

/* Signal delivery */
uint32_t PROC2_$DELIVER_SIGNAL_INTERNAL(int16_t proc_index, int16_t signal,
                                         int32_t param, status_$t *status_ret);

/* Build process info structure */
void PROC2_$BUILD_INFO_INTERNAL(int16_t proc2_index, int16_t proc1_pid,
                                 void *info, status_$t *status_ret);

/* Signal event logging */
void PROC2_$LOG_SIGNAL_EVENT(uint16_t event_type, int16_t target_idx,
                              uint16_t signal, uint32_t param, int32_t success);

/* Debug setup and teardown */
void DEBUG_UNLINK_FROM_LIST(int16_t proc_idx);
void DEBUG_SETUP_INTERNAL(int16_t target_idx, int16_t debugger_idx, int8_t flag);
void DEBUG_CLEAR_INTERNAL(int16_t proc_idx, int8_t flag);

/*
 * ============================================================================
 * Process Group Internal Functions
 * ============================================================================
 */

/* Find pgroup by UPGID - returns index (1-69) or 0 if not found */
int16_t PGROUP_FIND_BY_UPGID(uint16_t upgid);

/* Process group cleanup - mode: 0=leader only, 1=refcount only, 2=both */
void PGROUP_CLEANUP_INTERNAL(proc2_info_t *entry, int16_t mode);

/* Set process's process group */
void PGROUP_SET_INTERNAL(proc2_info_t *entry, uint16_t new_upgid, status_$t *status_ret);

/*
 * PROC2_$PGROUP_INHERIT_INTERNAL - Copy one entry's process group to another
 *
 * Bumps the source group's reference count (if any) and copies the pgroup
 * table index across.  Only caller: PROC2_$INIT_ENTRY_INTERNAL (0x00E733EC).
 * Original address: 0x00e4216e
 */
void PROC2_$PGROUP_INHERIT_INTERNAL(proc2_info_t *from, proc2_info_t *to);

/* Decrement pgroup leader count - signals orphaned group if count reaches 0 */
void PGROUP_DECR_LEADER_COUNT(int16_t pgroup_idx);

/* Signal process group internal implementation */
void PROC2_$SIGNAL_PGROUP_INTERNAL(int16_t pgroup_idx, int16_t signal,
                                    uint32_t param, int8_t check_perms,
                                    status_$t *status_ret);

/*
 * ============================================================================
 * Wait Subsystem Internal Functions
 * ============================================================================
 */

/*
 * PROC2_$WAIT_REAP_CHILD - Reap child and collect exit status
 *
 * Called when a child process has exited. Collects exit status,
 * resource usage, cleans up process group, and frees the process entry.
 * Original address: 0x00e3fb34
 */
void PROC2_$WAIT_REAP_CHILD(int16_t child_idx, int16_t parent_idx,
                            int16_t prev_sibling, uint32_t *result,
                            int16_t *pid_ret);

/*
 * PROC2_$WAIT_TRY_LIVE_CHILD - Try to collect status from live child
 *
 * Checks if a live child has stopped or exited and can be waited on.
 * Original address: 0x00e3fc5c
 */
void PROC2_$WAIT_TRY_LIVE_CHILD(int16_t child_idx, uint16_t options,
                                 int16_t parent_idx, int16_t prev_idx,
                                 int8_t *found, uint32_t *result,
                                 int16_t *pid_ret);

/*
 * PROC2_$WAIT_TRY_ZOMBIE - Try to collect status from zombie child
 *
 * Checks if a zombie can be reaped and collects its status.
 * Original address: 0x00e3fd06
 */
void PROC2_$WAIT_TRY_ZOMBIE(int16_t zombie_idx, uint16_t options,
                             int8_t *found, uint32_t *result,
                             int16_t *pid_ret);

/*
 * ============================================================================
 * Process Hierarchy Internal Functions
 * ============================================================================
 */

/*
 * PROC2_$DETACH_FROM_PARENT - Detach process from parent's child list
 *
 * Unlinks a process from its parent's child list. For zombies,
 * also cleans up pgroup and adds to free list.
 * Original address: 0x00e40df4
 */
void PROC2_$DETACH_FROM_PARENT(int16_t child_idx, int16_t prev_sibling_idx);

/*
 * ============================================================================
 * Signal Subsystem Internal Functions
 * ============================================================================
 */

/*
 * PROC2_$GET_NEXT_PENDING_SIGNAL - Get next pending signal
 *
 * Scans the pending signal mask to find the next unblocked signal.
 * Original address: 0x00e3ef38
 */
int16_t PROC2_$GET_NEXT_PENDING_SIGNAL(proc2_info_t *info);


#endif /* PROC2_INTERNAL_H */
