#!/usr/bin/env python3
#
# tools/check_guards.py - forbid architecture guards around data
#
# Generated by: Claude Opus 5.5
#
# docs/design-per-process-data.md (source-0i3), section 3: a module's data
# is one object, defined once, the same on every build; the target and the
# host differ in where the linker puts it, never in what it is.  The last
# step of that design (source-702z) makes the rule mechanical: outside
# arch/, a preprocessor conditional on the architecture (`#if
# defined(ARCH_M68K)', `#ifdef ARCH_M68K', `#if ARCH_M68K', `#ifndef', `#if
# !defined(...)', `#elif', and the ARCH_HOST spellings of the same test) may
# not contain, in ANY of its branches:
#
#   object       a declaration or definition of an object (file scope, or a
#                `static' object inside a function), including one made by
#                a MODULE_DATA_* or other macro invocation at file scope;
#   extern       any `extern' declaration, of an object or a function;
#   absaddr      a `#define' whose body casts an integer literal to a
#                pointer - an absolute-address macro (`(*(T *)0xE85684)');
#   record       a struct or union definition (typedef'd or not).
#
# What it allows, and --report counts, are:
#
#   assert       `_Static_assert's, which a pointer-bearing record may only
#                be able to state on the 32-bit target (class a);
#   function     a function definition: the host fallback body of a routine
#                that is hand-written assembly on the target, or a
#                target-only body (class b);
#   section      a `#define' that expands to a section attribute, placing
#                a function in its `.text.<symbol>' input section (class c);
#   hwcode       statements inside a function body (register access, inline
#                assembly, a hardware-only path); these must use the SAU's
#                hardware header (arch/m68k/sau2/hw.h) for their addresses,
#                which `absaddr' enforces for the macros (class d);
#   other        prototypes, non-address #defines, #includes, #error,
#                scalar typedefs (class f).
#
# The classification is textual (comments and strings are blanked first,
# continued lines joined); it is a gate, not a C parser, and the table in
# tools/arch_m68k_guards.md is the human-checked version of its report.
#
# Usage:
#   check_guards.py [--root DIR] [--report] [FILE...]
# With no FILE, scans every *.h and *.c under DIR (default: the directory
# above this script) except arch/, build/, dist/ and tools/.  Exits 1 and
# lists each forbidden item (file:line class: text) when any is found.

import argparse
import os
import re
import sys

ARCH_TOKEN = re.compile(r'\b(ARCH_M68K|ARCH_HOST)\b')
EXCLUDED_DIRS = {'arch', 'build', 'dist', 'tools'}

FORBIDDEN = ('object', 'extern', 'absaddr', 'record')

# Guards whose conversion is a tracked follow-up, keyed by (file, a name the
# guard defines): the whole guard is exempt while an entry names it, the
# report counts it as `exempt', and an entry that matches no forbidden guard
# is itself an error (the conversion landed; delete the entry).  Every entry
# cites the bead that removes it.  Keep this list short: it is the
# remainder of source-0i3, not a place for new guards.
EXEMPT = [
    # MMU_ASM cells the hand-written mmu/sau2 code owns, MMU_$PTTX, and the
    # MMU register page (moves to arch/m68k/sau2/hw.h with them)
    ('mmu/mmu.h', 'PTT_BASE', 'source-o56c'),
    ('mmu/mmu_data.c', 'mmu_ptt_base', 'source-o56c'),
]

# A cast of an integer literal to a pointer type:
#   (T *)0x..., (volatile T *)(0x...), (*(T *)0x...), (T *)(uintptr_t)0x...
ABS_CAST = re.compile(
    r'\(\s*(?:const\s+|volatile\s+)*[A-Za-z_$][\w$]*(?:\s+[A-Za-z_$][\w$]*)*'
    r'\s*(?:const\s+|volatile\s+)*\*+\s*(?:const\s*|volatile\s*)*\)\s*'
    r'(?:\(\s*(?:uintptr_t|uint32_t|unsigned\s+long|long)\s*\)\s*)?'
    r'\(?\s*(?:0[xX][0-9A-Fa-f]+|[1-9][0-9]*)[uUlL]*\b')

# The same cast in front of any operand; the operand is then expanded
# through the tree's object-like macros (MACROS, filled by collect_macros)
# and counts as an address when a literal >= ADDR_MIN is left in it - so
# `(T *)(uintptr_t)DIR_A5_BASE_VA' and `(T *)(CAL_$RTC_BASE + (off))' are
# caught as well as `(T *)0xE85684'.
PTR_CAST = re.compile(
    r'\(\s*(?:const\s+|volatile\s+)*[A-Za-z_$][\w$]*(?:\s+[A-Za-z_$][\w$]*)*'
    r'\s*(?:const\s+|volatile\s+)*\*+\s*(?:const\s*|volatile\s*)*\)\s*'
    r'(?:\(\s*(?:uintptr_t|uint32_t|unsigned\s+long|long)\s*\)\s*)?')
ADDR_MIN = 0x100
MACROS = {}


def collect_macros(paths):
    """Object-like #defines of the tree, name -> body (first one wins)."""
    for path in paths:
        try:
            with open(path, encoding='latin-1') as f:
                text = strip_comments(f.read())
        except OSError:
            continue
        for _, line in logical_lines(text):
            m = re.match(r'\s*#\s*define\s+([A-Za-z_$][\w$]*)(?!\()\s+(.*)$',
                         line)
            if m:
                MACROS.setdefault(m.group(1), m.group(2).strip())


def expand(text, depth=0):
    if depth > 8:
        return text
    def sub(m):
        name = m.group(0)
        if name in MACROS:
            return '(' + expand(MACROS[name], depth + 1) + ')'
        return name
    return re.sub(r'[A-Za-z_$][\w$]*', sub, text)


def cast_operand(text, start):
    """The operand following a cast that ends at `start'."""
    t = text[start:].lstrip()
    if t.startswith('('):
        depth = 0
        for i, ch in enumerate(t):
            if ch == '(':
                depth += 1
            elif ch == ')':
                depth -= 1
                if depth == 0:
                    return t[:i + 1]
        return t
    m = re.match(r'[A-Za-z_$][\w$]*|0[xX][0-9A-Fa-f]+|\d+', t)
    return m.group(0) if m else ''


def is_abs_address_cast(text):
    if ABS_CAST.search(text):
        return True
    for m in PTR_CAST.finditer(text):
        operand = expand(cast_operand(text, m.end()))
        for lit in re.findall(r'\b(0[xX][0-9A-Fa-f]+|\d+)[uUlL]*\b', operand):
            if int(lit, 0) >= ADDR_MIN:
                return True
    return False


ATTRIBUTE = re.compile(r'__attribute__\s*\(\(')
KEYWORDS = {'return', 'if', 'else', 'while', 'for', 'do', 'switch', 'case',
            'goto', 'break', 'continue', 'default', 'sizeof'}


def strip_comments(text):
    """Blank comments and string/char literals, keeping line structure."""
    out = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if text.startswith('/*', i):
            j = text.find('*/', i + 2)
            j = n if j < 0 else j + 2
            out.append(''.join('\n' if ch == '\n' else ' '
                               for ch in text[i:j]))
            i = j
        elif text.startswith('//', i):
            j = text.find('\n', i)
            j = n if j < 0 else j
            out.append(' ' * (j - i))
            i = j
        elif c in '"\'':
            j = i + 1
            while j < n and text[j] != c and text[j] != '\n':
                j += 2 if text[j] == '\\' else 1
            j = min(j + 1, n)
            out.append(c + ' ' * max(0, j - i - 2) + (c if j - i >= 2 else ''))
            i = j
        else:
            out.append(c)
            i += 1
    return ''.join(out)


def logical_lines(text):
    """(first physical line number, text) with backslash continuations
    joined."""
    lines = text.split('\n')
    result = []
    i = 0
    while i < len(lines):
        start = i
        line = lines[i]
        while line.endswith('\\') and i + 1 < len(lines):
            i += 1
            line = line[:-1] + ' ' + lines[i]
        result.append((start + 1, line))
        i += 1
    return result


def strip_attributes(s):
    """Remove __attribute__((...)) groups."""
    while True:
        m = ATTRIBUTE.search(s)
        if not m:
            return s
        depth = 0
        j = m.end() - 2
        while j < len(s):
            if s[j] == '(':
                depth += 1
            elif s[j] == ')':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        s = s[:m.start()] + ' ' + s[j + 1:]


class Block:
    """One architecture conditional group (#if .. #endif)."""

    def __init__(self, path, line, cond, depth):
        self.path = path
        self.line = line
        self.cond = cond
        self.depth = depth          # brace depth at the #if
        self.items = []             # (line, class, text)


def classify_file_scope_item(text):
    t = ' '.join(text.split())
    if not t or t == ';':
        return None
    if re.match(r'(_Static_assert|static_assert)\b', t):
        return 'assert'
    if re.search(r'\bextern\b', t):
        return 'extern'
    body = strip_attributes(t)
    if re.match(r'typedef\b', body):
        if re.search(r'\b(struct|union)\b[^;{]*\{', body):
            return 'record'
        return 'other'
    if re.match(r'(struct|union)\s+[\w$]+\s*\{', body):
        return 'record'
    if re.match(r'enum\b[^;]*\{', body) and body.rstrip().endswith('};'):
        return 'other'
    if body.endswith('}'):
        head = body[:body.find('{')]
        if '(' in head and '=' not in head:
            return 'function'
    # A macro invocation with no type in front: MODULE_DATA_DEFINE(...);
    if re.match(r'[A-Z_$][A-Z0-9_$]*\s*\(', body):
        return 'object'
    # Prototype: `type name(params);' - no initialiser and the name is not
    # parenthesised as a pointer declarator.
    if body.endswith(';') and '=' not in body:
        m = re.search(r'([A-Za-z_$][\w$]*)\s*\(', body)
        if m and '(*' not in body.replace(' ', '') and \
                m.group(1) not in KEYWORDS:
            return 'other'
    return 'object'


def classify_directive(t):
    m = re.match(r'#\s*(\w+)\s*(.*)', t)
    if not m:
        return 'other'
    kind, rest = m.group(1), m.group(2)
    if kind == 'define':
        dm = re.match(r'([A-Za-z_$][\w$]*)(\([^)]*\))?\s*(.*)', rest)
        value = dm.group(3) if dm else ''
        if is_abs_address_cast(value):
            return 'absaddr'
        if re.search(r'section\s*\(', value):
            return 'section'
        return 'other'
    return 'other'


def scan(path, report):
    with open(path, encoding='latin-1') as f:
        text = strip_comments(f.read())
    depth = 0
    stack = []      # open conditionals, innermost last
    blocks = []

    def innermost_arch():
        for e in reversed(stack):
            if e['blk'] is not None:
                return e['blk']
        return None

    # Depth is tracked along the TARGET's path (ARCH_M68K defined, ARCH_HOST
    # not) so that a guard whose branches each open a function body does not
    # unbalance it; a non-arch conditional takes its first branch unless it
    # is `#if 0'.  Each branch starts from the depth at its `#if', and after
    # `#endif' the depth is the one the taken branch left.
    cur_item = []   # (line, text) pieces of the current file-scope item

    def arch_taken(kind, cond):
        m68k = 'ARCH_M68K' in cond
        if kind == 'ifdef':
            return m68k
        if kind == 'ifndef':
            return not m68k
        neg = '!' in cond
        return m68k != neg

    for lineno, line in logical_lines(text):
        s = line.strip()
        if s.startswith('#'):
            m = re.match(r'#\s*(if|ifdef|ifndef|elif|else|endif)\b(.*)', s)
            if m:
                kind, cond = m.group(1), m.group(2).strip()
                if kind in ('if', 'ifdef', 'ifndef'):
                    is_arch = bool(ARCH_TOKEN.search(cond))
                    blk = None
                    if is_arch:
                        taken = arch_taken(kind, cond)
                        blk = Block(path, lineno, s, depth)
                        blocks.append(blk)
                    else:
                        taken = not re.match(r'0\s*$', cond)
                    stack.append({'blk': blk, 'at_if': depth,
                                  'taken': taken, 'any': taken,
                                  'after': None})
                    cur_item = []
                elif kind in ('elif', 'else') and stack:
                    e = stack[-1]
                    if e['taken']:
                        e['after'] = depth
                    depth = e['at_if']
                    if kind == 'else':
                        e['taken'] = not e['any']
                    else:
                        if ARCH_TOKEN.search(cond):
                            if e['blk'] is None:
                                e['blk'] = Block(path, lineno, s, e['at_if'])
                                blocks.append(e['blk'])
                            t = arch_taken('if', cond)
                        else:
                            t = True
                        e['taken'] = t and not e['any']
                    e['any'] = e['any'] or e['taken']
                    cur_item = []
                elif kind == 'endif' and stack:
                    e = stack.pop()
                    if not e['taken']:
                        depth = e['after'] if e['after'] is not None \
                            else e['at_if']
                    cur_item = []
                continue
            blk = innermost_arch()
            if blk is not None:
                blk.items.append((lineno, classify_directive(s), s))
            continue
        blk = innermost_arch()
        # track braces and items
        if blk is not None:
            if depth > blk.depth or (depth == blk.depth and blk.depth > 0):
                # inside a function body: flag static objects and externs
                if re.search(r'\bextern\b', s):
                    blk.items.append((lineno, 'extern', s))
                elif re.match(r'static\b', s) and '(' not in s.split('=')[0]:
                    blk.items.append((lineno, 'object', s))
                elif s:
                    blk.items.append((lineno, 'hwcode', s))
        for ch in line:
            if ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
        if blk is not None and blk.depth == 0:
            cur_item.append((lineno, line))
            joined = ' '.join(t for _, t in cur_item).strip()
            if depth == 0 and (joined.endswith(';') or joined.endswith('}')):
                # drop the hwcode entries recorded for a function body
                first = cur_item[0][0]
                blk.items = [it for it in blk.items
                             if not (it[1] == 'hwcode' and it[0] >= first)]
                cls = classify_file_scope_item(joined)
                if cls:
                    blk.items.append((first, cls, joined))
                cur_item = []
            elif not joined:
                cur_item = []
        else:
            cur_item = []
    return blocks


def item_name(cls, text):
    """The identifier a forbidden item defines or declares."""
    t = ' '.join(text.split())
    if cls == 'absaddr' or t.startswith('#'):
        m = re.match(r'#\s*define\s+([A-Za-z_$][\w$]*)', t)
        return m.group(1) if m else None
    t = strip_attributes(t).split('=')[0]
    t = re.sub(r'\[[^\]]*\]', '', t)
    names = re.findall(r'[A-Za-z_$][\w$]*', t)
    return names[-1] if names else None


def block_class(blk):
    classes = {c for _, c, _ in blk.items}
    for c in FORBIDDEN:
        if c in classes:
            return c
    for c in ('function', 'hwcode', 'assert', 'section', 'other'):
        if c in classes:
            return c
    return 'empty'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), '..'))
    ap.add_argument('--report', action='store_true',
                    help='list every guard with its class')
    ap.add_argument('files', nargs='*')
    args = ap.parse_args()

    files = args.files
    if not files:
        files = []
        for dirpath, dirnames, filenames in os.walk(args.root):
            rel = os.path.relpath(dirpath, args.root)
            if rel.split(os.sep)[0] in EXCLUDED_DIRS:
                dirnames[:] = []
                continue
            dirnames.sort()
            for fn in sorted(filenames):
                if fn.endswith(('.c', '.h')):
                    files.append(os.path.join(dirpath, fn))

    arch_headers = []
    for dirpath, dirnames, filenames in os.walk(os.path.join(args.root,
                                                             'arch')):
        arch_headers += [os.path.join(dirpath, f) for f in filenames
                         if f.endswith('.h')]
    collect_macros(files + arch_headers)

    bad = []
    counts = {}
    nblocks = 0
    used = set()
    for path in files:
        rel = os.path.relpath(path, args.root)
        for blk in scan(path, args.report):
            nblocks += 1
            cls = block_class(blk)
            forbidden = [(line, c, t) for line, c, t in blk.items
                         if c in FORBIDDEN]
            names = {item_name(c, t) for _, c, t in forbidden}
            exempt = [e for e in EXEMPT if e[0] == rel and e[1] in names]
            if forbidden and exempt:
                used.update(exempt)
                cls = 'exempt'
            counts[cls] = counts.get(cls, 0) + 1
            if args.report:
                print('%s:%d\t%s\t%s%s' % (rel, blk.line, cls, blk.cond,
                      ('\t' + exempt[0][2]) if cls == 'exempt' else ''))
            if cls == 'exempt':
                continue
            for line, c, t in forbidden:
                bad.append('%s:%d: %s: %s' % (rel, line, c, t[:100]))
    if not args.files:
        for e in EXEMPT:
            if e not in used:
                bad.append('%s: stale exemption for %s (%s): no forbidden '
                           'guard defines it any more' % e)

    summary = ', '.join('%s %d' % (k, counts[k]) for k in sorted(counts))
    print('check_guards: %d architecture guards in %d files (%s)' %
          (nblocks, len(files), summary or 'none'))
    if bad:
        print('check_guards: %d forbidden item(s) under an architecture '
              'guard (docs/design-per-process-data.md section 3):' % len(bad))
        for b in bad:
            print('  ' + b)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
