#!/usr/bin/env python3
#
# tools/gen_layout_ld.py - lay the kernel's code and module data blocks out
# in the order of the SAU2 link map (docs/design-per-process-data.md,
# sections 3 and 5)
#
# Generated by: Claude Opus 5.5
#
# Decision of 2026-09-28 (the owner): absolute addresses do not have to
# match the image; the RELATIVE PLACEMENT does.  Code and data are linked in
# the order the SAU2 link map (sau2-maps/domain_os.10.2.map, the map of the
# exact image in Ghidra) gives them, so a data block that follows its
# module's code in the image follows it in our link too, and modules come in
# the image's sequence.  Nothing is placed at a fixed address.
#
# The build compiles with -ffunction-sections, so every C function is its
# own input section `.text.<symbol>'; the hand-written assembly gives each
# routine a `.section ".text.<symbol>"' where that leaves its bytes intact;
# every MODULE_DATA_DEFINE site (arch/m68k/arch.h) is an input section
# `.moddata.<name>' whose declared original address is now the ORDERING
# KEY (and documentation), not a placement.
#
# This script reads the map into an address-ordered stream, finds every
# code section of the link inputs and the map position of the symbols it
# defines, merges in the module data blocks at their declared addresses,
# and writes build/sau2/layout.ld: the ordered list of input-section
# statements that sau2.ld INCLUDEs inside its one `.text' output section,
# followed by the catch-all for code the map does not name.
#
# Placement rules:
#   - A code section defining one or more map symbols is keyed by the
#     earliest of them (map address, then map line).
#   - A module data block is keyed by its declared address, ahead of any
#     map symbol at the same address.
#   - A few sections hold image data under C names the map does not use;
#     ANCHORS below keys them by their image address.
#   - A section whose map symbols straddle another placed section's key
#     (or a block's) would put the two out of order whatever we do; that
#     is an error naming the section, which must be split, one section per
#     routine (source-c573: fim/sau2/fim.s was the last such file; the rule
#     that placed it with its largest run and `held' the rest out of the
#     order check is gone with it).
#   - Sections of an object that define no map symbol (file-static helper
#     functions) follow the object's first placed section, so a module's
#     private code stays with it; objects with no placed section at all go
#     to the catch-all.
#
# Modes:
#
#   gen_layout_ld.py --map MAP -o build/sau2/layout.ld OBJ...
#       Scan, check and write the fragment (only if its text changed).
#
#   gen_layout_ld.py --map MAP --check-only OBJ...
#       The same checks, no output.
#
#   gen_layout_ld.py --map MAP --check-elf ELF OBJ...
#       After a scratch link: every placed map symbol, every ANCHORS section
#       (by its first symbol) and every block must appear in the ELF in map
#       order; the first inversion fails the check.
#       Prints how many map symbols were placed and what fell into the
#       catch-all.
#
# Checks that fail the build: a MODULE_DATA address that is not a literal
# or is odd; the same block name defined twice; a block whose section is in
# no link input; an ANCHORS section that no longer exists.  A block address
# inside no map segment is a warning naming the nearest segment.

import argparse
import bisect
import os
import re
import subprocess
import sys

RFC_LOAD_ADDR = 0x00E00000
KERNEL_VA_END = 0x01000000  # 24-bit physical/virtual space of the SAU2

# Sections holding image data whose C names are not the map's.  Keyed by the
# image address of their first byte.
ANCHORS = {
    # svc/svc_tables.c: the nine SVC dispatch tables, which in the image
    # follow the eight trap dispatchers inside SVC_CATCHER (0xE7B044, size
    # 0xE40), 0xE7B2DE..0xE7BE82, reached with `lea (TABLE:w,%pc)' - R_68K_PC16
    # (source-a5t8).  The map names only the dispatchers.
    '.text.svc_tables': 0xE7B2DE,
    # smd/smd_data.c: SMD_DISPLAY_INFO is the map's SMD_$DISPLAY_COM
    # (0xE27376, inside SMD_WIRED), reached from SMD_$DISP1_INT with
    # `lea (0x446,PC),A1' at 0xE26F2E (source-uwxz).
    '.text.smd_display_info': 0xE27376,
    # fp/sau2/fp_context.s: fp_$switch_owner .. fp_$save_state
    # (0xE21B10..0xE21B7F), which the map counts into FIM_$FLINE (it names
    # no symbol between FIM_$FLINE 0xE21ACC and FIM_$FP_ABORT 0xE21B80);
    # FIM_$FLINE reaches it with `bsr.s' (source-c573).
    '.text.fp_$switch_owner': 0xE21B10,
    # time/sau2/timer_handler.s: TIME_$TIMER_HANDLER (0xE2B130..0xE2B27F),
    # the end of the TIME_ASM segment; the map names no symbol after
    # TIME_$DI_RTE (0xE2B11E), and TIME_$SET_VECTOR reaches the handler with
    # `lea (0x2c,PC)' (source-lu78).
    '.text.TIME_$TIMER_HANDLER': 0xE2B130,
}

SITE_RE = re.compile(
    r'\bMODULE_DATA_DEFINE(?:_INIT)?\s*\(\s*'
    r'(?P<type>[^,()]+?)\s*,\s*'
    r'(?P<name>[A-Za-z_][A-Za-z0-9_$]*)\s*,\s*'
    r'(?P<addr>[^,()]+?)\s*[,)]')

LITERAL_RE = re.compile(r'^(0[xX][0-9A-Fa-f]+|[0-9]+)[uUlL]*$')

SEGMENT_RE = re.compile(
    r'^[DI][ 0-9]{0,3}\s+(?P<addr>[0-9A-F]+)\s+(?P<name>\S+)\s+.*'
    r'size = (?P<size>[0-9A-F]+)')

SYMTAB_RE = re.compile(
    r'^(?P<value>[0-9a-f]{8}) (?P<flags>.{7}) (?P<sec>\S+)\s+'
    r'(?P<size>[0-9a-f]{8}) (?P<name>.+)$')


def fail(msgs):
    for m in msgs:
        print('gen_layout_ld: error: ' + m, file=sys.stderr)
    sys.exit(1)


def warn(msg):
    print('gen_layout_ld: warning: ' + msg, file=sys.stderr)


# ---------------------------------------------------------------------------
# The link map
# ---------------------------------------------------------------------------

class LinkMap:
    def __init__(self, path):
        self.symbols = {}   # name -> (addr, line): first occurrence
        self.segments = []  # (addr, size, name)
        with open(path, encoding='latin-1') as f:
            for line_no, line in enumerate(f):
                if line_no == 0:
                    continue  # build banner
                if line.startswith(' '):
                    fields = line.split()
                    if (len(fields) >= 2
                            and re.fullmatch(r'[0-9A-F]+', fields[0])):
                        self.symbols.setdefault(
                            fields[1], (int(fields[0], 16), line_no))
                    continue
                m = SEGMENT_RE.match(line)
                if m and int(m.group('size'), 16):
                    self.segments.append((int(m.group('addr'), 16),
                                          int(m.group('size'), 16),
                                          m.group('name')))

    def key(self, name):
        """Ordering key of a map symbol: (address, 1 + map line)."""
        addr, line = self.symbols[name]
        return (addr, 1 + line)

    def segment_of(self, addr):
        """The innermost map segment holding addr (the map nests object
        segments inside the numbered load regions)."""
        inside = [(size, name) for start, size, name in self.segments
                  if start <= addr < start + size]
        return min(inside)[1] if inside else None

    def nearest_segment(self, addr):
        def dist(seg):
            start, size, _ = seg
            return 0 if start <= addr < start + size else \
                min(abs(addr - start), abs(addr - (start + size - 1)))
        start, size, name = min(self.segments, key=dist)
        return '%s (0x%06X, size 0x%X)' % (name, start, size)


def addr_key(addr):
    """Ordering key of a declared address: ahead of every map symbol there."""
    return (addr, 0)


# ---------------------------------------------------------------------------
# Module data blocks, from the MODULE_DATA_DEFINE sites
# ---------------------------------------------------------------------------

class Block:
    def __init__(self, name, ctype, addr, src, line):
        self.name = name
        self.ctype = ctype
        self.addr = addr
        self.src = src
        self.line = line

    @property
    def section(self):
        return '.moddata.' + self.name

    @property
    def where(self):
        return '%s:%d' % (self.src, self.line)


def strip_comments(text):
    # Keep newlines so line numbers survive; drop the comment bodies so a
    # macro name quoted in prose is not taken for a site.
    def blank(m):
        return re.sub(r'[^\n]', ' ', m.group(0))
    text = re.sub(r'/\*.*?\*/', blank, text, flags=re.S)
    text = re.sub(r'//[^\n]*', blank, text)
    return text


def scan_sources(root):
    """All MODULE_DATA_DEFINE* sites in root/**/*.c, test programs excluded
    (they are host-only and never linked into the kernel)."""
    blocks = []
    errors = []
    for dirpath, dirnames, filenames in os.walk(root):
        rel_dir = os.path.relpath(dirpath, root)
        parts = [] if rel_dir == '.' else rel_dir.split(os.sep)
        dirnames[:] = sorted(d for d in dirnames
                             if not (not parts and d in ('build', 'dist'))
                             and d != 'test')
        for fn in sorted(filenames):
            if not fn.endswith('.c'):
                continue
            path = os.path.join(dirpath, fn)
            rel = os.path.relpath(path, root)
            with open(path, encoding='latin-1') as f:
                text = strip_comments(f.read())
            for m in SITE_RE.finditer(text):
                line = text.count('\n', 0, m.start()) + 1
                addr_text = m.group('addr').strip()
                if not LITERAL_RE.match(addr_text):
                    errors.append('%s:%d: %s: address `%s\' is not a literal'
                                  % (rel, line, m.group('name'), addr_text))
                    continue
                addr = int(addr_text.rstrip('uUlL'), 0)
                blocks.append(Block(m.group('name'), m.group('type').strip(),
                                    addr, rel, line))
    return blocks, errors


def block_checks(blocks, linkmap):
    errors = []
    seen = {}
    for b in blocks:
        if b.name in seen:
            errors.append('%s: %s already defined at %s'
                          % (b.where, b.name, seen[b.name].where))
        seen[b.name] = b
        if b.addr & 1:
            errors.append('%s: %s at 0x%08X is not even-aligned'
                          % (b.where, b.name, b.addr))
        if b.addr < RFC_LOAD_ADDR or b.addr >= KERNEL_VA_END:
            errors.append('%s: %s at 0x%08X is outside the kernel range '
                          '0x%08X..0x%08X' % (b.where, b.name, b.addr,
                                              RFC_LOAD_ADDR, KERNEL_VA_END))
        elif linkmap.segment_of(b.addr) is None:
            warn('%s: %s at 0x%08X is inside no map segment; nearest is %s'
                 % (b.where, b.name, b.addr,
                    linkmap.nearest_segment(b.addr)))
    return errors


# ---------------------------------------------------------------------------
# The link inputs
# ---------------------------------------------------------------------------

class Section:
    def __init__(self, obj, name, size):
        self.obj = obj
        self.name = name
        self.size = size
        self.symbols = []   # symbols defined in it, in value order
        self.map_syms = []  # (key, name) of those the map knows
        self.key = None
        self.pattern = None
        self.why = None     # catch-all reason
        self.follows = None # placed section of the same object it trails

    @property
    def label(self):
        return '%s(%s)' % (self.obj, self.name)


def is_code_section(name):
    return name == '.text' or name.startswith('.text.')


def read_object(objdump, obj):
    """Code sections of one object with the symbols each defines."""
    hdr = subprocess.run([objdump, '-h', obj], check=True,
                         capture_output=True, text=True).stdout
    secs = {}
    order = []
    for line in hdr.splitlines():
        f = line.split()
        if len(f) >= 7 and f[0].isdigit() and is_code_section(f[1]):
            size = int(f[2], 16)
            if size:
                secs[f[1]] = Section(obj, f[1], size)
                order.append(f[1])
    if not secs:
        return []
    tab = subprocess.run([objdump, '-t', obj], check=True,
                         capture_output=True, text=True).stdout
    syms = []
    for line in tab.splitlines():
        m = SYMTAB_RE.match(line)
        if not m:
            continue
        flags = m.group('flags')
        if flags[5] == 'd' or flags[6] == 'f':
            continue  # section and file symbols
        name = m.group('name').strip()
        if name.startswith('.L'):
            continue
        sec = m.group('sec')
        if sec in secs:
            syms.append((int(m.group('value'), 16), name, sec))
    for value, name, sec in sorted(syms):
        secs[sec].symbols.append(name)
    return [secs[n] for n in order]


def module_data_sections(objdump, objects):
    """{section name: object} for every .moddata.* section of the inputs."""
    found = {}
    for obj in objects:
        hdr = subprocess.run([objdump, '-h', obj], check=True,
                             capture_output=True, text=True).stdout
        for line in hdr.splitlines():
            f = line.split()
            if len(f) >= 7 and f[0].isdigit() and \
                    f[1].startswith('.moddata.'):
                found.setdefault(f[1], obj)
    return found


class Layout:
    """The ordered placement of every code section and block."""

    def __init__(self, linkmap, blocks, objects, objdump):
        self.linkmap = linkmap
        self.blocks = blocks
        self.sections = []
        self.errors = []
        for obj in objects:
            self.sections += read_object(objdump, obj)
        self._key_sections()
        self._patterns()
        self._check_blocks(objdump, objects)

    def _key_sections(self):
        lm = self.linkmap
        present = set()
        for s in self.sections:
            present.add(s.name)
            s.map_syms = sorted((lm.key(n), n) for n in s.symbols
                                if n in lm.symbols)
            if s.map_syms:
                s.key = s.map_syms[0][0]
            elif s.name in ANCHORS:
                s.key = addr_key(ANCHORS[s.name])
        for name in ANCHORS:
            if name not in present:
                self.errors.append('ANCHORS names %s, which no link input '
                                   'defines' % name)

        # A section whose map symbols straddle other placed keys cannot be
        # wholly in order: an error (split the file per routine).
        for s in self.sections:
            if s.key is None or len(s.map_syms) < 2:
                continue
            others = sorted([t.key for t in self.sections
                             if t is not s and t.key is not None]
                            + [addr_key(b.addr) for b in self.blocks])
            for prev, cur in zip(s.map_syms, s.map_syms[1:]):
                i = bisect.bisect_right(others, prev[0])
                if i < len(others) and others[i] < cur[0]:
                    self.errors.append(
                        '%s: map symbols %s (0x%06X) and %s (0x%06X) '
                        'straddle another placed section or block; split '
                        'it one section per routine'
                        % (s.label, prev[1], prev[0][0], cur[1],
                           cur[0][0]))
                    break

        # File-static helpers follow their object's first placed section.
        by_obj = {}
        for s in self.sections:
            by_obj.setdefault(s.obj, []).append(s)
        for obj, secs in by_obj.items():
            placed = sorted((s for s in secs if s.key is not None),
                            key=lambda s: s.key)
            for s in secs:
                if s.key is not None or s.why:
                    continue
                if placed:
                    s.key = placed[0].key
                    s.follows = placed[0]
                else:
                    s.why = 'defines no map symbol'

    def _patterns(self):
        count = {}
        for s in self.sections:
            count[s.name] = count.get(s.name, 0) + 1
        for s in self.sections:
            if s.name != '.text' and count[s.name] == 1:
                s.pattern = 'KEEP(*("%s"))' % s.name
            else:
                s.pattern = 'KEEP(%s("%s"))' % (s.obj, s.name)

    def _check_blocks(self, objdump, objects):
        have = module_data_sections(objdump, objects)
        for b in self.blocks:
            if b.section not in have:
                self.errors.append('%s: no link input has section %s (is '
                                   'the site inside an #if?)'
                                   % (b.where, b.section))

    def ordered(self):
        """[(key, tiebreak, kind, item)] in link order."""
        items = []
        # tiebreaks are (rank, n) throughout so equal keys always compare:
        # a block first, then the section keyed there, then its followers
        for b in self.blocks:
            items.append((addr_key(b.addr), (0, 0), 'block', b))
        for n, s in enumerate(self.sections):
            if s.key is None:
                continue
            tie = 2 if s.follows else 1
            items.append((s.key, (tie, n), 'section', s))
        items.sort(key=lambda t: (t[0], t[1]))
        return items

    def catch_all(self):
        return [s for s in self.sections if s.key is None]


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def fragment(layout, map_path):
    lm = layout.linkmap
    out = []
    out.append('/*')
    out.append(' * layout.ld - GENERATED by tools/gen_layout_ld.py; do not '
               'edit.')
    out.append(' * INCLUDEd inside the `.text\' output section of sau2.ld.  '
               'Input sections')
    out.append(' * in the order of the SAU2 link map (%s),'
               % os.path.basename(map_path))
    out.append(' * each tagged with the map address that orders it; the '
               'addresses are')
    out.append(' * ordering keys, not placements.')
    out.append(' */')
    seg = None
    for key, _, kind, item in layout.ordered():
        addr = key[0]
        cur = lm.segment_of(addr)
        if cur != seg:
            out.append('')
            out.append('    /* ---- %s ---- */' % (cur or '(no map segment)'))
            seg = cur
        if kind == 'block':
            stmt = 'KEEP(*("%s"))' % item.section
            out.append('    %s%s/* %06X module data %s (%s) */'
                       % (stmt, pad(stmt, 0), addr, item.name, item.where))
        else:
            if item.follows:
                note = 'with %s' % (item.follows.map_syms[0][1]
                                    if item.follows.map_syms
                                    else item.follows.name)
            elif item.map_syms:
                note = item.map_syms[0][1]
                if len(item.map_syms) > 1:
                    note += ' .. ' + item.map_syms[-1][1]
            else:
                note = 'anchor'
            out.append('    %s%s/* %06X %s */'
                       % (item.pattern, pad(item.pattern, 0), addr, note))
    out.append('')
    out.append('    /* ---- not in the SAU2 map: catch-all ---- */')
    for s in layout.catch_all():
        out.append('    /* %s: %s */' % (s.label, s.why))
    out.append('    *(.text .text.*)')
    out.append('    KEEP(*(.moddata.*))')
    out.append('')
    return '\n'.join(out)


def pad(text, extra):
    width = 56
    n = len(text) + 4 + extra
    return ' ' * max(1, width - n)


# ---------------------------------------------------------------------------
# The order check
# ---------------------------------------------------------------------------

def elf_symbols(nm, elf):
    out = subprocess.run([nm, '--defined-only', elf], check=True,
                         capture_output=True, text=True).stdout
    # Absolute symbols (`a'/`A': the hand-written files' `.set' equates
    # for image addresses) are not linked objects; a global definition
    # wins over file-static ones of the same name.
    found = {}
    for line in out.splitlines():
        f = line.split()
        if len(f) == 3 and f[1] not in 'aA':
            found.setdefault(f[2], []).append((f[1], int(f[0], 16)))
    syms = {}
    for name, defs in found.items():
        glob = [a for t, a in defs if t.isupper()]
        syms[name] = glob if glob else [a for t, a in defs]
    return syms


def check_elf(layout, elf, nm):
    lm = layout.linkmap
    syms = elf_symbols(nm, elf)
    errors = []
    rows = []   # (map key, name, elf address)
    for key, _, kind, item in layout.ordered():
        if kind == 'block':
            addrs = syms.get(item.name)
            if not addrs:
                errors.append('%s: block %s is not in %s'
                              % (item.where, item.name, elf))
                continue
            rows.append((key, item.name, addrs[0], 'block'))
            continue
        if not item.map_syms and item.name in ANCHORS:
            # An anchored section defines no map symbol; check it by its
            # first symbol (SVC_$TRAP8_TABLE, SMD_DISPLAY_INFO) at the
            # anchor's key, so a table drifting away from the routine that
            # reaches it PC-relatively is an inversion like any other.
            if not item.symbols:
                errors.append('%s (anchor) defines no symbol to check'
                              % item.label)
                continue
            name = item.symbols[0]
            addrs = syms.get(name)
            if not addrs:
                errors.append('%s defines %s but %s does not'
                              % (item.label, name, elf))
                continue
            rows.append((key, name, addrs[0], 'anchor'))
            continue
        for mkey, name in item.map_syms:
            addrs = syms.get(name)
            if not addrs:
                errors.append('%s defines %s but %s does not'
                              % (item.label, name, elf))
                continue
            if len(addrs) > 1:
                errors.append('%s is defined %d times in %s'
                              % (name, len(addrs), elf))
            rows.append((mkey, name, addrs[0], 'symbol'))
    rows.sort(key=lambda r: r[0])
    inversions = 0
    first = None
    for a, b in zip(rows, rows[1:]):
        if b[2] < a[2]:
            inversions += 1
            if first is None:
                first = (a, b)
    nsym = sum(1 for r in rows if r[3] == 'symbol')
    nblk = sum(1 for r in rows if r[3] == 'block')
    nanc = sum(1 for r in rows if r[3] == 'anchor')
    print('gen_layout_ld: %d map symbols, %d anchored section(s) and %d '
          'module data block(s) placed in map order (of %d map symbols; the '
          'rest are not translated or live in .data/.bss)'
          % (nsym, nanc, nblk, len(lm.symbols)))
    catch = layout.catch_all()
    nfun = sum(len(s.symbols) for s in catch)
    print('gen_layout_ld: %d code section(s) with %d symbol(s) in the '
          'catch-all:' % (len(catch), nfun))
    for s in catch:
        print('    %s: %s' % (s.label, s.why))
    print('gen_layout_ld: %d order inversion(s)' % inversions)
    if first:
        (ka, na, ea, _), (kb, nb, eb, _) = first
        errors.append('first inversion: %s (map 0x%06X) is linked at 0x%08X '
                      'but %s (map 0x%06X) at 0x%08X'
                      % (na, ka[0], ea, nb, kb[0], eb))
    return errors


# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--map', required=True, help='SAU2 link map')
    ap.add_argument('-o', '--output', help='fragment to write')
    ap.add_argument('--check-only', action='store_true',
                    help='run the checks, write nothing')
    ap.add_argument('--check-elf', metavar='ELF',
                    help='verify the link order of a linked ELF')
    ap.add_argument('--root', default='.',
                    help='source root (domain_os/), default .')
    ap.add_argument('--objdump', default='m68k-elf-objdump')
    ap.add_argument('--nm', default='m68k-elf-nm')
    ap.add_argument('objects', nargs='*')
    args = ap.parse_args()

    if not os.path.exists(args.map):
        fail(['link map %s not found (set SAU2_MAP)' % args.map])
    linkmap = LinkMap(args.map)

    blocks, errors = scan_sources(args.root)
    if errors:
        fail(errors)
    errors = block_checks(blocks, linkmap)
    layout = Layout(linkmap, blocks, args.objects, args.objdump)
    errors += layout.errors
    if errors:
        fail(errors)

    if args.check_elf:
        if not os.path.exists(args.check_elf):
            fail(['%s not found (did the scratch link fail?)'
                  % args.check_elf])
        errors = check_elf(layout, args.check_elf, args.nm)
        if errors:
            fail(errors)
        return

    if args.check_only:
        print('gen_layout_ld: %d section(s) placed, %d block(s), '
              '%d in the catch-all; checks passed'
              % (len(layout.ordered()) - len(blocks), len(blocks),
                 len(layout.catch_all())))
        return
    if not args.output:
        fail(['-o, --check-only or --check-elf is required'])

    text = fragment(layout, args.map)
    try:
        with open(args.output) as f:
            if f.read() == text:
                # unchanged: refresh the timestamp so make is satisfied
                os.utime(args.output)
                return
    except FileNotFoundError:
        pass
    os.makedirs(os.path.dirname(args.output) or '.', exist_ok=True)
    with open(args.output, 'w') as f:
        f.write(text)


if __name__ == '__main__':
    main()
