#!/usr/bin/env python3
#
# tools/gen_rfc_fixups.py - write the SAU2 RFC image dist/sau2/domain_os
# from the linked kernel ELF: the loaded bytes, then the fixup table COLD
# applies on a 68020 (docs/rfc-cold-start.md sections 5 step 8 and 8.6;
# bead source-yheb)
#
# Generated by: Claude Opus 5.5
#
# Usage:
#   gen_rfc_fixups.py --elf build/sau2/domain_os.elf -o dist/sau2/domain_os
#                     [--objcopy m68k-elf-objcopy] [--list FILE]
#
# 1. The loaded bytes: `objcopy -O binary' of the ELF, which writes every
#    section with contents at (LMA - lowest LMA) and fills the holes with
#    zeros.  sau2.ld gives COLD LMA 0x101400 (the RFC load address) and DUMP
#    and the kernel LMA = VMA - 0xCFE800, so file byte 0 is COLD and the file
#    ends at RELOC's low address (checked).
# 2. The fixup table, appended at RELOC (its VMA; low = file end): count.w,
#    then `count' longwords, each the LOW address (file offset + 0x101400)
#    of a 32-bit cell holding an absolute address.  The cells are exactly
#    the R_68K_32 relocations ld resolved (--emit-relocs) in every section
#    with file bytes - COLD, DUMP and the kernel alike, COLD's own operands
#    and the info block's two VA fields included, as the binder's table
#    lists them.  PC-relative relocations (R_68K_PC32/16/8) need no fixup.
#    Sorted ascending (the image's table is unsorted; COLD does not care).
#    COLD reads the count with `dbf', so 0 would run 65,536 times over
#    garbage: an empty list is written as one harmless entry (the header's
#    load-address cell, 0x101400, whose value lies outside every window and
#    is left unchanged).  More than 65,535 entries is an error.  The table
#    must fit the room the layout leaves for it at the start of .bss
#    (RELOC..RFC_FIXUP_TABLE_END, sized by tools/gen_layout_ld.py from the
#    inputs' relocations), so it overlays no bss object.
#
# What the table cannot express, reported, not failed: absolute 16-bit and
# 8-bit relocations (R_68K_16 / R_68K_8: `(sym).w' operands), which COLD
# never moves; the 68010 boot (MAME dn300/dn320, source-uaea) reads no table
# at all.  Literal address constants (an `.equ' or a C integer cast to a
# pointer) are not relocations and are invisible to the table, as they were
# to the binder.

import argparse
import os
import struct
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rfc_elf  # noqa: E402

RFC_LOAD = 0x00101400


def fail(msg):
    print('gen_rfc_fixups: error: ' + msg, file=sys.stderr)
    sys.exit(1)


def fixup_cells(elf):
    """(sorted low addresses of the R_68K_32 cells, [inexpressible
    (type, vma, symbol)])."""
    cells = set()
    other = []
    for sec, vma, typ, name, addend in elf.relocations():
        if not sec.loaded:
            continue
        if typ == rfc_elf.R_68K_32:
            if not sec.addr <= vma <= sec.addr + sec.size - 4:
                fail('R_68K_32 at 0x%08X outside %s' % (vma, sec.name))
            cells.add(vma - sec.addr + sec.lma)
        elif typ in (rfc_elf.R_68K_16, rfc_elf.R_68K_8):
            other.append((typ, vma, name))
    return sorted(cells), other


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--elf', required=True)
    ap.add_argument('-o', '--output', required=True)
    ap.add_argument('--objcopy', default='m68k-elf-objcopy')
    ap.add_argument('--list', help='also write the entries, one per line')
    a = ap.parse_args()

    elf = rfc_elf.Elf(a.elf)
    loaded = [s for s in elf.sections if s.loaded]
    if not loaded:
        fail('%s has no loaded sections' % a.elf)
    low = min(s.lma for s in loaded)
    if low != RFC_LOAD:
        fail('the lowest load address is 0x%08X, not the RFC load address '
             '0x%08X' % (low, RFC_LOAD))
    reloc = elf.symbol('RELOC')
    if reloc is None:
        fail('%s defines no RELOC' % a.elf)
    last = max(loaded, key=lambda s: s.lma + s.size)
    if last.addr + last.size != reloc:
        fail('the last loaded byte (%s ends at VMA 0x%08X) is not RELOC - 1 '
             '(RELOC 0x%08X)' % (last.name, last.addr + last.size, reloc))
    reloc_low = last.lma + last.size

    with tempfile.TemporaryDirectory() as tmp:
        raw = os.path.join(tmp, 'image.bin')
        subprocess.run([a.objcopy, '-O', 'binary', a.elf, raw], check=True)
        with open(raw, 'rb') as f:
            image = f.read()
    if RFC_LOAD + len(image) != reloc_low:
        fail('objcopy wrote 0x%X bytes; RELOC\'s low address 0x%08X needs '
             '0x%X' % (len(image), reloc_low, reloc_low - RFC_LOAD))

    cells, other = fixup_cells(elf)
    for c in cells:
        if c & 1:
            fail('fixup cell at low 0x%08X is odd' % c)
        if not RFC_LOAD <= c <= reloc_low - 4:
            fail('fixup cell at low 0x%08X is outside the file' % c)
    entries = cells if cells else [RFC_LOAD]
    if len(entries) > 0xFFFF:
        fail('%d fixups: more than the count word holds' % len(entries))
    table = struct.pack('>H', len(entries)) + \
        b''.join(struct.pack('>I', c) for c in entries)
    room = elf.symbol('RFC_FIXUP_TABLE_END')
    if room is None or reloc + len(table) > room:
        fail('the fixup table (0x%X bytes) does not fit the room sau2.ld '
             'leaves for it at RELOC (to RFC_FIXUP_TABLE_END %s)'
             % (len(table), 'unset' if room is None else '0x%08X' % room))

    tmp_out = a.output + '.tmp'
    with open(tmp_out, 'wb') as f:
        f.write(image + table)
    os.replace(tmp_out, a.output)
    if a.list:
        with open(a.list, 'w') as f:
            for c in entries:
                f.write('%08X\n' % c)

    n16 = sum(1 for t, _, _ in other if t == rfc_elf.R_68K_16)
    n8 = sum(1 for t, _, _ in other if t == rfc_elf.R_68K_8)
    print('gen_rfc_fixups: %s: %d bytes = 0x%X loaded (low 0x%06X..0x%06X) '
          '+ fixup table at RELOC 0x%08X (low 0x%06X): %d entries%s'
          % (a.output, len(image) + len(table), len(image), RFC_LOAD,
             reloc_low, reloc, reloc_low, len(entries),
             '' if cells else ' (placeholder: no R_68K_32 cells)'))
    if n16 or n8:
        print('gen_rfc_fixups: not expressible in the table (COLD moves '
              '32-bit cells only): %d R_68K_16, %d R_68K_8' % (n16, n8))
        for t, vma, name in other[:10]:
            print('    %s at 0x%08X -> %s'
                  % (rfc_elf.RELOC_NAMES[t], vma, name or '(section)'))


if __name__ == '__main__':
    main()
