#!/usr/bin/env python3
#
# tools/rfc_elf.py - a minimal reader for the linked kernel ELF
# (build/sau2/domain_os.elf, 32-bit big-endian m68k), shared by
# tools/gen_rfc_fixups.py and tools/check_rfc.py (source-yheb)
#
# Generated by: Claude Opus 5.5
#
# Sections with their VMA and load address (LMA: from the PT_LOAD program
# header holding the section, as BFD computes it), section contents, the
# symbol table, and the relocations --emit-relocs leaves in the output
# (r_offset is the VMA of the cell in an ET_EXEC).

import struct

SHT_SYMTAB = 2
SHT_RELA = 4
SHT_NOBITS = 8
SHF_ALLOC = 0x2
PT_LOAD = 1

# m68k relocation types (elf/m68k.h)
R_68K_32 = 1
R_68K_16 = 2
R_68K_8 = 3
R_68K_PC32 = 4
R_68K_PC16 = 5
R_68K_PC8 = 6
RELOC_NAMES = {R_68K_32: 'R_68K_32', R_68K_16: 'R_68K_16', R_68K_8: 'R_68K_8',
               R_68K_PC32: 'R_68K_PC32', R_68K_PC16: 'R_68K_PC16',
               R_68K_PC8: 'R_68K_PC8'}


class Section:
    def __init__(self, index, name, sh):
        (self.name_off, self.type, self.flags, self.addr, self.offset,
         self.size, self.link, self.info, self.align, self.entsize) = sh
        self.index = index
        self.name = name
        self.lma = None

    @property
    def alloc(self):
        return bool(self.flags & SHF_ALLOC)

    @property
    def loaded(self):
        """Has bytes in the load image."""
        return self.alloc and self.type != SHT_NOBITS and self.size > 0


class Elf:
    def __init__(self, path):
        with open(path, 'rb') as f:
            self.data = f.read()
        d = self.data
        if d[:4] != b'\x7fELF' or d[4] != 1 or d[5] != 2:
            raise ValueError('%s: not a 32-bit big-endian ELF' % path)
        (self.e_type, self.machine, _, self.entry, phoff, shoff, _, _,
         phentsize, phnum, shentsize, shnum, shstrndx) = \
            struct.unpack_from('>HHIIIIIHHHHHH', d, 16)
        raw = [struct.unpack_from('>IIIIIIIIII', d, shoff + i * shentsize)
               for i in range(shnum)]
        strtab = raw[shstrndx]
        self.sections = []
        for i, sh in enumerate(raw):
            name = self._str(strtab[4], sh[0])
            self.sections.append(Section(i, name, sh))
        self.phdrs = [struct.unpack_from('>IIIIIIII', d, phoff + i * phentsize)
                      for i in range(phnum)]
        for s in self.sections:
            if not s.alloc:
                continue
            s.lma = s.addr
            for (p_type, p_off, p_vaddr, p_paddr, p_filesz, p_memsz, _,
                 _) in self.phdrs:
                if p_type != PT_LOAD:
                    continue
                if s.type != SHT_NOBITS:
                    inside = p_off <= s.offset and \
                        s.offset + s.size <= p_off + p_filesz and \
                        p_vaddr <= s.addr < p_vaddr + max(p_memsz, 1)
                else:
                    inside = p_vaddr <= s.addr and \
                        s.addr + s.size <= p_vaddr + p_memsz
                if inside:
                    s.lma = p_paddr + (s.addr - p_vaddr)
                    break
        self._symbols = None

    def _str(self, off, idx):
        d = self.data
        end = d.index(b'\0', off + idx)
        return d[off + idx:end].decode('latin-1')

    def section(self, name):
        for s in self.sections:
            if s.name == name:
                return s
        return None

    def contents(self, s):
        if s.type == SHT_NOBITS:
            return bytes(s.size)
        return self.data[s.offset:s.offset + s.size]

    def symbols(self):
        """[(name, value, size, info, shndx)] of the symbol table."""
        if self._symbols is None:
            self._symbols = []
            for s in self.sections:
                if s.type != SHT_SYMTAB:
                    continue
                strs = self.sections[s.link].offset
                for i in range(s.size // 16):
                    nm, value, size, info, _, shndx = struct.unpack_from(
                        '>IIIBBH', self.data, s.offset + i * 16)
                    self._symbols.append((self._str(strs, nm), value, size,
                                          info, shndx))
        return self._symbols

    def symbol(self, name):
        """The value of a global (or the only) symbol `name', or None."""
        found = [(info >> 4, v) for n, v, _, info, shndx in self.symbols()
                 if n == name and shndx != 0]
        glob = [v for b, v in found if b != 0]
        if glob:
            return glob[0]
        return found[0][1] if found else None

    def relocations(self):
        """[(target Section, r_offset, type, symbol name, addend)] of every
        .rela section that applies to an allocated section."""
        out = []
        syms = None
        for s in self.sections:
            if s.type != SHT_RELA:
                continue
            target = self.sections[s.info]
            if not target.alloc:
                continue
            if syms is None:
                syms = self.symbols()
            for i in range(s.size // 12):
                r_offset, r_info, r_addend = struct.unpack_from(
                    '>IIi', self.data, s.offset + i * 12)
                symi, typ = r_info >> 8, r_info & 0xFF
                name = syms[symi][0] if symi < len(syms) else ''
                out.append((target, r_offset, typ, name, r_addend))
        return out

    def section_of_vma(self, vma):
        """The allocated section holding VMA (None if none)."""
        for s in self.sections:
            if s.alloc and s.size and s.addr <= vma < s.addr + s.size:
                return s
        return None
