/*
 * io/dctes_data.c - the DCTES data segment
 *
 * SAU2 map:
 *   D    E2C8BC  DCTES              size = D0
 *        E2C8BC  RING_DCTE
 *        E2C8FC  FLP_DCTE
 *        E2C93C  WIN_DCTE
 *        E2C97C  DEV_DCTES
 * (the segment before it is IO_, whose last symbol IO_$IN_INIT is at
 * 0xE2C8BA; the one after is OS_TERM at 0xE2C98C).
 *
 * Generated by: Claude Opus 5.5 (reviewed by Claude Fable 5.1)
 *
 * Image (`gsk read 0xE2C8BC 0xD0`):
 *   e2c8bc  00 01 00 40 00 02 00 00  00 00 00 00 00 e2 fa e0   RING_DCTE
 *   e2c8cc  00 .. 00 (0x20 bytes)
 *   e2c8ec  00 00 00 00 00 ff 9c 00  00 e7 57 48 00 18 00 1b
 *   e2c8fc  00 01 00 40 00 01 00 00  00 00 00 00 00 e3 e0 02   FLP_DCTE
 *   e2c90c  00 .. 00 (0x20 bytes)
 *   e2c92c  00 00 00 00 00 ff a8 00  00 e1 9f 6c 00 17 00 00
 *   e2c93c  00 01 00 40 00 00 00 00  00 00 00 00 00 e3 03 40   WIN_DCTE
 *   e2c94c  00 .. 00 (0x20 bytes)
 *   e2c96c  00 00 00 00 00 ff a8 00  00 e1 9b fa 00 17 00 00
 *   e2c97c  00 e2 c9 3c 00 e2 c8 fc  00 e2 c8 bc 00 00 00 00   DEV_DCTES
 *
 * Each DCTE: kind 1 (IO_$INIT translates +0x2C, zero here), length 0x40,
 * controller type 2 / 1 / 0, controller number 0, no next, the controller
 * init procedure at +0x0C (RING_$INIT 0xE2FAE0, FLP_$CINIT 0xE3E002,
 * WIN_$CINIT 0xE30340), empty name (so IO_$INIT does not list them), the
 * register block at +0x34 (0xFF9C00 for the ring, 0xFFA800 for the floppy
 * and the Winchester), the interrupt routine at +0x38 (RING_$INT 0xE75748,
 * FLP_$INT 0xE19F6C, WIN_$INT 0xE19BFA) and the words at +0x3C.  The
 * procedure cells are written as the symbols the map gives their targets.
 */

#include "io/io_internal.h"
#include "ring/ring.h"          /* RING_$INIT, RING_$INT */
#include "flp/flp.h"            /* FLP_$CINIT, FLP_$INT */
#include "win/win.h"            /* WIN_$CINIT, WIN_$INT */

/*
 * The +0x34 register-block VAs of the image (map RING2 / DISK), from
 * arch/m68k/sau2/hw.h via arch/arch.h; a host test defines the two names
 * before including this file.
 */
#define DCTES_RING_REGS     SAU2_RING2_BASE
#define DCTES_DISK_REGS     SAU2_DISK_BASE

MODULE_DATA_DEFINE_INIT(io_$dctes_t, DCTES, 0x00E2C8BC, {
    .ring_dcte = {
        .kind           = IO_DCTE_KIND_MAPPED,
        .length         = 0x40,
        .ctype          = 2,
        .cnum           = 0,
        .nextp          = NULL,
        .csrsytr        = (io_$dcte_init_fn_t)RING_$INIT,       /* 0xE2FAE0 */
        .disk_dinit     = DCTES_RING_REGS,
        .disk_do_io     = ARCH_PTR_TO_VA_STATIC(RING_$INT, 0x00E75748),
        .disk_error_que = 0x0018001B,
    },
    .flp_dcte = {
        .kind           = IO_DCTE_KIND_MAPPED,
        .length         = 0x40,
        .ctype          = 1,
        .cnum           = 0,
        .nextp          = NULL,
        .csrsytr        = FLP_$CINIT,                           /* 0xE3E002 */
        .disk_dinit     = DCTES_DISK_REGS,
        .disk_do_io     = ARCH_PTR_TO_VA_STATIC(FLP_$INT, 0x00E19F6C),
        .disk_error_que = 0x00170000,
    },
    .win_dcte = {
        .kind           = IO_DCTE_KIND_MAPPED,
        .length         = 0x40,
        .ctype          = 0,
        .cnum           = 0,
        .nextp          = NULL,
        .csrsytr        = (io_$dcte_init_fn_t)WIN_$CINIT,       /* 0xE30340 */
        .disk_dinit     = DCTES_DISK_REGS,
        .disk_do_io     = ARCH_PTR_TO_VA_STATIC(WIN_$INT, 0x00E19BFA),
        .disk_error_que = 0x00170000,
    },
    .dev_dctes = {
        ARCH_PTR_TO_VA_STATIC(&DCTES.win_dcte, 0x00E2C93C),
        ARCH_PTR_TO_VA_STATIC(&DCTES.flp_dcte, 0x00E2C8FC),
        ARCH_PTR_TO_VA_STATIC(&DCTES.ring_dcte, 0x00E2C8BC),
        0,
    },
});
