/*
 * IO_$GET_CONFIG - report which controllers are configured
 *
 * Original address: 0x00E72334
 * Size: 134 bytes of code (0x00E72334 .. 0x00E723B9), then the three
 * controller-type words it passes CHK by reference (0x00E723BA ..
 * 0x00E723BF): the whole of the SAU2 map's "I E72334 IO_ size = 8C".
 * Generated by: Claude Opus 5.5
 *
 * Frame (link.w A6,-0x4; A2 saved; A5 is not touched):
 *   (0x08,A6) config1   (0x0C,A6) config2   (0x10,A6) config3
 *   (0x14,A6) config4   - all pointers to words
 *
 *   0x00E7233A-0x00E72354  *config1 = 0; CHK(&0) true: bset #0 in its low
 *                          byte (`bset.b #0x0,(0x1,A0)')
 *   0x00E7235A-0x00E7236E  CHK(&1) true: bset #1 in config1's low byte
 *   0x00E72374-0x00E7238E  *config2 = 0; CHK(&2) true: bset #0
 *   0x00E72394-0x00E72398  *config3 = 0
 *   0x00E7239A-0x00E723AC  *config4 = 0; the IO_ byte at +0x550
 *                          (0xE2C8B8, `tst.b (0x550,A2)' with A2 =
 *                          0xE2C368) negative: bset #0
 *
 * CHK answers a Domain boolean tested with `tst.b D0b' / bpl, so only a
 * negative byte counts.  Controller types 0/1/2 are the Winchester, the
 * floppy and the ring (DCTES: WIN_DCTE, FLP_DCTE, RING_DCTE).
 *
 * Sole caller ASKNODE_$INTERNET_INFO (0x00E64D4C).
 */

#include "io/io_internal.h"
#include "misc/misc.h"          /* CHK */

/* 0x00E723BA / 0x00E723BC / 0x00E723BE: `gsk read 0xE723BA 6` = 00 00 00 02
 * 00 01, reached by `pea (0x78,PC)', `pea (0x40,PC)' and `pea (0x62,PC)'. */
static const uint16_t io_get_config_ctype0 = 0;
static const uint16_t io_get_config_ctype2 = 2;
static const uint16_t io_get_config_ctype1 = 1;

void IO_$GET_CONFIG(uint16_t *config1, uint16_t *config2,
                    uint16_t *config3, uint16_t *config4)
{
    /* 0x00E7233A-0x00E72354 */
    *config1 = 0;
    if (CHK(&io_get_config_ctype0) < 0) {
        *config1 |= 0x0001;
    }

    /* 0x00E7235A-0x00E7236E */
    if (CHK(&io_get_config_ctype1) < 0) {
        *config1 |= 0x0002;
    }

    /* 0x00E72374-0x00E7238E */
    *config2 = 0;
    if (CHK(&io_get_config_ctype2) < 0) {
        *config2 |= 0x0001;
    }

    /* 0x00E72394-0x00E72398 */
    *config3 = 0;

    /* 0x00E7239A-0x00E723AC */
    *config4 = 0;
    if (io_$config_flag < 0) {
        *config4 |= 0x0001;
    }
}
