/*
 * IO_$GET_DCTE - find the DCTE for a controller type and number
 *
 * Original address: 0x00E1A448 (SAU2 map)
 * Size: 92 bytes (0x00E1A448 .. 0x00E1A4A3)
 * Generated by: Claude Opus 5.5
 *
 * A Pascal function returning the DCTE pointer in A0.  A5 = 0xE2C368 (the
 * IO_ segment), so (0x54c,A5) is IO_$DCTE_LIST (0x00E2C8B4).  Callers:
 * NETWORK_$INIT (0x00E2F764), RING_$GET_ID (0x00E2FA3C), OS_$INIT
 * (0x00E33CA6), RING_$RCV_FROM_UNIT_PRIV (0x00E76070).
 *
 * Frame (link.w A6,-0x14): (0x8,A6) ctypep, (0xc,A6) cnump, (0x10,A6)
 * status_ret (A1).  Both words are read once (0x00E1A462/0x00E1A464).
 *
 * Blocks:
 *   0x00E1A466-0x00E1A46C  found = NULL; p = IO_$DCTE_LIST; nil -> exit
 *   0x00E1A470-0x00E1A484  ctype and cnum match -> found = p,
 *                          *status_ret = p->cstatus; a zero cstatus ends the
 *                          walk (`beq` on the move.l), a non-zero one keeps
 *                          walking, so a later match replaces this one
 *   0x00E1A486-0x00E1A48A  p = p->nextp; non-nil -> loop
 *   0x00E1A48C-0x00E1A494  found nil -> *status_ret = 0x00100001
 *                          ("controller not found"); return found
 */

#include "io/io_internal.h"

dcte_t *IO_$GET_DCTE(uint16_t *ctypep, uint16_t *cnump, status_$t *status_ret)
{
    uint16_t ctype;     /* D0w */
    uint16_t cnum;      /* D1w */
    dcte_t *found;      /* D2 */
    dcte_t *p;          /* D3 / A0 */

    /* 0x00E1A462-0x00E1A466 */
    ctype = *ctypep;
    cnum = *cnump;
    found = NULL;

    /* 0x00E1A468-0x00E1A48A */
    for (p = IO_$DCTE_LIST; p != NULL; p = p->nextp) {
        if (p->ctype == ctype && p->cnum == cnum) {
            found = p;
            *status_ret = p->cstatus;
            if (*status_ret == status_$ok) {
                break;
            }
        }
    }

    /* 0x00E1A48C-0x00E1A494 */
    if (found == NULL) {
        *status_ret = status_$io_controller_not_found;
    }
    return found;
}
