/*
 * IO_$INIT - Initialise the I/O subsystem
 *
 * Original address: 0x00E328E0 (SAU2 map: IO_$INIT)
 * Size: 330 bytes (0x00E328E0 .. 0x00E32A29; unlk/rts at 0x00E32A2A), its
 * message texts and a zero longword follow at 0x00E32A2E.
 * Generated by: Claude Opus 5.5
 *
 * Called once by OS_$INIT (0x00E33B6A area).  Initialises the two I/O
 * exclusion locks and DMA, builds the DCTE list, runs the bus init
 * procedures, then initialises every controller on the list.
 *
 * Frame (link.w A6,-0x1c; D2-D4/A2-A3 saved; no A5 - the IO_ segment is
 * addressed absolutely, `movea.l #0xe2c368,A1`):
 *   (0x08,A6) param1, never read   (0x0C,A6) verbose (A2)   (0x10,A6) status
 *   D2 the last physical page number, D4/A3 the current DCTE
 *
 * Blocks:
 *   0x00E328EC-0x00E3291A  *status = 0; IO_$IN_INIT = true; both exclusion
 *                          locks initialised; DMA_$INIT
 *   0x00E32920             io_$build_dcte_list
 *   0x00E32924-0x00E3293A  call each non-nil IO_$BUS_EPV[0..4].init
 *   0x00E3293E-0x00E32A16  for each DCTE on IO_$DCTE_LIST:
 *     0x00E3294E-0x00E3296A  verbose and named: "Device: <name>: "
 *     0x00E3296E-0x00E329B8  status clear and kind 1: translate io_va
 *                            (MMU_$VTOP, failure crashes) into io_pa
 *     0x00E329BC-0x00E329DC  status clear: status = csrsytr(dcte), or 0
 *                            without one
 *     0x00E329E0-0x00E32A0E  verbose and named: "init failed: status
 *                            <status>" or "OK"
 *   0x00E32A1A-0x00E32A20  IO_$IN_INIT = false
 *
 * Quirks reproduced:
 *   - A kind-1 DCTE with io_va 0 still gets io_pa, built from D2 as the
 *     previous translation (or the bus loop's `dbf`, 0x0000FFFF) left it
 *     (0x00E3297C-0x00E329B8).
 *   - "init failed"/"OK" is printed only for a DCTE whose status was clear
 *     on arrival; one that failed in io_$build_dcte_list gets only its
 *     "Device:" line.
 *   - *status is cleared and never set.
 */

#include "io/io_internal.h"
#include "dma/dma.h"
#include "misc/misc.h"
#include "mmu/mmu.h"
#include "vfmt/vfmt.h"

/*
 * The texts and the zero argument cell after the code (`gsk read 0xE32A2E
 * 0x32`):
 *   0x00E32A2E "init failed: status %8zh%."  `pea (0x34,PC)` 0x00E329F8
 *   0x00E32A48 00 00 00 00                    `pea (0xee,PC)` 0x00E32958,
 *                                             (0x56,PC) 0x00E329F0,
 *                                             (0x48,PC) 0x00E329FE
 *   0x00E32A4C "OK%."                         `pea (0x46,PC)` 0x00E32A04
 *   0x00E32A50 "Device: %m8a: %$"             `pea (0xee,PC)` 0x00E32960
 */
static const char io_$fmt_init_failed[] = "init failed: status %8zh%.";
static const uint32_t io_$zero_long = 0;
static const char io_$fmt_ok[] = "OK%.";
static const char io_$fmt_device[] = "Device: %m8a: %$";

/* `cmpi.w #0x1,(A3)` 0x00E32976 */
/* IO_DCTE_KIND_MAPPED (1): io/io.h */

void IO_$INIT(void *param1, const int8_t *verbose_flag, status_$t *status_ret)
{
    dcte_t *d;                          /* D4 / A3 */
    io_$bus_epv_t *epv;                 /* A3 */
    uint32_t ppn;                       /* D2 */
    int16_t i;                          /* D2w */

    (void)param1;

    /* 0x00E328EC-0x00E3291A */
    *status_ret = status_$ok;
    IO_$IN_INIT = (int8_t)0xFF;                             /* st (0x552,A1) */
    ML_$EXCLUSION_INIT(&io_$exclusion);
    ML_$EXCLUSION_INIT(&IO_$WIRING_EXCLUSION);
    DMA_$INIT();

    /* 0x00E32920 */
    io_$build_dcte_list();

    /* 0x00E32924-0x00E3293A: moveq #0x4,D2 / dbf */
    epv = IO_$BUS_EPV;
    for (i = IO_BUS_EPV_COUNT - 1; i >= 0; i--) {
        if (epv->init != NULL) {
            epv->init();
        }
        epv++;
    }
    ppn = 0x0000FFFFu;                  /* D2 as the dbf leaves it */

    /* 0x00E3293E-0x00E32A16 */
    for (d = IO_$DCTE_LIST; d != NULL; d = d->nextp) {
        if (*verbose_flag < 0 && d->name[0] != 0) {
            VFMT_$WRITE10(io_$fmt_device, d->name, &io_$zero_long);
        }
        if (d->cstatus != status_$ok) {
            continue;
        }

        /* 0x00E32976-0x00E329B8 */
        if (d->kind == IO_DCTE_KIND_MAPPED) {
            if (d->io_va != 0) {
                ppn = MMU_$VTOP(d->io_va, &d->cstatus);
            }
            if (d->cstatus != status_$ok) {
                CRASH_SYSTEM(&d->cstatus);
            }
            d->io_pa = (ppn << 10) + (d->io_va & 0x3FF);
        }

        /* 0x00E329BC-0x00E329DC */
        if (d->cstatus != status_$ok) {
            continue;
        }
        if (d->csrsytr != NULL) {
            d->cstatus = d->csrsytr(d);
        } else {
            d->cstatus = status_$ok;
        }

        /* 0x00E329E0-0x00E32A0E */
        if (*verbose_flag < 0 && d->name[0] != 0) {
            if (d->cstatus != status_$ok) {
                VFMT_$WRITE10(io_$fmt_init_failed, &d->cstatus, &io_$zero_long);
            } else {
                VFMT_$WRITE10(io_$fmt_ok, &io_$zero_long, &io_$zero_long);
            }
        }
    }

    /* 0x00E32A1A-0x00E32A20 */
    IO_$IN_INIT = 0;
}
