/*
 * os/os_internal.h - Internal OS Definitions
 *
 * Contains internal functions, data, and types used only within
 * the OS subsystem. External consumers should use os/os.h.
 */

#ifndef OS_INTERNAL_H
#define OS_INTERNAL_H

#include "os/os.h"
#include "uid/uid.h"
#include "time/time.h"
#include "proc1/proc1.h"
#include "proc2/proc2.h"
#include "ast/ast.h"
#include "mst/mst.h"
#include "mmap/mmap.h"
#include "mmu/mmu.h"
#include "cal/cal.h"
#include "misc/misc.h"
#include "network/network.h"
#include "file/file.h"
#include "acl/acl.h"
#include "name/name.h"
#include "route/route.h"
#include "io/io.h"
#include "disk/disk.h"      /* DISK_$INIT, DISK_$DO_CHKSUM, status_$disk_needs_salvaging */
#include "pmap/pmap.h"      /* PMAP_$SHUTTING_DOWN_FLAG, PMAP_$PURIFIER_L/R */
#include "rgyc/rgyc.h"      /* RGYC_$G_LOCKSMITH_UID */
#include "as/as.h"          /* AS_$INIT, AS_$STACK_HIGH */
#include "fim/fim.h"        /* FIM_$BUS_ERR, FIM_$PARITY_TRAP */
#include "dxm/dxm.h"        /* DXM_$INIT, DXM_$HELPER_WIRED/UNWIRED */
#include "fp/fp.h"          /* FP_$SAVEP */
#include "peb/peb.h"        /* PEB_$INIT, PEB_$LOAD_WCS */
#include "term/term.h"      /* TERM_$INIT */
#include "dtty/dtty.h"      /* DTTY_$INIT */
#include "smd/smd.h"        /* SMD_$INIT, SMD_$INIT_BLINK, SMD_$INQ_DISP_TYPE */
#include "tpad/tpad.h"      /* TPAD_$INIT */
#include "ec/ec.h"          /* EC2_$INIT_S, EC2_$REGISTER_EC1 */
#include "area/area.h"      /* AREA_$INIT, AREA_$SHUTDOWN */
#include "dbuf/dbuf.h"      /* DBUF_$INIT, DBUF_$GET_BLOCK, DBUF_$SET_BUFF */
#include "volx/volx.h"      /* VOLX_$MOUNT, VOLX_$SHUTDOWN, VOLX_$REC_ENTRY */
#include "vtoc/vtoc.h"      /* VTOCE_$READ */
#include "sock/sock.h"      /* SOCK_$INIT */
#include "net_io/net_io.h"  /* NET_IO_$BOOT_DEVICE */
#include "ring/ring.h"      /* RING_$GET_ID */
#include "hint/hint.h"      /* HINT_$INIT, HINT_$INIT_CACHE, HINT_$ADD_NET, HINT_$SHUTDN */
#include "log/log.h"        /* LOG_$INIT, LOG_$SHUTDN */
#include "audit/audit.h"    /* AUDIT_$INIT, AUDIT_$SHUTDOWN */
#include "xpd/xpd.h"        /* XPD_$INIT */
#include "pchist/pchist.h"  /* PCHIST_$INIT */
#include "pacct/pacct.h"    /* PACCT_$INIT, PACCT_$SHUTDN */
#include "prom/prom.h"      /* io_$probe */

/*
 * Well-known UIDs (OS_WIRED_$UID, DISPLAY1_$UID, LV_LABEL_$UID) come from
 * uid/uid.h; ACL_$FNDWRX from acl/acl.h; RGYC_$G_LOCKSMITH_UID from
 * rgyc/rgyc.h; NAME_$NODE_UID from name/name.h.
 *
 * DISK_$DO_CHKSUM is in disk/disk.h, PMAP_$SHUTTING_DOWN_FLAG in pmap/pmap.h,
 * MST_$MST_PAGES_LIMIT in mst/mst.h, AS_$STACK_HIGH is a macro in as/as.h,
 * ROUTE_$PORT is in route/route.h, CAL_$BOOT_VOLX is a macro in cal/cal.h.
 */

/*
 * ============================================================================
 * Global Data - Boot Info
 * ============================================================================
 */

extern uint32_t BOOT_INFO_TABLE[];

/*
 * ============================================================================
 * Global Data - Interrupt Stack
 * ============================================================================
 */

/*
 * INT_STACK_BASE - the label the SAU2 map puts at 0x00EB2C00, the first byte
 * past the top of the interrupt stack: the end of the STACK segment block
 * OS_$STACK, defined with the block's other labels in os/os.h (source-4k71).
 * OS_$INIT reaches it with `movea.l #0xeb2c00,A0`, then zeroes the 0x400
 * bytes below it.
 */

/*
 * ============================================================================
 * The address-space boundaries OS_$INIT and os_$start_proc2 work from
 * ============================================================================
 *
 * Generated by: Claude Opus 5.5 (source-wh9b, 2026-10-06).
 *
 * In the image every boundary is a `move.l #<link-time value>' the binder
 * resolved, rounded at run time by `andi.l #-0x8000' (to a 32 KB segment)
 * or `andi.w #-0x400' (to a 1 KB page; the low word only, which for a VA
 * is the same as clearing bits 0..9).  Where the boundary is rounded UP the
 * binder folded `+ 0x7FFF' / `+ 0x3FF' into the immediate.  The table gives
 * each immediate, what the SAU2 map has there, and what replaces it; the
 * old os/init.c macro names are in brackets.  Docs: rfc-cold-start.md 8b.
 *
 *  immediate  instructions                map (domain_os.10.2.map)
 *    -> meaning                            -> our source
 *  0xD00000   0x00E33996 move.l, 0x00E339A2 andi.l   [OS_WIRED_LOW]
 *             `D92 D00000 OS_LOW' (UNWIRED_STACKS starts there)
 *    -> the bottom of the low region (canned map 1, start)        
 *                                          -> OS_LOW (sau2.ld, absolute)
 *  0xDAC7FF   0x00E3399C move.l, 0x00E339A8 andi.l   [OS_WIRED_HIGH 0xDA8000]
 *             `D93 DA4800 OS_LOW_END_' + 0x7FFF
 *    -> its top, OS_LOW_END rounded up     -> OS_LOW_END (sau2.ld, absolute)
 *  0xE00000   0x00E339AE move.l, 0x00E339BA andi.l   [OS_DATA_LOW]
 *             `D95 E00000 OS_BEGIN'
 *    -> the kernel's first VA (canned map 2, start)
 *                                          -> OS_BEGIN (sau2.ld)
 *  0xE38000   0x00E339B4 move.l, 0x00E339C6 andi.l   [OS_DATA_HIGH]
 *             `I 1 E38000 .TEXT', OS_PROC_UNWIRED
 *    -> the start of the unwired code: end of map 2, start of map 3, the
 *       paging file's origin (0x00E33ABA, 0x00E33B00, 0x00E343CC,
 *       0x00E34046) and the paging loop's start (0x00E34418)
 *                                          -> OS_PROC_UNWIRED (sau2.ld)
 *  0xE78400   0x00E339C0 move.l, 0x00E339CC andi.l   [OS_TEXT_LOW 0xE78000]
 *             `D21 E78400 .DATA', OS_DATA = OS_DATA_UNWIRED
 *    -> the unwired data rounded down: end of map 3 (read-only on a type-4
 *       boot), start of map 4; kept at A6-0x198
 *                                          -> OS_DATA_UNWIRED (sau2.ld)
 *  0xEB1683   0x00E339D6 move.l, 0x00E339DC andi.l   [OS_TEXT_HIGH 0xEB0000]
 *             `D91 EA9684 OS_DATA_END' + 0x7FFF (= `D90 EB0000 OS_PAGE')
 *    -> the end of the image proper (its bss blocks ACL_$DATA .. PROC2_$DATA
 *       included) rounded up: end of map 4, start of map 5, the paging
 *       loop's end; kept at A6-0x194      -> OS_DATA_END (sau2.ld)
 *  0xEF6400   0x00E339FA add.l                       [OS_MST_BASE]
 *             `EF6400 MSTE_PAGES' in VM_TABLES (not MST, which is EE5800)
 *    -> the MSTE pages; map 5 ends MST_PAGES_LIMIT pages past it, rounded
 *       up to a segment                    -> MST_PAGE_TABLE_BASE (mst/mst.h)
 *  0xF4FC00   0x00E3397C move.l                      [OS_WIRED_END]
 *             `D52 F4FC00 IODEFS_GUARD' = VM_TABLES_END = MSTE_PAGES +
 *             MST_MSTE_PAGES_MAX pages
 *    -> the top of the kernel's tables     -> OS_IODEFS_GUARD (below)
 *  0xFC0000   0x00E33982 cmp.l                       [OS_WIRED_LIMIT]
 *             `FC0000 IODEFS' = DISP1_MEM
 *    -> the start of the I/O space         -> SAU2_DISPLAY_MEM_BASE (hw.h)
 *  0xE00BFF   0x00E33B78 move.l, 0x00E33B84 andi.w   [OS_DATA_RO_LOW 0xE00800]
 *             `I 3 E00800 OS_PROC' + 0x3FF
 *    -> the first page of wired code, OS_PROC rounded up: type-4 read-only
 *       range start                        -> OS_PROC (sau2.ld)
 *  0xE1DC00   0x00E33B7E movea.l, 0x00E33BA2 andi.w  [OS_DATA_WIRED_BASE]
 *             `D24 E1DC00 WIRED_DATA', OS_DATA_WIRED
 *    -> the end of the wired code, rounded down: type-4 read-only range end
 *                                          -> OS_DATA_WIRED (sau2.ld)
 *  0xE3824C   0x00E343E6 move.l, 0x00E343EC andi.w   [OS_KEEP_WIRED1_LOW]
 *             `E3824C OS_DISK_PROC' (VTOC_)
 *    -> the disk code kept wired on a disked node, start rounded down;
 *       kept at A6-0x18c                   -> OS_DISK_PROC (os/os.h: the
 *                                             function the map names there)
 *  0xE3EB45   0x00E343F4 move.l, 0x00E343FA andi.w   [OS_KEEP_WIRED1_HIGH]
 *             `E3E746 OS_DISK_PROC_END' + 0x3FF
 *    -> its end rounded up; A6-0x188       -> OS_DISK_PROC_END (sau2.ld)
 *  0xE784D0   0x00E34402 move.l, 0x00E3440E andi.w   [OS_KEEP_WIRED2_LOW]
 *             `E784D0 OS_DISK_DATA' (VTOC_ data)
 *    -> the disk data kept wired, start rounded down; D7
 *                                          -> OS_DISK_DATA (sau2.ld)
 *  0xE7B443   0x00E34408 move.l, 0x00E34412 andi.w   [OS_KEEP_WIRED2_HIGH]
 *             `E7B044 OS_DISK_DATA_END' + 0x3FF
 *    -> its end rounded up; D6             -> OS_DISK_DATA_END (sau2.ld)
 *  0xEA9684   0x00E34452 cmp.l                       [OS_INIT_FREE_ABOVE]
 *             `D91 EA9684 OS_DATA_END' (not the init code's end)
 *    -> pages at or past it are freed, not given to the paging file
 *                                          -> OS_DATA_END (sau2.ld)
 *  0xEB0000   0x00E3441A movea.l to A3, never read again: OS_PAGE, dead
 *  os_$start_proc2 (0x00E6D254):
 *  0xE3D37F   0x00E6D25C move.l, 0x00E6D268 andi.l
 *             `E35380 OS_INIT_END' + 0x7FFF (= .TEXT 0xE38000)
 *    -> the end of the boot-only part, rounded up
 *                                          -> OS_INIT_END (sau2.ld)
 *  0xE2F000   0x00E6D262 move.l
 *             `I 5 E2F000 OS_INIT_PROC', OS_INIT_START
 *    -> the start of the boot-only part    -> OS_INIT_START (sau2.ld)
 *
 * Ours, not the image's (docs section 8b): OS_LINK_UNPLACED .. RELOC holds
 * what the map gives no position (the catch-all code, C .rodata and .data,
 * wired and unwired modules mixed); OS_$INIT keeps it wired with a third
 * test shaped like the two disk ranges', but on every node: a diskless node
 * lets the disk ranges go (0x00E34506) and still needs the wired modules
 * placed there.
 *
 * The link symbols are defined by sau2.ld and the fragments
 * tools/gen_layout_ld.py writes, at the map positions of the objects that
 * follow them; sau2.ld ASSERTs their order and the two segment alignments
 * the run-time rounding depends on.  A host test defines its own.
 */
extern char OS_PROC[];          /* the first wired code page */
extern char OS_DATA_WIRED[];    /* the first wired data */
extern char OS_INIT_START[];    /* the boot-only code and data ... */
extern char OS_INIT_END[];      /* ... up to here */
extern char OS_PROC_UNWIRED[];  /* .TEXT: the unwired code */
extern char OS_DISK_PROC_END[]; /* the end of the disk code kept wired */
extern char OS_DATA_UNWIRED[];  /* .DATA: the unwired data */
extern char OS_DISK_DATA[];     /* the disk data kept wired ... */
extern char OS_DISK_DATA_END[]; /* ... up to here */
extern char OS_LINK_UNPLACED[]; /* ours: the start of what the map does not
                                 * place, kept wired up to RELOC */
extern char RELOC[];            /* the first byte past the file */
extern char OS_DATA_END[];      /* the end of the image's bss blocks */

/*
 * The low region (canned map 1): fixed VAs below the kernel, not in the
 * file, laid out by the map and owned by several modules (UNWIRED_STACKS
 * D00000, DISK_BUFFERS D50000, NETPOOL D64C00, AREA_PAGES D94C00; see
 * proc1/proc1_config.h, netbuf/netbuf_internal.h, xns/xns_data.c).
 * docs/handbook-dn3xx.md 7-1 puts the unwired stacks at 0xD00000.  Their
 * values are the map's, fixed: sau2.ld defines them as absolute symbols
 * (`OS_LOW = 0x00D00000', `OS_LOW_END = 0x00DA4800', like OS_BEGIN) so the
 * cells that name them are R_68K_32 relocations and land in the fixup
 * table, as the image's immediates at 0x00E33998 / 0x00E3399E are RELOC
 * entries (the DN330 path moves them).
 */
extern char OS_LOW[];           /* `D92 D00000 OS_LOW' */
extern char OS_LOW_END[];       /* `D93 DA4800 OS_LOW_END_' */
extern char OS_BEGIN[];         /* `D95 E00000 OS_BEGIN' */

/*
 * The ceiling of the kernel's tables, checked at 0x00E3397C against the
 * start of the I/O space: the map's IODEFS_GUARD 0xF4FC00 is VM_TABLES_END,
 * the end of the room MST_$INIT can give the MSTE pages.  0xEF6400 + 0x166
 * * 0x400 = 0xF4FC00.
 */
#define OS_IODEFS_GUARD \
    ((uint32_t)MST_PAGE_TABLE_BASE + (uint32_t)MST_MSTE_PAGES_MAX * 0x400u)

/* 1 KB pages, 32 KB segments of 32 pages */
#define OS_PAGE_SIZE 0x400u
#define OS_SEG_SIZE  0x8000u

/* `andi.l #-0x8000,Dn' and `andi.w #-0x400,Dn' */
#define OS_SEG_TRUNC(va)  ((uint32_t)(va) & 0xFFFF8000u)
#define OS_PAGE_TRUNC(va) ((uint32_t)(va) & 0xFFFFFC00u)

/*
 * Each boundary as the image computes it from its link-time value.  OS_$INIT
 * applies them to the symbols above; the host test applies them to the
 * map's values and gets the image's immediates back.
 */
#define OS_INIT_SEG_DOWN(va) OS_SEG_TRUNC(va)                  /* D2, D4, D5, D6 */
#define OS_INIT_SEG_UP(va)   OS_SEG_TRUNC((uint32_t)(va) + 0x7FFFu) /* D3, D7 */
#define OS_INIT_PAGE_DOWN(va) OS_PAGE_TRUNC(va)                /* keep lows */
#define OS_INIT_PAGE_UP(va)  OS_PAGE_TRUNC((uint32_t)(va) + 0x3FFu) /* keep highs */

/*
 * 0x00E339E6-0x00E33A06: the top of canned map 5, MST_$MST_PAGES_LIMIT
 * pages past the MSTE pages, rounded up to a segment.  The limit word is
 * sign-extended (`ext.l D6') and scaled by `lsl.l #8' / `lsl.l #2'.
 */
#define OS_INIT_MST_HIGH(mste_pages, limit)                                  \
    OS_SEG_TRUNC(((uint32_t)(int32_t)(int16_t)(limit) << 10) +               \
                 (uint32_t)(mste_pages) + 0x7FFFu)

/*
 * ============================================================================
 * The m68k exception vector table
 * ============================================================================
 *
 * OS_$INIT writes exception vectors three ways: through the boot info table
 * walk at 0x00E33876 (`move.l (0xdc,A1),(A4)` with A4 = vector * 4), and by
 * two absolute stores, `move.l #0xe21f84,(0x7c).l` (vector 31, the parity
 * trap) and `move.l #0xe218e8,(0x8).l` (vector 2, bus error).  All three go
 * through ARCH_VECTOR(n) (arch/arch.h), the architecture's vector-table
 * entry; on the host a test defines arch_$vector_table.  (source-702z: this
 * was an OS_$VECTOR_TABLE macro chosen by an architecture guard.)
 */

/*
 * ============================================================================
 * Global Data - Trap Handlers
 * ============================================================================
 */

/*
 * NULL_PC - the null process's saved PC cell, 0x00EB07FC (map: NULL_PC, in
 * the STACK segment at 0x00EB0000; NULL_STACK is at 0x00EB07F4), a field of
 * OS_$STACK (os/os.h; source-4k71).  OS_$INIT stores the address of NULLPROC
 * there (`move.l #0xe24c60,(0x00eb07fc).l` at 0x00E33CE6), so it holds a VA.
 * The tree used to spell it `_NULL_PC`; the map name is NULL_PC (bead
 * source-wk2f).
 *
 * NULLPROC is the null process's code (os/sau2/nullproc.s; map "D E24C60
 * NULLPROC size = 18"): a routine, not a cell.
 */
void NULLPROC(void);
extern void *_BUS_ERROR_VEC;
/* FIM_$BUS_ERR and FIM_$PARITY_TRAP: see fim/fim.h */

/*
 * Daemon entry points PMAP_$PURIFIER_L/R (pmap/pmap.h) and
 * DXM_$HELPER_WIRED/UNWIRED (dxm/dxm.h) are declared by their owners.
 */

/*
 * ============================================================================
 * Global Data - Shutdown Wiring Info
 * ============================================================================
 */

/* FP_$SAVEP: see fp/fp.h */
/* 0xE82738: the clock_t OS_$SHUTDOWN waits on (os_data.c) */
extern clock_t OS_$SHUTDOWN_WAIT_TIME;
extern m68k_ptr_t PTR_OS_PROC_SHUTWIRED;
extern m68k_ptr_t PTR_OS_PROC_SHUTWIRED_END;
/* PTR_OS_DATA_SHUTWIRED is declared in os/os.h (shared with stop/) */
extern m68k_ptr_t PTR_OS_DATA_SHUTWIRED_END;

/*
 * ============================================================================
 * Global Data - Status Constants
 * ============================================================================
 *
 * The statuses OS_$INIT passes to its callees are `pea (d,PC)` constant cells
 * in the OS module's own code region; they are file-static constants in
 * os/init.c, not globals (see bead source-tzmw).
 */

/* status_$disk_needs_salvaging is a macro in disk/disk.h */
/* status_$cal_refused is a macro in cal/cal.h */
/* status_$pmap_bad_assoc is a macro in ast/ast.h */

/*
 * ============================================================================
 * Subsystem Init/Shutdown Functions
 * ============================================================================
 *
 * All of the subsystem entry points called by OS_$INIT and OS_$SHUTDOWN are
 * declared by their owning subsystem's public header (included above):
 *
 *   mst/mst.h        MST_$PRE_INIT, MST_$INIT, MST_$DISKLESS_INIT,
 *                    MST_$MAP_CANNED_AT, MST_$ALLOC_ASID
 *   as/as.h          AS_$INIT
 *   mmu/mmu.h        MMU_$INIT, MMU_$REMOVE, MMU_$SET_SYSREV, MMU_$SET_PROT
 *   mmap/mmap.h      MMAP_$INIT, MMAP_$UNWIRE
 *   peb/peb.h        PEB_$INIT, PEB_$LOAD_WCS
 *   dxm/dxm.h        DXM_$INIT
 *   io/io.h          IO_$INIT, IO_$GET_DCTE
 *   term/term.h      TERM_$INIT
 *   dtty/dtty.h      DTTY_$INIT
 *   smd/smd.h        SMD_$INIT, SMD_$INIT_BLINK, SMD_$INQ_DISP_TYPE
 *   tpad/tpad.h      TPAD_$INIT
 *   time/time.h      TIME_$INIT
 *   uid/uid.h        UID_$INIT
 *   proc1/proc1.h    PROC1_$INIT, PROC1_$CREATE_P, ...
 *   proc2/proc2.h    PROC2_$INIT, PROC2_$SHUTDOWN
 *   ec/ec.h          EC2_$INIT_S, EC2_$REGISTER_EC1
 *   acl/acl.h        ACL_$INIT, ACL_$ENTER_SUPER
 *   ast/ast.h        AST_$INIT, AST_$ACTIVATE_AOTE_CANNED, AST_$PMAP_ASSOC
 *   area/area.h      AREA_$INIT, AREA_$SHUTDOWN
 *   disk/disk.h      DISK_$INIT
 *   dbuf/dbuf.h      DBUF_$INIT, DBUF_$GET_BLOCK, DBUF_$SET_BUFF
 *   volx/volx.h      VOLX_$MOUNT, VOLX_$SHUTDOWN, VOLX_$REC_ENTRY
 *   vtoc/vtoc.h      VTOCE_$READ
 *   sock/sock.h      SOCK_$INIT
 *   network/network.h NETWORK_$INIT, NETWORK_$LOAD, NETWORK_$ADD_REQUEST_SERVERS,
 *                    NETWORK_$DISMISS_REQUEST_SERVERS, NETWORK_$SET_SERVICE,
 *                    network_$fetch_diskless_info
 *   net_io/net_io.h  NET_IO_$BOOT_DEVICE
 *   ring/ring.h      RING_$GET_ID
 *   route/route.h    ROUTE_$SHUTDOWN
 *   file/file.h      FILE_$LOCK_INIT, FILE_$LOCK, FILE_$SET_LEN,
 *                    FILE_$SET_REFCNT, FILE_$PRIV_UNLOCK_ALL
 *   hint/hint.h      HINT_$INIT, HINT_$INIT_CACHE, HINT_$ADD_NET, HINT_$SHUTDN
 *   name/name.h      NAME_$INIT, NAME_$SET_WDIR
 *   log/log.h        LOG_$INIT, LOG_$SHUTDN
 *   audit/audit.h    AUDIT_$INIT, AUDIT_$SHUTDOWN
 *   xpd/xpd.h        XPD_$INIT
 *   pchist/pchist.h  PCHIST_$INIT
 *   pacct/pacct.h    PACCT_$INIT, PACCT_$SHUTDN
 *   cal/cal.h        CAL_$VERIFY, CAL_$SHUTDOWN, ...
 */

/*
 * ============================================================================
 * Utility Functions
 * ============================================================================
 */

/* VFMT_$FORMATN declared in vfmt/vfmt.h (via misc/misc.h) */
void CRASH_SHOW_STRING(const char *str);
/* CRASH_SYSTEM declared in misc/misc.h */
/* MMU_$NORMAL_MODE declared in mmu/mmu.h */
/* prompt_for_yes_or_no declared in misc/misc.h */
/*
 * VTOP_OR_CRASH (0x00E6D1E8) - translate a virtual address, or crash.
 *
 * Pascal `var` parameter: the caller pushes the ADDRESS of a longword
 * holding the virtual address (`pea (-0x1c4,A6)` in OS_$INIT, `pea (0x8,A6)`
 * in os_$free_va_page).  The physical page number comes back in D0.
 */
uint32_t VTOP_OR_CRASH(uint32_t *va_p);
/* SUB48 declared in cal/cal.h */
/* PRINT_BUILD_TIME declared in misc/misc.h */
/* VFMT_$WRITE10 declared in vfmt/vfmt.h (via misc/misc.h) */

/*
 * ============================================================================
 * Internal Helper Functions (FUN_*)
 * ============================================================================
 */

/* io_$probe: see prom/prom.h */
/* AST_$ACTIVATE_ASTE_CANNED (0x00E2F1D4): see ast/ast.h */
/* network_$fetch_diskless_info: see network/network.h (2=time, 8=tz, 0x37=route) */
void OS_$PRINT_INIT_ERROR(const char *msg);            /* Display message */
void os_$free_va_page(uint32_t vaddr);          /* Free page at virtual address */
void os_$start_proc2(void *param);             /* Free init pages and start proc2 */

/*
 * The VTOCE the boot volume's paging file resolves to: a named view of the
 * fields OS_$INIT and OS_$INSTALL_DISPLAY_ASTE touch inside a vtoce_$result_t.
 *
 * The original clears exactly 0x90 bytes at A6-0x128 (0x00E34018:
 * `moveq #0x23` + `dbf` = 36 longwords), and the next frame slot -- the
 * lookup request at A6-0x98 -- starts 0x90 bytes later, so the buffer is
 * 0x90 bytes.  That is the true size of the record: VTOCE_$READ moves the
 * same 36 longwords into it (0x00E395B0) and VTOCE_$WRITE and VTOC_$ALLOCATE
 * move 36 back out (0x00E3977A, 0x00E38C26).  0x150 is the on-disk entry
 * stride, not the size of this record; vtoc/vtoc.h now says so.
 */
typedef struct os_$init_vtoce_t {
    uint32_t reserved00;                  /* +0x00 */
    uid_t file_uid;                       /* +0x04 (A6-0x124) */
    uint32_t reserved0c;                  /* +0x0C */
    uint32_t reserved10;                  /* +0x10 */
    uint32_t length;                      /* +0x14 (A6-0x114) */
    uint8_t reserved18[0x74 - 0x18];      /* +0x18 */
    uint16_t field74;                     /* +0x74 (A6-0xB4) */
    uint8_t reserved76[0x88 - 0x76];      /* +0x76 */
    uid_t acl_uid;                        /* +0x88 (A6-0xA0) */
} os_$init_vtoce_t;

#if defined(ARCH_M68K)
_Static_assert(sizeof(os_$init_vtoce_t) == 0x90, "os_$init_vtoce_t size");
_Static_assert(sizeof(os_$init_vtoce_t) == sizeof(vtoce_$result_t),
               "os_$init_vtoce_t must be the same record as vtoce_$result_t");
_Static_assert(__builtin_offsetof(os_$init_vtoce_t, file_uid) == 0x04, "uid");
_Static_assert(__builtin_offsetof(os_$init_vtoce_t, length) == 0x14, "length");
_Static_assert(__builtin_offsetof(os_$init_vtoce_t, field74) == 0x74, "f74");
_Static_assert(__builtin_offsetof(os_$init_vtoce_t, acl_uid) == 0x88, "acl");
#endif

#endif /* OS_INTERNAL_H */
