/*
 * misc/sau2/disp_lites.s - DISP_LITES (SAU2)
 *
 * Generated by: Claude Opus 5.5
 *
 * Byte gate (tools/asm_compare.py, `make check'): encodings identical to
 * the image; the routine has no relocations (every address operand is a
 * hardware address or an immediate).
 *
 * The SAU2 map files the routine as a data segment of its own in the wired
 * area ("D E1E9F4 DISP_LITES size = D4", between DMA_ and PROC1_ASM), with
 * its entry the segment's only symbol.  Hand-written: no frame, a `movem'
 * of D2-D5, arguments read straight off SP, and an IPL-7 bracket.
 *
 * DISP_LITES(pattern, y) - 0x00E1E9F4, 212 bytes (0x00E1E9F4..0x00E1EAC7)
 *   0x14(SP)  pattern  word (after the 16 bytes of saved registers and the
 *                       return address): bit 15 is the leftmost light
 *   0x16(SP)  y        word: the row; A0 = 0xFC0000 + y*0x80 + 6
 * Called only by SMD_$LITES (0x00E1D8CC), which pushes two words.  (As for
 * PROC1_$SET_LOCK, a C caller built by gcc passes each word promoted to a
 * longword, so the offsets here are those of the Pascal caller.)
 *
 * With IPL 7 (`ori #0x700,SR'; the exit `andi #0xF8FF,SR' forces IPL 0,
 * it does not restore) and the display controller's first register word
 * (0xFF9800, map DISP1 = SAU2_DISPLAY_CTRL_REGS) non-negative, it draws 16
 * lights as a 4 x 4 row: groups of four 16-row by 16-pixel blocks, one word
 * of the frame buffer (0xFC0000, SAU2_DISPLAY_MEM_BASE) per row, a longword
 * apart within a group and a further longword between groups.  A set bit
 * draws a solid block (16 rows of 0xFFFF); a clear bit a hollow one (0xFFFF,
 * 14 rows of 0x8001, 0xFFFF).  The pattern is rotated left one bit per light.
 * A negative controller word skips the drawing.
 */

        .section ".text.DISP_LITES","ax",@progbits
        .globl  DISP_LITES

DISP_LITES:
        movem.l %d2-%d5,-(%sp)          /* 00e1e9f4 */
        move.w  (0x14,%sp),%d1          /* 00e1e9f8  pattern */
        clr.l   %d0                     /* 00e1e9fc */
        move.w  (0x16,%sp),%d0          /* 00e1e9fe  y */
        lsl.l   #7,%d0                  /* 00e1ea02  y * 0x80 */
        addq.l  #6,%d0                  /* 00e1ea04 */
        .short  0xd0bc                  /* 00e1ea06  add.l #0xfc0000,%d0: the image */
        .long   0x00fc0000              /*           uses the ADD <ea>=#imm form (D0BC), */
                                        /*           which gas spells ADDI (0680) */
        movea.l %d0,%a0                 /* 00e1ea0c */
        ori.w   #0x700,%sr              /* 00e1ea0e  IPL 7 */
        tst.w   0x00ff9800              /* 00e1ea12  display controller */
        bmi.w   Ldisp_lites_exit        /* 00e1ea18 */
        move.w  #-1,%d2                 /* 00e1ea1c  solid row */
        move.w  #-0x7fff,%d3            /* 00e1ea20  hollow row 0x8001 */
        move.w  #3,%d4                  /* 00e1ea24  four groups */
Ldisp_lites_group:
        move.w  #3,%d5                  /* 00e1ea28  four lights a group */
Ldisp_lites_light:
        btst.l  #15,%d1                 /* 00e1ea2c */
        beq.b   Ldisp_lites_hollow      /* 00e1ea30 */
        move.w  %d2,(%a0)               /* 00e1ea32 */
        move.w  %d2,(0x80,%a0)
        move.w  %d2,(0x100,%a0)
        move.w  %d2,(0x180,%a0)
        move.w  %d2,(0x200,%a0)
        move.w  %d2,(0x280,%a0)
        move.w  %d2,(0x300,%a0)
        move.w  %d2,(0x380,%a0)
        move.w  %d2,(0x400,%a0)
        move.w  %d2,(0x480,%a0)
        move.w  %d2,(0x500,%a0)
        move.w  %d2,(0x580,%a0)
        move.w  %d2,(0x600,%a0)
        move.w  %d2,(0x680,%a0)
        move.w  %d2,(0x700,%a0)
        move.w  %d2,(0x780,%a0)         /* 00e1ea6c */
        bra.b   Ldisp_lites_next        /* 00e1ea70 */
Ldisp_lites_hollow:
        move.w  %d2,(%a0)               /* 00e1ea72 */
        move.w  %d3,(0x80,%a0)
        move.w  %d3,(0x100,%a0)
        move.w  %d3,(0x180,%a0)
        move.w  %d3,(0x200,%a0)
        move.w  %d3,(0x280,%a0)
        move.w  %d3,(0x300,%a0)
        move.w  %d3,(0x380,%a0)
        move.w  %d3,(0x400,%a0)
        move.w  %d3,(0x480,%a0)
        move.w  %d3,(0x500,%a0)
        move.w  %d3,(0x580,%a0)
        move.w  %d3,(0x600,%a0)
        move.w  %d3,(0x680,%a0)
        move.w  %d3,(0x700,%a0)
        move.w  %d2,(0x780,%a0)         /* 00e1eaac */
Ldisp_lites_next:
        rol.w   #1,%d1                  /* 00e1eab0 */
        addq.w  #4,%a0                  /* 00e1eab2 */
        dbf     %d5,Ldisp_lites_light   /* 00e1eab4 */
        addq.w  #4,%a0                  /* 00e1eab8 */
        dbf     %d4,Ldisp_lites_group   /* 00e1eaba */
Ldisp_lites_exit:
        andi.w  #0xf8ff,%sr             /* 00e1eabe  IPL 0 */
        movem.l (%sp)+,%d2-%d5          /* 00e1eac2 */
        rts                             /* 00e1eac6 */
