/*
 * sock/test/test_sock_data.c - the SOCK module data block (source-gy7x)
 *
 * Generated by: Claude Opus 5.5
 *
 * sock/sock_data.c is #included, so the object under test is the real
 * block with the image's contents:
 *
 *   SOCK_$DATA  map "D E27510 SOCK size = 1C28"
 *
 * Checked: the image address, the offsets that hold on every build (those
 * behind the pointer-bearing descriptors are asserted at compile time on
 * the target only), the two Pascal [1..0xE0] tables' overlays, the initial
 * contents, and - through the real SOCK_$INIT, SOCK_$ALLOCATE and
 * SOCK_$OPEN - that socket n's descriptor and pointer slot are indexed with
 * n and that the free list threads target VAs through the block.
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

/* ==========================================================================
 * Test framework
 * ========================================================================== */

static int tests_failed = 0;
static int tests_run = 0;

#define TEST(name) static void test_##name(void)
#define RUN_TEST(name)                                                        \
    do {                                                                      \
        printf("  Running %s... ", #name);                                    \
        tests_run++;                                                          \
        test_##name();                                                        \
        printf("done\n");                                                     \
    } while (0)

#define ASSERT_EQ(expected, actual)                                           \
    do {                                                                      \
        long long _e = (long long)(expected);                                 \
        long long _a = (long long)(actual);                                   \
        if (_e != _a) {                                                       \
            printf("FAILED\n    Expected: 0x%llx, Got: 0x%llx at line %d\n",  \
                   (unsigned long long)_e, (unsigned long long)_a, __LINE__); \
            tests_failed++;                                                   \
            return;                                                           \
        }                                                                     \
    } while (0)

#include "sock/sock_internal.h"

/* ==========================================================================
 * Mocked callees
 * ========================================================================== */

static int ec_inits;

void EC_$INIT(ec_$eventcount_t *ec)
{
    ec->value = 0;
    ec_inits++;
}

static void *spin_lock_arg;

ml_$spin_token_t ML_$SPIN_LOCK(void *lockp)
{
    spin_lock_arg = lockp;
    return 0;
}

void ML_$SPIN_UNLOCK(void *lockp, ml_$spin_token_t token)
{
    (void)lockp;
    (void)token;
}

static int add_pages_calls;

void NETBUF_$ADD_PAGES(int16_t hdr_pages, int16_t data_pages)
{
    (void)hdr_pages;
    (void)data_pages;
    add_pages_calls++;
}

#include "../sock_data.c"
#include "../init.c"
#include "../allocate.c"
#include "../open.c"

#define OFF(field) \
    ((size_t)((const uint8_t *)&(field) - (const uint8_t *)&SOCK_$DATA))

/*
 * VAs are offsets from ARCH_HOST_VA_BASE; putting the base a page below the
 * block keeps every descriptor's VA non-zero and inside 32 bits.
 */
static void use_block_arena(void)
{
    ARCH_HOST_VA_BASE = (uintptr_t)&SOCK_$DATA - 0x1000;
}

static int free_list_length(void)
{
    int n = 0;
    uint32_t va = SOCK_$DATA.list.free_head;

    while (va != 0 && n < 0x200) {
        va = ((sock_$sock_t *)ARCH_VA_TO_PTR(va))->queue_head;
        n++;
    }
    return n;
}

/* ==========================================================================
 * Tests
 * ========================================================================== */

TEST(block_address_and_size)
{
    ASSERT_EQ(0x00E27510u, MODULE_DATA_ADDR(SOCK_$DATA));
    ASSERT_EQ(0x1C28, SOCK_$DATA_SIZE);
    /* map SOCK_$SOCKET 0xE27530 and SOCK_$SOCKET_PTR 0xE28DB4 */
    ASSERT_EQ(0x00E27530u, MODULE_DATA_ADDR(SOCK_$DATA) + 0x20);
    ASSERT_EQ(0x00E28DB4u, MODULE_DATA_ADDR(SOCK_$DATA) + 0x18A4);
}

TEST(list_header)
{
    /* SOCK_LIST: 0x20 bytes, the head at +0x0C ("tst.l (0xc,A5)") */
    ASSERT_EQ(0x00, OFF(SOCK_$DATA.list));
    ASSERT_EQ(0x0C, OFF(SOCK_$DATA.list.free_head));
    ASSERT_EQ(0x20, sizeof(SOCK_$DATA.list));
}

TEST(table_shapes)
{
    /* both tables are Pascal [1..0xE0] declared from their bias slot */
    ASSERT_EQ(SOCK_MAX_NUMBER + 1,
              sizeof(SOCK_$DATA.socket) / sizeof(SOCK_$DATA.socket[0]));
    ASSERT_EQ(SOCK_MAX_NUMBER + 2,
              sizeof(SOCK_$DATA.socket_ptr) / sizeof(SOCK_$DATA.socket_ptr[0]));
    /* socket_ptr[0] is the lock, socket_ptr[0xE1] the user limit */
    ASSERT_EQ(OFF(SOCK_$DATA.socket_ptr[0]), OFF(SOCK_$DATA.lock));
    ASSERT_EQ(OFF(SOCK_$DATA.socket_ptr[SOCK_MAX_NUMBER + 1]),
              OFF(SOCK_$DATA.user_limit));
    /* the descriptors end where the lock starts: socket[0xE0] is the last */
    ASSERT_EQ(OFF(SOCK_$DATA.lock),
              OFF(SOCK_$DATA.socket[SOCK_MAX_NUMBER]) + sizeof(sock_$sock_t));
}

TEST(initial_contents)
{
    const uint8_t *p = (const uint8_t *)&SOCK_$DATA;
    size_t i;
    size_t limit = OFF(SOCK_$DATA.user_limit);

    /* 0x00E29134: 00 40, everything else zero */
    ASSERT_EQ(0x0040, SOCK_$DATA.user_limit);
    for (i = 0; i < sizeof(SOCK_$DATA); i++) {
        if (i == limit || i == limit + 1) {
            continue;
        }
        ASSERT_EQ(0, p[i]);
    }
}

TEST(init_points_each_slot_at_its_descriptor)
{
    int n;

    use_block_arena();
    SOCK_$INIT();

    ASSERT_EQ(0xE0, ec_inits);
    for (n = 1; n <= SOCK_MAX_NUMBER; n++) {
        ASSERT_EQ((uintptr_t)&SOCK_$DATA.socket[n],
                  (uintptr_t)SOCK_$DATA.socket_ptr[n]);
        ASSERT_EQ(n, SOCK_$DATA.socket[n].flags & SOCK_FLAG_NUMBER_MASK);
    }
    /* sockets 0x20..0xE0 on the free list, last pushed first */
    ASSERT_EQ(SOCK_MAX_NUMBER - SOCK_DYNAMIC_MIN + 1, free_list_length());
    ASSERT_EQ(ARCH_PTR_TO_VA(&SOCK_$DATA.socket[SOCK_MAX_NUMBER]),
              SOCK_$DATA.list.free_head);
    ASSERT_EQ(ARCH_PTR_TO_VA(&SOCK_$DATA.socket[SOCK_DYNAMIC_MIN]),
              SOCK_$DATA.socket[SOCK_DYNAMIC_MIN + 1].queue_head);
    ASSERT_EQ(0, SOCK_$DATA.socket[SOCK_DYNAMIC_MIN].queue_head);
    /* the untouched user limit */
    ASSERT_EQ(0x0040, SOCK_$DATA.user_limit);
}

TEST(allocate_takes_the_head_and_open_unlinks_from_the_middle)
{
    uint16_t sock = 0;
    int before = free_list_length();

    ASSERT_EQ(-1, SOCK_$ALLOCATE(&sock, 0x00040000, 0x00000400));
    ASSERT_EQ(SOCK_MAX_NUMBER, sock);
    ASSERT_EQ((uintptr_t)&SOCK_$DATA.lock, (uintptr_t)spin_lock_arg);
    ASSERT_EQ(before - 1, free_list_length());
    ASSERT_EQ(4, SOCK_$DATA.socket_ptr[sock]->max_queue);

    /* SOCK_$OPEN of a dynamic socket walks the list from the block base */
    ASSERT_EQ(-1, SOCK_$OPEN(0x40, 0x00020000, 0x00000100));
    ASSERT_EQ(before - 2, free_list_length());
    ASSERT_EQ(ARCH_PTR_TO_VA(&SOCK_$DATA.socket[0x3F]),
              SOCK_$DATA.socket[0x41].queue_head);
    ASSERT_EQ(0, add_pages_calls);
}

int main(void)
{
    printf("SOCK module data tests\n");
    RUN_TEST(block_address_and_size);
    RUN_TEST(list_header);
    RUN_TEST(table_shapes);
    RUN_TEST(initial_contents);
    RUN_TEST(init_points_each_slot_at_its_descriptor);
    RUN_TEST(allocate_takes_the_head_and_open_unlinks_from_the_middle);
    printf("%d tests, %d failed\n", tests_run, tests_failed);
    return tests_failed ? 1 : 0;
}
