/*
 * io/sau2/cond_switch_back.s - IO_$COND_SWITCH_BACK (SAU2)
 *
 * Generated by: Claude Opus 5.5
 *
 * Byte gate (tools/asm_compare.py, `make check'): encodings identical to
 * the image, except the one documented widening below; address operands
 * resolve to our objects.
 *
 * Original address: 0x00E2E846, 22 bytes (IO_$TBLS, between
 * IO_$USE_INT_STACK and io_$flih_dispatch):
 *   22 5f                 movea.l (SP)+,A1
 *   bf fc 00 eb 2b e8     cmpa.l #0xeb2be8,SP       ; the interrupt stack top
 *   66 0a                 bne.b 0x00e2e85a
 *   2e 7a ff d0           movea.l (-0x30,PC),SP     ; IO_$SAVED_OS_SP
 *   42 b9 00 e2 e8 22     clr.l (0x00e2e822).l
 *   4e d1                 jmp (A1)
 *
 * The undo of IO_$USE_INT_STACK (io/sau2/use_int_stack.s): an interrupt
 * routine about to leave calls it, and if SP is exactly the interrupt
 * stack top that IO_$USE_INT_STACK switched to (no nested frames left), SP
 * goes back to the saved OS stack and the save cell is cleared.  It pops
 * its own return address and leaves with `jmp (A1)', since SP may change.
 * Caller: TIME_$TIMER_HANDLER's spurious-interrupt arm (0x00E2B270).
 *
 * Widening: `movea.l (IO_$SAVED_OS_SP,PC),SP' becomes an absolute long
 * operand - the cell is io/io_data.c's object, not in reach of a 16-bit
 * displacement from this section (closes source-9ysy).
 */

        .section ".text.IO_$COND_SWITCH_BACK","ax",@progbits
        .even

        .extern IO_$SAVED_OS_SP
        .extern OS_$STACK

/* The interrupt stack top IO_$USE_INT_STACK loads (0xEB2BE8). */
        .set    IO_INT_STACK_TOP, OS_$STACK + 0x2BE8

        .globl  IO_$COND_SWITCH_BACK
IO_$COND_SWITCH_BACK:
        movea.l (%sp)+,%a1                      /* 00e2e846 */
        cmpa.l  #IO_INT_STACK_TOP,%sp           /* 00e2e848 */
        bne.b   1f                              /* 00e2e84e */
        movea.l (IO_$SAVED_OS_SP).l,%sp         /* 00e2e850: (-0x30,PC) */
        clr.l   (IO_$SAVED_OS_SP).l             /* 00e2e854 */
1:      jmp     (%a1)                           /* 00e2e85a */
