/*
 * kbd_$fetch_key - take the next key from a keyboard line's ring
 *
 * Original address: 0x00E1CAFE (module-local; was Ghidra kbd_$fetch_key)
 * Size: 242 bytes per Ghidra (which excludes the 30-byte jump table at
 * 0x00E1CB66); the code runs 0x00E1CAFE .. 0x00E1CC0F (`rts`)
 * Generated by: Claude Opus 5.5
 *
 * Runs the ring bytes through the keyboard state machine until one of them
 * yields a character or the ring is empty.  Returns a Domain boolean (0xFF =
 * a key in *key_out).  Callers: KBD_$RCV (0x00E1CE6C), KBD_$GET_CHAR_AND_MODE
 * (0x00E724F0).
 *
 * Frame (link.w A6,-0x14): (0x8,A6) state (A4), (0xc,A6) key_out (A2),
 * (0x10,A6) mode_out (D6).  A5 = 0xE2DDE4 (`lea`, 0x00E1CB06).
 * Registers: D2w ring head, D3b result, D4w sub-state, D5b "high key
 * translated through SMD_$KTT".
 *
 * Blocks:
 *   0x00E1CB18-0x00E1CB2A  result = 0; *mode_out = state->pending_mode;
 *                          D4 = sub_state; D2 = ring_head; D5 = 0
 *   0x00E1CB30-0x00E1CB3E  *key_out = ring[D2]; D2 wraps 0x40 -> 1
 *   0x00E1CB40-0x00E1CB62  entry = kbd_$state_lookup(D4, *key_out); action
 *                          = entry->next >> 4; >= 15 -> no action; jump table
 *                          at 0x00E1CB66 (15 word offsets):
 *     1, 2, 13, 14  0x00E1CB84  mode 0: *key_out = ktt[*key_out]; result true
 *     10            0x00E1CB98  *key_out = 0xCB; result true
 *     12            0x00E1CBA0  key > 0x7F: *key_out = SMD_$KTT[key];
 *                               D5 = result = true
 *     7             0x00E1CBBA  *mode_out = kbd_$get_mode(*key_out)
 *     0, 3-6, 8, 9, 11          nothing
 *   0x00E1CBC8-0x00E1CBE0  next nibble 0xF -> D4 = kbd_$escape_state[*mode_out]
 *                          (indexed by the MODE word, not the keyboard type)
 *                          else D4 = nibble
 *   0x00E1CBE2-0x00E1CBEA  loop while !result && D2 != ring_tail
 *   0x00E1CBEE-0x00E1CC04  ring_head = D2; sub_state = D4; pending_mode =
 *                          *mode_out; D5 -> *mode_out = 7 (after the save)
 */

#include "kbd/kbd_internal.h"

int8_t kbd_$fetch_key(kbd_state_t *state, uint8_t *key_out, int16_t *mode_out)
{
    int8_t result;                  /* D3b */
    int8_t high_key;                /* D5b */
    uint16_t sub_state;             /* D4w */
    uint16_t head;                  /* D2w */
    kbd_$state_entry_t *entry;      /* A3 */
    uint16_t action;                /* D0w */
    uint16_t next;                  /* D0w */

    /* 0x00E1CB18-0x00E1CB28 */
    result = 0;
    *mode_out = (int16_t)state->pending_mode;
    sub_state = state->sub_state;
    head = state->ring_head;
    high_key = result;

    /* 0x00E1CB2A: bra.w into the loop test */
    while (result >= 0 && head != state->ring_tail) {
        /* 0x00E1CB30: element i is at state+0x5D+i */
        *key_out = state->ring_buffer[head - 1];

        /* 0x00E1CB34-0x00E1CB3E */
        if (head == KBD_RING_SIZE) {
            head = 1;
        } else {
            head++;
        }

        /* 0x00E1CB40-0x00E1CB4A */
        entry = kbd_$state_lookup(sub_state, *key_out);

        /* 0x00E1CB4C-0x00E1CB62 */
        action = (uint16_t)((entry->next & 0xF0) >> 4);
        switch (action) {
        case 1:
        case 2:
        case 13:
        case 14:
            /* 0x00E1CB84-0x00E1CB9C */
            if (*mode_out == 0) {
                *key_out = ((const uint8_t *)state->ktt_ptr)[*key_out];
            }
            result = (int8_t)0xFF;
            break;

        case 10:
            /* 0x00E1CB98-0x00E1CB9C: move.b #-0x35 */
            *key_out = 0xCB;
            result = (int8_t)0xFF;
            break;

        case 12:
            /* 0x00E1CBA0-0x00E1CBB6: movea.l #0xe273fe = SMD_$KTT */
            if (*key_out > 0x7F) {
                *key_out = SMD_$KTT[*key_out];
            }
            high_key = (int8_t)0xFF;
            result = high_key;
            break;

        case 7:
            /* 0x00E1CBBA-0x00E1CBC6 */
            *mode_out = kbd_$get_mode(*key_out);
            break;

        default:
            /* 0, 3-6, 8, 9, 11 and >= 15: 0x00E1CBC8 */
            break;
        }

        /* 0x00E1CBC8-0x00E1CBE0 */
        next = (uint16_t)(entry->next & 0x0F);
        if (next == 0x0F) {
            sub_state = kbd_$escape_state[*mode_out];
        } else {
            sub_state = next;
        }
    }

    /* 0x00E1CBEE-0x00E1CBF8 */
    state->ring_head = head;
    state->sub_state = sub_state;
    state->pending_mode = (uint16_t)*mode_out;

    /* 0x00E1CBFC-0x00E1CC00 */
    if (high_key < 0) {
        *mode_out = 7;
    }

    /* 0x00E1CC04 */
    return result;
}
