/*
 * kbd_$translate_key - map a few keyboard codes to control characters
 *
 * Original address: 0x00E1CC64 (module-local; was Ghidra kbd_$translate_key)
 * Size: 92 bytes (0x00E1CC64 .. 0x00E1CCBF)
 * Generated by: Claude Opus 5.5
 *
 * A Pascal function (KBD_$RCV reserves the result slot, 0x00E1CE4A, and
 * pushes the key with `move.b`, so it is the high half of the word at
 * (0x8,A6)).  The key is zero-extended into D0w (`clr.w` / `move.b`,
 * 0x00E1CC6C) and compared as a word; unmatched keys come back unchanged
 * (`move.b D1b,D0b`, 0x00E1CCBA).
 *
 *   0xC0 -> 0x16   0x91 -> 0x18   0x92 -> 0x04   0x95 -> 0x08
 *   0x96 -> 0x0D   0x97, 0x98, 0x99 -> 0x09
 */

#include "kbd/kbd_internal.h"

uint8_t kbd_$translate_key(uint8_t key)
{
    /* 0x00E1CC70-0x00E1CCBA */
    switch (key) {
    case 0xc0: return 0x16;     /* 0x00E1CCA2 */
    case 0x91: return 0x18;     /* 0x00E1CCA6 */
    case 0x92: return 0x04;     /* 0x00E1CCAA */
    case 0x95: return 0x08;     /* 0x00E1CCAE */
    case 0x96: return 0x0d;     /* 0x00E1CCB2 */
    case 0x99:
    case 0x98:
    case 0x97: return 0x09;     /* 0x00E1CCB6 */
    default:   return key;      /* 0x00E1CCBA */
    }
}
